### ISSUE TITLE
NPE in ModifiedControlVariableCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#1012]
java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.coding.ModifiedControlVariableCheck.checkIdent(ModifiedControlVariableCheck.java:266)
	at com.puppycrawl.tools.checkstyle.checks.coding.ModifiedControlVariableCheck.visitToken(ModifiedControlVariableCheck.java:189)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:412)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:505)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:338)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:204)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:271)
	at com.puppycrawl.tools.checkstyle.Main.processCommandLine(Main.java:161)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:59)
	at gov.ssa.enterprisetest.server.standalone.CodeStyleCheck.main(CodeStyleCheck.java:15)

Code:
`````
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name="user") //<-- cause of exception
@SessionScoped
public class TestClass3 {
}
`````

**Comment by romani** [comment]
merged
