### ISSUE TITLE
OneTopLevelClass check example is broken and documentation missing, for 'tokens' property

### ISSUE THREAD

**Issue by dhendriks** [checkstyle/checkstyle#1017]
The documentation for the OneTopLevelClass check provides the following example:

```xml
<module name="OneTopLevelClass">
    <property name="tokens" value="CLASS_DEF">
</module>
```

However, when using that, I get the following output of Checkstyle:

```
Could not execute Checkstyle: cannot initialize module TreeWalker - Token "CLASS_DEF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.design.OneTopLevelClassCheck@768debd
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "CLASS_DEF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.design.OneTopLevelClassCheck@768debd
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:183)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:173)
        at com.puppycrawl.tools.checkstyle.Main.createChecker(Main.java:187)
        at com.puppycrawl.tools.checkstyle.Main.processCommandLine(Main.java:156)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:59)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "CLASS_DEF" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.design.OneTopLevelClassCheck@768debd
        at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:272)
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:180)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:173)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:163)
        ... 4 more
```

It appears the 'OneTopLevelClassCheck' doesn't accept 'CLASS_DEF' as token. So the example seems to be broken?

I actually wanted to use the following (configured using 'Eclipse Checkstyle Plugin'):

```xml
    <module name="OneTopLevelClass">
      <property name="tokens" value="CLASS_DEF,ENUM_DEF,INTERFACE_DEF"/>
    </module>
```

Besides 'CLASS_DEF', also 'ENUM_DEF' and 'INTERFACE_DEF' seems to be unsupported as well. I could not find a way to make this check work. In fact, the 'tokens' property doesn't even seem to be documented, so it is hard to guess what, if anything, is allowed for it.

**Comment by romani** [comment]
that was a problem in Documentation, this Check does not support customization by "tokens", it works against tokens CLASS_DEF,ENUM_DEF,INTERFACE_DEF .

**Comment by dhendriks** [comment]
Thanks for the clarification, and fixing the documentation. However, you added this to the documentation:

```html
 <b>ATTENTION:</b> This Check does support customization of validated token, to not use "tokens" property
```

Should it not be something like this?

```html
 <b>ATTENTION:</b> This Check does not support customization of validated tokens, so do not use the "tokens" property.
```

**Comment by romani** [comment]
Thanks a LOT !!! fixed.
