### ISSUE TITLE
Checkstyle fails to parse local enum and interface declarations

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#10464]
As part of [JEP 395](https://openjdk.java.net/jeps/395), along with local records, we are able to declare local enums and interfaces. Checkstyle fails to parse the following:

```bash
➜  src /usr/lib/jvm/java-16-openjdk/bin/javac Test.java

➜  src cat Test.java 
class Test {
    void m() {
        enum E {a, b, c};
    }
}

➜  src java -jar checkstyle-8.44-all.jar -t Test.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/nick/Desktop/Tester/src/Test.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:120)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFileText(JavaParser.java:137)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFile(JavaParser.java:157)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:65)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:285)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: java.lang.IllegalStateException: /home/nick/Desktop/Tester/src/Test.java:3:9: expecting RCURLY, found 'enum'
...

```

and 

```bash
➜  src /usr/lib/jvm/java-16-openjdk/bin/javac Test.java

➜  src cat Test.java
class Test {
    void m() {
        interface I{}
    }
}

➜  src java -jar checkstyle-8.44-all.jar -t Test.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/nick/Desktop/Tester/src/Test.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:120)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFileText(JavaParser.java:137)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFile(JavaParser.java:157)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:65)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:285)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: java.lang.IllegalStateException: /home/nick/Desktop/Tester/src/Test.java:3:9: expecting RCURLY, found 'interface'
...

```

I would expect Checkstyle to parse this code.

**Comment by nmancus1** [comment]
We can remove the following file filters from `openjdk16-excluded.files` in fix for this issue:

```xml
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="[\\/]test[\\/]langtools[\\/]tools[\\/]javac[\\/]enum[\\/]LocalEnum.java$"/>
</module>
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="[\\/]test[\\/]langtools[\\/]tools[\\/]javac[\\/]enum[\\/]LocalEnum.java$"/>
</module>
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="[\\/]test[\\/]langtools[\\/]tools[\\/]javac[\\/]diags[\\/]examples[\\/]LocalEnum.java$"/>
</module>
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="[\\/]test[\\/]langtools[\\/]tools[\\/]javac[\\/]LocalInterface.java$"/>
</module>

```

**Comment by pbludov** [comment]
Fix is merged.
