### ISSUE TITLE
Checkstyle fails to parse local record with `final` modifier

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#10516]
Since Java 15, local records can have the `final` modifier applied to them.

I would expect Checkstyle to parse the following code:

```bash

➜  src cat Test.java
public class Test {
    void method() {
        final record MyFinalRecord (int x) { }
    }
}

➜  src /usr/lib/jvm/java-16-openjdk/bin/javac Test.java

➜  src java -jar checkstyle-8.45-all.jar -t Test.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/nick/Desktop/Tester/src/Test.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:120)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFileText(JavaParser.java:137)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFile(JavaParser.java:157)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:65)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:285)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: java.lang.IllegalStateException: /home/nick/Desktop/Tester/src/Test.java:3:15: expecting "class", found 'record'
        at com.puppycrawl.tools.checkstyle.JavaParser$1.reportError(JavaParser.java:108)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:429)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:212)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:114)
        ... 6 more
Caused by: /home/nick/Desktop/Tester/src/Test.java:3:15: expecting "class", found 'record'
        at antlr.Parser.match(Parser.java:211)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:625)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.traditionalStatement(GeneratedJavaRecognizer.java:6195)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.statement(GeneratedJavaRecognizer.java:4978)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compoundStatement(GeneratedJavaRecognizer.java:4704)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3241)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:3556)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:655)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:566)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:407)
        ... 8 more
Checkstyle ends with 1 errors.


```

I would expect the following AST:

```bash

[8:42:19] ➜  src java -jar checkstyle-8.46-SNAPSHOT-all.jar -t Test.java                        
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> Test [1:13]
`--OBJBLOCK -> OBJBLOCK [1:18]
    |--LCURLY -> { [1:18]
    |--METHOD_DEF -> METHOD_DEF [2:4]
    |   |--MODIFIERS -> MODIFIERS [2:4]
    |   |--TYPE -> TYPE [2:4]
    |   |   `--LITERAL_VOID -> void [2:4]
    |   |--IDENT -> method [2:9]
    |   |--LPAREN -> ( [2:15]
    |   |--PARAMETERS -> PARAMETERS [2:16]
    |   |--RPAREN -> ) [2:16]
    |   `--SLIST -> { [2:18]
    |       |--RECORD_DEF -> RECORD_DEF [3:8]
    |       |   |--MODIFIERS -> MODIFIERS [3:8]
    |       |   |   `--FINAL -> final [3:8]
    |       |   |--LITERAL_RECORD -> record [3:14]
    |       |   |--IDENT -> MyFinalRecord [3:21]
    |       |   |--LPAREN -> ( [3:35]
    |       |   |--RECORD_COMPONENTS -> RECORD_COMPONENTS [3:36]
    |       |   |   `--RECORD_COMPONENT_DEF -> RECORD_COMPONENT_DEF [3:36]
    |       |   |       |--ANNOTATIONS -> ANNOTATIONS [3:36]
    |       |   |       |--TYPE -> TYPE [3:36]
    |       |   |       |   `--LITERAL_INT -> int [3:36]
    |       |   |       `--IDENT -> x [3:40]
    |       |   |--RPAREN -> ) [3:41]
    |       |   `--OBJBLOCK -> OBJBLOCK [3:43]
    |       |       |--LCURLY -> { [3:43]
    |       |       `--RCURLY -> } [3:45]
    |       `--RCURLY -> } [4:4]
    `--RCURLY -> } [5:0]


```

**Comment by nmancus1** [comment]
We can remove the following file filters from `openjdk16-excluded.files` in fix for this issue:

```xml

<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="[\\/]test[\\/]jdk[\\/]java[\\/]lang[\\/]reflect[\\/]records[\\/]IsRecordTest.java$"/>
</module>

```

**Comment by pbludov** [comment]
Fix is merged.
