### ISSUE TITLE
Javadoc grammar does not support unicode characters

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#10629]
We need to revisit this issue

While our ANTLR4 Java grammar now supports unicode characters, our ANTLR4 Javadoc grammar still does not:

```bash

 ➜  src cat Test.java                                         
public class Test {

    /**
     *
     * @param ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ
     */
    void aᇭᇮᇯᇰᇱᇲᇳᇴᇵᇶᇷᇸᇹᇺ(int ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ) {}


}

 ➜  src java -jar checkstyle-9.0-SNAPSHOT-all.jar -T Test.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> Test [1:13]
`--OBJBLOCK -> OBJBLOCK [1:18]
    |--LCURLY -> { [1:18]
    |--METHOD_DEF -> METHOD_DEF [7:4]
    |   |--MODIFIERS -> MODIFIERS [7:4]
    |   |--TYPE -> TYPE [7:4]
    |   |   |--BLOCK_COMMENT_BEGIN -> /* [3:4]
    |   |   |   |--COMMENT_CONTENT -> *\n     *\n     * @param ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ\n      [3:6]
    |   |   |   `--BLOCK_COMMENT_END -> */ [6:5]
    |   |   `--LITERAL_VOID -> void [7:4]
    |   |--IDENT -> aᇭᇮᇯᇰᇱᇲᇳᇴᇵᇶᇷᇸᇹᇺ [7:9]
    |   |--LPAREN -> ( [7:24]
    |   |--PARAMETERS -> PARAMETERS [7:25]
    |   |   `--PARAMETER_DEF -> PARAMETER_DEF [7:25]
    |   |       |--MODIFIERS -> MODIFIERS [7:25]
    |   |       |--TYPE -> TYPE [7:25]
    |   |       |   `--LITERAL_INT -> int [7:25]
    |   |       `--IDENT -> ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ [7:29]
    |   |--RPAREN -> ) [7:40]
    |   `--SLIST -> { [7:42]
    |       `--RCURLY -> } [7:43]
    `--RCURLY -> } [10:0]

 ➜  src java -jar checkstyle-9.0-SNAPSHOT-all.jar -J Test.java
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:5] Javadoc comment at column 15 has parse error. Details: no viable alternative at input 'ᇤ' while parsing JAVADOC_TAG
        at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseAndPrintJavadocTree(AstTreeStringPrinter.java:116)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:97)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:79)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:306)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)


```

We must update the documentation accordingly, as we cannot claim full unicode character support until we support it in both Javadoc and Java grammar.

_Originally posted by @nmancus1 in https://github.com/checkstyle/checkstyle/issues/8050#issuecomment-898897547_

**Comment by aclfe** [comment]
@romani
I would like to work on this. 

I investigated the file `JavadocCommentsLexer.g4` (renamed from `JavadocLexer.g4` in the original issue)
Please judge my approach:

My Plan:

First:
- Add Letter and LetterOrDigit fragments to JavadocCommentsLexer.g4 (supporting full Unicode & surrogate pairs).

Then I see that rules like 

- `BlockTag_CUSTOM_NAME`
- `PARAMETER_NAME`
- `FIELD_TYPE, IDENTIFIER`
- and other relevant ones

need refactoring

**Comment by aclfe** [comment]
Hi all. Seems I have some progress locally. The IllegalArgumentException is gone. Confirming direction 

`java -jar /target/checkstyle-13.0.1-SNAPSHOT-all.jar -J Test.java`

```
COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
`--CLASS_DEF -> CLASS_DEF [1:0]
    |--MODIFIERS -> MODIFIERS [1:0]
    |   `--LITERAL_PUBLIC -> public [1:0]
    |--LITERAL_CLASS -> class [1:7]
    |--IDENT -> Test [1:13]
    `--OBJBLOCK -> OBJBLOCK [1:18]
        |--LCURLY -> { [1:18]
        |--METHOD_DEF -> METHOD_DEF [7:4]
        |   |--MODIFIERS -> MODIFIERS [7:4]
        |   |--TYPE -> TYPE [7:4]
        |   |   |--BLOCK_COMMENT_BEGIN -> /* [3:4]
        |   |   |   |--COMMENT_CONTENT -> *\n     *\n     * @param ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ\n      [3:6]
        |   |   |   |   `--JAVADOC_CONTENT -> JAVADOC_CONTENT [3:7]
        |   |   |   |       |--NEWLINE -> \n [3:7]
        |   |   |   |       |--LEADING_ASTERISK ->      * [4:0]
        |   |   |   |       |--NEWLINE -> \n [4:6]
        |   |   |   |       |--LEADING_ASTERISK ->      * [5:0]
        |   |   |   |       |--TEXT ->   [5:6]
        |   |   |   |       |--JAVADOC_BLOCK_TAG -> JAVADOC_BLOCK_TAG [5:7]
        |   |   |   |       |   `--PARAM_BLOCK_TAG -> PARAM_BLOCK_TAG [5:7]
        |   |   |   |       |       |--AT_SIGN -> @ [5:7]
        |   |   |   |       |       |--TAG_NAME -> param [5:8]
        |   |   |   |       |       `--PARAMETER_NAME ->  ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ [5:13] //recognized 
        |   |   |   |       |--NEWLINE -> \n [5:25]
        |   |   |   |       `--TEXT ->       [6:0]
        |   |   |   `--BLOCK_COMMENT_END -> */ [6:5]
        |   |   `--LITERAL_VOID -> void [7:4]
        |   |--IDENT -> aᇭᇮᇯᇰᇱᇲᇳᇴᇵᇶᇷᇸᇹᇺ [7:9]
        |   |--LPAREN -> ( [7:24]
        |   |--PARAMETERS -> PARAMETERS [7:25]
        |   |   `--PARAMETER_DEF -> PARAMETER_DEF [7:25]
        |   |       |--MODIFIERS -> MODIFIERS [7:25]
        |   |       |--TYPE -> TYPE [7:25]
        |   |       |   `--LITERAL_INT -> int [7:25]
        |   |       `--IDENT -> ᇤᇥᇦᇧᇨᇩᇪᇫᇬᇭᇮ [7:29]
        |   |--RPAREN -> ) [7:40]
        |   `--SLIST -> { [7:42]
        |       `--RCURLY -> } [7:43]
        `--RCURLY -> } [10:0]
```

**Comment by romani** [comment]
This issue looks like resolved by summer 2025 javadoc grammar rewrite.

If we don't have exception any more it means all resolved and we can simply close issue.

**Comment by romani** [comment]
@aclfe, if you see a problem please reproduce it by CLI and share it

**Comment by aclfe** [comment]
> [@aclfe](https://github.com/aclfe), if you see a problem please reproduce it by CLI and share it

Hello, here's the latest error reproduced. I'm using the latest 13.0 from the release to show the exception. 

`cat Test.java`

```
public class Test {

    /**
     *
     * @param 건반
     */
    void aᇭᇮᇯᇰᇱᇲᇳᇴᇵᇶ(int 건반) {}


}
```

`javac Test.java`
(no output)


`java -jar checkstyle-13.0.0-all.jar -J Test.java `

```
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:5] Javadoc comment at column 15 has parse error. Details: token recognition error at: '반' while parsing  
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:69)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseAndPrintJavadocTree(AstTreeStringPrinter.java:116)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:97)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:79)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:323)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:206)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
```

You can see that `IllegalArgumentException` is still being thrown in version 13.0.

**Comment by aclfe** [comment]
> This issue looks like resolved by summer 2025 javadoc grammar rewrite.
> 
> If we don't have exception any more it means all resolved and we can simply close issue.

Are those changes merged into master? I checked `JavadocCommentsLexer.g4`, it doesn't have anything related to the `fragment Letter` allowing unicode. Values are only hard coded to use `[a-zA-Z$_]` that's why I was working on this issue

**Comment by romani** [comment]
We are not going to support non English variables.
We can support Unicode plain text in comments only

**Comment by aclfe** [comment]
> We are not going to support non English variables

I agree with your decision, but I would like to make a humble point regarding this.

I understand the policy regarding English variables, but I believe there is a difference in enforcing English names and parsing valid Java without crashing. 

The current issue is not that Checkstyle flags an error on Unicode variables; the issue is that Checkstyle crashes with an `IllegalArgumentException`. Checkstyle is a static analysis tool that enforces styling rules / best practices onto Java code. Ideally, **a static analysis tool shouldn't crash on valid Java code, even if that code violates the project's specific style rules**

I only suggest that non English variables should be gracefully handled by Checks, rather than the Javadoc Lexer itself crashing completely. 

An example:

---


When you declare `int 건반 = 30;` in a Java file, for example: 

```
public class Test {
    void myMethod(int hello) { 

        int 건반 = 30;

    }
}
```

Java Parser: Successfully parses 건반 as an IDENT. There is no crash.

`        |       |   |--IDENT -> 건반 [7:12]`

Checks: The LocalVariableName check will correctly flag this as a violation (because of the regex)
`Name '건반' must match pattern '^([a-z][a-zA-Z0-9]*|_)$'. [LocalVariableName]`

This is gracefully handled by the checks. 

---

However, as mentioned here:
https://github.com/checkstyle/checkstyle/issues/10629#issuecomment-3726958073

Javadoc Parser: Crashes with `IllegalArgumentException` when having unicode in `@param 건반`

---

I only believe they should be matching.

Naturally I'm okay with whatever approach is taken in regards to this

**Comment by romani** [comment]
Even we do extra effort to make it parse-able.
Checks will not like such code. There are a lot of checks that are based on assumption that there are get/set, there are words that starts with capital letters.

For now, we will not be able to finish such support in way that customers can use it. In future, as we reduce issue tracker open issues fom 800 to 100, we can come back to this and make it happen. 
But for now this direction is big distraction.

**Comment by aclfe** [comment]
> But for now this direction is big distraction.

Thank you for being direct with me regarding this. I understand your concern regarding the scope and stability. Cheers to more PRs and discussions!
