### ISSUE TITLE
OneTopLevelClass Check fails when analyzing package-info.java

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1065]
Problem can be reproduced by running [OneTopLevelClass](http://checkstyle.sourceforge.net/config_design.html#OneTopLevelClass) on any `package-info.java` file.

```
com.puppycrawl.tools.checkstyle.TreeWalker processFiltered
SEVERE: NoSuchElementException occurred during the analysis of file
com\puppycrawl\tools\checkstyle\api\package-info.java.
java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1221)
	at java.util.TreeMap.firstKey(TreeMap.java:285)
	at com.puppycrawl.tools.checkstyle.checks.design.OneTopLevelClassCheck.finishTree(OneTopLevelClassCheck.java:147)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyEnd(TreeWalker.java:383)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:339)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:205)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:271)
```

**Comment by romani** [comment]
merged.
