### ISSUE TITLE
Inline Config Parser throws complex exception without config in input file

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#10764]
Identified at https://github.com/checkstyle/checkstyle/pull/10758#discussion_r698910973 ,

Steps to reproduce:
1) Modify `InputParenPadNoStackoverflowError.java` to remove the configuration javadoc at the top of the file.
2) Run JUnit tests connected to the input file.

The following trimmed stack trace is printed:
````
Caused by: java.lang.IndexOutOfBoundsException: Index: 36, Size: 36
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.setProperties(InlineConfigParser.java:206)
	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.setModules(InlineConfigParser.java:122)
	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.parse(InlineConfigParser.java:104)
	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.parse(InlineConfigParser.java:88)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyWithInlineConfigParser(AbstractModuleTestSupport.java:249)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.lambda$2(AbstractModuleTestSupport.java:380)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
````

It is not clear what the issue is from the exception alone. I also question if the exception is actually coincidence that the tool is looking for any Javadoc and not the normal top most one.

An inexperienced user to our repo may not have any idea of our BDD and the requirement that the Javadoc configuration be inside our input files. This message gives no guidance on the issue and how to resolve.

https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_input_checks.xml#L20-L28
I understand we have a checkstyle item to print out the requirement of the BDD text, but that checkstyle item is only run after the tests and not before. Again, this doesn't help new users as they expect things to be clear when validated by the default order (which is currently compile, junits, IT, checks. external checks, etc...). Even outside the order, the users can build and debug their tests before even touching the checkstyle run.

We should change the parser to validate the necessity of the BDD text and it be in the correct location and remove the checkstyle item.

Additionally, the exception message should be made into clearer text on what the error is and guide new users on how to use it properly.

**Comment by rnveach** [comment]
Fix was merged
