### ISSUE TITLE
StackOverflow Error in IndentationCheck on deeply concatenated strings

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#10810]
I have read check documentation: https://checkstyle.sourceforge.io/config_misc.html#Indentation

Noticed at https://github.com/checkstyle/checkstyle/pull/9622#issuecomment-924361613:

```bash

➜  cat Test.java
public class Test {
    public void test() {
        String s = " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " +
                " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " +
                " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " +
...
                " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " +
                " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " +
                " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " +
                " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " " + " ";

    }
}

➜  cat Test.java | wc -l        
3028

➜  cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="error"/>

    <module name="TreeWalker">
        <module name="IndentationCheck">
    </module>

    </module>
</module>

➜  javac Test.java

➜  java -jar checkstyle-9.0-all.jar -c config.xml Test.java
Starting audit...
Exception in thread "main" java.lang.Error: Error was thrown while processing Test.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:310)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:409)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:332)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: java.lang.StackOverflowError
        at com.puppycrawl.tools.checkstyle.DetailAstImpl.getLineNo(DetailAstImpl.java:264)
        at com.puppycrawl.tools.checkstyle.DetailAstImpl.findLineNo(DetailAstImpl.java:361)
        at com.puppycrawl.tools.checkstyle.DetailAstImpl.getLineNo(DetailAstImpl.java:267)
        at com.puppycrawl.tools.checkstyle.DetailAstImpl.findLineNo(DetailAstImpl.java:361)
        at com.puppycrawl.tools.checkstyle.DetailAstImpl.getLineNo(DetailAstImpl.java:264)
        at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.getFirstAst(AbstractExpressionHandler.java:442)
        at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.getFirstAst(AbstractExpressionHandler.java:453)
        at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.getFirstAst(AbstractExpressionHandler.java:453)
        at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.getFirstAst(AbstractExpressionHandler.java:453)
        at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.getFirstAst(AbstractExpressionHandler.java:453)
 ...

```

IndentationCheck is failing on a large number of string concatenations, the culprit is recursive calls to `AbstractExpressionHandler#getFirstAst`:

https://github.com/checkstyle/checkstyle/blob/1ce8eea267305f00807620768887949cca220d76/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java#L453

Perhaps some iterative approach will provide better performance and solve this issue.

**Comment by rnveach** [comment]
It appears to me the section of the code should be swapped with the iterative tree walking we see in `TreeWalker`, with the only thing to do is look for the first node by line/column in the AST's complete children list.

**Comment by Vyom-Yadav** [comment]
I am working on it.

**Comment by nmancus1** [comment]
After merging this, we can revert changes at https://github.com/checkstyle/contribution/issues/564
