### ISSUE TITLE
Message validation in our Inputs should not have trailing and leading '.*'

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#10943]
detected during code review https://github.com/checkstyle/checkstyle/pull/10839#discussion_r735038465

Message validation in our Inputs should not have trailinng and leading `.*`.

following modification of test should be acceptable 
```
✔ ~/java/github/romani/checkstyle [strkkk/10144_multicatch L|✚ 1] 
$ git diff
diff --git a/src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityImplementsAndNestedCount.java b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityImplementsAndNestedCount.java
index 25daa35..82b09e1 100644
--- a/src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityImplementsAndNestedCount.java
+++ b/src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityImplementsAndNestedCount.java
@@ -24,7 +24,7 @@ import java.io.Serializable;
 import java.util.RandomAccess;
 
 // count is 3 - two interfaces and parent class
-public class InputClassFanOutComplexityImplementsAndNestedCount // violation '.* Complexity is 3 .*'
+public class InputClassFanOutComplexityImplementsAndNestedCount // violation 'Complexity is 3'
     extends Outer.Nested implements Serializable, RandomAccess {
 
 }

```

![image](https://user-images.githubusercontent.com/812984/141371980-7977a8ba-8cea-4354-a212-71f16bf0edfc.png)

But UT failing.
```
Actual and expected violations differ.
expected to match: 27:(?:\d+:)?\s.*Complexity is 3
but was          : 27:1: Class Fan-Out Complexity is 3 (max allowed is 0).

	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyViolations(AbstractModuleTestSupport.java:431)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyWithInlineConfigParser(AbstractModuleTestSupport.java:270)
	at com.puppycrawl.tools.checkstyle.checks.metrics.ClassFanOutComplexityCheckTest.testImplementsAndNestedCount(ClassFanOutComplexityCheckTest.java:239)
```

**Comment by Vyom-Yadav** [comment]
I am on it.
