### ISSUE TITLE
Wercker failure on no-exception-checkstyle-sevntu over InputIndentationLongConcatenatedString.java

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11059]
CI failure https://app.wercker.com/checkstyle/checkstyle/runs/build/61bf7b27237ec9000897316c?step=61bf7baec148e300072ce2ab

command `./.ci/validation.sh no-exception-checkstyle-sevntu`

`Exception in thread "main" java.lang.Error: Error was thrown while processing /pipeline/source/.ci-temp/contribution/checkstyle-tester/src/main/java/local-checkstyle/target/test-classes/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLongConcatenatedString.java`

we have exclude over: `src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLongConcatenatedString`

attention that problematic file is in `local-checkstyle/target/test-classes` folder.

**Comment by romani** [comment]
I was lucky to reproduce this problem on local:
```
constituent[41]: file:/opt/maven/apache-maven-3.6.2/lib/plexus-sec-dispatcher-1.4.jar
---------------------------------------------------
Exception in thread "main" java.lang.Error: Error was thrown while processing
 /home/rivanov/java/github/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/
src/main/java/local-checkstyle/target/test-classes/
com/puppycrawl/tools/checkstyle/checks/indentation/
indentation/InputIndentationLongConcatenatedString.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:310)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:202)

```
content of folder:
```
~/java/github/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/src/main/java/local-checkstyle/target/test-classes/com/puppycrawl/tools/checkstyle/checks/indentation/indentation [master|✚ 2] 
14:30 $ ls | grep ".java"
InputIndentation15Extensions.java
InputIndentationAndroidStyle.java
InputIndentationAnnArrInit2.java
InputIndentationAnnArrInit.java
InputIndentationAnnotationArrayInitGood.java
InputIndentationAnnotationArrayInitOldStyle.java
InputIndentationAnnotationClosingParenthesisEndsInSameIndentationAsOpening.java
InputIndentationAnnotationDefinition.java
InputIndentationAnnotationFieldDefinition.java
InputIndentationAnnotationIncorrect.java
InputIndentationAnnotationScopeIndentationCheck.java
InputIndentationAnonymousClasses.java
InputIndentationAnonymousClassInMethodCurlyOnNewLine.java
InputIndentationAnonymousClassInMethod.java
InputIndentationArrays.java
....
```

**Comment by romani** [comment]
fixed by https://github.com/checkstyle/contribution/commit/589d33bfcb0970ee0e2d2e4772090ec0877a5882

**Comment by romani** [comment]
still a problem:
```
constituent[42]: file:/usr/share/maven/lib/commons-lang3-3.8.1.jar
---------------------------------------------------
Exception in thread "main" java.lang.Error: 
Error was thrown while processing /pipeline/source/.ci-temp/contribution/checkstyle-tester/
src/main/java/local-checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks
/indentation/indentation/InputIndentationLongConcatenatedString.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:310)

```

**Comment by romani** [comment]
might be fixed by commit https://github.com/checkstyle/contribution/commit/c54c502960c40bb1058f8d960b67c83b8790603d 
at leas for now wercker is green.
