### ISSUE TITLE
MutableException check fails with NPE if extended class is in canonical form

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1124]
[MutableException](http://checkstyle.sourceforge.net/config_design.html#MutableException) check fails with `NullPointerException` if extended class is in canonical form.

#### Configuration
```xml
<module name="MutableException"/>
```
#### Input file
```java
class CustomException extends java.lang.Exception {}
```
#### Stacktrace
```
java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.design.MutableExceptionCheck.isExtendedClassNamedAsException(MutableExceptionCheck.java:155)
        at com.puppycrawl.tools.checkstyle.checks.design.MutableExceptionCheck.visitClassDef(MutableExceptionCheck.java:114)
        at com.puppycrawl.tools.checkstyle.checks.design.MutableExceptionCheck.visitToken(MutableExceptionCheck.java:91)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:393)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:482)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:322)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:195)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:76)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:260)
```

**Comment by romani** [comment]
Pleaese let me know name of opensource project where you found such code, we might use it in checkstyle-checker.

**Comment by mkordas** [comment]
It's the project we already use - Findbugs.

**Comment by romani** [comment]
Hmm, i checked it on 6.6 it worked fine, so i put priority Hight. I will think how to can make huge regression testing on each commit.

**Comment by Vladlis** [comment]
Sorry, this is my fault
https://github.com/checkstyle/checkstyle/issues/1103

**Comment by romani** [comment]
merged.

**Comment by romani** [comment]
@Vladlis, on any next PR from you, please test by checkstyle-tester all your changes, and confirm that there is no Errors after your changes for "dead code".

**Comment by mkordas** [comment]
This issue needs to be reopened. In this case removing "dead" code and then having NPE was VERY valuable, as it revealed missing implementation for canonical class names. Adding null check hid the issue once again.
I'll provide failing test and new implementation shortly.

**Comment by romani** [comment]
I keep it close, as you already fixed it.
