### ISSUE TITLE
google_checks.xml fails with `Token "ELLIPSIS" was not found`

### ISSUE THREAD

**Issue by salomvary** [checkstyle/checkstyle#11329]
I'm trying to use the latest `google_checks.xml` published in the `checkstyle` repo with no modifications: https://raw.githubusercontent.com/checkstyle/checkstyle/63d2e5cfea074bf200353b496cd0bfebe9b4ca97/src/main/resources/google_checks.xml 

Note: `sun_checks.xml` seems to be working fine.

```bash
/var/tmp $ javac Hello.java
✅

/var/tmp $ cat Hello.java
public class Hello {
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}


/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-9.3-all.jar -c https://raw.githubusercontent.com/checkstyle/checkstyle/63d2e5cfea074bf200353b496cd0bfebe9b4ca97/src/main/resources/google_checks.xml Hello.java 
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "ELLIPSIS" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:476)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:403)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:330)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:189)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "ELLIPSIS" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck
	at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:223)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:133)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:471)
	... 5 more
Checkstyle ends with 1 errors.
```

---

**Describe what you expect in detail.**

---

I expect checkstyle not to fail with `CheckstyleException: cannot initialize module TreeWalker`

**Comment by nmancus1** [comment]
Support for the `ELLIPSIS` token in `WhitespaceAfterCheck` has not been released yet, you can use the google_checks.xml file in the 9.3 zip until then.

**Comment by salomvary** [comment]
Oh, ok, that worked, thanks for the quick response!

**Comment by nmancus1** [comment]
@salomvary please close issue if you are all set :)
