### ISSUE TITLE
SuppressionsLoaderTest.loadFilterSet failing with SSLHandshakeException while fetching file from checkstyle.org

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11345]
I run into stable failure of UTs:
```
-------------------------------------------------------------------------------
Test set: com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest
-------------------------------------------------------------------------------
Tests run: 19, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.549 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest
testLoadFromUrl  Time elapsed: 6.523 s  <<< ERROR!
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to read https://checkstyle.org/files/suppressions_none.xml
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest.loadFilterSet(SuppressionsLoaderTest.java:201)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest.testLoadFromUrl(SuppressionsLoaderTest.java:70)
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching checkstyle.org found.
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest.loadFilterSet(SuppressionsLoaderTest.java:201)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest.testLoadFromUrl(SuppressionsLoaderTest.java:70)
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching checkstyle.org found.
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest.loadFilterSet(SuppressionsLoaderTest.java:201)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoaderTest.testLoadFromUrl(SuppressionsLoaderTest.java:70)
```

**Comment by romani** [comment]
Fixed in 10.0 as it was blocker to release for me.
