### ISSUE TITLE
IllegalArgumentException at SuppressWarningsHolder

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1148]
Config:
```
    <module name="SuppressWarningsHolder"/>
```

code base as of 28 May 2015.

output:
```
    SEVERE: IllegalArgumentException occurred during the analysis of file checkstyle/contribution/checkstyle-tester/src/main/java/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/annotation/SuppressWarningsConstants.java.
java.lang.IllegalArgumentException: String literal AST expected: .[13x51]
  at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.getStringExpr(SuppressWarningsHolder.java:402)
  at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.getAnnotationValues(SuppressWarningsHolder.java:419)
  at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.visitToken(SuppressWarningsHolder.java:248)
  at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:393)
  at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:482)
  at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:322)
  at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:195)
  at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:76)
  at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:260)
  at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:253)
```

**Comment by romani** [comment]
Merged
