### ISSUE TITLE
NullPointerException at PackageDeclarationCheck

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1149]
```
    <module name="PackageDeclaration"/>
```
https://github.com/checkstyle/contribution/tree/master/checkstyle-tester
openjdk|hg|http://hg.openjdk.java.net/jdk7/jdk7/jdk/

output:
```
      SEVERE: NullPointerException occurred during the analysis of file checkstyle/contribution/checkstyle-tester/src/main/java/openjdk/test/com/sun/jdi/RedefineCrossStart.java.
java.lang.NullPointerException
  at com.puppycrawl.tools.checkstyle.checks.coding.PackageDeclarationCheck.finishTree(PackageDeclarationCheck.java:68)
  at com.puppycrawl.tools.checkstyle.TreeWalker.notifyEnd(TreeWalker.java:366)
  at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:324)
  at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:195)
  at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:76)
  at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:260)
  at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:253)
  at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
  at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:155)
  at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
  at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
  at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:317)
  at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:134)
  at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
  at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
  at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

May 25, 2015 12:01:11 AM com.puppycrawl.tools.checkstyle.TreeWalker processFiltered
SEVERE: NullPointerException occurred during the analysis of file checkstyle/contribution/checkstyle-tester/src/main/java/openjdk/test/com/sun/jdi/RedefineCrossEvent.java.
java.lang.NullPointerException
  at com.puppycrawl.tools.checkstyle.checks.coding.PackageDeclarationCheck.finishTree(PackageDeclarationCheck.java:68)
  at com.puppycrawl.tools.checkstyle.TreeWalker.notifyEnd(TreeWalker.java:366)
  at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:324)
  at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:195)
  at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:76)
  at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:260)
  at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:253)
  at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
  at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:155)
  at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
  at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
  at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:317)
  at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:134)
  at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
  at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
  at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
``

**Comment by romani** [comment]
merged.
