### ISSUE TITLE
Missing default value on custom module property values with property expansion

### ISSUE THREAD

**Issue by stechio** [checkstyle/checkstyle#11537]
Check documentation:
- https://checkstyle.sourceforge.io/config.html#Properties
- https://checkstyle.sourceforge.io/config_naming.html#TypeName

```bash
$ javac Test.java

$ cat test-checkstyle.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="TypeName">
      <property name="format" value="${checkstyle.typename.format}"/>
    </module>  
  </module>
</module>

$ cat Test.java
public class Test {
  public static void main(String[] args) {
  }
}

$ java -jar checkstyle-10.1-all.jar -c test-checkstyle.xml Test.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:325)
	. . .
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: org.xml.sax.SAXException: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property ${checkstyle.typename.format} has not been set
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property ${checkstyle.typename.format} has not been set
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader.startElement(ConfigurationLoader.java:530)
	. . .
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:315)
	... 5 more
CCaused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property ${checkstyle.typename.format} has not been set
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.replaceProperties(ConfigurationLoader.java:376)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader.startElement(ConfigurationLoader.java:525)
	... 20 more
Checkstyle ends with 1 errors.
```

---

CURRENT BEHAVIOR

As I wanted to reuse the configuration document (checkstyle.xml) across my projects, I decided to expose custom properties like `checkstyle.typename.format` to decouple the (centralized) configuration document from its (decentralized) project-specific settings, *redefining module property values through property expansion* [as suggested in the documentation](https://checkstyle.sourceforge.io/config.html#Properties).

The PROBLEM, as shown in the error output above, is that, ***if a property is overridden*** (in my example, [`TypeName.format`](https://checkstyle.sourceforge.io/config_naming.html#TypeName)), ***its unspecified attributes (such as `default`) are undefined***, contrary to their documented initial state. The documentation declares that the default value of `TypeName.format` is `"^[A-Z][a-zA-Z0-9]*$"`, yet it seems lost... The [property expansion documentation](https://checkstyle.sourceforge.io/config.html#Properties) suggests to define the `default` attribute "when a property in the value cannot be resolved":

```xml
<module name="TypeName">
  <property name="format" value="${checkstyle.typename.format}" default="^[A-Z][a-zA-Z0-9]*$"/>
  . . .
</module>
```

This way, the processor is finally happy, but I'm NOT, since to me, as a fan of the DRY principle, it feels like an awkward redundancy (why repeating the SAME default value, when it should be, implicitly, already there?).

---

EXPECTED BEHAVIOR

Probably I'm missing some design principle/convention informing this project, nonetheless IMO inheriting the predefined behavior is a common expectation in modern systems: if the default value of `TypeName.format` is `"^[A-Z][a-zA-Z0-9]*$"`, ***when I override that property I expect its default value to be still there, until I explicitly redefine it***.

**Comment by romani** [comment]
There might be some confusion of:
1) default value of Check property if property not mentioned at all
2) custom/user's default value in config if property is mentioned but actual value is missing due to variable evaluation.

"1)" is for default values that we mentioning in our documentation.

"2)" is for situation when Check default is not good for user and he override it with some value, in addition to this he wants to customization by variable evaluation.

What we might missing is in case "2)" use Check's default if "default" attribute is not defined in property configuration.

**Comment by stechio** [comment]
> What we might missing is in case "2)" use Check's default if "default" attribute is not defined in property configuration.

Yes, exactly. In case of Check override, its `default` attribute should be inherited from the corresponding property's predefined `default` attribute.

**Comment by stechio** [comment]
BTW, this flaw affects also properties with _empty_ predefined `default` attribute, such as [`AbbreviationAsWordInName.allowedAbbreviations`](https://checkstyle.sourceforge.io/config_naming.html#AbbreviationAsWordInName): because of the lack of inheritance, users are forced to initialize the expandable property even if it's still empty!

```
# In this properties file, referenced through the `propertiesLocation` of the `maven-checkstyle-plugin`,
# the expandable property is assigned empty just to satisfy the checkstyle processor.
checkstyle.abbreviationAsWordInName.allowedAbbreviations=
```

**Comment by romani** [comment]
we have default for properties, example:
https://github.com/checkstyle/checkstyle/blob/d6fc0f3c526b6c556d669f2b5eae516b3a6fa284/src/main/resources/google_checks.xml#L32-L35
