### ISSUE TITLE
RedundantImport exception on non-compilable file from spoon regression

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#11685]
Identified at https://github.com/checkstyle/checkstyle/pull/11683 ,

````
$ cat TestClass.java
import Enclosing;

public class Caller {
public Caller() {
Enclosing<Object, Object> e = new Enclosing<>();
Enclosing$Nested<Object> n = new Enclosing<>(System.out);
}
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="RedundantImport"/>
    </module>
</module>

$ java -jar checkstyle-10.3-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:305)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:407)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:330)
    at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:189)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 9
    at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
    at java.base/java.lang.String.substring(String.java:1874)
    at com.puppycrawl.tools.checkstyle.checks.imports.RedundantImportCheck.isFromPackage(RedundantImportCheck.java:185)
    at com.puppycrawl.tools.checkstyle.checks.imports.RedundantImportCheck.visitToken(RedundantImportCheck.java:147)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:335)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:406)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:273)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:154)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:331)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:292)
    ... 5 more
Checkstyle ends with 1 errors.
````

Did not confirm if the file is compilable.
Edit:
Class is not compilable. 
http://java.sun.com/docs/books/jls/third_edition/html/packages.html#7.5
> It is a compile time error to import a type from the unnamed package.

**Comment by rnveach** [comment]
The file is from 2018, so this begs the question why are we getting the exception now.

**Comment by rnveach** [comment]
Exception started with version 6.8 .

**Comment by rnveach** [comment]
@romani @Rahulkhinchi03 

This is coming up now because of 3ca6f75b82b16e6c4a5a73a4387227deb0c5ff13 .
````
  sed -i.'' 's/#spoon/spoon/' projects-to-test-on.properties
-  groovy ./diff.groovy --listOfProjects projects-for-wercker.properties \
+ groovy ./diff.groovy --listOfProjects projects-to-test-on.properties \
````

We were manipulating `projects-to-test-on.properties` for spoon but accidentally running on `projects-for-wercker.properties`. We were not running regression on spoon at all.

The commit fixed this bug and brought the regression to light.

**Comment by nick-mancuso** [comment]
File is not compilable:

```
➜  java cat Test.java
import Enclosing;

import Test.Inner;

public class Test {
    class Inner{}
    public Test() {
        Enclosing<Object, Object> e = new Enclosing<>();
    }
}

class Enclosing<T, W>{}
➜  java javac Test.java 
Test.java:1: error: '.' expected
import Enclosing;
                ^
1 error
➜  java 


```

**Comment by romani** [comment]
If this file isn't compiled - we need to exclude it by config.

**Comment by rnveach** [comment]
This is what https://github.com/checkstyle/contribution/pull/609 is doing

**Comment by romani** [comment]
Fix is merged, relaunched https://app.circleci.com/pipelines/github/checkstyle/checkstyle?branch=master

**Comment by romani** [comment]
Passed
