### ISSUE TITLE
ImportControlLoader does not throw exception unrecognized element

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11983]
ConfigurationLoader throws an exception for unrecognized elements while using custom DTD but ImportControlLoader does not-

### ConfigurationLoader
```
➜  java git:(master) ✗ diff configuration_1_3.dtd configuration_custom.dtd 
8c8
< <!ELEMENT module (module|property|metadata|message)*>
---
> <!ELEMENT module (module|property|metadata|message|newelement)*>
52a53,58
>     value CDATA #REQUIRED
> >
> 
> <!ELEMENT newelement EMPTY>
> <!ATTLIST newelement
>     name NMTOKEN #REQUIRED


➜  java git:(master) ✗ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "CUSTOM_DTD" "configuration_1_4.dtd" >

<module name="Checker">
    <property name="fileExtensions" value="java,js,css,xml"/>
    <module name="LineLength">
        <property name="max" value="100"/>
        <newelement name="stuff_here" value="value"/>

    </module>
</module>


➜  java git:(master) ✗ java -jar checkstyle-10.3.1-all.jar -c config.xml Test.java
Exception in thread "main" java.lang.IllegalStateException: Unknown name:newelement.
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader.startElement(ConfigurationLoader.java:552)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
        at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:752)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1377)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:79)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:199)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:317)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:268)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:372)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:330)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:189)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
```

### ImportControlLoader
```
➜  java git:(master) ✗ diff import_control_1_4.dtd InputImportControlCustomDtd.dtd 
11c11
< <!ELEMENT import-control ((allow|disallow)*,(subpackage|file)*)>
---
> <!ELEMENT import-control ((allow|disallow|someElementNotSupported)*,(subpackage|file)*)>
31c31
< <!ELEMENT subpackage ((allow|disallow)*,(subpackage|file)*)>
---
> <!ELEMENT subpackage ((allow|disallow|someElementNotSupported)*,(subpackage|file)*)>
100a101,104
> 
> <!ELEMENT someElementNotSupported EMPTY>
> <!ATTLIST someElementNotSupported
>     %attlist.importrule;>



➜  java git:(master) ✗ cat config.xml 
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="ImportControl">
      <property name="file" value="InputImportControlCustomDtd.xml"/>
    </module>
  </module>
</module>

➜  java git:(master) ✗ cat InputImportControlCustomDtd.xml 
<?xml version="1.0"?>
<!DOCTYPE import-control PUBLIC
        "CUSTOM_DTD"
        "InputImportControlCustom.dtd">

<import-control pkg="com.puppycrawl.tools.checkstyle.checks.imports">
  <allow class="java.awt.Image"/>
  <subpackage name="importcontrol">
    <someElementNotSupported class="java.awt.Image" local-only="true"/>
  </subpackage>
</import-control>


➜  java git:(master) ✗ java -jar checkstyle-10.3.1-all.jar -c config.xml Test.java
Starting audit...
Audit done.
```

Just like `ConfigurationLoader`, `ImportControlLoader` should also throw an exception when it sees an unrecognized element.

**Comment by rnveach** [comment]
My only question is if DTDs are required, why don't we also require the DTD being used to be one we recognize? What is the purpose of using a custom DTD if we are going to force users to only the elements we know?

**Comment by Vyom-Yadav** [comment]
I think we should lock down the DTD instead of allowing unknown elements.

**Comment by romani** [comment]
Please use `diff -u`

**Comment by rnveach** [comment]
@romani Look at config's DTD and my comment. DTD in example here is a custom DTD, not one we created.

**Comment by romani** [comment]
@Vyom-Yadav, what is point of using custom dtd ?
We do not support any customization/hack.

**Comment by rnveach** [comment]
@romani This is steming from a PR where we don't throw exception on unknown element. Configuration loader does throw an exception on an unknown element. This is what lead to my comment on why we allow custom DTDs in the first place.

**Comment by romani** [comment]
Better to not be allow, it is our module and we are not going to support what user can do in his customization.
Placing bunch of code to enforce this might not reasonable also.

**Comment by Vyom-Yadav** [comment]
@romani 
> what is point of using custom dtd ?
> We do not support any customization/hack.

We do not support but it is allowed.

> Is it some survival of mutation trigger this question?

Yes, it is a mutation that has led to this discussion, see #11921. Though if we only use pre-defined DTD then the mutation can be simply killed by replacing the `else if` branch with `else`. But since using custom DTD was allowed so I chose to kill it that way.

**Comment by romani** [comment]
> Though if we only use pre-defined DTD then the mutation can be simply killed by replacing the else if branch with else

let do this.
 it is too much effort to support custom DTD , and nobody actually need this. if somebody request it in future, we will do this and proper test coverage.

**Comment by rnveach** [comment]
@romani So this issue is approved to enforce only our DTDs be allowed?

**Comment by romani** [comment]
Yes, we should allow only our dtd

**Comment by Vyom-Yadav** [comment]
@romani Just to be clear, there are two tasks needed to be done-

1. Kill mutation by replacing the `else if` branch with `else`
2. Add rule in `ImportControlLoader` to allow only usage of pre-defined DTD, using custom DTD will throw an exception, right?

**Comment by rnveach** [comment]
Approved label is needed.

I think all our XML loaders need to enforce our own DTDs. So `ConfigurationLoader` will have to change as well.

**Comment by romani** [comment]
>Kill mutation by replacing the else if branch with else

Please do this sooner, all other can wait.

**Comment by Vyom-Yadav** [comment]
> Please do this sooner, all other can wait.

Done

**Comment by romani** [comment]
I think we can close this issue.

**Comment by romani** [comment]
@Vyom-Yadav , please update issue title and descripton to:
- use `diff -u`
- focus on fact that we allow custom dtds in Checks xml files, better to now give user hope that we can change it and we will support this.
