### ISSUE TITLE
StringIndexOutOfBoundsException in AvoidStaticImport check trying to exclude inner class

### ISSUE THREAD

**Issue by ivanov-alex** [checkstyle/checkstyle#1209]
Checkstyle throws exception
```
SEVERE: StringIndexOutOfBoundsException occurred during the analysis of file StaticImportExample.java.
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1919)
	at com.puppycrawl.tools.checkstyle.checks.imports.AvoidStaticImportCheck.isExempt(AvoidStaticImportCheck.java:126)
	at com.puppycrawl.tools.checkstyle.checks.imports.AvoidStaticImportCheck.visitToken(AvoidStaticImportCheck.java:102)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:393)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:482)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:322)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:195)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:76)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:260)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:235)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:86)
```
when running 
`java -jar checkstyle-6.7-all.jar -c ./check_static_import.xml StaticImportExample.java`
on following files:
check_static_import.xml:
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name = "Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <module name="TreeWalker">
	    <module name="AvoidStaticImport">
	        <property name="excludes" value="test.StaticExample.InnerClass.*"/>
	    </module>
    </module>
</module>
```
StaticImportExample.java:
```
package test;

import static test.StaticExample.zero;
import static test.StaticExample.InnerClass;
import static test.StaticExample.InnerClass.one;

public class StaticImportExample{
    
    public static void main(String s[]) {
        System.out.println(zero);
        System.out.println(InnerClass.one);
        System.out.println(one);
    }
}
```
StaticExample.java:
```
package test;

public class StaticExample{
    public static Integer zero=0;
    
    public static class InnerClass {
        public static Integer one=1;
    }
}
```

**Comment by romani** [comment]
merged.
