### ISSUE TITLE
Upgrade Maven required Version for Contributors

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12111]
https://checkstyle.org/beginning_development.html
> 1. Ensure that Git, Java JDK >= 11 until JDK 17, maven >= 3.0.1 are installed.

Document states ATLEAST maven 3.0.1, however certain plugins are failing with versions within this range.

PMD has moved to now require >=3.8.2 . https://issues.apache.org/jira/projects/MPMD/issues/MPMD-353
````
Caused by: java.lang.NoSuchMethodError: 'org.fusesource.jansi.AnsiPrintStream org.fusesource.jansi.AnsiConsole.out()'
    at org.apache.maven.shared.utils.logging.MessageUtils.setColorEnabled(MessageUtils.java:113)
    at org.apache.maven.plugins.pmd.exec.Executor.setupPmdLogging(Executor.java:59)
````

maven-enforcer-plugin requires >=3.2.5
````
Caused by: org.apache.maven.plugin.PluginIncompatibleException: The plugin org.apache.maven.plugins:maven-enforcer-plugin:3.1.0 requires Maven version 3.2.5
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.checkRequiredMavenVersion(DefaultMavenPluginManager.java:283)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:166)
````

**Comment by strkkk** [comment]
fix is merged
