### ISSUE TITLE
pitest-survival-check-xml.groovy: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12132]
````
PS M:\checkstyleWorkspaceEclipse\checkstyle\.ci> groovy .\pitest-survival-check-xml.groovy

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/RickysPrograms/groovy-2.5.18/lib/groovy-2.5.18.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Caught: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at pitest-survival-check-xml.run(pitest-survival-check-xml.groovy:16)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
````

I would like to learn more about the script and how to execute it locally. I am having some issues with one my PRs and pitests, where each CI run says something different than the last run.

I think we should display a short usage statement on the expected/optional parameters.

**Comment by rnveach** [comment]
Fix was merged
