### ISSUE TITLE
pitest-survival-check-xml.groovy: IllegalArgumentException: character to be escaped is missing

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12133]
````
PS M:\checkstyleWorkspaceEclipse\checkstyle> groovy .\.ci\pitest-survival-check-xml.groovy pitest-xpath

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/RickysPrograms/groovy-2.5.18/lib/groovy-2.5.18.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Caught: java.lang.IllegalArgumentException: character to be escaped is missing
java.lang.IllegalArgumentException: character to be escaped is missing
        at java_lang_String$replaceAll$2.call(Unknown Source)
        at pitest-survival-check-xml.getMutation(pitest-survival-check-xml.groovy:207)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at pitest-survival-check-xml$_getSurvivingMutations_closure4.doCall(pitest-survival-check-xml.groovy:130)
        at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at pitest-survival-check-xml.getSurvivingMutations(pitest-survival-check-xml.groovy:124)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at pitest-survival-check-xml.checkPitestReport(pitest-survival-check-xml.groovy:101)
        at pitest-survival-check-xml.parseArgumentAndExecute(pitest-survival-check-xml.groovy:40)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at pitest-survival-check-xml.run(pitest-survival-check-xml.groovy:16)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
````

Expecting no exceptions when running the script.

Note: This is run on a Windows machine.

**Comment by nick-mancuso** [comment]
We should check all groovy scripts for windows path related issues.
