### ISSUE TITLE
StackOverflow at java.util.regex.*

### ISSUE THREAD

**Issue by vorburger** [checkstyle/checkstyle#1221]
java.util.regex.Matcher apparently has known issues which cause will cause StackOverflow for certain RegExps on certain input (Google it, there are various blog posts, JDK bug reports which are closed or non-action-ed). 

This "fact of live" (the JDK is not going to fix this) can cause Checkstyle to abruptly stop unexpectedly - without any indication as to which input file made it choke for what regexp (once you know that, you can use excludes or refine the regexps it seems).

Checkstyle should never fail that abruptly, and instead treat a StackOverflow at java.util.regex.* more gracefully.

I have a unit test illustrating this problem, and a PR with proposed fixes for this issue which I'll post in a minute.

PS: This bug can be confused with https://github.com/checkstyle/checkstyle/issues/48 (like I initially did), but is actually completely unrelated to that one, which is a StackOverflow in Checkstyle's own com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch code that uses recursion itself; this one is technically completely different - other than also being about a StackOverflow.

**Comment by vorburger** [comment]
Just FTR and for future web searching, here is how this problem actually exactly looks:

```
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.Character.codePointAt(Character.java:2338)
 	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3344)
 	at java.util.regex.Pattern$Curly.match0(Pattern.java:3770)
 	at java.util.regex.Pattern$Curly.match0(Pattern.java:3773)
 	at java.util.regex.Pattern$Curly.match0(Pattern.java:3773)```

**Comment by vorburger** [comment]
https://github.com/checkstyle/checkstyle/pull/1222
