### ISSUE TITLE
"Unable to persist cache file" if target directory is a symlink

### ISSUE THREAD

**Issue by ud1** [checkstyle/checkstyle#12238]
To optimize build performance, I create all of my project's "target" directories as symlinks (using the Linux `ln -s` command) to directories that exist on the tmp filesystem (memory filesystem).

But checkstyle plugins fails:

```
Caused by: java.lang.IllegalStateException: Unable to persist cache file.
    at com.puppycrawl.tools.checkstyle.Checker.destroy (Checker.java:180)
    at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle (DefaultCheckstyleExecutor.java:250)
    at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute (CheckstyleViolationCheckMojo.java:529)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.nio.file.FileAlreadyExistsException: /home/proj/myProject/target
    at sun.nio.fs.UnixException.translateToIOException (UnixException.java:88)
    at sun.nio.fs.UnixException.rethrowAsIOException (UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException (UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.createDirectory (UnixFileSystemProvider.java:384)
    at java.nio.file.Files.createDirectory (Files.java:674)
    at java.nio.file.Files.createAndCheckIsDirectory (Files.java:781)
    at java.nio.file.Files.createDirectories (Files.java:727)
    at com.puppycrawl.tools.checkstyle.PropertyCacheFile.persist (PropertyCacheFile.java:140)
    at com.puppycrawl.tools.checkstyle.Checker.destroy (Checker.java:177)
    at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle (DefaultCheckstyleExecutor.java:250)
    at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute (CheckstyleViolationCheckMojo.java:529)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

```

This is because `Files.createDirectories` throws an exception if the directory is a symbolic link. As a workaround, you can add a `file.exists()` or `file.isDirectory()` check before calling `Files.createDirectories`.

FYI
https://bugs.openjdk.org/browse/JDK-8130464

**Comment by romani** [comment]
Thanks a lot for report on this.
Can you reproduce problem by our CLI ?
You can set cache at Checker property https://checkstyle.org/config.html#Checker_Properties

If you have time please send PR to fix issue

**Comment by ud1** [comment]
[test.zip](https://github.com/checkstyle/checkstyle/files/9692397/test.zip)
Problem is reproducible by command line, see check.sh.

```
./check.sh 
Starting audit...
Audit done.
Exception in thread "main" java.lang.IllegalStateException: Unable to persist cache file.
        at com.puppycrawl.tools.checkstyle.Checker.destroy(Checker.java:186)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:419)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:339)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:196)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:131)
Caused by: java.nio.file.FileAlreadyExistsException: target
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398)
        at java.base/java.nio.file.Files.createDirectory(Files.java:700)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        at java.base/java.nio.file.Files.createDirectories(Files.java:753)
        at com.puppycrawl.tools.checkstyle.PropertyCacheFile.persist(PropertyCacheFile.java:151)
        at com.puppycrawl.tools.checkstyle.Checker.destroy(Checker.java:183)
        ... 4 more
```

**Comment by romani** [comment]
It would have to wait for laptop time to validate issue. We demand CLI output on all exactly on purpose to see all details transparently and be able to copy paste from text if description to reproduce quickly.
I would appreciate if you find to create/print all by shell/bash/cmd commands.

**Comment by relentless-pursuit** [comment]
I am able to reproduce the issue in my local. Currently, looking into the possible solution.
