### ISSUE TITLE
NullPointerException at java.util.regex.Pattern from com.puppycrawl.tools.checkstyle.checks.regexp.DetectorOptions.getPattern

### ISSUE THREAD

**Issue by vorburger** [checkstyle/checkstyle#1224]
I've hit the NPE below, funnily enough when using the Eclipse Checkstyle Plugin (v6.5.0 installed from http://eclipse-cs.sf.net/update today) on checkstyle's own code (this repository, not the Eclipse plug-in), and activating it's very own https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml !! ;-)

This NPE error clearly has nothing much to do with the Eclipse Plugin but comes from core CS.

I'll see if I still have the energy to submit a PR about this, or if I'll have to leave this one to you...

PS: Do you know if it's possible to easily update the core CS JAR used by the Eclipse Plugin?

```
Error
Thu Jun 18 19:43:03 CEST 2015
Errors running builder 'Checkstyle Builder' on project 'checkstyle'.

java.lang.NullPointerException
	at java.util.regex.Pattern.<init>(Pattern.java:1350)
	at java.util.regex.Pattern.compile(Pattern.java:1054)
	at com.puppycrawl.tools.checkstyle.checks.regexp.DetectorOptions.getPattern(DetectorOptions.java:200)
	at com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.processLines(MultilineDetector.java:70)
	at com.puppycrawl.tools.checkstyle.checks.regexp.RegexpMultilineCheck.processFiltered(RegexpMultilineCheck.java:51)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:270)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:159)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:300)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:171)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by vorburger** [comment]
This or a very similar error has also been raised elsewhere before, e.g. on http://sourceforge.net/p/eclipse-cs/bugs/312/, http://sonarqube.15.x6.nabble.com/NPE-from-Checkstyle-td5028077.html or http://marc.info/?l=sonar-user&m=134572101424647

**Comment by vorburger** [comment]
see PR https://github.com/checkstyle/checkstyle/pull/1226

**Comment by romani** [comment]
1) 
> "empty.regexp";

make it "regexp.empty"

2) 
> on checkstyle's own code

strange, we test our config on each commit by Travis, but that only mean that problem is interesting but not obvious.

3)
> PS: Do you know if it's possible to easily update the core CS JAR used by the Eclipse Plugin?

Eclipse-CS have problems with options recognition, metadata files have to be updated to reflect actual Check options. That is not automated process, work is manual and boring, that is why owner of Eclispe-cs always behind our library. But you can try and contribute it to speed up Eclipse-cs release.


4)
>  if (Strings.isNullOrEmpty(options.getFormat())) {
 options.getReporter().log(0, EMPTY);
 return;

please make single point of exit from method. Abrupt return is ok only certain cases, but not in your case.

**Comment by romani** [comment]
related issue - #1129

**Comment by romani** [comment]
merged.
