### ISSUE TITLE
ModuleReflectionUtil/guava isn't working in pure ant with custom libraries

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12385]
Identified at https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/935 and confirmed through https://github.com/rnveach/sevntu_issue_935 .

Our code in question:
https://github.com/checkstyle/checkstyle/blob/f741ccecd32fb4d45946ade13ce3f858684cfdfd/src/main/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtil.java#L57-L65

There are 2 issues going on with guava in pure ANT.
1) As the repo is right now, Guava fails to load a class it found itself with nothing else besides `ClassNotFoundException`.
2) Even switching the repo to our form of pure ant sample ( https://github.com/sevntu-checkstyle/checkstyle-samples/tree/master/ant-project and https://github.com/sevntu-checkstyle/checkstyle-samples/blob/master/ant-project/build.xml#L35 ) , guava does pass this time, but fails to find any 3rd party modules.
a. In this case, the only way for checkstyle to function with the 3rd party modules is for the module name to be the fully qualified classpath in the configuration file. The short name won't work anymore, while it is not an issue in maven or maven with ant.

Both of these are concerns in the main checkstyle library, but the direct problem is not clear yet.

1 sounds like classloading issue and is either a guava issue or our issue that we aren't verifying we can actually load the class before attempting to load it. It could also be ant is not being properly set up somehow, but even still, guava shouldn't fail like this.

2 sounds like another class loading issue and is either an issue with guava or the ant setup itself.

**Comment by pci-mthompson** [comment]
Can confirm everything was working with latest JDK8.  Switching to JDK11 is ok with the suggested workaround.

- Removed "-lib" argument from ant
- Removed xmlns  definition from CS
- Removed cs: from checkstyle task tag
- Updated config.xml to full class "com.github.sevntu.checkstyle.checks.coding.ForbidReturnInFinallyBlockCheck"
- Added these lines to build.xml

<path id="checkstyle.lib.path"><fileset dir="cs2" includes="*.jar"/></path>
<taskdef resource="com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties" classpathref="checkstyle.lib.path"/>

**Comment by pci-mthompson** [comment]
Another data point.  I tried again with my full checkstyle config and it fails with the same class not found for ForbidAnnotationElementValueCheck if I have MultipleVariableDeclarationsExtended included.  Commented out and everything is OK with numerous other base and SevNTU checks active.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="FinalParameters"/>
    <module name="com.github.sevntu.checkstyle.checks.coding.ForbidReturnInFinallyBlockCheck">
      <metadata name="net.sf.eclipsecs.core.comment" value="Added."/>
      <property name="severity" value="error"/>
    </module>
    <module name="MultipleVariableDeclarationsExtended">
      <metadata name="net.sf.eclipsecs.core.comment" value="Added."/>
    </module>
  </module>
</module>

**Comment by pci-mthompson** [comment]
[config.xml.txt](https://github.com/checkstyle/checkstyle/files/9983132/config.xml.txt)

**Comment by romani** [comment]
@pci-mthompson, if you are in open source are please share link to your code and ant config

**Comment by pci-mthompson** [comment]
Just upgraded to CS 11.0.1 and SevNTU 1.44.1 and looks like this is still happening.  Using ant-1.10.14.  Can't post the full build file but I think this is the important parts.
---------------------

<project name="build.ant4eclipse" default="build" xmlns:ant4eclipse="antlib:org.ant4eclipse" xmlns:cs="antlib:com.puppycrawl.tools.checkstyle.ant" xmlns:ivy="antlib:org.apache.ivy.ant">
   <taskdef resource="net/sf/antcontrib/antcontrib.properties"/>
   <taskdef resource="net/sf/antcontrib/antlib.xml"/>
...
            
            <if> <not><equals arg1="${ProjectType}" arg2="BSH"/></not>
               <then> <property name="csConfig" value="${st.dir}\projects\common\checkstyle\checkstyle-Java_PCI.xml" /> </then>
               <else> <property name="csConfig" value="${st.dir}\projects\common\checkstyle\checkstyle-BSH_PCI.xml" /> </else>
            </if>

            <echo />
            <echo>Checks : ${csConfig}</echo>
            <cs:checkstyle failOnViolation="false" config="${csConfig}">
               <fileset dir="${prj.dir}\src" includes="**/*.java" />
               <formatter type="xml" toFile="${prj.dir}\bin\checkstyle-result.xml" />
            </cs:checkstyle>
...



---------------------

BUILD FAILED
C:\PCI_Dev\jenkins\build.xml:178: java.lang.IllegalStateException: java.lang.ClassNotFoundException: com.github.sevntu.checkstyle.checks.annotation.ForbidAnnotationCheck
	at com.google.common.reflect.ClassPath$ClassInfo.load(ClassPath.java:381)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.puppycrawl.tools.checkstyle.utils.ModuleReflectionUtil.getCheckstyleModules(ModuleReflectionUtil.java:64)
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.generateThirdPartyNameToFullModuleName(PackageObjectFactory.java:308)
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.lambda$createObjectFromClassPath$0(PackageObjectFactory.java:251)
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.lazyLoad(PackageObjectFactory.java:414)
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createObjectFromClassPath(PackageObjectFactory.java:249)
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:191)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:151)
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:211)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:485)
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:211)
	at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.createRootModule(CheckstyleAntTask.java:404)
	at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.realExecute(CheckstyleAntTask.java:300)
	at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.execute(CheckstyleAntTask.java:282)

**Comment by pci-mthompson** [comment]
Also this is with JDK17, the previous workaround of adding the full package does work.  But that gets smashed if we update the config from the Eclipse GUI.

For example:
    <module name="com.github.sevntu.checkstyle.checks.coding.AvoidConstantAsFirstOperandInConditionCheck">

**Comment by romani** [comment]
Can you help us to reproduce it at https://github.com/sevntu-checkstyle/checkstyle-samples/tree/master/ant-project ?

**Comment by avadhutmali** [comment]
@romani  Is this bug still open? Can I take this up and reproduce it at checkstyle-samples/ant-project?

**Comment by romani** [comment]
we still waiting how to reproduce it reliably ..

@pci-mthompson , is there way to reproduce this on small test project?

**Comment by avadhutmali** [comment]
> we still waiting how to reproduce it reliably ..
> 
> [@pci-mthompson](https://github.com/pci-mthompson) , is there way to reproduce this on small test project?

@romani Reproduced both bugs on checkstyle-samples/ant-project on JDK 21, Windows 11, Ant 1.10.15, checkstyle-10.17.0-all.jar, sevntu-checks-1.44.1.jar.

Full reproduction details, configs and stack traces: https://gist.github.com/avadhutmali/21b8518b72add826837304053dfff556

Bug 1 — JARs loaded via -lib argument → Guava finds sevntu classes during scan but BuiltinClassLoader (Java 9+ system classloader) fails to load them → IllegalStateException wrapping ClassNotFoundException
Bug 2 — JARs loaded via classpathref in taskdef → Guava cannot scan sevntu JAR at all through Ant's classloader → short name resolution fails completely
