### ISSUE TITLE
Support latest pattern matching syntax in switch labels

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#12515]
**Pattern support in `switch` is still a preview feature.**

Now that https://openjdk.org/jeps/427 has superceded https://openjdk.org/jeps/420, pattern matching for `switch` statements and expressions has changed. The guarded patterns using `&&` in `switch` have been modified to use `when`:

```
➜  src cat Test.java
public class Test {
    static void m1(Object o) {
        // patterns in switch are guarded by 'when'
        switch (o) {
            case Integer i when i >= 0 -> System.out.println(i);
            case Integer i -> System.out.println(i << 1);
            default -> throw new IllegalStateException(
                    "Unexpected value: " + o);
        }
    }

    static void m2(Object o) {
        // patterns in expressions are still guarded by '&&'
        if (o instanceof String s && s.length() > 3) {
            System.out.println(s);
        } else {
            System.out.println("Not a string");
        }
    }
}
➜  src javac --enable-preview --release 19 Test.jav
error: Class names, 'Test.jav', are only accepted if annotation processing is explicitly requested
1 error
➜  src javac --enable-preview --release 19 Test.java
Note: Test.java uses preview features of Java SE 19.
Note: Recompile with -Xlint:preview for details.
➜  src java -jar checkstyle-10.4-all.jar -t Test.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/nick/IdeaProjects/tester/src/Test.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFileText(JavaParser.java:122)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFile(JavaParser.java:142)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:65)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:291)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: java.lang.IllegalStateException: 5:34: no viable alternative at input 'switch(o){caseIntegeriwheni>='
        ...
        at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:396)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.statement(JavaLanguageParser.java:6723)
        ... 18 more
Checkstyle ends with 1 errors.


```

A good summary of these changes can be found at https://blogs.oracle.com/javamagazine/post/java-pattern-matching-switch-when-null

--------------------
Note that the old patterns introduced in JEP 406/420 do not compile any longer:
```
➜  src cat Test.java                                 
public class Test {
    static void m1(Object o) {
        switch (o) {
            case Integer i && i >= 0 -> System.out.println(i);
            case Integer i -> System.out.println(i << 1);
            default -> throw new IllegalStateException(
                    "Unexpected value: " + o);
        }
    }
}
➜  src javac --enable-preview --release 19 Test.java 
Test.java:5: error: : or -> expected
            case Integer i && i >= 0 -> System.out.println(i);
                          ^
Test.java:5: error: illegal start of expression
            case Integer i && i >= 0 -> System.out.println(i);
                           ^
Test.java:5: error: ';' expected
            case Integer i && i >= 0 -> System.out.println(i);
                                    ^
Note: Test.java uses preview features of Java SE 19.
Note: Recompile with -Xlint:preview for details.
3 errors


```
We will need to remove old input related to old syntax.

**Comment by romani** [comment]
fix is merged

**Comment by rnveach** [comment]
@nrmancuso See https://github.com/rnveach/checkstyle/blob/pitest_require_this_2/config/projects-to-test/openjdk19-excluded.files#L32

**Comment by nrmancuso** [comment]
@rnveach https://github.com/checkstyle/checkstyle/pull/12660
