### ISSUE TITLE
RequireThis NPE

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12629]
````
$ cat TestClass.java
public class TestClass {
    private String field1;

    public static void foo56() {
        try {
        } catch(Exception e) {
            String field1 = "values";
            field1 = field1;
        }
    } 
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <property name="haltOnException" value="false"/>

    <module name="TreeWalker">
<module name="RequireThis">
</module>
    </module>
</module>

$ java -jar checkstyle-10.6.0-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:1: Got an exception - java.lang.NullPointerException
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.canBeReferencedFromStaticContext(RequireThisCheck.java:910)
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.getClassFrameWhereViolationIsFound(RequireThisCheck.java:765)
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.getFieldWithoutThis(RequireThisCheck.java:523)
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.processIdent(RequireThisCheck.java:475)
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.visitToken(RequireThisCheck.java:399)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:336)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:407)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:274)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:155)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:98)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:335)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:415)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:338)
    at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
[Checker]
Audit done.
Checkstyle ends with 1 errors.
````

Not expecting any exceptions.

**Comment by rnveach** [comment]
I have a fix for this, but I am looking into it and if it can kill a mutation.

**Comment by Kevin222004** [comment]
@rnveach I think you resolve the mutation but it is still null pointer exception right?

**Comment by rnveach** [comment]
> this code is still giving null pointer exception right

Current Code NPE Area: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java#L910
PR Code Area: https://github.com/checkstyle/checkstyle/pull/12628/files#diff-9bedac2996d0bc061df6fd8e1d2e6486e6009c22fd97ecaa0f2d81fca5e6cda5L910

PR Code will remove offending code, so NPE will no longer happen. It can be reconfirmed after PR is merged for closing this issue.

**Comment by nrmancuso** [comment]
Fixed via https://github.com/checkstyle/checkstyle/pull/12628:

```
➜  src cat TestClass.java 
public class TestClass {
    private String field1;

    public static void foo56() {
        try {
        } catch(Exception e) {
            String field1 = "values";
            field1 = field1;
        }
    }
}%                                                                                                             

➜  src javac TestClass.java 

➜  src cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="charset" value="UTF-8"/>
  <property name="severity" value="warning"/>
  <property name="haltOnException" value="false"/>

  <module name="TreeWalker">
    <module name="RequireThis">
    </module>
  </module>
</module>%                                                                                                     

➜  src java -jar checkstyle-10.7.0-all.jar -c config.xml TestClass.java 
Starting audit...
Audit done.


```

**Comment by rnveach** [comment]
Closing as it is fixed
