### ISSUE TITLE
Terminated the program due to a file parsing failure

### ISSUE THREAD

**Issue by Lucienxhh** [checkstyle/checkstyle#13021]
I have downloaded the latest checkstyle from: https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-10.9.3

i run this command to check the project [Questdb-6.6](https://github.com/questdb/questdb/releases/tag/6.6) using jdk11.
```bash
jdk11\bin\java.exe -jar checkstyle-10.9.3-all.jar -c CS_TEDIOUS.xml -f plain -o csResults\questdb-6.6.csv ..\projects\questdb-6.6
```

it gave no results but some error messages below.
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing ..\projects\questdb-6.6\benchmarks\src\main\java\module-info.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:306)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:223)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:415)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:338)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file E:\DownLoad\dataset\myTEDIOUS\..\projects\questdb-6.6\benchmarks\src\main\java\module-info.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:152)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:98)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:334)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:293)
        ... 5 more
Caused by: java.lang.IllegalStateException: 1:0: no viable alternative at input 'module'
        at com.puppycrawl.tools.checkstyle.JavaParser$CheckstyleErrorListener.syntaxError(JavaParser.java:255)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:424)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
        ... 9 more
Caused by: org.antlr.v4.runtime.NoViableAltException
        at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2031)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:470)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:396)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:380)
        ... 10 more
Checkstyle ends with 1 errors.

```

I think if parsing this file **module-info.java** fails, the program should not be terminated. The parsing of other Java files in the directory should continue.

**Comment by romani** [comment]
Use this filter in your config

https://checkstyle.org/config_filefilters.html#BeforeExecutionExclusionFileFilter_Examples

**Comment by romani** [comment]
Issue template ask to print config as plain text, CS_TEDIOUS.xml .

But I think your issue is clear.

**Comment by Lucienxhh** [comment]
> Issue template ask to print config as plain text, CS_TEDIOUS.xml .
> 
> But I think your issue is clear.

you are right, thanks a lot
