### ISSUE TITLE
Do not use cause excpetion message durging wrapping

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13023]
detected at https://github.com/checkstyle/checkstyle/pull/13016#discussion_r1173731475

we should update all code to not put caught exception message to exception that we are going to throw. 
```
        catch (ParserConfigurationException | SAXException ex) {
            throw new CheckstyleException("unable to parse " + uri
                    + " - " + ex.getMessage(), ex);
        }
```

should be:
```
        catch (ParserConfigurationException | SAXException ex) {
            throw new CheckstyleException("unable to parse " + uri, ex);
        }
```

we need to update all other cases like this.

**Comment by romani** [comment]
Where to fix:
```
~/java/github/romani/checkstyle/src/main/java [master|✔] 
$ ag -C 4 "ex.getMessage()"
com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.java
287-            throw new CheckstyleException(UNABLE_TO_FIND_ERROR_MESSAGE + sourceName, ex);
288-        }
289-        catch (final ParserConfigurationException | SAXException ex) {
290-            final String message = String.format(Locale.ROOT, "Unable to parse %s - %s",
291:                    sourceName, ex.getMessage());
292-            throw new CheckstyleException(message, ex);
293-        }
294-        catch (final IOException ex) {
295-            throw new CheckstyleException("Unable to read " + sourceName, ex);
296-        }
297-        catch (final NumberFormatException ex) {
298-            final String message = String.format(Locale.ROOT, "Number format exception %s - %s",
299:                    sourceName, ex.getMessage());
300-            throw new CheckstyleException(message, ex);
301-        }
302-    }
303-

com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
316-        }
317-        catch (final SAXParseException ex) {
318-            final String message = String.format(Locale.ROOT, SAX_PARSE_EXCEPTION_FORMAT,
319-                    UNABLE_TO_PARSE_EXCEPTION_PREFIX,
320:                    ex.getMessage(), ex.getLineNumber(), ex.getColumnNumber());
321-            throw new CheckstyleException(message, ex);
322-        }
323-        catch (final ParserConfigurationException | IOException | SAXException ex) {
324-            throw new CheckstyleException(UNABLE_TO_PARSE_EXCEPTION_PREFIX, ex);

com/puppycrawl/tools/checkstyle/Checker.java
476-            }
477-        }
478-        catch (final CheckstyleException ex) {
479-            throw new CheckstyleException("cannot initialize module " + name
480:                    + " - " + ex.getMessage(), ex);
481-        }
482-        if (child instanceof FileSetCheck) {
483-            final FileSetCheck fsc = (FileSetCheck) child;
484-            fsc.init();

com/puppycrawl/tools/checkstyle/TreeWalker.java
124-            }
125-        }
126-        catch (final CheckstyleException ex) {
127-            throw new CheckstyleException("cannot initialize module " + name
128:                    + " - " + ex.getMessage(), ex);
129-        }
130-        if (module instanceof AbstractCheck) {
131-            final AbstractCheck check = (AbstractCheck) module;
132-            check.init();

com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java
271-            return loader.getRoot();
272-        }
273-        catch (ParserConfigurationException | SAXException ex) {
274-            throw new CheckstyleException("unable to parse " + uri
275:                    + " - " + ex.getMessage(), ex);
276-        }
277-        catch (IOException ex) {
278-            throw new CheckstyleException("unable to read " + uri, ex);
279-        }

```

**Comment by romani** [comment]
this even looks like good new Check to implement in future, as it is very common mistake.

**Comment by AayushSaini101** [comment]
I am on it. Can i create another issue to create new check for this

**Comment by AayushSaini101** [comment]
Hi @romani Is it necessary to remove the message came from the TreeWalker ?
```
 catch (final CheckstyleException ex) {
            throw new CheckstyleException("cannot initialize module " + name, ex);
   }
```
We cannot able to get the proper name in the following test case: 
```
[ERROR]   ConstantNameCheckTest.testIllegalRegexp:63 Invalid exception message
expected: …ng.ConstantNameCheck - illegal value '\' for property 'format'
but was : …ng.ConstantNameCheck
```

**Comment by romani** [comment]
>name, ex);

This is good.

We need to fix code of this pattern `ex.getMessage(), ex);`

**Comment by AayushSaini101** [comment]
> com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java
> 271-            return loader.getRoot();
> 272-        }
> 273-        catch (ParserConfigurationException | SAXException ex) {
> 274-            throw new CheckstyleException("unable to parse " + uri
> 275:                    + " - " + ex.getMessage(), ex);
> 276-        }
> 277-        catch (IOException ex) {
> 278-            throw new CheckstyleException("unable to read " + uri, ex);
> 279-        }

@romani I guess for this issue we need to only change class message only. We can create another issue for the remaining one

**Comment by romani** [comment]
I am not sure what you mean by remaining, but you can create separate issue to discuss problem that you see

**Comment by romani** [comment]
@Youssefalaa7 , how much is left to be updated ?
to split it in multiple PRs we need to make list of file:line that needs to be updated.


Sounds like we need Check to detect such situations.

**Comment by Youssefalaa7** [comment]
@romani there is a lot left to be updated i can help to collect this list to create an issue so that each contrubuter change one and all tests that this change will affect

**Comment by Youssefalaa7** [comment]
@romani i created a check for this case and these are what need to be updated

[ERROR] [checkstyle] [WARN] /home/youssef/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java:483:13: Avoid using 'exc.getMessage()' in throw statement within catch block. The exception message is already available through the cause chain. [NoGetMessageInCatchThrow]
[ERROR] [checkstyle] [WARN] /home/youssef/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Main.java:458:13: Avoid using 'exc.getMessage()' in throw statement within catch block. The exception message is already available through the cause chain. [NoGetMessageInCatchThrow]
[ERROR] [checkstyle] [WARN] /home/youssef/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java:1190:13: Avoid using 'exc.getMessage()' in throw statement within catch block. The exception message is already available through the cause chain. [NoGetMessageInCatchThrow]
[ERROR] [checkstyle] [WARN] /home/youssef/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java:481:13: Avoid using 'exc.getMessage()' in throw statement within catch block. The exception message is already available through the cause chain. [NoGetMessageInCatchThrow]
[ERROR] [checkstyle] [WARN] /home/youssef/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java:499:13: Avoid using 'exc.getMessage()' in throw statement within catch block. The exception message is already available through the cause chain. [NoGetMessageInCatchThrow]
[ERROR] [checkstyle] [WARN] /home/youssef/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java:518:13: Avoid using 'exc.getMessage()' in throw statement within catch block. The exception message is already available through the cause chain. [NoGetMessageInCatchThrow]
[ERROR] [checkstyle] [WARN] /home/youssef/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java:564:13: Avoid using 'exc.getMessage()' in throw statement within catch block. The exception message is already available through the cause chain. [NoGetMessageInCatchThrow]
[ERROR] [checkstyle] [WARN] /home/youssef/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java:809:17: Avoid using 'exc.getMessage()' in throw statement within catch block. The exception message is already available through the cause chain. [NoGetMessageInCatchThrow]
[ERROR] [checkstyle] [WARN] /home/youssef/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/utils/ChainedPropertyUtilTest.java:135:13: Avoid using 'exc.getMessage()' in throw statement within catch block. The exception message is already available through the cause chain. [NoGetMessageInCatchThrow]

**Comment by romani** [comment]
@Youssefalaa7 , please send fixes for all code before Check,  this will reduce PR for Check.
and we can use all such bad code in Inputs.

**Comment by romani** [comment]
@Youssefalaa7 , lets create new issue with discussion on design of new Check. 
https://checkstyle.org/report_issue.html#How_to_request_new_Check.2FModule.3F, attention to "Example of good new Check proposal is ..."

**Comment by Youssefalaa7** [comment]
@romani,Thanks I understand. I will finish all the fixes for this existing issue first and then focus on the new check

**Comment by romani** [comment]
these are all cases left
These wrapped in LocalizedMessage as these examples should not be removed right?

```
        catch (final CheckstyleException exc) {
            throw new CheckstyleException(
                    getLocalizedMessage("Checker.setupChildModule", name, exc.getMessage()), exc);
        }
```

```
        catch (final IOException exc) {
            final LocalizedMessage loadPropertiesExceptionMessage = new LocalizedMessage(
                    Definitions.CHECKSTYLE_BUNDLE, Main.class,
                    LOAD_PROPERTIES_EXCEPTION, file.getAbsolutePath());
            throw new CheckstyleException(loadPropertiesExceptionMessage.getMessage(), exc);
        }
```


https://github.com/checkstyle/checkstyle/blob/972c64c00f091fbad63192855f75a4a8cfdce2fe/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L482-L485
message
https://github.com/checkstyle/checkstyle/blob/972c64c00f091fbad63192855f75a4a8cfdce2fe/src/main/resources/com/puppycrawl/tools/checkstyle/messages.properties#L10


Example of message in exception:
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker -
   cannot initialize module SuppressionXpathFilter  -
   Unable to parse suppressions-xpath.xml - Premature end of file.
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:480)
        at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:207)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:411)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:338)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: 
  cannot initialize module SuppressionXpathFilter - 
  Unable to parse suppressions-xpath.xml - Premature end of file.
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:128)
        at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:207)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:475)
        ... 5 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException:
 Unable to parse suppressions-xpath.xml - Premature end of file.
        at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.getSuppressionLoader(SuppressionsLoader.java:292)
        at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadXpathSuppressions(SuppressionsLoader.java:267)
        at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadXpathSuppressions(SuppressionsLoader.java:253)
        at com.puppycrawl.tools.checkstyle.filters.SuppressionXpathFilter.finishLocalSetup(SuppressionXpathFilter.java:583)
        at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:203)
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:123)

```

considering this anti-pattern was done to show user all problems in most to exception message as concatentation of most "Caused by" exceptions. 
It is very clear on usage on user side, but to avoid damage user experience, let not fix code and keep it as is, as it is existed for long time.
