### ISSUE TITLE
Have "cursor" position in CheckstyleException

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/checkstyle#13049]
**How it works Now:**

A Java parser exception in checkstyle itself contains the file name but not position inside the file being parsed.
Only the nested IllegalStateException actually has the position. Real world example (paths have been shortened), where "64:37" marks the wanted position:
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C:\dev\...\SomeClass.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:307)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:146)
	at net.sf.eclipsecs.core.jobs.AuditorJob.runInWorkspace(AuditorJob.java:73)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file C:\dev\...\SomeClass.java.
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:153)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:98)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:335)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
	... 5 more
Caused by: java.lang.IllegalStateException: 64:37: mismatched input '(' expecting ';'
	at com.puppycrawl.tools.checkstyle.JavaParser$CheckstyleErrorListener.syntaxError(JavaParser.java:255)
```

It would be nice if the cursor position of a parser exception would be available by a method, field or other more formal method than "check nested exception types and messages".

**Is your feature request related to a problem? Please describe.**
It would be more simple to point to the problematic file and position in all kinds of checkstyle integrations. Specifically, I was thinking about pointing to the exact parser problem location in eclipse-cs by getting the location from the exception. It's always bad if a tool breaks on a (valid) code file, and the user has to guess where exactly the problem happened.

**Describe the solution you'd like**
I'm not sure if a more specialized subclass of the general CheckstyleException (with additional fields) would be reasonable, or if other possibilities exist to easily transfer the position without additional fields and methods. If you can foresee that this kind of exception nesting remains stable for eternity, then I could also live with that (and parse the exceptions on the eclipse side).

**Comment by Bananeweizen** [comment]
@nrmancuso No I don't expect the exceptions to be shuffled around. I just would like to see a stable API for getting the parser position. If that stable API is "It will remain as it is right now for eternity" then that's also fine for me, because having 2 or 3 nested if-statements for parsing this in eclipse-cs is no big effort. If we wanted to create a more formal API, then I would probably create something like
```
CheckstyleParserException extends CheckstyleException {
String path;
int row, column;
...
}
``` and I would catch the IllegalStateException and rethrow it wrapped into an instance of this new exception. However, I have no idea how well that fits the remaining checkstyle architecture and design.

@romani I'm aware that eclipse-cs should not confuse users by pointing at code positions that are actually fine. However, right now even the error message itself is rather unhelpful and confusing, and I would like to improve at least the error message (and have an optional error marker for advanced users maybe).

**Comment by romani** [comment]
> It would be nice if the cursor position of a parser exception would be available by a method, field or other more formal method than "check nested exception types and messages".

I probably missed this .... ok so we already have column, and you want it to be in Exception class field, rather then in message. right ?
