### ISSUE TITLE
How to correctly configure to check file headers for different files?

### ISSUE THREAD

**Issue by pandaapo** [checkstyle/checkstyle#13079]
I am try to check file header for different file types separately. I prepared header1.txt for java file, header2.txt for properties file.
```
<project root>
        └── style           
                └── checkstyle.xml   
                └── header1.txt
                └── header2.txt
```
And I configured my checkStyle.xml like this:
```
<module name="Checker">
  ...
  <module name="Header">
    <property name="headerFile" value="/header1.txt"/>
    <property name="fileExtensions" value="java"/>
  </module>
  <module name="Header">
    <property name="headerFile" value="/header2.txt"/>
    <property name="fileExtensions" value="properties"/>
  </module>
  ...
</module>
```
It can execute checking correctly in IDE when I check a file via click the button of CheckStyle plugin. But when run `gradlew checkMain` to check, exception will be thrown.
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: /header1.header
        at com.puppycrawl.tools.checkstyle.utils.CommonUtil.getResourceFromClassPath(CommonUtil.java:457)
        at com.puppycrawl.tools.checkstyle.utils.CommonUtil.getFilepathOrClasspathUri(CommonUtil.java:434)
        at com.puppycrawl.tools.checkstyle.utils.CommonUtil.getUriByFilename(CommonUtil.java:385)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean$UriConverter.convert(AutomaticBean.java:341)
        ... 47 more
```

How to configure this value correctly?

**Comment by rnveach** [comment]
Files are relative to the folder you are in, not relative to the configuration file.

Either provide a full file path, or a proper relative one from your current working directory when you execute Checkstyle.

I recommend not using paths starting with `/` unless you are specifying a classpath location.

It looks like this information is missing from https://checkstyle.org/property_types.html#URI .
