### ISSUE TITLE
ITs rule43onestatement/OneStatementPerLineTest is failing

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#1348]
src/it/java/com/google/checkstyle/test/chapter4formatting/rule43onestatement/OneStatementPerLineTest.java

is failing https://travis-ci.org/checkstyle/checkstyle/jobs/70314374#L699
```
oneStatmentTest(com.google.checkstyle.test.chapter4formatting.rule43onestatement.OneStatementPerLineTest)  Time elapsed: 0.127 sec  <<< FAILURE!
java.lang.AssertionError: error message 0 expected:<0> but was:<6>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.google.checkstyle.test.base.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:140)
	at com.google.checkstyle.test.base.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:109)
	at com.google.checkstyle.test.base.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:94)
	at 
```
, due to build problem it was not noticed.

Test has to be resolved. Problem caused by #1237.

**Comment by romani** [comment]
problem was missed due to "The Failsafe Plugin will not fail the build during the integration-test phase,...." https://maven.apache.org/surefire/maven-failsafe-plugin/ . Verify goal was added to Travis.

**Comment by romani** [comment]
@MEZk , please take a look at missed/failed test ASAP please.
On a completion please remove Ignore annotation from test.

**Comment by romani** [comment]
merged.
