### ISSUE TITLE
MacroExecutionException: TypecastParenPadCheck: Failed to find setter javadoc for property 'option'

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13867]
after changes:
```
$ git diff src/xdocs/checks/whitespace/typecastparenpad.xml.template
diff --git a/src/xdocs/checks/whitespace/typecastparenpad.xml.template b/src/xdocs/checks/whitespace/typecastparenpad.xml.template
index 43686e1..a205273 100644
--- a/src/xdocs/checks/whitespace/typecastparenpad.xml.template
+++ b/src/xdocs/checks/whitespace/typecastparenpad.xml.template
@@ -18,22 +18,10 @@
 
       <subsection name="Properties" id="Properties">
         <div class="wrapper">
-          <table>
-            <tr>
-              <th>name</th>
-              <th>description</th>
-              <th>type</th>
-              <th>default value</th>
-              <th>since</th>
-            </tr>
-            <tr>
-              <td>option</td>
-              <td>Specify policy on how to pad parentheses.</td>
-              <td><a href="../../property_types.html#PadOption">PadOption</a></td>
-              <td><code>nospace</code></td>
-              <td>3.2</td>
-            </tr>
-          </table>
+          <macro name="properties">
+            <param name="modulePath"
+                   value="src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPadCheck.java"/>
+          </macro>
         </div>
       </subsection>

```
error during `mvn clean test`
```
[INFO] Running com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.373 s <<< FAILURE! -- in com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest
[ERROR] com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest -- Time elapsed: 0.373 s <<< ERROR!
org.apache.maven.doxia.parser.ParseException: Macro execution failed: TypecastParenPadCheck: Failed to find setter javadoc for property 'option'
  at org.apache.maven.doxia.parser.AbstractXmlParser.parse(AbstractXmlParser.java:165)
  at org.apache.maven.doxia.parser.XhtmlBaseParser.parse(XhtmlBaseParser.java:92)
  at org.apache.maven.doxia.module.xdoc.XdocParser.parse(XdocParser.java:113)
  at com.puppycrawl.tools.checkstyle.site.XdocsTemplateParser.parse(XdocsTemplateParser.java:76)
  at org.apache.maven.doxia.parser.AbstractParser.parse(AbstractParser.java:207)
  at com.puppycrawl.tools.checkstyle.internal.utils.XdocGenerator.generateXdocContent(XdocGenerator.java:66)
  at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.generateXdocContent(XdocsPagesTest.java:238)
....
Caused by: org.apache.maven.doxia.macro.MacroExecutionException: TypecastParenPadCheck: Failed to find setter javadoc for property 'option'
  at com.puppycrawl.tools.checkstyle.site.SiteUtil.assertAllPropertySetterJavadocsAreFound(SiteUtil.java:489)
  at com.puppycrawl.tools.checkstyle.site.SiteUtil.getPropertiesJavadocs(SiteUtil.java:464)
  at com.puppycrawl.tools.checkstyle.site.PropertiesMacro.writeTablePropertiesRows(PropertiesMacro.java:159)
  at com.puppycrawl.tools.checkstyle.site.PropertiesMacro.writePropertiesTable(PropertiesMacro.java:109)
  at com.puppycrawl.tools.checkstyle.site.PropertiesMacro.execute(PropertiesMacro.java:81)
  at org.apache.maven.doxia.parser.AbstractParser.executeMacro(AbstractParser.java:145)
  at com.puppycrawl.tools.checkstyle.site.XdocsTemplateParser.processMacroEnd(XdocsTemplateParser.java:187)
  at com.puppycrawl.tools.checkstyle.site.XdocsTemplateParser.handleEndTag(XdocsTemplateParser.java:116)
  at org.apache.maven.doxia.parser.AbstractXmlParser.parseXml(AbstractXmlParser.java:238)
  at org.apache.maven.doxia.parser.AbstractXmlParser.parse(AbstractXmlParser.java:156)
  ... 67 more
```

**Comment by romani** [comment]
same for ParenPadCheck:
```
Caused by: org.apache.maven.doxia.macro.MacroExecutionException: ParenPadCheck: Failed to find setter javadoc for property 'option'
	at com.puppycrawl.tools.checkstyle.site.SiteUtil.assertAllPropertySetterJavadocsAreFound(SiteUtil.java:489)
	at com.puppycrawl.tools.checkstyle.site.SiteUtil.getPropertiesJavadocs(SiteUtil.java:464)
	at com.puppycrawl.tools.checkstyle.site.PropertiesMacro.writeTablePropertiesRows(PropertiesMacro.java:159)
	at com.puppycrawl.tools.checkstyle.site.PropertiesMacro.writePropertiesTable(PropertiesMacro.java:109)
	at com.puppycrawl.tools.checkstyle.site.PropertiesMacro.execute(PropertiesMacro.java:81)
	at org.apache.maven.doxia.parser.AbstractParser.executeMacro(AbstractParser.java:145)
	at com.puppycrawl.tools.checkstyle.site.XdocsTemplateParser.processMacroEnd(XdocsTemplateParser.java:187)
	at com.puppycrawl.tools.checkstyle.site.XdocsTemplateParser.handleEndTag(XdocsTemplateParser.java:116)
	at org.apache.maven.doxia.parser.AbstractXmlParser.parseXml(AbstractXmlParser.java:238)
	at org.apache.maven.doxia.parser.AbstractXmlParser.parse(AbstractXmlParser.java:156)
	... 67 more
```

**Comment by rnveach** [comment]
All the checks have custom super classes, which is where the properties that were failed to find are located.
`TypecastParenPadCheck` has `AbstractParenPadCheck`. `ParenPadCheck` has `AbstractParenPadCheck`.

I assume the list will grow as there are others like `AbstractSuperCheck` and such.

We talked about this before as this tool uses Checkstyle and Checkstyle doesn't support multi-files or examining the classpath.

**Comment by romani** [comment]
here is code to change:
https://github.com/checkstyle/checkstyle/blob/4ce632888c00606a6c44417fcd743c34e7e25347/src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java#L175-L187

**Comment by relentless-pursuit** [comment]
I am on it.
