### ISSUE TITLE
migrate IllegalToken to properties macros

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#13860]
```
[INFO] Running com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest
[ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.079 s <<< FAILURE! -- in com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest
[ERROR] com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.testAllCheckSections -- Time elapsed: 0.175 s <<< FAILURE!
illegaltoken.xml section 'IllegalToken' should have all the acceptable tokens
expected: set of any supported tokens
but was : TokenTypes
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validatePropertySectionPropertyTokens(XdocsPagesTest.java:1069)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validatePropertySectionProperties(XdocsPagesTest.java:964)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validatePropertySection(XdocsPagesTest.java:805)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validateCheckSection(XdocsPagesTest.java:662)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.testAllCheckSections(XdocsPagesTest.java:579)

```

**Comment by piyush-1234** [comment]
hi romani, i want to pick this issue.

**Comment by romani** [comment]
@piyush-1234 , I highly recommend to read https://github.com/checkstyle/checkstyle/wiki/To-GSoC-participant and start working from issues we suggest in this wiki page.

**Comment by piyush-1234** [comment]
> @piyush-1234 , I highly recommend to read https://github.com/checkstyle/checkstyle/wiki/To-GSoC-participant and start working from issues we suggest in this wiki page.

thanx for recommendation @romani, starting with the issues having tag gsoc first issue.

**Comment by relentless-pursuit** [comment]
I am on it

**Comment by relentless-pursuit** [comment]
I am stuck on this error:
```
illegaltoken.xml section 'IllegalToken' should have all the acceptable tokens
expected: set of any supported tokens
but was : TokenTypes
Expected :set of any supported tokens
Actual   :TokenTypes
```

The only reference i found for `set of any supported token` is descendanttoken.xml. 
```
            <tr>
              <td>tokens</td>
              <td>tokens to check</td>
              <td>set of any supported
                <a href="../../apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html">
                    tokens</a>
              </td>
              <td><code>empty</code></td>
              <td>3.2</td>
            </tr>
```

Any clue on how to progress? Should i alter the xml to make the test cases pass?

**Comment by relentless-pursuit** [comment]
Update: 
```
<tr>
  <td>tokens</td>
  <td>tokens to check</td>
  <td>set of any supported
    <a href="../../apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html">
        tokens</a>
  </td>
  <td>
    <a href="../../apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LABELED_STAT">LABELED_STAT</a>
      .
  </td>
  <td>3.2</td>
</tr>
```
Logs:
```
Column 0: tokens
Column 1: tokens to check
Column 2: TokenTypes
Column 3: LABELED_STAT                 .
Column 4: 3.2
```
The text content of the third <td> element in the XML is "set of any supported tokens", but the debug output for Column 2 is "TokenTypes", which is a mismatch. I am not sure why is it happening but still trying to look in PropertiesMacros. If any insights, please let me know.
