### ISSUE TITLE
BaseCheckTestSupport.verify() fails on Windows

### ISSUE THREAD

**Issue by WonderCsabo** [checkstyle/checkstyle#1388]
Lots of test are failing on Windows due to this method, like this:

```
java.lang.NumberFormatException: For input string: "\Repo\checkstyle\src\it\resources\com\google\checkstyle\test\chapter2filebasic\rule21filename\OuterTypeFilenameInput_3.java"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.google.checkstyle.test.base.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:138)
        at com.google.checkstyle.test.base.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:109)
        at com.google.checkstyle.test.base.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:94)
        at com.google.checkstyle.test.chapter2filebasic.rule21filename.OuterTypeFilenameTest.outerTypeFilenameTest_3(OuterTypeFilenameTest.java:61)

```

The problem is that on Windows, full paths contain a `:` sign, which denotes a device in the path: *D:\folder\file*. The method in question ignores this, and reads the string part after the first occurrence of `:`. This is incorrect, and also results in an exception, because that part will not be a number on Windows.

**Comment by romani** [comment]
merged.
