### ISSUE TITLE
Migrate DescendantToken to properties macros

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#13885]
there is problem to migrate DescendantToken to property macro.

```
diff --git a/config/checkstyle-non-main-files-suppressions.xml b/config/checkstyle-non-main-files-suppressions.xml
index 9c93ac93b..e0d773e8d 100644
--- a/config/checkstyle-non-main-files-suppressions.xml
+++ b/config/checkstyle-non-main-files-suppressions.xml
@@ -398,8 +398,6 @@
          files="src[\\/]xdocs[\\/]checks[\\/]misc[\\/]avoidescapedunicodecharacters.xml.template"/>
   <suppress id="propertiesMacroMustExist"
          files="src[\\/]xdocs[\\/]checks[\\/]misc[\\/]commentsindentation.xml.template"/>
-  <suppress id="propertiesMacroMustExist"
-         files="src[\\/]xdocs[\\/]checks[\\/]misc[\\/]descendanttoken.xml.template"/>
   <suppress id="propertiesMacroMustExist"
          files="src[\\/]xdocs[\\/]checks[\\/]misc[\\/]finalparameters.xml.template"/>
```

```
diff --git a/src/xdocs/checks/misc/descendanttoken.xml.template b/src/xdocs/checks/misc/descendanttoken.xml.template
index bfcadc6b9..fd17ab36e 100644
--- a/src/xdocs/checks/misc/descendanttoken.xml.template
+++ b/src/xdocs/checks/misc/descendanttoken.xml.template
@@ -25,87 +25,10 @@
 
       <subsection name="Properties" id="Properties">
         <div class="wrapper">
-          <table>
-            <tr>
-              <th>name</th>
-              <th>description</th>
-              <th>type</th>
-              <th>default value</th>
-              <th>since</th>
-            </tr>
-            <tr>
-              <td>limitedTokens</td>
-              <td>Specify set of tokens with limited occurrences as descendants.</td>
-              <td>
-                subset of tokens
-                <a href="../../apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html">TokenTypes</a>
-              </td>
-              <td><code>{}</code></td>
-              <td>3.2</td>
-            </tr>
-            <tr>
-              <td>maximumDepth</td>
-              <td>Specify the maximum depth for descendant counts.</td>
-              <td><a href="../../property_types.html#int">int</a></td>
-              <td><code>2147483647</code></td>
-              <td>3.2</td>
-            </tr>
-            <tr>
-              <td>maximumMessage</td>
-              <td>Define the violation message when the maximum count is exceeded.</td>
-              <td><a href="../../property_types.html#String">String</a></td>
-              <td><code>null</code></td>
-              <td>3.2</td>
-            </tr>
-            <tr>
-              <td>maximumNumber</td>
-              <td>Specify a maximum count for descendants.</td>
-              <td><a href="../../property_types.html#int">int</a></td>
-              <td><code>2147483647</code></td>
-              <td>3.2</td>
-            </tr>
-            <tr>
-              <td>minimumDepth</td>
-              <td>Specify the minimum depth for descendant counts.</td>
-              <td><a href="../../property_types.html#int">int</a></td>
-              <td><code>0</code></td>
-              <td>3.2</td>
-            </tr>
-            <tr>
-              <td>minimumMessage</td>
-              <td>Define the violation message when the minimum count is not reached.</td>
-              <td><a href="../../property_types.html#String">String</a></td>
-              <td><code>null</code></td>
-              <td>3.2</td>
-            </tr>
-            <tr>
-              <td>minimumNumber</td>
-              <td>Specify a minimum count for descendants.</td>
-              <td><a href="../../property_types.html#int">int</a></td>
-              <td><code>0</code></td>
-              <td>3.2</td>
-            </tr>
-            <tr>
-              <td>sumTokenCounts</td>
-              <td>
-                Control whether the number of tokens found should be calculated
-                from the sum of the individual token counts.
-              </td>
-              <td><a href="../../property_types.html#boolean">boolean</a></td>
-              <td><code>false</code></td>
-              <td>5.0</td>
-            </tr>
-            <tr>
-              <td>tokens</td>
-              <td>tokens to check</td>
-              <td>set of any supported
-                <a href="../../apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html">
-                    tokens</a>
-              </td>
-              <td><code>empty</code></td>
-              <td>3.2</td>
-            </tr>
-          </table>
+          <macro name="properties">
+            <param name="modulePath"
+                   value="src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java"/>
+         </macro>
         </div>
       </subsection>
```
Failure:
```
descendanttoken.xml section 'DescendantToken' should have all the acceptable tokens
expected: set of any supported tokens
but was : TokenTypes
Expected :set of any supported tokens
Actual   :TokenTypes
<Click to see difference>


	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validatePropertySectionPropertyTokens(XdocsPagesTest.java:1069)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validatePropertySectionProperties(XdocsPagesTest.java:964)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validatePropertySection(XdocsPagesTest.java:805)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validateCheckSection(XdocsPagesTest.java:662)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.testAllCheckSections(XdocsPagesTest.java:579)
	at [[Reflective call: 4 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at [[Testing framework: 27 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at [[Testing framework: 9 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at [[Testing framework: 22 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

**Comment by nrmancuso** [comment]
@relentless-pursuit please as some details/context to your issue description, it is not clear what the problem is.

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit please add some details/context to your issue description, it is not clear what the problem is.

Updated. Please let me know if any further clarification required.

**Comment by relentless-pursuit** [comment]
I have been working on a similar issue. If approved, I can push my PR

**Comment by relentless-pursuit** [comment]
I am on it.
