### ISSUE TITLE
remove openjdk25 excludes for implicitly declared classes

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#13987]
Reading: https://openjdk.org/jeps/445

>Summary
Evolve the Java language so that students can write their first programs without needing to understand language features designed for large programs. Far from using a separate dialect of Java, students can write streamlined declarations for single-class programs and then seamlessly expand their programs to use more advanced features as their skills grow. This is a [preview language feature](https://openjdk.org/jeps/12).

Example of failure:
```bash
➜  src cat Unnamed.java
void main() {}
➜  src javac --release 21 --enable-preview Unnamed.java
Note: Unnamed.java uses preview features of Java SE 21.
Note: Recompile with -Xlint:preview for details.
➜  src java -jar checkstyle-10.12.3-all.jar -t Unnamed.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/nick/IdeaProjects/tester/src/Unnamed.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFileText(JavaParser.java:122)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFile(JavaParser.java:142)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:65)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:291)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: java.lang.IllegalStateException: 1:0: no viable alternative at input 'void'
        at com.puppycrawl.tools.checkstyle.JavaParser$CheckstyleErrorListener.syntaxError(JavaParser.java:255)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:427)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
        ... 6 more
Caused by: org.antlr.v4.runtime.NoViableAltException
        at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2031)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:470)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:396)
        at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:383)
        ... 7 more
Checkstyle ends with 1 errors.
```

Now, it is debatable whether we should support unnamed classes, since this is a preview feature that is also geared towards students. However, I can imagine that  unnamed classes could possibly be used for scripting. We should allow this feature to mature a bit before we undertake supporting this syntax.

**Comment by romani** [comment]
I agree.

**Comment by stoyanK7** [comment]
Related issue:
-  #17810

**Comment by romani** [comment]
fixed from 13.6.0

**Comment by romani** [comment]
We need to remove reference to this issue at config/projects-to-test/openjdk25-excluded.files

**Comment by arturict** [comment]
I am on it.

**Comment by romani** [comment]
extra suppression is removed.
