### ISSUE TITLE
Support Java 21 String Template Syntax (Text Blocks)

### ISSUE THREAD

**Issue by nrmancuso** [checkstyle/checkstyle#14195]
Continuation of https://github.com/checkstyle/checkstyle/issues/13830, we need to add support for text block syntax. 

```bash
➜  src cat Test.java         
public class Test {
    void m0() {
        // string template
        String s = STR."x"; // added in #13830
    }

    void m1() {
        String s = "x";
    }

    void m2() {
        // text block string  template
        String s = STR."""
                x
                """;
    }
}
➜  src javac --enable-preview --release 21 Test.java
Note: Test.java uses preview features of Java SE 21.
Note: Recompile with -Xlint:preview for details.
➜  src java -jar checkstyle-10.12.8-SNAPSHOT-all.jar -t Test.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file Test.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:104)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFileText(JavaParser.java:121)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFile(JavaParser.java:141)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:65)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:291)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: java.lang.IllegalStateException: 13:22: mismatched input '.' expecting ';'
        at com.puppycrawl.tools.checkstyle.JavaParser$CheckstyleErrorListener.syntaxError(JavaParser.java:254)
...
Caused by: org.antlr.v4.runtime.InputMismatchException
        ... 20 more
Checkstyle ends with 1 errors.


```

------------
Link to grammar: https://docs.oracle.com/javase/specs/jls/se21/preview/specs/string-templates-jls.html

```
TextBlockTemplateBegin:
    """ { TextBlockWhiteSpace } LineTerminator TextBlockFragment \{

TextBlockTemplateMid:
    } TextBlockFragment \{

TextBlockTemplateEnd:
    } TextBlockFragment """

TextBlockFragment:
    { TextBlockCharacter }
```

**Comment by romani** [comment]
@nrmancuso, please add example in issue description, it took me a while to spot a difference.

**Comment by nrmancuso** [comment]
> @nrmancuso, please add example in issue description, it took me a while to spot a difference.

Done

**Comment by nrmancuso** [comment]
I am removing approved label from this issue. Java is not supporting this syntax any longer, nor should we. 

https://github.com/checkstyle/checkstyle/issues/14805

**Comment by romani** [comment]
We can close issue, it is delayed for long time. We can reopen it later on or create new without old context that might be confusing in future.

**Comment by romani** [comment]
Removal of this syntax support will be done at https://github.com/checkstyle/checkstyle/issues/14805

**Comment by romani** [comment]
Reopened as we need to remove some suppression of validation in code

**Comment by MANISH-K-07** [comment]
> Reopened as we need to remove some suppression of validation in code. We need to change referenced issue to issue where we remove template support

@romani , @nrmancuso , can I help in anyway regarding this?

**Comment by nrmancuso** [comment]
https://github.com/checkstyle/checkstyle/pull/14809
