### ISSUE TITLE
Outdated wiki description about imports

### ISSUE THREAD

**Issue by marwin1991** [checkstyle/checkstyle#15128]
I have copied config from:

https://checkstyle.sourceforge.io/checks/imports/customimportorder.html#Example10-config

but i got:

```
rror: (CC::CLI::Analyze::EngineFailure) engine checkstyle failed with status 254 and stderr 
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - cannot initialize module CustomImportOrder - Cannot set property 'customImportOrderRules' to 'THIRD_PARTY_PACKAGE, SPECIAL_IMPORTS, STANDARD_JAVA_PACKAGE, STATIC'
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:481)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:411)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:338)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module CustomImportOrder - Cannot set property 'customImportOrderRules' to 'THIRD_PARTY_PACKAGE, SPECIAL_IMPORTS, STANDARD_JAVA_PACKAGE, STATIC'
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:129)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:476)
	... 5 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Cannot set property 'customImportOrderRules' to 'THIRD_PARTY_PACKAGE, SPECIAL_IMPORTS, STANDARD_JAVA_PACKAGE, STATIC'
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:241)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:1[94](https://gitlab.corp.softnet.com.pl/softnet/p5/p51/soknet/-/jobs/1172663#L94))
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:124)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2128)
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2109)
	at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:437)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:231)
	... 9 more
Caused by: java.lang.IllegalStateException: Unexpected rule: THIRD_PARTY_PACKAGE, SPECIAL_IMPORTS, STANDARD_JAVA_PACKAGE, STATIC
	at com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck.addRulesToList(CustomImportOrderCheck.java:1236)
	at com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck.setCustomImportOrderRules(CustomImportOrderCheck.java:812)
	... 17 more
Checkstyle ends with 1 errors.
```

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/blob/0c13df61a826ad81668aab4c790a6342454de976/src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckExamplesTest.java#L28

These examples aren't being validated until https://github.com/checkstyle/checkstyle/issues/13345 . This explains why the example you picked may not be working. This is suppose to be resolved "eventually".

**Comment by marwin1991** [comment]
@rnveach so maybe we should add some information about it? Or maybe I don't understand what do you mean :)

**Comment by rnveach** [comment]
Add some information about what?

Basically it is a known issue the examples aren't correct. They should be fixed under the issue I mentioned previously.

**Comment by marwin1991** [comment]
@rnveach okay i get it now. So this issue should be closed

**Comment by romani** [comment]
@marwin1991 , sorry about having bad configs.
If you see where is typo in examples, we can fix it.

Please share details by CLi output as our issue template demands, so we will see where is problem.

**Comment by rnveach** [comment]
Exception is on config, but config works fine on latest. Most likely user is using an outdated CS version before we allowed comma separation as this check only allowed separation by `###`.

**Comment by romani** [comment]
Change was released at https://checkstyle.org/releasenotes.html#Release_10.13.0

https://github.com/checkstyle/checkstyle/issues/14216

@marwin1991 , please check version you use on your side.
Pick version you need at https://checkstyle.org/index.html#Previous_Version_Documentation

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/blob/0c13df61a826ad81668aab4c790a6342454de976/src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckExamplesTest.java#L27-L28
Removing disablement just shows issues with violations on example 3, 4, 5, 6, 12. No config issues.
