### ISSUE TITLE
MultipleVariableDeclarationsCheck throws NPE when variable is declared inside case block.

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#1539]
MultipleVariableDeclarationsCheckTest throws NPE when variable is declared inside case block.

Example:
````java
void method2() {
        for (int i=0, j=0; i < 10; i++, j--) {
        }

        for(int i=0; i<4;i++) {
            
        }

        switch("") {
            case "0": // no problem
            case "1":
                // my comment
                break;
            case "2":
                // my comment
                //comment
                // comment
                break;
            case "3":
            /* com */
                /* com */
                break;
            case "5":
                // fall through
            case "6":
                int k = 7; // NPE HERE
                // fall through
            case "7":
                if (true) {}
                // fall through
            case "8":
                break;
            default:
                // comment
                break;
        }
    }
````

Stack trace:

```
SEVERE: NullPointerException occurred during the analysis of file /media/andreiselkin/TOURO/IDEA_Projects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/coding/InputMultipleVariableDeclarations.java.
java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.coding.MultipleVariableDeclarationsCheck.visitToken(MultipleVariableDeclarationsCheck.java:91)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:399)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:495)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:328)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:201)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:262)
	at com.puppycrawl.tools.checkstyle.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:121)
	at com.puppycrawl.tools.checkstyle.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:108)
	at com.puppycrawl.tools.checkstyle.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:95)
	at com.puppycrawl.tools.checkstyle.checks.coding.MultipleVariableDeclarationsCheckTest.testIt(MultipleVariableDeclarationsCheckTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Problem location:
[nextNode](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java#L91) can equal to null and should be checked.

**Comment by mkordas** [comment]
Thanks for the report. Offending commit: 192a2eecfeb8dcc5e8dd000599c72758ad46868f - @baratali, can you have a look?

**Comment by MEZk** [comment]
@mkordas 
This issue was discovered when I tried to implement ITs for CommentsIndentationCheck based on UT's input files. So it would be good to resolve that issue to let me use such inputs without problems.

**Comment by baratali** [comment]
@mkordas, yes, I'll provide a fix.

**Comment by baratali** [comment]
Pull request: https://github.com/checkstyle/checkstyle/pull/1541
