### ISSUE TITLE
Upgrade from apache commons-collections:3.2.2 to commons-collections4:4.x

### ISSUE THREAD

**Issue by crosswi** [checkstyle/checkstyle#15892]
**How it works Now:**
Works as expected, this request is for upgrading one of the dependencies.

**Is your feature request related to a problem? Please describe.**
Per the commons-collections documentation. They have moved from commons-collections 3.x to 4.x.

https://commons.apache.org/proper/commons-collections/

**Describe the solution you'd like**
Upgrading to the newest version will ensure that checkstyle stays ahead of any future vulnerabilities or end of life.

**Comment by romani** [comment]
Strange that dependabot did not notify us on this.

**Comment by romani** [comment]
@crosswi , can you send a Pull request with upgrade ?

**Comment by romani** [comment]
upgrade is not easy:
```
[ERROR] com.puppycrawl.tools.checkstyle.utils.AnnotationUtilTest.testValuePairAnnotation -- Time elapsed: 0.003 s <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/commons/collections/FastHashMap
	at org.apache.commons.beanutils.PropertyUtilsBean.getPropertyDescriptor(PropertyUtilsBean.java:964)
	at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:391)
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.tryCopyProperty(AbstractAutomaticBean.java:241)
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.contextualize(AbstractAutomaticBean.java:273)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:478)
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:211)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.createChecker(AbstractModuleTestSupport.java:103)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.getActualViolationsForFile(AbstractModuleTestSupport.java:574)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyWithInlineConfigParser(AbstractModuleTestSupport.java:257)
	at com.puppycrawl.tools.checkstyle.utils.AnnotationUtilTest.testValuePairAnnotation(AnnotationUtilTest.java:362)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)

```

beanutils use some removed class `org/apache/commons/collections/FastHashMap`.

**Comment by romani** [comment]
this issue is blocked by https://github.com/checkstyle/checkstyle/issues/16043

**Comment by romani** [comment]
@crosswi , can you send PR to upgrade ?
we upgraded beanutils, so I hope this issue is unblocked now.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/pom.xml

We don't have direct dependency to `commons-collections` , we do have transitive dependency (by means of other dependencies).

commons-beanutils is upgraded to resolve bunch security concerns, so if more to be updated we will wait for direct dependencies to release new versions.
