### ISSUE TITLE
ArrayIndexOutOfBoundsException on indentation check of try-with-resources

### ISSUE THREAD

**Issue by peter-hamader-dynatrace** [checkstyle/checkstyle#15943]
I have read check documentation: https://checkstyle.sourceforge.io/checks/misc/indentation.html#Indentation
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac Thingie.java
no output (success)

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <property name="severity" value="error"/>

    <property name="fileExtensions" value="java, properties, xml"/>

    <module name="TreeWalker">
        <module name="Indentation">
        </module>
    </module>
</module>

/var/tmp $ cat Thingie.java
public class Thingie implements AutoCloseable {
    public void doIt() {
        open();
        try (this) {
            System.out.println("doIt");
        }
    }
    
    public void open() {
        System.out.println("open");
    }
    
    @Override
    public void close() {
        System.out.println("close");
    }
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar  checkstyle-10.20.1-all.jar -c config.xml Thingie.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Thingie.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:312)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:226)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:415)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:338)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2147483647 out of bounds for length 17
	at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:222)
	at com.puppycrawl.tools.checkstyle.api.FileContents.getLine(FileContents.java:100)
	at com.puppycrawl.tools.checkstyle.api.AbstractCheck.getLine(AbstractCheck.java:308)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.getLineStart(AbstractExpressionHandler.java:224)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.getLineStart(AbstractExpressionHandler.java:213)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.isOnStartOfLine(AbstractExpressionHandler.java:178)
	at com.puppycrawl.tools.checkstyle.checks.indentation.TryHandler.checkTryResources(TryHandler.java:150)
	at com.puppycrawl.tools.checkstyle.checks.indentation.TryHandler.checkIndentation(TryHandler.java:83)
	at com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck.visitToken(IndentationCheck.java:435)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:393)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:466)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:331)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:211)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:101)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:340)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:299)
	... 5 more
Checkstyle ends with 1 errors.
```
---

I expect no ArrayIndexOutOfBoundsException exception to be thrown.

```
$ java -jar  checkstyle-10.20.1-all.jar -t Test.java
COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
`--CLASS_DEF -> CLASS_DEF [1:0]
    |--MODIFIERS -> MODIFIERS [1:0]
    |   `--LITERAL_PUBLIC -> public [1:0]
    |--LITERAL_CLASS -> class [1:7]
    |--IDENT -> Thingie [1:13]
    |--IMPLEMENTS_CLAUSE -> implements [1:21]
    |   `--IDENT -> AutoCloseable [1:32]
    `--OBJBLOCK -> OBJBLOCK [1:46]
        |--LCURLY -> { [1:46]
        |--METHOD_DEF -> METHOD_DEF [2:4]
        |   |--MODIFIERS -> MODIFIERS [2:4]
        |   |   `--LITERAL_PUBLIC -> public [2:4]
        |   |--TYPE -> TYPE [2:11]
        |   |   `--LITERAL_VOID -> void [2:11]
        |   |--IDENT -> doIt [2:16]
        |   |--LPAREN -> ( [2:20]
        |   |--PARAMETERS -> PARAMETERS [2:21]
        |   |--RPAREN -> ) [2:21]
        |   `--SLIST -> { [2:23]
        |       |--EXPR -> EXPR [3:12]
        |       |   `--METHOD_CALL -> ( [3:12]
        |       |       |--IDENT -> open [3:8]
        |       |       |--ELIST -> ELIST [3:13]
        |       |       `--RPAREN -> ) [3:13]
        |       |--SEMI -> ; [3:14]
        |       |--LITERAL_TRY -> try [4:8]
        |       |   |--RESOURCE_SPECIFICATION -> RESOURCE_SPECIFICATION [4:12]
        |       |   |   |--LPAREN -> ( [4:12]
        |       |   |   |--RESOURCES -> RESOURCES [-2147483648:-2147483648]
        |       |   |   |   `--RESOURCE -> RESOURCE [-2147483648:-2147483648]
        |       |   |   `--RPAREN -> ) [4:17]
        |       |   `--SLIST -> { [4:19]
        |       |       |--EXPR -> EXPR [5:30]
        |       |       |   `--METHOD_CALL -> ( [5:30]
        |       |       |       |--DOT -> . [5:22]
        |       |       |       |   |--DOT -> . [5:18]
        |       |       |       |   |   |--IDENT -> System [5:12]
        |       |       |       |   |   `--IDENT -> out [5:19]
        |       |       |       |   `--IDENT -> println [5:23]
        |       |       |       |--ELIST -> ELIST [5:31]
        |       |       |       |   `--EXPR -> EXPR [5:31]
        |       |       |       |       `--STRING_LITERAL -> "doIt" [5:31]
        |       |       |       `--RPAREN -> ) [5:37]
        |       |       |--SEMI -> ; [5:38]
        |       |       `--RCURLY -> } [6:8]
        |       `--RCURLY -> } [7:4]
...

```

**Comment by nrmancuso** [comment]
I am on it

**Comment by romani** [comment]
```
$ java -jar  checkstyle-10.20.1-all.jar -t Test.java
COMPILATION_UNIT -> COMPILATION_UNIT [1:0]
`--CLASS_DEF -> CLASS_DEF [1:0]
    |--MODIFIERS -> MODIFIERS [1:0]
    |   `--LITERAL_PUBLIC -> public [1:0]
    |--LITERAL_CLASS -> class [1:7]
    |--IDENT -> Thingie [1:13]
    |--IMPLEMENTS_CLAUSE -> implements [1:21]
    |   `--IDENT -> AutoCloseable [1:32]
    `--OBJBLOCK -> OBJBLOCK [1:46]
        |--LCURLY -> { [1:46]
        |--METHOD_DEF -> METHOD_DEF [2:4]
        |   |--MODIFIERS -> MODIFIERS [2:4]
        |   |   `--LITERAL_PUBLIC -> public [2:4]
        |   |--TYPE -> TYPE [2:11]
        |   |   `--LITERAL_VOID -> void [2:11]
        |   |--IDENT -> doIt [2:16]
        |   |--LPAREN -> ( [2:20]
        |   |--PARAMETERS -> PARAMETERS [2:21]
        |   |--RPAREN -> ) [2:21]
        |   `--SLIST -> { [2:23]
        |       |--EXPR -> EXPR [3:12]
        |       |   `--METHOD_CALL -> ( [3:12]
        |       |       |--IDENT -> open [3:8]
        |       |       |--ELIST -> ELIST [3:13]
        |       |       `--RPAREN -> ) [3:13]
        |       |--SEMI -> ; [3:14]
        |       |--LITERAL_TRY -> try [4:8]
        |       |   |--RESOURCE_SPECIFICATION -> RESOURCE_SPECIFICATION [4:12]
        |       |   |   |--LPAREN -> ( [4:12]
        |       |   |   |--RESOURCES -> RESOURCES [-2147483648:-2147483648]
        |       |   |   |   `--RESOURCE -> RESOURCE [-2147483648:-2147483648]
        |       |   |   `--RPAREN -> ) [4:17]
        |       |   `--SLIST -> { [4:19]
        |       |       |--EXPR -> EXPR [5:30]
        |       |       |   `--METHOD_CALL -> ( [5:30]
        |       |       |       |--DOT -> . [5:22]
        |       |       |       |   |--DOT -> . [5:18]
        |       |       |       |   |   |--IDENT -> System [5:12]
        |       |       |       |   |   `--IDENT -> out [5:19]
        |       |       |       |   `--IDENT -> println [5:23]
        |       |       |       |--ELIST -> ELIST [5:31]
        |       |       |       |   `--EXPR -> EXPR [5:31]
        |       |       |       |       `--STRING_LITERAL -> "doIt" [5:31]
        |       |       |       `--RPAREN -> ) [5:37]
        |       |       |--SEMI -> ; [5:38]
        |       |       `--RCURLY -> } [6:8]
        |       `--RCURLY -> } [7:4]
        |--METHOD_DEF -> METHOD_DEF [9:4]
        |   |--MODIFIERS -> MODIFIERS [9:4]
        |   |   `--LITERAL_PUBLIC -> public [9:4]
        |   |--TYPE -> TYPE [9:11]
        |   |   `--LITERAL_VOID -> void [9:11]
        |   |--IDENT -> open [9:16]
        |   |--LPAREN -> ( [9:20]
        |   |--PARAMETERS -> PARAMETERS [9:21]
        |   |--RPAREN -> ) [9:21]
        |   `--SLIST -> { [9:23]
        |       |--EXPR -> EXPR [10:26]
        |       |   `--METHOD_CALL -> ( [10:26]
        |       |       |--DOT -> . [10:18]
        |       |       |   |--DOT -> . [10:14]
        |       |       |   |   |--IDENT -> System [10:8]
        |       |       |   |   `--IDENT -> out [10:15]
        |       |       |   `--IDENT -> println [10:19]
        |       |       |--ELIST -> ELIST [10:27]
        |       |       |   `--EXPR -> EXPR [10:27]
        |       |       |       `--STRING_LITERAL -> "open" [10:27]
        |       |       `--RPAREN -> ) [10:33]
        |       |--SEMI -> ; [10:34]
        |       `--RCURLY -> } [11:4]
        |--METHOD_DEF -> METHOD_DEF [13:4]
        |   |--MODIFIERS -> MODIFIERS [13:4]
        |   |   |--ANNOTATION -> ANNOTATION [13:4]
        |   |   |   |--AT -> @ [13:4]
        |   |   |   `--IDENT -> Override [13:5]
        |   |   `--LITERAL_PUBLIC -> public [14:4]
        |   |--TYPE -> TYPE [14:11]
        |   |   `--LITERAL_VOID -> void [14:11]
        |   |--IDENT -> close [14:16]
        |   |--LPAREN -> ( [14:21]
        |   |--PARAMETERS -> PARAMETERS [14:22]
        |   |--RPAREN -> ) [14:22]
        |   `--SLIST -> { [14:24]
        |       |--EXPR -> EXPR [15:26]
        |       |   `--METHOD_CALL -> ( [15:26]
        |       |       |--DOT -> . [15:18]
        |       |       |   |--DOT -> . [15:14]
        |       |       |   |   |--IDENT -> System [15:8]
        |       |       |   |   `--IDENT -> out [15:15]
        |       |       |   `--IDENT -> println [15:19]
        |       |       |--ELIST -> ELIST [15:27]
        |       |       |   `--EXPR -> EXPR [15:27]
        |       |       |       `--STRING_LITERAL -> "close" [15:27]
        |       |       `--RPAREN -> ) [15:34]
        |       |--SEMI -> ; [15:35]
        |       `--RCURLY -> } [16:4]
        `--RCURLY -> } [17:0]

```

**Comment by romani** [comment]
@peter-hamader-dynatrace , fix is released https://github.com/checkstyle/checkstyle/issues/15943
