### ISSUE TITLE
NPE in MutableExceptionCheck.isExtendedClassNamedAsException

### ISSUE THREAD

**Issue by dkulp** [checkstyle/checkstyle#1903]
Since Checkstyle 6.7, one of the classes in Apache Camel is resulting in a NPE in MutableExceptionCheck.

```
ERROR] NullPointerException occurred during the analysis of file /Users/dkulp/working/camel/camel-core/src/main/java/org/apache/camel/util/concurrent/AtomicException.java.
java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.design.MutableExceptionCheck.isExtendedClassNamedAsException(MutableExceptionCheck.java:155)
	at com.puppycrawl.tools.checkstyle.checks.design.MutableExceptionCheck.visitClassDef(MutableExceptionCheck.java:114)
	at com.puppycrawl.tools.checkstyle.checks.design.MutableExceptionCheck.visitToken(MutableExceptionCheck.java:91)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:393)
```

The class in question is:

https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/util/concurrent/AtomicException.java

**Comment by romani** [comment]
http://checkstyle.sourceforge.net/config_design.html#MutableException has options , please provide link to checkstyle config.

**Comment by romani** [comment]
merged.
