### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by asashour** [checkstyle/checkstyle#2094]
Hi all,

With Github version, checking a file with the below JavaDoc (notice the 'period'):

    /**
     * .
     * @throws Exception if an error occurs
     */

with the command:

    >java -jar checkstyle-6.11-SNAPSHOT-all.jar -c sun_checks.xml MyTest.java

throws an error:

    Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String inex out of range: -1
        at java.lang.AbstractStringBuilder.charAt(Unknown Source)
        at java.lang.StringBuilder.charAt(Unknown Source)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.triTail(JavadocStyleCheck.java:317)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.getommentText(JavadocStyleCheck.java:271)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.chekFirstSentenceEnding(JavadocStyleCheck.java:231)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.chekComment(JavadocStyleCheck.java:208)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.vistToken(JavadocStyleCheck.java:149)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.jaa:392)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.jaa:503)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:334)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalke.java:209)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbsractFileSetCheck.java:79)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:265)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:271)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:121)

**Comment by romani** [comment]
merged
