### ISSUE TITLE
CLI should print a flie name where exception is happen

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2109]
```
java -jar checkstyle-6.10.1-all.jar -c sun_checks.xml *.java

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.AbstractStringBuilder.charAt(Unknown Source)
        at java.lang.StringBuilder.charAt(Unknown Source)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.trimTail(JavadocStyleCheck.java:315)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.getCommentText(JavadocStyleCheck.java:269)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.checkFirstSentenceEnding(JavadocStyleCheck.java:230)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.checkComment(JavadocStyleCheck.java:207)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.visitToken(JavadocStyleCheck.java:148)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:392)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:503)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:334)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:209)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:265)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:271)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:121)
```

So where is no easy way to find a reason (input file) of problem. File path should be printed.

**Comment by romani** [comment]
Getting details failure is almost impossible now, we need to address this ASAP.

See #2327 , #2326 .

**Comment by Vampire** [comment]
I don't think this is related to #2326, there the real error is not shown at all, but the previously found one :-)

**Comment by romani** [comment]
@mkordas , do you have better approach to fix this ? (see my non merged commit and PR)

**Comment by romani** [comment]
We need to catch and rethrow with context information (file path) in Exception as we do not know how our code is used (plugin, embedded, ....), we can not reply on logger, as it could be switched off.

**Comment by mkordas** [comment]
@romani, I like the approach.

**Comment by romani** [comment]
merged.

See discussions at #2476 , #2487 .
