### ISSUE TITLE
Checkstyle fails to parse files with non-ASCII characters on Windows

### ISSUE THREAD

**Issue by jshiell** [checkstyle/checkstyle#2189]
Files with non-ASCII characters in method/variable names result in a TokenStreamRecognitionException on Windows 7 (both 32 and 64 bit). On OS X, the files parses successfully.

Using a very basic rules file:

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker"/>
</module>
```

And a simple sample file:

```
public class Sample {
    public void méthod() {
    }
}
```

We receive the following output on Windows 7 (32bit, en_US - Windows 7/IE 11 VMWare VM from https://dev.modern.ie/tools/vms/mac/):

```
Z:\>java -jar checkstyle-6.10.1-all.jar -c checks.xml Sample.java
TokenStreamRecognitionException occurred during the analysis of file Sample.java
.
Checkstyle ends with 1 errors.
```

CheckStyle 6.9 offers a more helpful error:

```
Z:\>java -jar checkstyle-6.9-all.jar -c checkstyle_checks.xml Sample.java
Sep 15, 2015 10:34:08 AM com.puppycrawl.tools.checkstyle.TreeWalker processFiltered
SEVERE: TokenStreamRecognitionException occurred during the analysis of file Sample.java.
Starting audit...
Z:\Sample.java:0: Got an exception - Unexpected character 0xa9 in identifier
Audit done.
Checkstyle ends with 1 errors.
```

On OS X 10.10.5 (en_GB) the parse succeeds, as expected:

```
$  java -jar checkstyle-6.10.1-all.jar -c checkstyle_checks.xml Sample.java
Starting audit...
Audit done.
```

This was raised due to [a bug reported against the IDEA plugin](https://github.com/jshiell/checkstyle-idea/issues/186) where the reported found it on a real Windows 7 x64 box.
##

**Comment by romani** [comment]
@mkordas , can you verify that issue ?

I doubt that we could fix this issue easily, but at least we can confirm it existance.

**Comment by mkordas** [comment]
@romani, Issue is present, I'm able to reproduce it. #2213 created to handle decreased amount of logging.
> On OS X 10.10.5 (en_GB) the parse succeeds, as expected

@jshiell, did you make sure that on this run you've saved file with UTF-8 encoding?

**Comment by jshiell** [comment]
@mkordas confirmed via `file`:

    Sample.java: UTF-8 Unicode C++ program text

The same file was copied between OSs with no further editing, so I'm confident it was UTF-8 on both.

I encountered a similar problem to this some time ago in my plugin, and it turned out to be a stream that didn't force the character encoding. This lead to all sorts of fun as it just inherited the default JVM encoding, which is UTF-8 on modern Mac JVMs, and (at least was at the time) ISO-8859-1 on Win32/64.

**Comment by melkashef12** [comment]
Hello, 

Is there any fix planned for this issue? 

Thanks

**Comment by jshiell** [comment]
To be honest it's unlikely at present, as I don't work in Windows, which makes it problematic to debug.

**Comment by romani** [comment]
@rnveach , can you reproduce this issue ?
you are the only maintainer who use Windows.

**Comment by rnveach** [comment]
@romani It is probably more on how the file is saved than the OS.
`Checkstyle Web Tester` which runs on linux fails with the following:
````
$ cat TestClass.java
public class Sample {
    public void méthod() {
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
         <module name="ThrowsCount">
             <property name="max" value="20000000"/>
         </module>
    </module>
</module>

$ java -jar checkstyle-8.0-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:430)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:362)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:177)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred during the analysis of file TestClass.java.
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:194)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
    ... 4 more
Caused by: TestClass.java:2:18: Unexpected character 0xfffd in identifier
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:405)
    at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
    at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)
    at antlr.TokenBuffer.fill(TokenBuffer.java:69)
    at antlr.TokenBuffer.LA(TokenBuffer.java:80)
    at antlr.LLkParser.LA(LLkParser.java:52)
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3231)
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2542)
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
    at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:446)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:179)
    ... 7 more
Checkstyle ends with 1 errors.
````

If I save the file in Notepad++ on Windows, there is no exception and the hexcode of the file stored the accented `e` as `C3 A9`.
If I open that same file in regular Notepad and save it directly as UTF-8, I get the following exception, which is similar to the web version:
````
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing M:\Test.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:508)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:431)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:209)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred during the analysis of file M:\Test.java.
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:191)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
	... 4 more
Caused by: M:\Test.java:1:1: Unexpected character 0xfeff in identifier
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:405)
	at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
	at antlr.TokenStreamHiddenTokenFilter.consumeFirst(TokenStreamHiddenTokenFilter.java:42)
	at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:122)
	at antlr.TokenBuffer.fill(TokenBuffer.java:69)
	at antlr.TokenBuffer.LA(TokenBuffer.java:80)
	at antlr.LLkParser.LA(LLkParser.java:52)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:158)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:445)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:176)
	... 7 more
Checkstyle ends with 1 errors.
````
The accented `e` is stored with the same hexcode but the file starts with the hexcode `EF BB BF`.

Storing the file as unicode is similar to the UTF8 exception.

**Comment by romani** [comment]
strange that this issue is still open as we know that checkstyle limitations http://checkstyle.sourceforge.net/writingchecks.html#Limitations clearly state 
`Java code should be written with ASCII characters only, no UTF-8 support.`

it will never be fixed as it demands us to support UTF8 on parser level - it is very hard task for our team/project with minimal benefit.
