### ISSUE TITLE
Concurrent execution from maven failed

### ISSUE THREAD

**Issue by holub** [checkstyle/checkstyle#2237]
I'm using checkstyle from maven with -T option. Sometime the build failed. Most likely it's concurrent issue but I'm not sure on which side it must be fixed: checkstyle or maven plugin.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check (validate) on project yyy-1: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check (validate) on project yyy-1: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    ...
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    ...
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 11 more
Caused by: java.lang.NullPointerException
    at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck.visitToken(AbstractJavadocCheck.java:182)
    ...
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:265)
    at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
    at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:538)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 12 more
```

**Comment by michael-o** [comment]
Here is the reference: http://stackoverflow.com/q/32769955/696632

**Comment by mkordas** [comment]
I've tried to fix that issue in #1122, but PR was not accepted.

**Comment by michael-o** [comment]
One can mark a Maven plugin as not threadsafe but that is supported with Maven 3.0+. The current plugin still supports 2.2.1+.

**Comment by romani** [comment]
Is it time to reconsider this issue ?

**Comment by mkordas** [comment]
@romani, as I wrote in the comment, using `static` mutable cache is bad practice anyway. `ThreadLocal` is solution to maintain performance within one thread but enable safe multithreaded usage. Should I raise PR for that?

**Comment by romani** [comment]
lets try to use ThreadLocal , all Javadoc Checks need to be reimplemented, so we need some temporal solution.

**Comment by romani** [comment]
fixed in 6.11 .

But I would NOT make it official that we are multi-threading.

**Comment by holub** [comment]
Thanks! What is the schedule fro 6.11?

**Comment by romani** [comment]
this weekends - please pay attention to milestones https://github.com/checkstyle/checkstyle/milestones
