### ISSUE TITLE
Concurrency issue in JavadocParagraph check

### ISSUE THREAD

**Issue by holub** [checkstyle/checkstyle#2269]
Non-deterministic exception with maven concurrent build (-T):
```
[INFO] Starting audit...
XXX.java:11: warning: Empty line should be followed by <p> tag on the next line.
Audit done.
[WARNING] XXX.java[11] (javadoc) JavadocParagraph: Empty line should be followed by <p> tag on the next line.
```
maven-checkstyle-plugin: 2.16
checkstyle: 6.11

plugin exception:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check (validate) on project amelia-humanization: You have 1 Checkstyle violation. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check (validate) on project amelia-humanization: You have 1 Checkstyle violation.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:189)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.MojoFailureException: You have 1 Checkstyle violation.
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:588)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 11 more
```

**Comment by romani** [comment]
@holub , can you report issue like it done at https://github.com/checkstyle/checkstyle/issues/2250 . thanks in advance.

**Comment by holub** [comment]
@romani Working on it. Just hit [enter] accidentally.

**Comment by holub** [comment]
Ooops. It was actual issue. Sorry!
