### ISSUE TITLE
NPE with NeedBraces/allowSingleLineStatement

### ISSUE THREAD

**Issue by Jurax** [checkstyle/checkstyle#2283]
With NeedBraces/allowSingleLineStatement enabled the following code causes a NullPointerException. (Using Checkstyle 6.11.2 / 6.11.1)

```java
public static void main(String[] args) {
    for (;;)
        break;
}
```

```xml
<module name="Checker">
  <module name="TreeWalker">
    <module name="NeedBraces">
      <property name="allowSingleLineStatement" value="true"/>
    </module>
  </module>
</module>
```

```
Exception in thread "main" java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.isSingleLineFor(NeedBracesCheck.java:286)
	at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.isSingleLineStatement(NeedBracesCheck.java:203)
	at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.isSkipStatement(NeedBracesCheck.java:177)
	at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.visitToken(NeedBracesCheck.java:164)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:388)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:499)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:330)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:203)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:265)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:277)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:118)
```

**Comment by romani** [comment]
merged.
