### ISSUE TITLE
JavaDocMethod: Exception thrown for incomplete @return tag if next line is empty

### ISSUE THREAD

**Issue by johnerikhalse** [checkstyle/checkstyle#2398]
For a `@return` tag with no description of what it returns, a message like `Expected an @return tag.` is expected. But if this `@return` tag is followed by a blank line, an exception is thrown instead.

This reports the expected error:
````java
/**
 * A Javadoc comment.
 *
 * @return
 */
public String foo() {
    ...
}
````

This throws an exception:
````java
/**
 * A Javadoc comment.
 *
 * @return
 *
 */
public String foo() {
    ...
}
````

This is the important part of the stack trace:
````
java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck.getMultilineNoArgTags(JavadocMethodCheck.java:669)
````

A solution which seems to work is to add an if statement, but I'm not familiar enough with the code base to tell if this is the best solution:

````
--- HEAD
+++ Modified In Working Tree
@@ -664,12 +664,13 @@
         while (remIndex < lines.length) {
             final Matcher multilineCont = MATCH_JAVADOC_MULTILINE_CONT
                     .matcher(lines[remIndex]);
-            multilineCont.find();
-            remIndex = lines.length;
-            final String lFin = multilineCont.group(1);
-            if (!lFin.equals(NEXT_TAG)
-                && !lFin.equals(END_JAVADOC)) {
-                tags.add(new JavadocTag(tagLine, col, param1));
+            if (multilineCont.find()) {
+                remIndex = lines.length;
+                final String lFin = multilineCont.group(1);
+                if (!lFin.equals(NEXT_TAG)
+                    && !lFin.equals(END_JAVADOC)) {
+                    tags.add(new JavadocTag(tagLine, col, param1));
+                }
             }
             remIndex++;
         }
````

**Comment by romani** [comment]
Please send that patch as Pull Request

**Comment by johnerikhalse** [comment]
Sure, just did (#2403).

I also added this case to the unit tests.

**Comment by romani** [comment]
merrged.

**Comment by gayanW** [comment]
Issue still persist in 2.17. 

Repoduce:
See: https://github.com/openmrs/openmrs-module-coreapps/blob/3b67555d587960e0d0161b40bce53d8bbec4aae1/api/src/main/java/org/openmrs/module/coreapps/CoreAppsActivator.java#L44

Processing this fails.

**Comment by rnveach** [comment]
> Issue still persist in 2.17.

@gayanW I'm not sure what version you are referring to. We are in version 7.7 and I get the violation `Expected an @return tag` when running it against the code and no exception.
````
$ cat TestClass.java
public class TestClass {
    /**
     * Public static so it can be used in tests
     * @param emrApiProperties
     * @return
     */
    public static EncounterDispositionTagHandler setupEncounterDispositionTagHandler(EmrApiProperties emrApiProperties, DispositionService dispositionService, AdtService adtService) {}
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="JavadocMethod"/>
    </module>
</module>

$ java -jar checkstyle-7.7-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:7: Expected an @return tag. [JavadocMethod]
[ERROR] TestClass.java:7:103: Expected @param tag for 'emrApiProperties'. [JavadocMethod]
[ERROR] TestClass.java:7:140: Expected @param tag for 'dispositionService'. [JavadocMethod]
[ERROR] TestClass.java:7:171: Expected @param tag for 'adtService'. [JavadocMethod]
Audit done.
Checkstyle ends with 4 errors.
````

**Comment by jhickman** [comment]
I believe version 2.17 above is referring to the maven-checkstyle-plugin, which appears to be using checkstyle version 6.11.2.

**Comment by gayanW** [comment]
Yeah sorry for posing in the wrong place. It's about maven-checkstyle-plugin.

**Comment by jhickman** [comment]
For future reference if anyone else comes across this ticket for the same reason (just as I had), you can change the version of Checkstyle used in the plugin:  https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html
