### ISSUE TITLE
After upgrade to 6.12.1 IntelliJ plugin throws exceptions:

### ISSUE THREAD

**Issue by vrozov** [checkstyle/checkstyle#2630]
```
CheckStyle threw an exception when scanning: DiskStorage.java: Exception was thrown while processing /var/folders/vx/mfh0w1ld4p374hd749qg47j40000gp/T/csi-a6e8b38b-2623-4075-b9a7-ee51f8dc960d/src/main/java/com/datatorrent/bufferserver/storage/DiskStorage.java
org.infernus.idea.checkstyle.exception.CheckStylePluginException: Exception was thrown while processing /var/folders/vx/mfh0w1ld4p374hd749qg47j40000gp/T/csi-a6e8b38b-2623-4075-b9a7-ee51f8dc960d/src/main/java/com/datatorrent/bufferserver/storage/DiskStorage.java
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:34)
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:23)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:66)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:40)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$15(CheckStyleInspection.java:81)
	at org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$55/2044049815.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:81)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$14(CheckStyleInspection.java:57)
	at org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$41/928200120.call(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl$9.call(ApplicationImpl.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /var/folders/vx/mfh0w1ld4p374hd749qg47j40000gp/T/csi-a6e8b38b-2623-4075-b9a7-ee51f8dc960d/src/main/java/com/datatorrent/bufferserver/storage/DiskStorage.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:64)
	... 13 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 112
	at java.lang.String.charAt(String.java:646)
	at com.puppycrawl.tools.checkstyle.utils.CommonUtils.lengthExpandedTabs(CommonUtils.java:150)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.expandedTabsColumnNo(AbstractExpressionHandler.java:468)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.findSubtreeLines(AbstractExpressionHandler.java:488)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.findSubtreeLines(AbstractExpressionHandler.java:497)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.checkExpressionSubtree(AbstractExpressionHandler.java:426)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.checkChildren(AbstractExpressionHandler.java:400)
	at com.puppycrawl.tools.checkstyle.checks.indentation.BlockParentHandler.checkIndentation(BlockParentHandler.java:279)
	at com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck.visitToken(IndentationCheck.java:292)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:332)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:204)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 14 more

```

**Comment by mkordas** [comment]
@vrozov, can you provide stacktrace?

**Comment by mkordas** [comment]
@vrozov Can you also provide `DiskStorage.java` and submit to github.com/checkstyle/checkstyle/issues?

**Comment by vrozov** [comment]
https://github.com/apache/incubator-apex-core/blob/master/bufferserver/src/main/java/com/datatorrent/bufferserver/storage/DiskStorage.java

checkstyle - https://github.com/apache/incubator-apex-core/blob/master/apex_checks.xml

**Comment by romani** [comment]
can not reproduce. Please read - http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

```
$ curl -O https://raw.githubusercontent.com/apache/incubator-apex-core/master/bufferserver/src/main/java/com/datatorrent/bufferserver/storage/DiskStorage.java
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6972  100  6972    0     0  54972      0 --:--:-- --:--:-- --:--:--  100k

$ curl -O https://raw.githubusercontent.com/apache/incubator-apex-core/master/apex_checks.xml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5804  100  5804    0     0  24240      0 --:--:-- --:--:-- --:--:-- 32977

$ java -jar checkstyle-6.13-all.jar -c apex_checks.xml DiskStorage.java 
Starting audit...
/var/tmp/DiskStorage.java:69:7: error: '}' at column 7 should be on the same line as the next part of a multi-block statement.
........
/var/tmp/DiskStorage.java:210:5: error: '}' at column 5 should be on the same line as the next part of a multi-block statement.
Audit done.
Checkstyle ends with 19 errors.
```
