### ISSUE TITLE
StringIndexOutOfBoundsException in Indentation check

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#2645]
Input (valid Java file):
```
$ javac Test.java 

$ import java.io.* // indent:0 exp:0

    ; //indent:4 exp:4

$ cat Test.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">


<module name = "Checker">
    <module name="TreeWalker">
         <module name="Indentation"/>
    </module>
</module>

$java -jar checkstyle-6.13-all.jar -c Test.xml Test.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Test.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:276)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:646)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.getLineStart(AbstractExpressionHandler.java:251)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.checkSingleLine(AbstractExpressionHandler.java:351)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.checkLinesIndent(AbstractExpressionHandler.java:285)
	at com.puppycrawl.tools.checkstyle.checks.indentation.ImportHandler.checkIndentation(ImportHandler.java:51)
	at com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck.visitToken(IndentationCheck.java:292)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:332)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:204)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 2 more
Checkstyle ends with 1 errors.

```

**Comment by rnveach** [comment]
@mkordas 

> ; //indent:0 exp:0

Why do you expect this to be at position 0, and not what we currently require, position 4?
If your input was similar to:

````
import java. //indent:0
    util.Arrays; //indent:4
````

You would still expect the 2nd line to be at position 0?

**Comment by mkordas** [comment]
@rnveach you are right, I've changed description accordingly

**Comment by romani** [comment]
fix is merged.
