### ISSUE TITLE
ParameterNameCheck: NullPointerException over checkstyle's input file

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#2678]
config: https://github.com/checkstyle/contribution/blob/5d0634ce96420e3049250899a740296597481a90/checkstyle-tester/checks-nonjavadoc-error.xml#L152

command: https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L82

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/travis/build/checkstyle/checkstyle/contribution/checkstyle-tester/src/main/java/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/InputParameterNumber.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
	at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
	... 28 more
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck.isOverriddenMethod(ParameterNameCheck.java:125)
	at com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck.mustCheckName(ParameterNameCheck.java:106)
	at com.puppycrawl.tools.checkstyle.checks.naming.AbstractNameCheck.visitToken(AbstractNameCheck.java:67)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:332)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:204)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 30 more
```

after fix, https://github.com/checkstyle/contribution/commit/a2d7f1a64a087715dc9c698d6615ba52b6179acf need to be reverted.

**Comment by romani** [comment]
merged.
