### ISSUE TITLE
Exception when using method reference in lamba "Class<?>[]::new"

### ISSUE THREAD

**Issue by valliman** [checkstyle/checkstyle#2729]
Using Checkstyle version 6.13

When using the method reference "Class<?>[]::new" in a lambda expression like:
```java
//Compilable with Java8
//Issue #2729
package com.puppycrawl.tools.checkstyle.grammars.java8;
import java.util.Arrays;

public class InputMethodReferences4 {
    public void doSomething(final Object... arguments) {
        Arrays.stream(arguments)
                .map(Object::getClass)
                .toArray(Class<?>[]::new);
    }
}
```

the exception below is thrown:

```java
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing SomeClass.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:538)
	... 27 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred during the analysis of file SomeClass.java
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:218)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 29 more
Caused by: SomeClass.java:37:13: expecting EOF, found 'Method'
	at antlr.Parser.match(Parser.java:211)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:210)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:468)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:200)
	... 31 more
```

Using instead "size -> new Class<?>[size]" is a workaround.

**Comment by sabaka** [comment]
@romani, assign it please

**Comment by sabaka** [comment]
Fully compilable file:
```java
//Compilable with Java8
//Issue #2729
package com.puppycrawl.tools.checkstyle.grammars.java8;
import java.util.Arrays;

public class InputMethodReferences4 {
    public void doSomething(final Object... arguments) {
        Arrays.stream(arguments)
                .map(Object::getClass)
                .toArray(Class<?>[]::new);
    }
}
```

I use this file in tests now.
Problem is `Class<?>[]::new`
Our grammar doesn't know, that here can be an array.
I think I can fix it by simply adding [] to this rule, but better to put an existed rule here with all possible cases, because we want to understand our grammar in future :)

**Comment by romani** [comment]
fix is merged.
