### ISSUE TITLE
Cannot parse compilable statement written in unicode

### ISSUE THREAD

**Issue by pmcevoy12** [checkstyle/checkstyle#2784]
The following method cannot be parsed by checkstyle.
The code compiles and runs as expected using Java 1.8.
This method is based on Puzzle 17 in Java Puzzlers by Bloch
```java
    private static void runP17Huh() {
        // the next line compiles to System.out.println("Hello World");
        \u0053\u0079\u0073\u0074\u0065\u006d\u002e\u006f\u0075\u0074\u002e\u0070\u0072\u0069\u006e\u0074\u006c\u006e\u0028\u0022\u0048\u0065\u006c\u006c\u006f\u0020\u0057\u006f\u0072\u006c\u0064\u0022\u0029\u003b;
    }
```

Here is the error
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException:
Exception was thrown while processing C:\Puzzlers\src\books\puzzlers\character\Main.java
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.processFiles(CheckstyleAntTask.java:362)
        ... 18 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred during the
analysis of file C:\Puzzlers\src\books\puzzlers\character\Main.java.
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:198)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
        ... 19 more
Caused by: C:\Puzzlers\src\books\puzzlers\character\Main.java:94:9: unexpected char: '\'
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:405)
        at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
        at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:148)
        at antlr.TokenBuffer.fill(TokenBuffer.java:69)
        at antlr.TokenBuffer.LA(TokenBuffer.java:80)
        at antlr.LLkParser.LA(LLkParser.java:52)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.declaratorBrackets(GeneratedJavaRecognizer.java:3077)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3295)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2542)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:633)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:555)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:388)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:201)
        at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:453)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:185)
        ... 21 more
```

**Comment by romani** [comment]
Thanks for reporting this.

:), but, please do not expect quick fix for such weird code.

**Comment by pmcevoy12** [comment]
I don't need an actual fix.  I commented out the bizarre code after seeing it work.
It would be good to get a better error message in this case as I had to enable "verbose" to get the posted stack trace.  Nothing is blocked.

**Comment by romani** [comment]
It might be good idea create a Check that forbid usage of unicode symbols, but it also could be done by http://checkstyle.sourceforge.net/config_regexp.html#RegexpSinglelineJava

**Comment by romani** [comment]
unfortunately it is by design http://checkstyle.sourceforge.net/writingchecks.html#Limitations 

> Java code should be written with ASCII characters only, no UTF-8 support.

We are not interpreting code as java do, we just parse file and make a tree from it.

**Comment by pmcevoy12** [comment]
Closing this issue is fine.  Thanks for checking on it.
