### ISSUE TITLE
JavadocStyleCheck: String index out of range: -1

### ISSUE THREAD

**Issue by snepcadep** [checkstyle/checkstyle#2788]
When running Checkstyle plugin 2.4 on Sonar 5.2, with this "[checkstyle.xml](https://github.com/checkstyle/checkstyle/files/74809/checkstyle.txt)" file, we came across the following error during the analysis of one of our Java classes:

```
$ cat checkstyle.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="JavadocStyle">
            <property name="severity" value="warning" />
            <property name="scope" value="private" />
            <property name="checkFirstSentence" value="true" />
            <property name="checkHtml" value="true" />
            <property name="checkEmptyJavadoc" value="false" />
        </module>
    </module>
</module>
$ cat ConsultasServiceImpl.java 
public class ConsultasServiceImpl {

  /**
     * /
     */
    public void buscarLaminas() {
    }    

}

$ java -jar checkstyle-6.13-all.jar -c checkstyle.xml ConsultasServiceImpl.java 
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing ConsultasServiceImpl.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:276)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.trimTail(JavadocStyleCheck.java:316)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.getCommentText(JavadocStyleCheck.java:269)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.checkFirstSentenceEnding(JavadocStyleCheck.java:230)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.checkComment(JavadocStyleCheck.java:207)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.visitToken(JavadocStyleCheck.java:148)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:332)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:204)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 2 more
Checkstyle ends with 1 errors.
```

In a [comment](https://github.com/checkstyle/checkstyle/issues/2728#issuecomment-167800504) on issue #2728, @romani suggested we disabled the JavadocStyleCheck on Sonar as a workaround. We did it, and it worked, the analysis passed. So we're going to keep it disabled till this issue is resolved.

So, here it is "[ConsultasServiceImpl.java](https://github.com/checkstyle/checkstyle/files/80007/ConsultasServiceImpl.txt)" file.

**Comment by romani** [comment]
Please provide a file to let me reproduce the issue by cli. You can obfuscate source file. Some javadoc comment in this file cause a problem.

**Comment by romani** [comment]
@snepcadep , please provide details, without input file, this report is not helpful at all, will be closed at the end of the month.

**Comment by mkordas** [comment]
@snepcadep just send us file `ConsultasServiceImpl.java` if possible

**Comment by snepcadep** [comment]
Sorry for the delay, guys. We were trying to obfuscate the content of the file in a way we could still reproduce the error. Since the class was so large, it took us a while to do this and reduce it to a minimum necessary.

So, here it is "[ConsultasServiceImpl.java](https://github.com/checkstyle/checkstyle/files/80007/ConsultasServiceImpl.txt)" file.

Thanks for all the help!

**Comment by romani** [comment]
description is updated with minimal test case

**Comment by romani** [comment]
fix is merged.
