### ISSUE TITLE
MismatchedTokenException using annotations on arrays

### ISSUE THREAD

**Issue by MarkZ3** [checkstyle/checkstyle#2821]
Using Checkstyle 6.14.1

```
testNullAnnotations-checkstyle/src/testNullAnnotations$ javac Nullable.java NonNullUtils.java

testNullAnnotations-checkstyle/src/testNullAnnotations$ cat Nullable.java 
package testNullAnnotations;

import static java.lang.annotation.ElementType.TYPE_USE;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.CLASS)
@Target({ TYPE_USE })
public @interface Nullable {
}

testNullAnnotations-checkstyle/src/testNullAnnotations$ cat NonNullUtils.java 
package testNullAnnotations;

public final class NonNullUtils {

    private NonNullUtils() {
    }

    public static <T> T[] checkNotNullContents(T @Nullable [] array) {
        if (array == null) {
            throw new NullPointerException();
        }

        return array;
    }
}

testNullAnnotations-checkstyle/src/testNullAnnotations$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="WhitespaceAround">
            <property name="allowEmptyTypes" value="true"/>
        </module>
    </module>
</module>

testNullAnnotations-checkstyle/src/testNullAnnotations$ java -jar checkstyle-6.14.1-all.jar -c config.xml NonNullUtils.java Starting audit...
/.../testNullAnnotations-checkstyle/src/testNullAnnotations/NonNullUtils.java:8:50: expecting ELLIPSIS, found '@'
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing NonNullUtils.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:276)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred during the analysis of file NonNullUtils.java.
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:203)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 2 more
Caused by: /home/emalape/Downloads/testNullAnnotations-checkstyle/src/testNullAnnotations/NonNullUtils.java:11:9: expecting EOF, found '}'
	at antlr.Parser.match(Parser.java:211)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:210)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:453)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:185)
	... 4 more
Checkstyle ends with 1 errors.
```

[testNullAnnotations-checkstyle2.zip](https://github.com/checkstyle/checkstyle/files/89179/testNullAnnotations-checkstyle2.zip)

**Comment by romani** [comment]
thanks for reporting, just for future, the best way to report an issue is http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by MarkZ3** [comment]
I updated the report and updated the attachment to be more in line with the How-to

**Comment by romani** [comment]
thanks a lot !!

**Comment by romani** [comment]
fixed by #2891

**Comment by romani** [comment]
@MarkZ3 , 
as soon as https://travis-ci.org/checkstyle/checkstyle/jobs/108286542 is finished , binaries will be at 
https://oss.sonatype.org/content/repositories/snapshots/com/puppycrawl/tools/checkstyle/6.16-SNAPSHOT/ . Please test your sources to make sure that did not miss anything. Feel free to open new issues.

**Comment by MarkZ3** [comment]
I tested with version 6.16 (I noticed it was already released) and it worked. Thank you very much!
