### ISSUE TITLE
StringIndexOutOfBoundsException in RightCurlyCheck

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#2863]
Input:
```java
import pack;

class Test {
  public static final String CONSTANT = "This
          is
          constant";}
```
Result:
```
vlad@vlad-N61PC-M2S ~/cli $ java -jar checkstyle-6.15-all.jar -c /google_checks.xml Test.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Test.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:276)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 45
	at java.lang.String.charAt(String.java:658)
	at com.puppycrawl.tools.checkstyle.utils.CommonUtils.lengthExpandedTabs(CommonUtils.java:184)
	at com.puppycrawl.tools.checkstyle.api.Check.log(Check.java:254)
	at com.puppycrawl.tools.checkstyle.api.AbstractViolationReporter.log(AbstractViolationReporter.java:143)
	at com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck.visitToken(RightCurlyCheck.java:194)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:375)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:486)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:317)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:189)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 2 more
Checkstyle ends with 1 errors.

```
Config: /google_checks.xml

**Comment by Vladlis** [comment]
Sorry, the input file is non-compilable :)
Strange that TreeWalker parses it without exceptions if right curly brace is on the next line:
```java
import pack;

class Test {
  public static final String CONSTANT = "This
          is
          constant";
}
```

**Comment by romani** [comment]
> Strange that TreeWalker parses it without exceptions

it is happens and it is expected, as  our parser is not ideal.
