### ISSUE TITLE
FileContents confused about number of lines in comment separated by '\r'

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3066]
Taken from [PR #3060](https://github.com/checkstyle/checkstyle/pull/3060#issuecomment-201306771)

When the java lexer is given the comment `/* \r\u0000\u0000 */` it throws an ArrayIndexOutOfBoundsException.

Code in AstRegressionTest:
````
verifyAstRaw(getPath("InputRegressionEmptyAst.txt"), "/* \r\u0000\u0000 */", true);
````
Exception:
````
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:324)
	at com.puppycrawl.tools.checkstyle.api.FileContents.line(FileContents.java:224)
	at com.puppycrawl.tools.checkstyle.api.FileContents.extractCComment(FileContents.java:189)
	at com.puppycrawl.tools.checkstyle.api.FileContents.reportCComment(FileContents.java:136)
	at com.puppycrawl.tools.checkstyle.api.FileContents.reportBlockComment(FileContents.java:102)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.mBLOCK_COMMENT_BEGIN(GeneratedJavaLexer.java:1204)
````

Some of the cause:
Basically `FileContents.extractCComment` retrieved start and ends positions for the comment saying this was a 2 line comment. `FileContents.line` on the other hand says this is only a 1 line comment. So the exception occurs when `FileContents.extractCComment` tries to retrieve the non-existent second line of the comment.

**Comment by robertpainsi** [comment]
Relates to https://github.com/checkstyle/checkstyle/issues/2329?

**Comment by rnveach** [comment]
@robertpainsi No.
This issue is specifically with the Java parser. #2329 is with a utility call to the JavaDoc parser, and it not checking for errors after parsing.

**Comment by robertpainsi** [comment]
Ah, ok.

**Comment by romani** [comment]
fix is merged.
