### ISSUE TITLE
new Filter: SuppressByMessageFilter

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3082]
base on discussion at #3077 , we had a lot similar cases in the past and it is already known good enhancement, but now we create an issue on this.

we need to make new filter to allow to do suppression base on violation message.

Config should looks like:

```
<module name="SuppressByMessageFilter">
  <property name="checkFormat" value="RequireThis"/>
  <property name="messageFormat" value=".*(logger|log).*"/>
</module>
```

This issue is slightly related (as it might cover) #2804 case.

```
<module name="SuppressByMessageFilter">
  <property name="checkFormat" value=".*"/>
  <property name="messageFormat" value="Missing a Javadoc comment\."/>
</module>
```

> #2804

This issue suggest update for http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter
that let users choose their own model of excludes/suppressions in separate file. Main point - separate config file.

> #3082

is an update to let user filter-out/suppress violation from main configuration file. 

Summary:
Both approaches have right to exists and do make sense (user will chose what is more suitable for his project himself). Both features are approved. 

PS:
filter and suppression has the same meaning in checkstyle.
http://checkstyle.sourceforge.net/config_filters.html.
## 

-------

<a href="https://www.bountysource.com/issues/32708276-new-filter-suppressbymessagefilter">
<img src="https://api.bountysource.com/badge/issue?issue_id=32708276">
</a>

**Comment by romani** [comment]
@mmoayyed ,
If you need this feature sooner rather than later, please be welcome to contribute. Such filter is so easy to implement - http://checkstyle.sourceforge.net/writingfilters.html , I will guide through development process.

**Comment by rnveach** [comment]
@romani 
Isn't this just a different approach of #2804 but leading to the same result? One suggestion is a filter, while the other suggestion is a suppression.
Are we going to include both?

**Comment by romani** [comment]
Result is the same , but approach is different.

in #2804 , we are going to suppress by message without considering name of the Check
in this issue we are strict to name of Check, the more options to be exact the better.

user can always do:
```
<module name="SuppressByMessageFilter">
  <property name="checkFormat" value=".*"/>
  <property name="messageFormat" value="Missing a Javadoc comment\."/>
</module>
```
to make it general for all.

Am I miss smth ? 
@rnveach , if result is the same, lets close #2804 , as special filter is more flexible solution.

**Comment by rnveach** [comment]
#2804 was more asking for the addition of suppression by message, not really requesting message can only be by itself. It was just the example was for a specific message by multiple checks. Ignoring the specific check names or adding each one would lead to the same result.

Suppression right now allows single attributes or multiple. We can ignore by file, or ignore by file and check, etc. I see no reason we can't allow something like the below to the suppressions:
````
<suppressions>
    <suppress checks="RequireThis" messages=".*'(logger|log)'.*" />
</suppressions>
````

What flexibility can the filter provide that it is impossible, or doesn't fit, to add to the suppression?

**Comment by mmoayyed** [comment]
Sure. I would be happy to contribute once the discussion settles.

**Comment by romani** [comment]
> One suggestion is a filter, while the other suggestion is a suppression.

filter and suppression has the same meaning in checkstyle.
http://checkstyle.sourceforge.net/config_filters.html

> #2804 

This issue suggest update for http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter
that let users choose their own model of excludes/suppressions in separate file. Main point - separate config file.

> #3082

is an update to let user filter-out/suppress violation from main configuration file. 

Summary:
Both approaches have right to exists and do make sense (user will chose what is more suitable for his project himself). Both features are approved.

**Comment by romani** [comment]
@rnveach , I am squashing discussion to keep issue clean and easy to read.

**Comment by romani** [comment]
@mmoayyed , please be welcome with PullRequest.

**Comment by romani** [comment]
it is become available as part of existing Filter - http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter 

> message - a Regular Expression matched against the message of the check associated with an audit event. Optional as long as checks or id is specified.

**Comment by rnveach** [comment]
@romani as stated at https://github.com/checkstyle/checkstyle/issues/3082#issue-146621733 , this issue was to let users suppress message inside configuration file and not require an external file. #2804 requires they put the suppression in an external file.

**Comment by nmancus1** [comment]
I'm on this.

**Comment by nmancus1** [comment]
Can I work on this?

**Comment by bossever** [comment]
I'm on it.

**Comment by Rahulkhinchi03** [comment]
I am on it.

**Comment by Rahulkhinchi03** [comment]
![abcd](https://user-images.githubusercontent.com/71710042/148689204-a185d456-2a9e-4876-bd25-d124e86896f6.png)


com.puppycrawl.tools.checkstyle.api.CheckstyleException: Config comment not specified properly in C:\Users\ASUS\Desktop\OpenSource\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressbymessagefilter\InputSuppressByMessageFilter.java

	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.parse(InlineConfigParser.java:116)
	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.parse(InlineConfigParser.java:95)
	at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyWithInlineConfigParser(AbstractModuleTestSupport.java:267)
	at com.puppycrawl.tools.checkstyle.filters.SuppressByMessageFilterTest.verifySuppressed(SuppressByMessageFilterTest.java:154)
	at com.puppycrawl.tools.checkstyle.filters.SuppressByMessageFilterTest.testNoMatchMessage(SuppressByMessageFilterTest.java:131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to resolve module name: Config:. Please check for spelling errors or specify fully qualified class name.
	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.getFullyQualifiedClassName(InlineConfigParser.java:157)
	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.setModuleName(InlineConfigParser.java:217)
	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.setModules(InlineConfigParser.java:138)
	at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.parse(InlineConfigParser.java:112)
	... 69 more


Process finished with exit code -1

**Comment by rnveach** [comment]
@Rahulkhinchi03 Check name and filter name are missing from javadoc. I don't believe `Config:` is valid.
Look at other input files for examples.

**Comment by Rahulkhinchi03** [comment]
Changes done but found new error:
`com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module com.puppycrawl.tools.checkstyle.TreeWalker - TreeWalker is not allowed as a parent of com.puppycrawl.tools.checkstyle.filters.SuppressByMessageFilter Please review 'Parent Module' section for this Check in web documentation if Check is standard.`

**Comment by Vyom-Yadav** [comment]
@Rahulkhinchi03 Are you still on this? If not I would like to solve this issue.

**Comment by Rahulkhinchi03** [comment]
@Vyom-Yadav I want to work on this issue but I'm stuck at one thing and not able to resolve the error!

**Comment by Vyom-Yadav** [comment]
> I can continue with this but I believe you can resolve this issue better.

Thanks for the kind words, I will start working on this issue.

**Comment by stoyanK7** [comment]
@Vyom-Yadav Are you still on it? If not, I would like to take it :)

**Comment by Vyom-Yadav** [comment]
@stoyanK7 I am not working on it, feel free to take it up :)

**Comment by romani** [comment]
@rnveach ,

https://checkstyle.org/config_filters.html#SuppressionSingleFilter

> message | Define the RegExp for matching against the message of the check associated                   with an audit event. | Pattern | null | 8.23

>  Suppress naming violations on variable named 'log' in all files:
```
<module name="SuppressionSingleFilter">
  <property name="message" value="Name 'log' must match pattern"/>
</module>
```

So this feature already implemented..... I am curios why we still need    https://github.com/checkstyle/checkstyle/issues/3082 ?
I think we can close this issue.

**Comment by rnveach** [comment]
I agree, this seems to have been already implemented by #6402 . It can be closed.

**Comment by romani** [comment]
@bossever , this ticket has bounty.
Please login to bountysource and start a progress on it.
I will close issue and and you will be able to claim a bounty, in other case it will be lost. So better to give it to person who did some activity on it, even it resulted in no code solution.

**Comment by bossever** [comment]
@romani, I have started issue on bountysource.

**Comment by romani** [comment]
please claim bounty
