### ISSUE TITLE
Checkstyle crashes when it encounters a syntax error

### ISSUE THREAD

**Issue by dylemma** [checkstyle/checkstyle#3084]
If, for example, there is a file called `Fake.java` that has non-java content, Checkstyle will crash with an exception, and ignore all other files that it hadn't gotten around to yet.

	com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing [...]\Fake.java
		at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
		at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:276)
		at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
	Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred during the analysis of file [...]\Fake.java.
		at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:203)
		at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
		at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
		... 2 more
	Caused by: [...]\Fake.java:1:1: unexpected token: Fake
		at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:180)
		at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:453)
		at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:185)
		... 4 more
	Checkstyle ends with 1 errors.

I think it would be better to emit an Error as output, and move on to the next file, rather than crash.

FWIW - I'm on Windows, and using checkstyle 6.15

**Comment by romani** [comment]
This is our limitations, usage of checkstyle for non java content is NOT the way we expect , we do not support it. There might be more problems.
http://checkstyle.sourceforge.net/writingchecks.html#Limitations
We use this fast-fail mode in our testing (we already benefit from it).

If you need this, you can fork from us make a hack to catch exception and continue execution (should not be that complicated). 
If your fix will be elegant enough you can propose it will take a look, bit no guaranty on merge of it.
