### ISSUE TITLE
NullPointerException in FinalLocalVariableCheck with Lambdas

### ISSUE THREAD

**Issue by zapster** [checkstyle/checkstyle#3144]
Checkstyle terminates due to a `NullPointerExcetpion` when processing the file `Operation.java`:
``` java
@FunctionalInterface
public interface Operation {

    public Object apply();

    public static final Operation OPERATION = () -> {
        Object result;
        result = null;
        return result;
    };
}
```
`java -jar checkstyle-6.17-all.jar -c checks.xml Operation.java` 

```
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Operation.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:318)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:274)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:330)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:159)
Caused by: java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.findFirstUpperNamedBlock(FinalLocalVariableCheck.java:488)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.isSameVariables(FinalLocalVariableCheck.java:505)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.removeVariable(FinalLocalVariableCheck.java:393)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.visitToken(FinalLocalVariableCheck.java:212)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:363)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:478)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:305)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:181)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:338)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:308)
        ... 3 more
Checkstyle ends with 1 errors.
```

If the line `result = null;` is removed the issues disappears. The same happens if the Lambda is replace with an anonymous class instance, i.e. `OPERATION = new Operation() {...`.

Content of `checks.xml`:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="severity" value="error"/>
  <module name="TreeWalker">
    <module name="FinalLocalVariable">
      <property name="severity" value="ignore"/>
      <metadata name="net.sf.eclipsecs.core.lastEnabledSeverity" value="inherit"/>
    </module>
  </module>
</module>
```

**Comment by rnveach** [comment]
The exception still exists in the latest master, using commit 12718d8. Below are the current line numbers.
```
$ java -jar checkstyle-nightly-2016-04-28-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
....
Caused by: java.lang.NullPointerException
    at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.findFirstUpperNamedBlock(FinalLocalVariableCheck.java:571)
    at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.isSameVariables(FinalLocalVariableCheck.java:587)
    at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.access$700(FinalLocalVariableCheck.java:77)
    at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck$ScopeData.findFinalVariableCandidateForAst(FinalLocalVariableCheck.java:644)
    at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.getFinalCandidate(FinalLocalVariableCheck.java:295)
    at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.visitToken(FinalLocalVariableCheck.java:212)
```
