### ISSUE TITLE
CheckstyleException Caused by: java.util.NoSuchElementException at com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck.leaveToken

### ISSUE THREAD

**Issue by vorburger** [checkstyle/checkstyle#3190]
I'm occasionally, not 100% reliably reproducible, but regularly enough (like it occurs every now and then, not just once) seeing the error below, in the Error Log of Eclipse when using eCS 6.16.0.

I've not yet seen it on the CLI when running CS through mvn, but that's likely just because I run that less often than workspace rebuilds in E.. ;-) I don't see how this could be an eCS bug, and must suspect this is something not quite right somewhere in CS core, do you agree?

Perhaps just seeing this means something to you, and you could figure out a way to "harden" respective CS code to prevent this? (The XMLStreamNormalizedNodeStreamWriter.java file under check causing this is OSS, so you may be able to reproduce it locally if you really want and have the time; let me know if you want details how to obtain this.)

Unless you have reason to believe that some specific change likely already fixed this in latest CS version, of course.

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/vorburger/dev/ODL/git/yangtools/yang/yang-data-impl/src/main/java/org/opendaylight/yangtools/yang/data/impl/codec/xml/XMLStreamNormalizedNodeStreamWriter.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:319)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:275)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:159)
	at net.sf.eclipsecs.core.jobs.AuditorJob.runInWorkspace(AuditorJob.java:82)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.NoSuchElementException
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:280)
	at java.util.ArrayDeque.pop(ArrayDeque.java:517)
	at com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck.leaveToken(AbstractTypeAwareCheck.java:178)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyLeave(TreeWalker.java:379)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:481)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:305)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:185)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:339)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:309)
	... 5 more

```

**Comment by vorburger** [comment]
BTW here is another similar one which could likely have the same underlying root cause - it seems that under certain circumstances something is off somewhere in that TreeWalker...

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/vorburger/dev/ODL/git/yangtools/yang/yang-parser-impl/target/generated-sources/parser/org/opendaylight/yangtools/antlrv4/code/gen/YangParserBaseVisitor.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:319)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:275)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:159)
	at net.sf.eclipsecs.core.jobs.AuditorJob.runInWorkspace(AuditorJob.java:82)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 671
	at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:321)
	at com.puppycrawl.tools.checkstyle.api.FileContents.line(FileContents.java:224)
	at com.puppycrawl.tools.checkstyle.api.FileContents.lineIsBlank(FileContents.java:277)
	at com.puppycrawl.tools.checkstyle.api.FileContents.getJavadocBefore(FileContents.java:208)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck.processAST(JavadocMethodCheck.java:352)
	at com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck.visitToken(AbstractTypeAwareCheck.java:154)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:363)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:478)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:305)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:185)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:339)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:309)
	... 5 more
```
