### ISSUE TITLE
CLI Javadoc tree printer doesn't show errors

### ISSUE THREAD

**Issue by baratali** [checkstyle/checkstyle#3219]
myjavadoc.txt:

```
<audio>
```

Output:

```
git\checkstyle>java -jar target\checkstyle-6.18-SNAPSHOT-all.jar -j myjavadoc.txt

git\checkstyle>
```
##

**Comment by romani** [comment]
Exception should not be printed if that is not Checkstyle logic failure as we treat Javadoc parse failures as violations.

Printed exception from CLI is scary and users will open issues on this , as it is not clear for them is it their input file problem or Checkstyle internal problem.

So issue is not resolved but we did good step forward.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinter.java#L70

No exception should be thrown, or `DetailNodeTreeStringPrinter.printFileAst` should catch it and print only error message `getParseErrorMessage(status.getParseErrorMessage())`.

**Comment by romani** [comment]
assigned to aaditya sharma .
https://groups.google.com/forum/#!topic/checkstyle-devel/icKK3_JPcgc

**Comment by lordozb** [comment]
I'm on it.

**Comment by romani** [comment]
@kazachka , please help us this this issue. previous assignments are not valid as there were no actions for more than month

**Comment by romani** [comment]
issue is resolved already:
```
$ java -jar checkstyle-7.6-all.jar -j myjavadoc.txt
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:0] Javadoc comment at column 1 has parse error. Missed HTML close tag 'audio'. Sometimes it means that close tag missed for one of previous tags.
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:83)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseFile(DetailNodeTreeStringPrinter.java:175)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.printFileAst(DetailNodeTreeStringPrinter.java:59)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:328)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)

```

**Comment by rnveach** [comment]
The problem was fixed in 6.19.

````
java -jar checkstyle-6.19-all.jar -j myjavadoc.txt
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:0] Javadoc comment at column 1 has parse error. Missed HTML close tag 'audio'. Sometimes it means that close tag missed for one of previous tags.
````

**Comment by rnveach** [comment]
@romani Are you sure this issue is done?
You commented above you don't want it to be displayed as an exception because it would scare users.

https://github.com/checkstyle/checkstyle/issues/3219#issuecomment-222358834
> Printed exception from CLI is scary and users will open issues on this , as it is not clear for them is it their input file problem or Checkstyle internal problem.

https://github.com/checkstyle/checkstyle/issues/3219#issuecomment-283192570
> No exception should be thrown ... should catch it and print only error message

**Comment by romani** [comment]
@rnveach , good point

but we do stacktrace for java grammar error, so for consistency it will be better to print whole stake trace:
```
$ cat Test.java 

public1 class Test {
}

$ java -jar checkstyle-7.6-all.jar -t Test.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred during the analysis of file Test.java.
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseFileText(AstTreeStringPrinter.java:249)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseFile(AstTreeStringPrinter.java:223)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:69)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:318)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)
Caused by: Test.java:2:1: unexpected token: public1
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:181)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:439)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseFileText(AstTreeStringPrinter.java:242)
	... 4 more
Checkstyle ends with 1 errors.

```

**Comment by lordozb** [comment]
And I went on pulling my hair out for finding the bug.
