### ISSUE TITLE
Java Grammar: annotation before variable declaration

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3236]
Taken from PR #3230 when working on Issue #3033 from a run on OpenJDK 8 in `test/tools/pack200/typeannos/TypeUseTarget.java`.

```
$ cat TestClass.java
package test;

import java.lang.annotation.Target;
import java.lang.annotation.ElementType;

public class TestClass {
    void method() {
        @B Object o = new @B String @B [3];
    }
}
@Target(ElementType.TYPE_USE)
@interface B { }

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="FinalLocalVariable" />
    </module>
</module>

$ java -jar checkstyle-6.19-all.jar -c TestConfig.xml TestClass.java
Starting audit...
TestClass.java:8:12: expecting "class", found 'Object'
TestClass.java:8:30: unexpected token: String
TestClass.java:8:40: unexpected token: [
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:281)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:196)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:396)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:330)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:161)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred during the analysis of file TestClass.java.
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:193)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:301)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:271)
    ... 4 more
Caused by: TestClass.java:9:5: expecting EOF, found '}'
    at antlr.Parser.match(Parser.java:211)
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:211)
    at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:440)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:175)
    ... 7 more
Checkstyle ends with 1 errors.
```

Input is compilable with java 8 javac.

-----

https://github.com/wcm-io looks like using this syntax, all projects should be used to validate grammar update.

**Comment by esilkensen** [comment]
Has this issue been fixed? With the latest code, running the example from above prints out
```
Starting audit...
Audit done.
```

**Comment by romani** [comment]
fix is merged

**Comment by romani** [comment]
@esilkensen ,

> https://github.com/wcm-io looks like using this syntax, all projects should be used to validate grammar update.

we forgot to test fix on real code of users, please run some regression test on such projects, to make sure we do not have parse error any more. 
@stefanseifert  should be notified to activate checkstyle back if they still want it.
release of fix will be done tomorrow.

**Comment by esilkensen** [comment]
Sounds good, I will do that and report back here soon.

**Comment by romani** [comment]
Please do me extra favor and update https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L15 to remove file from exclude that now is supported :) as you fixed parse issue.

**Comment by esilkensen** [comment]
Here is a regression report comparing current master with the commit right before it: http://esilkensen.github.io/checkstyle-tester/3238-wcm-io/index.html

I will open a checkstyle-tester PR later today.

**Comment by romani** [comment]
Hmm, there are still bunch of parse errors, did you had a chance to take a look at what syntax we still do not support ? New issues should be created ...
