### ISSUE TITLE
RequireThisCheck: NPE when surrounded by braces

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3334]
````
$ cat TestClass.java
public final class TestClass {
    protected void test() throws Exception {
        {
            boolean hasSponsor = false;

            hasSponsor = true;
        }

        {
            boolean hasChanges = false;


            hasChanges = true;
        }
    }
}


$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="RequireThisCheck">
<property name="checkFields" value="true" />
<property name="checkMethods" value="false" />
<property name="validateOnlyOverlapping" value="false" />
</module>
    </module>
</module>

$ java -jar checkstyle-7.0-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:281)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:196)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:389)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:323)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:161)
Caused by: java.lang.NullPointerException
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.isUserDefinedArrangementOfThis(RequireThisCheck.java:485)
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.getClassFrameWhereViolationIsFound(RequireThisCheck.java:461)
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.getFieldWithoutThis(RequireThisCheck.java:308)
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.processIdent(RequireThisCheck.java:264)
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.visitToken(RequireThisCheck.java:225)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:362)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:505)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:304)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:179)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:301)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:271)
    ... 4 more
Checkstyle ends with 1 errors.
````

Removing the braces around `hasChanges` makes the exception go away.

**Comment by rnveach** [comment]
PR was merged, so issue is fixed.
