### ISSUE TITLE
PackageObjectFactory hides real exception

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3778]
While upgrading backport to 7.5, running Checkstyle on the project resulted in `AtclauseOrderCheck` to not be able to be instantiated.
````
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Unable to instantiate 'AtclauseOrder' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.blocks.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.coding.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.design.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.header.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.imports.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.indentation.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.javadoc.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.metrics.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.modifier.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.naming.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.regexp.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.sizes.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.whitespace.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.AtclauseOrder, com.puppycrawl.tools.checkstyle.filefilters.AtclauseOrder, com.puppycrawl.tools.checkstyle.filters.AtclauseOrder, com.puppycrawl.tools.checkstyle.AtclauseOrder, AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.annotation.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.blocks.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.coding.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.design.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.header.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.imports.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.indentation.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.metrics.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.modifier.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.naming.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.regexp.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.sizes.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.filefilters.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.filters.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.AtclauseOrderCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:455)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:171)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:423)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:361)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:176)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'AtclauseOrder' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.blocks.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.coding.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.design.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.header.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.imports.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.indentation.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.javadoc.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.metrics.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.modifier.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.naming.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.regexp.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.sizes.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.whitespace.AtclauseOrder, com.puppycrawl.tools.checkstyle.checks.AtclauseOrder, com.puppycrawl.tools.checkstyle.filefilters.AtclauseOrder, com.puppycrawl.tools.checkstyle.filters.AtclauseOrder, com.puppycrawl.tools.checkstyle.AtclauseOrder, AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.annotation.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.blocks.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.coding.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.design.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.header.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.imports.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.indentation.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.metrics.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.modifier.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.naming.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.regexp.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.sizes.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.checks.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.filefilters.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.filters.AtclauseOrderCheck, com.puppycrawl.tools.checkstyle.AtclauseOrderCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:139)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:152)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:171)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:450)
	... 4 more
Checkstyle ends with 1 errors.
````

There was no good reason for the problem given in the exception log so I had to dig into the problem manually. When debugging the problem, I found that the module was found in the `Map` and was located using `Class.for` but it failed to instantiate the check. No exception was being printed or reported because it was being ignored via https://github.com/checkstyle/checkstyle/blob/b4a337a599e853cdc44b19a76da28fcfab2956cd/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L221 .
When adding a `printStackTrace` the reason for the problem was shown.
````
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createObject(PackageObjectFactory.java:223)
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createObjectFromMap(PackageObjectFactory.java:160)
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:124)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:152)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:171)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:450)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:171)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:423)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:361)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:176)
Caused by: java.lang.UnsupportedClassVersionError: org/antlr/v4/runtime/misc/ParseCancellationException : Unsupported major.minor version 51.0
````
Reason for exception was antlr upgraded to Java 7 in 4.6 .

I think this error should have been reported in the console. The original reason for ignoring the exception was because `Class.for` could fail while we search for the module. In this case, it wasn't failing to find it.
IMO, we should report any exception after `Class.for` succeeds when we fail to work with the constructor or instantiating. We found the class, no other work or searching we do will get it to instantiate correctly.

**Comment by romani** [comment]
> IMO, we should report any exception after Class.for

agree, the place for logic that is based on exception should be as narrow as possible. Brute force search is our old design problem. Ignorance of exceptions should only for code/lines that support brute force search of module in classpath.

**Comment by romani** [comment]
fix is merged.
