### ISSUE TITLE
Eclipse-CS plugin 7.3.0 cannot be installed from Marketplace or updatesite

### ISSUE THREAD

**Issue by KTannenberg** [checkstyle/checkstyle#3834]
Eclipse-CS (7.3.0) can be found on Eclipse Marketplace, but installation fails:
![image](https://cloud.githubusercontent.com/assets/1444439/22971649/4e8f9c7c-f36e-11e6-9bd4-7470f3a11438.png)

Following error is shown in Error Log:
```
Unable to read repository at https://sourceforge.net/projects/eclipse-cs/files/updatesite/7.3.0/content.xml.
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.SNIAwareHttpClient$1.connectSocket(SNIAwareHttpClient.java:63)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:263)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

Eclipse-CS is also not available for installation from updatesite:
![image](https://cloud.githubusercontent.com/assets/1444439/22971750/a96866ba-f36e-11e6-8057-f52162cddd04.png)
Same exception appears in Error Log when Eclipse attempts to get list of available plugins from updatesite.

Plugin works fine after manual installation from zip archive downloaded from SF

**Comment by KTannenberg** [comment]
Ups, wrong place, I'll move it to https://sourceforge.net/p/eclipse-cs/bugs/, sorry
