### ISSUE TITLE
Type annotations on array make Checkstyle crash

### ISSUE THREAD

**Issue by tomvandenberge** [checkstyle/checkstyle#3857]
/var/tmp $ cat MyClass.java

```
import org.eclipse.jdt.annotation.NonNull;
public class MyClass {
	int[] array = new int @NonNull []{};
}
```

/var/tmp $ java -jarcheckstyle-7.5.1-all -c /google_checks.xml MyClass.java
```
Starting audit...
.../MyClass.java:7:24: unexpected token: @
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src/test/java/MyClass.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:293)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:211)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:425)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:359)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred during the analysis of file src/test/java/MyClass.java.
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:192)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:314)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:284)
	... 4 more
Caused by: .../MyClass.java:8:1: expecting EOF, found '}'
	at antlr.Parser.match(Parser.java:211)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:211)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:439)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:174)
	... 7 more
```
---------------

The type annotation on the array seem to be not supported?

**Comment by romani** [comment]
first line of PR template is verification that file is compilable by java, please do not skip it.

```
/var/tmp$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

/var/tmp$ cat MyClass1.java 
import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.LOCAL_VARIABLE;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.PARAMETER;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

public class MyClass1 {
    @NonNull
    int[] array = new int @NonNull []{};
}

@Documented
@Retention(RetentionPolicy.CLASS)
@Target({ FIELD, METHOD, PARAMETER, LOCAL_VARIABLE })
@interface NonNull {
    // marker annotation with no members
}

/var/tmp$ javac MyClass1.java 
javac MyClass1.java 
MyClass1.java:13: error: annotation type not applicable to this kind of declaration
    int[] array = new int @NonNull []{};
                          ^
1 error
```

if that is allowed in some new java - please prove this by commands.

**Comment by tomvandenberge** [comment]
This is supported since Java8.

I'm sorry, I didn't include an accurate reference to the NonNull annotation. You've picked an old version. You should get it from https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.annotation/src/org/eclipse/jdt/annotation/NonNull.java:

```
import static java.lang.annotation.ElementType.TYPE_USE;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

public class MyClass {
	int[] array = new int @NonNull []{};
}

@Retention(RetentionPolicy.CLASS)
@Target({ TYPE_USE })
@interface NonNull {}
```

**Comment by rnveach** [comment]
If input is now compilable, it looks like it might be related to #3236. That example just has more annotation uses.

**Comment by tomvandenberge** [comment]
You're right, #3236 seems to be the same problem.
