### ISSUE TITLE
code cleanup: to make updates to xdoc easy to review

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#3934]
apply patch:
```
$ git diff
diff --git a/src/xdocs/config_blocks.xml b/src/xdocs/config_blocks.xml
index 65a4327..ac72e26 100644
--- a/src/xdocs/config_blocks.xml
+++ b/src/xdocs/config_blocks.xml
@@ -799,7 +799,8 @@ for(int i = 0; i &lt; 10; value.incrementValue()); // OK
             <a
              href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#STATIC_INIT">STATIC_INIT</a>,
             <a
-             href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#INSTANCE_INIT">INSTANCE_INIT</a>.</td>
+             href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#INSTANCE_INIT">INSTANCE_INIT</a>
+            .</td>
 
             <td><a
              href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_TRY">LITERAL_TRY</a>,
@@ -810,7 +811,8 @@ for(int i = 0; i &lt; 10; value.incrementValue()); // OK
             <a
              href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_IF">LITERAL_IF</a>,
             <a
-             href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_ELSE">LITERAL_ELSE</a>.</td>
+             href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#LITERAL_ELSE">LITERAL_ELSE</a>
+            .</td>
           </tr>
         </table>
       </subsection>
diff --git a/src/xdocs/config_whitespace.xml b/src/xdocs/config_whitespace.xml
index 49513b7..96362bf 100644
--- a/src/xdocs/config_whitespace.xml
+++ b/src/xdocs/config_whitespace.xml
@@ -831,7 +831,8 @@ sort(list, Comparable::&lt;String&gt;compareTo);             // Method reference
             <td><a
             href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#PACKAGE_DEF">PACKAGE_DEF</a>,
             <a
-             href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#IMPORT">IMPORT</a>.</td>
+             href="apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#IMPORT">IMPORT</a>
+            .</td>
           </tr>
         </table>
       </subsection>
```

patch is required to avoid changes on existing lines when new token is added

resolve UT failure:
```
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.345 sec <<< FAILURE! - in com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest
testAllCheckSections(com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest)  Time elapsed: 0.181 sec  <<< FAILURE!
org.junit.ComparisonFailure: config_whitespace.xml section 'NoLineWrap' should have all the default tokens expected:<PACKAGE_DEF, IMPORT[].> but was:<PACKAGE_DEF, IMPORT[ ].>
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validatePropertySectionPropertyTokens(XdocsPagesTest.java:563)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validatePropertySectionProperties(XdocsPagesTest.java:506)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validatePropertySection(XdocsPagesTest.java:419)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.validateCheckSection(XdocsPagesTest.java:351)
	at com.puppycrawl.tools.checkstyle.internal.XdocsPagesTest.testAllCheckSections(XdocsPagesTest.java:280)

```

**Comment by nikhilgupta23** [comment]
I am on it.

**Comment by Kietzmann** [comment]
@romani 
Looks like that previous contributor stopped the process of development. I observed that patch to config_whitespace.xml is outdated. @romani Could you please give me the latest information about this issue? Thanks.

**Comment by romani** [comment]
Problem is the same, we need to move for punctuation to new line to minimize diff when new token is added.
