### ISSUE TITLE
Checkstyle will crash if special unicode notation is used

### ISSUE THREAD

**Issue by Muselgrusel** [checkstyle/checkstyle#4112]
/var/tmp $ javac YOUR_FILE.java

Nothing

/var/tmp $ cat YOUR_FILE.java

``` java
package test;
/**
 * Comment.
 * @author user
 *
 */
public class TestClass {
    /**
     * Comment.
     */
    public void \u039cFoo() {
        System.out.println("bar");
    }
}
```

/var/tmp $ cat config.xml

https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/sun_checks.xml

/var/tmp $ java -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java

D:\Entwicklung\EclipseWorkspace\Test\src\test>java -jar checkstyle-7.6.1-all.jar -c sun_checks.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:293)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:211)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:425)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:359)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred during the analysis of file TestClass.java.
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:187)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:314)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:284)
        ... 4 more
Caused by: D:\Entwicklung\EclipseWorkspace\Test\src\test\TestClass.java:11:17: unexpected char: '\'
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:405)
        at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
        at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)
        at antlr.TokenBuffer.fill(TokenBuffer.java:69)
        at antlr.TokenBuffer.LA(TokenBuffer.java:80)
        at antlr.LLkParser.LA(LLkParser.java:52)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3231)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2542)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
        at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:439)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:174)
        ... 7 more
Checkstyle ends with 1 errors.

---------------

I would expect that checkstyle can handle the \uXXXX notation and warns the user about this kind of notation in the source code.

--------------

Still not clear ??? - see example - http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug

**Comment by rnveach** [comment]
This is similar to https://github.com/checkstyle/checkstyle/issues/2784

> unfortunately it is by design http://checkstyle.sourceforge.net/writingchecks.html#Limitations
> 
> >     Java code should be written with ASCII characters only, no UTF-8 support.

>  We are not interpreting code as java do, we just parse file and make a tree from it.
