### ISSUE TITLE
Wercker CI is unstable while cloning repositories

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4329]
reported to wercker support, no actions from them.

Wercker is periodically failing , and we can not relaunch CI bdue to another issue on wercker that is confirmed and reproduced by them and will be fixed some day.
```
27 seconds NoExceptiontest - Guava

export WERCKER_STEP_ROOT="/pipeline/script-0cb30b75-e225-4766-8c34-cdb47e58ccdd"
export WERCKER_STEP_ID="script-0cb30b75-e225-4766-8c34-cdb47e58ccdd"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="script"
export WERCKER_REPORT_NUMBERS_FILE="/report/script-0cb30b75-e225-4766-8c34-cdb47e58ccdd/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/script-0cb30b75-e225-4766-8c34-cdb47e58ccdd/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/script-0cb30b75-e225-4766-8c34-cdb47e58ccdd/artifacts"
source "/pipeline/script-0cb30b75-e225-4766-8c34-cdb47e58ccdd/run.sh" < /dev/null
Cloning into 'contribution'...
fatal: unable to access 'https://github.com/checkstyle/contribution/': Could not resolve host: github.com
```

```
NoExceptiontest - pmd elasticsearch lombok-ast

.....
Cloning git repository 'elasticsearch' to repositories/elasticsearch folder ...
Cloning into 'repositories/elasticsearch'...
fatal: unable to access 'https://github.com/elastic/elasticsearch/': Could not resolve host: github.com
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
	at launch.executeCmd(launch.groovy:294)
	at launch.executeCmd(launch.groovy:288)
	at launch$executeCmd$4.callCurrent(Unknown Source)
	at launch.cloneRepository(launch.groovy:116)
	at launch$_generateCheckstyleReport_closure2.doCall(launch.groovy:82)
	at launch.generateCheckstyleReport(launch.groovy:64)
	at launch$generateCheckstyleReport$1.callCurrent(Unknown Source)
	at launch.run(launch.groovy:10)
```

**Comment by romani** [comment]
usage of IP does not work ....
```
$ ping github.com
PING github.com (192.30.253.112) 56(84) bytes of data.
64 bytes from 192.30.253.112: icmp_seq=1 ttl=54 time=74.0 ms
64 bytes from 192.30.253.112: icmp_seq=2 ttl=54 time=75.8 ms
64 bytes from 192.30.253.112: icmp_seq=3 ttl=54 time=75.6 ms
64 bytes from 192.30.253.112: icmp_seq=4 ttl=54 time=75.9 ms
64 bytes from 192.30.253.112: icmp_seq=5 ttl=54 time=75.5 ms
64 bytes from 192.30.253.112: icmp_seq=6 ttl=54 time=73.9 ms
64 bytes from 192.30.253.112: icmp_seq=7 ttl=54 time=75.8 ms
^C
--- github.com ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6007ms
rtt min/avg/max/mdev = 73.901/75.281/75.979/0.906 ms
✔  
11:06 $ nslookup github.com
Server:     127.0.1.1
Address:    127.0.1.1#53

Non-authoritative answer:
Name:   github.com
Address: 192.30.253.113
Name:   github.com
Address: 192.30.253.112

✔  
11:08 $ git clone https://192.30.253.112/checkstyle/checkstyle.git
Cloning into 'checkstyle'...
fatal: unable to access 'https://192.30.253.112/checkstyle/checkstyle.git/': SSL: certificate subject name (github.com) does not match target host name '192.30.253.112'
✘-128 
11:09 $ git clone http://192.30.253.112/checkstyle/checkstyle.git
Cloning into 'checkstyle'...
fatal: unable to access 'https://192.30.253.112/checkstyle/checkstyle.git/': SSL: certificate subject name (github.com) does not match target host name '192.30.253.112'
```

**Comment by rnveach** [comment]
Fix was merged, I will leave this issue open for now to verify this solves the issue

**Comment by romani** [comment]
Works fine, fixed
