### ISSUE TITLE
CLI Javadoc tree printing does not check placement of Javadoc

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4405]
Identified when talking about it at https://github.com/checkstyle/contribution/issues/237#issuecomment-305376062 and considered an issue from romani's comments at https://github.com/checkstyle/checkstyle/issues/4390#issuecomment-305358371 .

````
$ cat TestClass.java
public class TestClass {
    void method() {
/** <html */
    }
}

$ java -jar checkstyle-7.8-all.jar -J TestClass.java
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:3] Javadoc comment at column 7 has parse error. Details: no viable alternative at input '<html ' while parsing HTML_ELEMENT
    at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseAndPrintJavadocTree(AstTreeStringPrinter.java:117)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:99)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:103)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:103)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:103)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:103)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:103)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:82)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:333)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)
````

From @romani 's comments in another issue, we shouldn't be parsing this "javadoc" as it is in an invalid position. We should treat is as a normal comment.

Issue is with the following code:
https://github.com/checkstyle/checkstyle/blob/3bd3a52280388520c64ec813dd1e4ffb3a0063a2/src/main/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinter.java#L98
https://github.com/checkstyle/checkstyle/blob/073c370de2e65fc346b51ef09763ecb30b5cd14f/src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java#L246

**Comment by romani** [comment]
fix is merged.

**Comment by Vladlis** [comment]
regression testing is required

**Comment by romani** [comment]
regression reports are in PR, they are fine.
