### ISSUE TITLE
NoWhitespaceAfterCheck for some array initialization crashes Checkstyle

### ISSUE THREAD

**Issue by denizarsan** [checkstyle/checkstyle#4557]
$ javac C.java

$ cat C.java
```java
class C {
    int i = new int[]{1}[0];
}
```

$ cat config.xml
```
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="NoWhitespaceAfter"/>
  </module>
</module>
```

$ java -jar checkstyle-7.8.2-all.jar -c config.xml C.java
```
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:425)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:359)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)
Caused by: java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck.getPositionAfter(NoWhitespaceAfterCheck.java:175)
        at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck.visitToken(NoWhitespaceAfterCheck.java:133)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:370)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:507)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:312)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:184)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 4 more
Checkstyle ends with 1 errors.
```
---------------

The tool crashes with a NPE for the given config and class.  The problem is the array-initialization expression that creates an array with concrete values (in this case "1") and then indexes into it.

Please let me know if you want me to help with fixing this.

Attention: suppressed at circleci by - https://github.com/checkstyle/contribution/commit/284acd31b9f3d5274f72ba489d6aff335c286437

**Comment by rnveach** [comment]
@denizarsan Please don't report issues using snapshot version. It is unclear what commit you used or if you added any of your own custom code on top of it. Please use release versions and update your first post.

**Comment by denizarsan** [comment]
@rnveach I have updated my post. I'm using the latest release (7.8.2) from https://sourceforge.net/projects/checkstyle/files/checkstyle/

**Comment by sergileon** [comment]
I am on it

**Comment by Vladlis** [comment]
checkstyle/contribution@284acd3 is still to be reverted

**Comment by romani** [comment]
commit is reverted in contribution

**Comment by romani** [comment]
I think this issue is fixed.

**Comment by Vladlis** [comment]
java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck.getPositionAfter(NoWhitespaceAfterCheck.java:181)
	at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck.visitToken(NoWhitespaceAfterCheck.java:139)

is caught by Werckwr on on checkstyle/sevntu-checkstyle job, @sergileon please investigate and fix

**Comment by sergileon** [comment]
i run job on the master and not see exception

**Comment by romani** [comment]
@Vladlis , I do not see problem on master wercker, please share link

**Comment by romani** [comment]
I am closing issue, till smb show we exact and reproducible case

**Comment by romani** [comment]
please make sure you use checkstyle version 8.3 and above to run without exception.

**Comment by msimko81** [comment]
Thanks. I have used the default plugin referenced from gradle 4.6
By specifying the checkstyle tool version 8.10, everything works now.
