### ISSUE TITLE
Checkstyle does not support annotations on array types

### ISSUE THREAD

**Issue by denizarsan** [checkstyle/checkstyle#4589]
$ javac C.java

$ cat C.java
```java
@java.lang.annotation.Target(java.lang.annotation.ElementType.TYPE_USE)
@interface A {}

class C {
    int i @A [];
}
```
$ cat config.xml
```
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="LineLength"/> <!-- can be any check that requires parsing -->
  </module>
</module>
```
$ java -jar checkstyle-7.8.2-all.jar -c config.xml C.java
```
Starting audit...
/tmp/C.java:5:14: unexpected token: [
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:425)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:359)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred during the analysis of file C.java.
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:201)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 4 more
Caused by: /tmp/C.java:6:1: expecting EOF, found '}'
        at antlr.Parser.match(Parser.java:211)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:211)
        at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:448)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:179)
        ... 7 more
Checkstyle ends with 1 errors.
```
---------------

Such annotations are supported, at least in javac 1.8.0_131, but Checkstyle crashes.

-------

<a href="https://www.bountysource.com/issues/46820976-checkstyle-does-not-support-annotations-on-array-types">
<img src="https://api.bountysource.com/badge/issue?issue_id=46820976">
</a>

**Comment by rnveach** [comment]
Is probably the same as https://github.com/checkstyle/checkstyle/issues/3236

**Comment by romani** [comment]
fix is merged.

@esilkensen , please request bounty.
