### ISSUE TITLE
SummaryJavadocCheck crashes for some comments with "=>"

### ISSUE THREAD

**Issue by denizarsan** [checkstyle/checkstyle#4590]
$ javac C.java

$ cat C.java
```java
// simplified from https://github.com/jclouds/legacy-jclouds/blob/1665a70471609aed0314dc60e27a80c7ffa65d45/providers/gogrid/src/main/java/org/jclouds/gogrid/services/GridServerClient.java
public class C {
    /**
     * @return map <X =>
     */
    public int m() { return 0; }
}
```
$ cat config.xml
```
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="SummaryJavadoc"/>
  </module>
</module>
```
$ java -jar checkstyle-7.8.2-all.jar -c config.xml C.java
```
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:425)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:359)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)
Caused by: java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser$DescriptiveErrorListener.syntaxError(JavadocDetailNodeParser.java:494)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Lexer.notifyListeners(Lexer.java:364)
        at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:144)
        at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
        at org.antlr.v4.runtime.BufferedTokenStream.fill(BufferedTokenStream.java:485)
        at org.antlr.v4.runtime.BufferedTokenStream.getText(BufferedTokenStream.java:452)
        at org.antlr.v4.runtime.BufferedTokenStream.getText(BufferedTokenStream.java:474)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:276)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:121)
        at com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser.htmlElement(JavadocParser.java:886)
        at com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser.description(JavadocParser.java:13846)
        at com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser.javadocTag(JavadocParser.java:14510)
        at com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser.javadoc(JavadocParser.java:363)
        at com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser.parseJavadocAsParseTree(JavadocDetailNodeParser.java:177)
        at com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser.parseJavadocAsDetailNode(JavadocDetailNodeParser.java:118)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck.visitToken(AbstractJavadocCheck.java:268)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:370)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:507)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:312)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:189)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 4 more
Checkstyle ends with 1 errors.
```
---------------

The source file can be parsed fine with Javadoc, although the resulting HTML doesn't look the best.

**Comment by rnveach** [comment]
Error is `LexerNoViableAltException('>')`.

https://github.com/checkstyle/checkstyle/blob/3744f4c56845e82bd85f4b92f07b06d0de2ab1f2/src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java#L512
`ex.getCtx()` is `null`.

**Comment by rnveach** [comment]
Exception isn't being displayed anymore, but a parse error is given.
````
$ cat TestClass.java
// simplified from https://github.com/jclouds/legacy-jclouds/blob/1665a70471609aed0314dc60e27a80c7ffa65d45/providers/gogrid/src/main/java/org/jclouds/gogrid/services/GridServerClient.java
public class C {
    /**
     * @return map <X =>
     */
    public int m() { return 0; }
}

$ cat TestConfig.xml
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="SummaryJavadoc"/>
  </module>
</module>

$ java -jar checkstyle-8.8-all.jar -c TestConfig.xml TestClass.java
Starting audit...
line 2:23 token recognition error at: '>'
[ERROR] TestClass.java:4: Javadoc comment at column 22 has parse error. Details: no viable alternative at input '<X =' while parsing HTML_ELEMENT [SummaryJavadoc]
Audit done.
Checkstyle ends with 1 errors.
````

@romani Should this issue be closed or should something change?

**Comment by romani** [comment]
It is better to close the issue, as there is no exception that kill whole execution. Message is not very clear , but this is another issue (hard to make it better).
