### ISSUE TITLE
Possible 8.0 regression with Ant relative config file

### ISSUE THREAD

**Issue by don-vip** [checkstyle/checkstyle#4612]
We have this working setup for JOSM plugins Ant build files:

```
plugins/
       /00_core_tools/checkstyle/checkstyle-all.jar
       /00_core_tools/checkstyle/josm_checks.xml
       /build.xml
       /build-common.xml
       /jna/build.xml
       /jts/build.xml
       /log4j/build.xml
       /todo/build.xml
```

(In reality there are about 140 plugins, not just these four). We have two possible ways to call checkstyle: `ant checkstyle` at top level performs the analysis on all plugins, while `ant checkstyle` in a single plugin directory performs it for the given plugin only.

This works fine up to version 7.8.2, but is broken since 8.0 for the top-level target with following error:

```
C:\SVN\josm\plugins\build-common.xml:513: Unable to create Root Module: config {../00_core_tools/checkstyle/josm_checks.xml}, classpath {null}.
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.createRootModule(CheckstyleAntTask.java:419)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.realExecute(CheckstyleAntTask.java:309)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.execute(CheckstyleAntTask.java:292)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:309)
        at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:224)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:402)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: ../00_core_tools/checkstyle/josm_checks.xml
        at com.puppycrawl.tools.checkstyle.utils.CommonUtils.getUriByFilename(CommonUtils.java:394)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:179)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.createRootModule(CheckstyleAntTask.java:395)
        ... 49 more
```

The setup is as follows. The build-common.xml defines the checkstyle target:

```xml
<project name="plugin_common" basedir="." xmlns:if="ant:if">
    <property name="checkstyle.jar" location="../00_core_tools/checkstyle/checkstyle-all.jar"/>
    <target name="checkstyle">
        <taskdef resource="com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties" classpath="${checkstyle.jar}"/>
        <checkstyle config="../00_core_tools/checkstyle/josm_checks.xml">
            <fileset dir="${basedir}/src" includes="**/*.java" excludes="org/apache/**/*.java"/>
            <fileset dir="${basedir}/test" includes="**/*.java" erroronmissingdir="false"/>
            <formatter type="xml" toFile="checkstyle-josm-${ant.project.name}.xml"/>
        </checkstyle>
    </target>
</project>
```

Each plugin build.xml includes the build-common.xml:

```xml
<project name="jna" default="dist" basedir=".">
    <property name="plugin.class" value="org.openstreetmap.josm.plugins.jna.JNAPlugin"/>
    <property name="plugin.description" value="Provides Java Native Access (JNA) library."/>
    <!-- ** include targets that all plugins have in common ** -->
    <import file="../build-common.xml"/>
</project>
```

And finally the global build.xml iterates on all plugin build files:

```xml
<project name="josm-plugins" default="dist" basedir=".">
    <property name="ordered_plugins" value="jna/build.xml
                                            jts/build.xml
                                            log4j/build.xml"/>
    <macrodef name="iterate">
        <attribute name="target"/>
        <sequential>
            <subant target="@{target}" inheritall="true">
                <filelist dir="." files="${ordered_plugins}"/>
                <fileset  dir="." includes="*/build.xml" excludes="00_*/build.xml ${ordered_plugins}"/>
            </subant>
        </sequential>
    </macrodef>
    <target name="checkstyle">
        <iterate target="checkstyle"/>
    </target>
</project>
```

I'm not sure if this is a checkstyle regression or a breaking change to which we must adapt.

**Comment by romani** [comment]
related to fix that we did at #4449 and released in 8.0.

but code that we use try to load file from URL, filesystem, resource  before throw exception.

@don-vip , try to use absolute path first..... if is works, may be current directory is changed from our perspective.

**Comment by don-vip** [comment]
Yes, it's working with an absolute path.

**Comment by romani** [comment]
It should work with relative too, as just try to create file from string that you specify in config, but what is current directory is a good question.

**Comment by jawitthuhn** [comment]
I'm having the same issue. We have a similar setup, but how we are doing things is a bit different (in case this provides additional clues). Our setup is like this:

```
Project/
    ant/
        Build.xml
        CheckStyleAntScript.xml
        checkStyleConfig.xml
        {some other ant scripts that likely don't matter here}
```

Build.xml calls the checkStyleAntScript.xml script like this:
```xml
<ant antfile="CheckStyleAntScript.xml" target="checkStyleMain" inheritall="false" inheritrefs="false"/>
```

CheckStyleAnt script contains this in its header (which should move the basedir up to the project level instead of the ant folder):
```xml
<project name="Project_CheckStyle_Script" default="checkStyleMain" basedir="..\">
```

We then invoke it like this:

```xml
<checkstyle config="ant/checkStyleConfig.xml"
			failureProperty="checkstyle.failure"
			failOnViolation="false"
			classpathref ="classpath.checkstyle"
			maxErrors="0"
			maxWarnings="0">
  <formatter type="xml" tofile="${dir.tmpBuildDir}/${log.file}"/>
  <fileset dir="${dir.source}" includes="**/*.java"/>
</checkstyle>
```

We get a stack trace identical to the report that opened this thread.

If I change the `config` attribute to `checkStyleConfig.xml` instead of `ant/checkStyleConfig.xml`, then it works just fine. So ... something changed in where it is calculating relatives paths from. This isn't a dealbreaker for us - we can just go and update all of our scripts. But there is a definite change in behavior. It worked fine in 7.8.2, but the behavior changed with 8.0 (the checkstyle version was all that we had changed between a working build and a broken build).

**Comment by romani** [comment]
@jawitthuhn , thanks a lot for sharing a problem and fix.

> But there is a definite change in behavior. It worked fine in 7.8.2, but the behavior changed with 8.0 

yes it is planned change in behavior. Related to fix that we did at #4449 and released in 8.0.

> If I change the config attribute to checkStyleConfig.xml instead of ant/checkStyleConfig.xml, then it works just fine

@don-vip , looks like you also need to change path of config path related to location of `build.xml`.

I need to close this issue, as we will not restore old behavior, but users can share there their problems and solution to help others to upgrade.

**Comment by don-vip** [comment]
Sorry I didn't see the update. It doesn't work in my case. I need to be able to call "ant checkstyle" from both levels (top-level directory and plugin directory).
Currently with .. it works at plugin level but not at top level.
Removing the .. makes it work at top level, but breaks at plugin level, it does not solve the situation.

**Comment by don-vip** [comment]
OK thanks for the basedir hint, I found how to solve the problem in my situation.
Changed:
`<checkstyle config="../00_core_tools/checkstyle/josm_checks.xml"> `
to:
`<checkstyle config="${basedir}/../00_core_tools/checkstyle/josm_checks.xml"> `
and that's all!
