### ISSUE TITLE
idea: fixing HtmlTagCanBeJavadocTag cause ant build error

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#4805]
sub-task of #4681

when we change all occurances of `<code>...</code>` by `{@code ...}` in TokenTypes.java build fails with an exception:
```
[INFO] Executing tasks

main:

execute:
[propertyfile] Creating new property file: /home/valeria/IdeaProjects/checkstyle/target/classes/checkstylecompilation.properties
  [javadoc] Generating Javadoc
  [javadoc] Javadoc execution
  [javadoc] Loading source file /home/valeria/IdeaProjects/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java...
  [javadoc] Constructing Javadoc information...
  [javadoc] 1 error
  [javadoc] javadoc: error - In doclet class com.puppycrawl.tools.checkstyle.doclets.TokenTypesDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
  [javadoc] java.lang.IllegalArgumentException: Should be only one tag.
  [javadoc] 	at com.puppycrawl.tools.checkstyle.doclets.TokenTypesDoclet.start(TokenTypesDoclet.java:73)
  [javadoc] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  [javadoc] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  [javadoc] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [javadoc] 	at java.lang.reflect.Method.invoke(Method.java:498)
  [javadoc] 	at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
  [javadoc] 	at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
  [javadoc] 	at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
  [javadoc] 	at com.sun.tools.javadoc.Start.begin(Start.java:219)
  [javadoc] 	at com.sun.tools.javadoc.Start.begin(Start.java:205)
  [javadoc] 	at com.sun.tools.javadoc.Main.execute(Main.java:64)
  [javadoc] 	at com.sun.tools.javadoc.Main.main(Main.java:54)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.710 s
[INFO] Finished at: 2017-07-23T19:02:50+03:00
[INFO] Final Memory: 38M/439M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (ant-phase-compile) on project checkstyle: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/valeria/IdeaProjects/checkstyle/config/ant-phase-compile.xml:13: Javadoc returned 1
[ERROR] around Ant part ...<ant antfile="config/ant-phase-compile.xml"/>... @ 7:48 in /home/valeria/IdeaProjects/checkstyle/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1
```
System specifications:
```
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T21:37:52+03:00)
Maven home: /usr/local/apache-maven-3.2.1
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_131/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-514.21.1.el7.x86_64", arch: "amd64", family: "unix"
```
changes are provided in the [PR](https://github.com/checkstyle/checkstyle/pull/4807)

**Comment by romani** [comment]
@Nimfadora , docklet fix is merged, please update provide fix for javadoc's

**Comment by romani** [comment]
fix is merged
