### ISSUE TITLE
skipCurrentTokenConsuming makes Character Position in line incorrect by 1

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4824]
`JavadocLexer.g4` uses `seek` method from `ANTLRInputStream` in `skipCurrentTokenConsuming` at [JavadocLexer.g4#L35](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4#L35). As the [documentation says](http://www.antlr.org/api/Java/org/antlr/v4/runtime/ANTLRInputStream.html#seek(int)):

> consume() ahead until p==index; can't just set p=index as we must update line and charPositionInLine. If we seek backwards, just set [p](http://www.antlr.org/api/Java/org/antlr/v4/runtime/ANTLRInputStream.html#p)

And you can see here what documentation means by it as `seek` just sets `p` which can be seen here in [ANTLRInputStream.java#L192-#L202](https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/ANTLRInputStream.java#L192-#L202)

The following javadoc trees help exhibit this bug

$ cat test.javadoc
```
*@see A://www.something.com
```

$ java -jar checkstyle-8.1-SNAPSHOT-all-master.jar -j test.javadoc

```
JAVADOC -> JAVADOC [0:0]
|--LEADING_ASTERISK -> * [0:0]
|--JAVADOC_TAG -> JAVADOC_TAG [0:1]
|   |--SEE_LITERAL -> @see [0:1]
|   |--WS ->   [0:5]
|   |--REFERENCE -> REFERENCE **[0:6]**
|   |   `--CLASS -> A **[0:6]**
|   `--DESCRIPTION -> DESCRIPTION **[0:8]**
|       `--TEXT -> ://www.something.com **[0:8]**
`--EOF -> <EOF> [0:28]
```

$ cat test2.javadoc
```
*@see a://www.something.com
```

$ java -jar checkstyle-8.1-SNAPSHOT-all-master.jar -j test2.javadoc
```
JAVADOC -> JAVADOC [0:0]
|--LEADING_ASTERISK -> * [0:0]
|--JAVADOC_TAG -> JAVADOC_TAG [0:1]
|   |--SEE_LITERAL -> @see [0:1]
|   |--WS ->   [0:5]
|   `--DESCRIPTION -> DESCRIPTION **[0:7]**
|       `--TEXT -> a://www.something.com **[0:7]**
`--EOF -> <EOF> [0:28]
```

In `JavadocLexer`'s  `seeLink` mode when `CHAR` is encountered, a call to `skipCurrentTokenConsuming` is made at [JavadocLexer.g4#L138](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4#L138). This results in `charPositionInLine` to increase by 1 which is not corrected for either by method `seek` or by method `skipCurrentTokenConsuming`. 

This behaviour can be seen when `a` in `a://www.something.com` is treated as `CHAR` and in the resultant javadoc tree the Column Number for `DESCRIPTION` is `7` even though it is at the same position as `A`, which is recognized as `CLASS`, in `A://www.something.com`.

This behavior can also be observed in just tree 1 in which `DESCRIPTION` should start at `column 7` but starts at `column 8` rather.

Either we should specify this bug in doc or try to extend `ANTLRInputStream` and override the call to `seek` and correct it somehow.

**Comment by Vladlis** [comment]
ANTLRInputStream is deprecated - https://github.com/antlr/antlr4/blob/46b3aa98cc8d8b6908c2cabb64a9587b6b973e6c/runtime/Java/src/org/antlr/v4/runtime/ANTLRInputStream.java#L23
Does this problem repeat with `CharStreams` interface?

**Comment by ps-sp** [comment]
> Does this problem repeat with CharStreams interface?

`Seek` method is from `IntStream` interface and methods in `CharStreams` are designed to return implementation `CodePointCharStream`. The same problem exists in `seek` of `CodePointCharStream`.

**Comment by romani** [comment]
@ps-sp  , we need to report problem to ANTLR project, as any of our override could make another side effects.

**Comment by ps-sp** [comment]
@romani ANTLR already warns against this behaviour in their [doc](http://www.antlr.org/api/Java/org/antlr/v4/runtime/ANTLRInputStream.html#seek(int)). I don't think creating an issue there will be of much help. I haven't been able to find any alternative implementation of this concerned method, method `seek`, that we use in `skipCurrentTokenConsuming`. Also, I haven't been able to find any other ANTLR method that we can use in its place. You can also search through ANTLR and let me know if you find anything.

**Comment by romani** [comment]
<img width="998" height="634" alt="Image" src="https://github.com/user-attachments/assets/2b5a5de2-2075-49d1-b70d-86240bfce1ca" />

https://docs.oracle.com/en/java/javase/22/docs/specs/javadoc/doc-comment-spec.html#see

this is not correct javadoc content, we support only content that pass javadoc tool wihtout errors.

```
$ cat Test.java 
/**
 * @see A://www.something.com"
 */
public class OuterCompany {
}

$ javadoc Test.java
Loading source file Test.java...
Constructing Javadoc information...
Test.java:4: error: class OuterCompany is public, should be declared in a file named OuterCompany.java
public class OuterCompany {
       ^
1 error

$ java -jar checkstyle-13.7.0-all.jar -J Test.java 
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:2] Javadoc comment at column 11 has parse error. Details: mismatched input '/' expecting IDENTIFIER while parsing QUALIFIED_NAME
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseAndPrintJavadocTree(AstTreeStringPrinter.java:116)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:97)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:79)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:323)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:205)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:129)

```
