### ISSUE TITLE
RequireThisCheck: NPE on method from base class with validateOnlyOverlapping off

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4856]
Identified at https://github.com/checkstyle/checkstyle/pull/4853#issuecomment-318850557 and taken from https://raw.githubusercontent.com/sevntu-checkstyle/sevntu.checkstyle/7003e1e7ba87e50fd5654805ee6c4288544d8a97/sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputAvoidModifiersForTypesCheck.java ,

````
$ cat TestClass.java
package com.github.sevntu.checkstyle.checks.coding;

import java.util.logging.Logger;

public class InputAvoidModifiersForTypesCheck
{
    public class Check {
        private Logger log1 = Logger.getLogger(getClass().getName());
    }
}

$ cat TestConfig.xml
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="RequireThisCheck">
  <property name="validateOnlyOverlapping" value="false" />
</module>
    </module>
</module>

$ java -jar checkstyle-8.1-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:508)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:431)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:209)
Caused by: java.lang.NullPointerException
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.getMethodWithoutThis(RequireThisCheck.java:801)
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.processIdent(RequireThisCheck.java:262)
    at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.visitToken(RequireThisCheck.java:231)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:419)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:556)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:359)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:205)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
    ... 4 more
Checkstyle ends with 1 errors.
````

**Comment by rnveach** [comment]
I trimmed the test case down to the smallest denominator.

**Comment by romani** [comment]
fix is merged
