### ISSUE TITLE
Remove usage of javax.xml.bind.DatatypeConverter (removed in Java 9)

### ISSUE THREAD

**Issue by osiegmar** [checkstyle/checkstyle#5027]
Since #3093 Checkstyle uses javax.xml.bind.DatatypeConverter to create a hex string of an SHA1 hash.

JDK 9 marks the package (module) javax.xml.bind as deprecated for removal - [javadoc](http://download.java.net/java/jdk9/docs/api/java.xml.bind-summary.html). Whole list of deprecations - [here](http://download.java.net/java/jdk9/docs/api/deprecated-list.html) .

More dramatically, the current use in Checkstyle results in a NoClassDefFoundError/ClassNotFoundException if java weren't started with the --add-modules javax.xml.bind parameter.

```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at com.puppycrawl.tools.checkstyle.PropertyCacheFile.getHashCodeBasedOnObjectContent(PropertyCacheFile.java:233)
        at com.puppycrawl.tools.checkstyle.PropertyCacheFile.load(PropertyCacheFile.java:118)
        at com.puppycrawl.tools.checkstyle.Checker.setCacheFile(Checker.java:151)
```

**Comment by romani** [comment]
`-all` jar do work on jdk9:
```
$ JAVA_HOME="/opt/jvm/jdk-9_181/" PATH=$JAVA_HOME/bin:$PATH java --version ; java -jar checkstyle-8.1-all.jar -c config.xml MyClass.java 
java 9
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
Starting audit...
[ERROR] /var/tmp/MyClass.java:12: Array should contain trailing comma. [ArrayTrailingComma]
Audit done.
Checkstyle ends with 1 errors.
```

**Comment by romani** [comment]
@osiegmar ,

> the current use in Checkstyle results in a 

can you share how you use Checkstyle ? to know where such problem could happen. 
I can not reproduce problems with our CLI, see my post above.

**Comment by osiegmar** [comment]
It doesn't work here. I have created the exact same `MyClass.java` and `config.xml`. My `java --version` says:

```
java 9
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

Also note, that I'm on macOS.

`java -jar checkstyle-8.1-all.jar -c config.xml MyClass.java` gives:

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Cannot set property 'cacheFile' to 'cachefile' in module Checker
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:212)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:164)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:504)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:431)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:209)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2127)
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2108)
	at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:437)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:202)
	... 4 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.puppycrawl.tools.checkstyle.PropertyCacheFile.getHashCodeBasedOnObjectContent(PropertyCacheFile.java:233)
	at com.puppycrawl.tools.checkstyle.PropertyCacheFile.load(PropertyCacheFile.java:118)
	at com.puppycrawl.tools.checkstyle.Checker.setCacheFile(Checker.java:151)
	... 12 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 15 more
```

**Comment by osiegmar** [comment]
Some related material:

[How to resolve java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException in Java 9](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j)

[java.corba and EE modules not resolved by default](http://mail.openjdk.java.net/pipermail/jdk9-dev/2016-May/004309.html)

**Comment by romani** [comment]
fix is merged, I hope it will work for all.
