### ISSUE TITLE
@see tag with leading asterisk before arguments lead to parse failure

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#5035]
cat test.javadoc
```
* @see
* package.Class#member() 
* Description
```

java -jar master-8.2-all.jar -j test.javadoc 
```
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:1] Javadoc comment at column 2 has parse error. Details: mismatched input 'package' expecting <EOF> while parsing JAVADOC
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:83)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseFile(DetailNodeTreeStringPrinter.java:173)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.printFileAst(DetailNodeTreeStringPrinter.java:59)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:406)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:210)
```

cat test.javadoc
```
* @see
* "string"
```

java -jar master-8.2-all.jar -j test.javadoc 
```
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:1] Javadoc comment at column 2 has parse error. Details: mismatched input '"string"' expecting <EOF> while parsing JAVADOC
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:83)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseFile(DetailNodeTreeStringPrinter.java:173)
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.printFileAst(DetailNodeTreeStringPrinter.java:59)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:406)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:210)
```

**Comment by romani** [comment]
fix is merged.
