### ISSUE TITLE
Intellij Checkstyle gives error NoClassDefFoundError

### ISSUE THREAD

**Issue by sigma85** [checkstyle/checkstyle#5067]
I have Intellij 2017.2.3 and Checkstyle-IDEA 5.10.0 running on my Ubuntu 17 desktop. When i try to add a checkstyle for my Java project (at Settings->Other settings->Checkstyle) I get this error message:

```
java.lang.NoClassDefFoundError: org/apache/commons/collections/FastHashMap
    at org.apache.commons.beanutils.PropertyUtilsBean.getPropertyDescriptor(PropertyUtilsBean.java:963)
    at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:391)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:217)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.contextualize(AutomaticBean.java:249)
    at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:455)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:186)
    at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:58)
    at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:126)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:56)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:47)
    at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:44)
```

**Comment by rnveach** [comment]
@sigma85 Why do you say this is a problem directly with Checkstyle and not Checkstyle-IDEA? We are not the same group.

Our CLI is working just fine, and `org/apache/commons/collections/FastHashMap` is imported in our maven pom via `commons-collections` via [common-beanutils](https://github.com/checkstyle/checkstyle/blob/589f08fe29385e47968381a6bda30e5b2bfee5aa/pom.xml#L260-L264).

**Comment by romani** [comment]
please report issue to https://github.com/jshiell/checkstyle-idea
