### ISSUE TITLE
Travis failing to execute some item on trusty instances

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5086]
https://travis-ci.org/checkstyle/checkstyle/jobs/272702074

randomly killed process during download for maven artifacts, no error printed:
```
Downloaded: https://repo.maven.apache.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar (562 KB at 412.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8.jar (4929 KB at 3613.1 KB/sec)
```

**Comment by romani** [comment]
from Travis support:
>It seems like there are two issues as play here. We see in our internal logs that the following error occurs: 'Killed process 49814 (java) total-vm:22729700kB, anon-rss:3608732kB, file-rss:0kB, shmem-rss:0kB'. The process you run consumes too much RAM. The reason why you do not see anything about this in the logs, is that 'set -e' is executed before. This makes it impossible to put the information in the build log, as the build process is killed immediately as well due to being configured to exit immediately on error. We do not support the use of 'set -e' directly in build script.
To address the memory issue, we would advise to consider to move to the 'sudo: required' builds. They have 7.5 GB of dedicated RAM, in stead of "on average" 4 GB on the container builds.

**Comment by romani** [comment]
After I set `set +e`:
```
Downloaded: https://repo.maven.apache.org/maven2/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8.jar (4929 KB at 1988.0 KB/sec)
/home/travis/.travis/job_stages: line 60:  4831 Killed                  mvn clean compile pmd:check findbugs:check spotbugs:check
eval of CMD is completed
```

Attempt to limit memory:
```
export MAVEN_OPTS='-Xmx3000m' && set +e && mvn clean compile pmd:check findbugs:check spotbugs:check
....
Downloaded: https://repo.maven.apache.org/maven2/com/google/collections/google-collections/1.0/google-collections-1.0.jar (625 KB at 273.3 KB/sec)
[INFO] Fork Value is true
     [java] Sep 07, 2017 1:28:22 PM java.util.prefs.FileSystemPreferences$1 run
     [java] INFO: Created user preferences directory.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:19 min
[INFO] Finished at: 2017-09-07T13:28:31+00:00
[INFO] Final Memory: 104M/4091M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.5:findbugs 
```

Limit to more lower level:
`$ export MAVEN_OPTS='-Xmx2000m' && set +e && mvn clean compile pmd:check findbugs:check spotbugs:check`
Passed

**Comment by romani** [comment]
issue is resolved.
https://travis-ci.org/checkstyle/checkstyle/jobs/272906844#L771

**Comment by romani** [comment]
Looks like the same issue with sonarqube validation
https://travis-ci.org/checkstyle/checkstyle/jobs/272906876

**Comment by romani** [comment]
looks like all unstable items are fixed

**Comment by romani** [comment]
https://travis-ci.org/checkstyle/checkstyle/jobs/273071481#L985

one more problem:
```
[INFO] Building sample 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-site-plugin:3.3:site (default-site) @ sample ---
[INFO] configuring report plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17
[INFO] configuring report plugin org.apache.maven.plugins:maven-jxr-plugin:2.5
[WARNING] Report plugin org.apache.maven.plugins:maven-project-info-reports-plugin has an empty version.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:2.9
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Skipped "Source Xref" report, file "xref/index.html" already exists for the English version.
[INFO] Generating "Checkstyle" report    --- maven-checkstyle-plugin:2.17
[INFO] Generating "Source Xref" report    --- maven-jxr-plugin:2.5
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
	at launch.executeCmd(launch.groovy:294)
	at launch.executeCmd(launch.groovy:288)
	at launch$executeCmd$10.callCurrent(Unknown Source)
	at launch.runMavenExecution(launch.groovy:219)
	at launch$_generateCheckstyleReport_closure2.doCall(launch.groovy:85)
	at launch.generateCheckstyleReport(launch.groovy:64)
	at launch$generateCheckstyleReport$1.callCurrent(Unknown Source)
	at launch.run(launch.groovy:10)
```

**Comment by romani** [comment]
contribution issue is fixed.
travis is passed
