### ISSUE TITLE
unstable SuppressionFilterTest.isConnectionAvailableAndStable on Travis and Appveyor

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5158]
https://travis-ci.org/checkstyle/checkstyle/jobs/280868014#L1093
https://ci.appveyor.com/project/Checkstyle/checkstyle/build/9933/job/fay625bycasg6w2t#L638

from travis:
```
[ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 260.417 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.filters.SuppressionFilterTest
[ERROR] testRemoteFileExternalResourceContentDoesNotChange(com.puppycrawl.tools.checkstyle.filters.SuppressionFilterTest)  Time elapsed: 131.034 s  <<< ERROR!
java.net.ConnectException: Connection timed out (Connection timed out)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionFilterTest.isConnectionAvailableAndStable(SuppressionFilterTest.java:244)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionFilterTest.testRemoteFileExternalResourceContentDoesNotChange(SuppressionFilterTest.java:186)
```

**Comment by rnveach** [comment]
I haven't seen this issue in a while and it is not clarified how this should be fixed.
@romani ping

**Comment by romani** [comment]
I do not remember details, it will come back :)
