### ISSUE TITLE
Checkstyle produces invalid XML file 

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5162]
Identified at https://github.com/checkstyle/checkstyle/pull/5063#issuecomment-330052949 ,

patch-diff-report-tool produced the following exception when running regression with `MultipleStringLiteralsCheck`.
````
Starting diff report generation ...
patch-diff-report-tool execution started.
XML parsing is started.
Exception in thread "main" javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1722,79]
Message: Character reference "&#
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
	at com.github.checkstyle.parser.CheckstyleReportsParser.parseXmlPortion(CheckstyleReportsParser.java:160)
	at com.github.checkstyle.parser.CheckstyleReportsParser.parse(CheckstyleReportsParser.java:132)
	at com.github.checkstyle.Main.main(Main.java:163)
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
	at diff.executeCmd(diff.groovy:344)
	at diff.executeCmd(diff.groovy:338)
	at diff$_generateDiffReport_closure3.doCall(diff.groovy:237)
	at diff.generateDiffReport(diff.groovy:220)
	at diff$generateDiffReport$4.callCurrent(Unknown Source)
	at diff.run(diff.groovy:32)
````

> [at com.github.checkstyle.parser.CheckstyleReportsParser.parse(CheckstyleReportsParser.java:132)](https://github.com/checkstyle/contribution/blob/288b4da7f16dc25c4d7be3a889142805cf169ae8/patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/CheckstyleReportsParser.java#L132)

Is when reading the master/base report.
This is the XML file: https://nimfadora.github.io/diff5008/checkstyle-result-master.txt

The specific problem line in the XML is:
> `<error line="64" column="14" severity="warning" message="The String &quot;&#0;&quot; appears 3 times in the file." source="com.puppycrawl.tools.checkstyle.checks.coding.MultipleStringLiteralsCheck"/>`

The problem is in XMLLogger and showcased in our UTs at https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java#L65 .
> `  {"&#0;", "&#0;"}, //reference`

We deal with pure text in our messages, not references.
`&#0;` should not stay as it is, but be converted to `&amp;#0;` This is why the XML file isn't valid.

**Comment by rnveach** [comment]
Fix was merged and marked as a bug
