### ISSUE TITLE
RequireThisCheck is not thread safe

### ISSUE THREAD

**Issue by hhuijser** [checkstyle/checkstyle#5178]
Possible NPE when running RequireThisCheck on multiple threads.

**Comment by rnveach** [comment]
"Possible"?
Going by our current PR, https://github.com/checkstyle/checkstyle/pull/4892/files#diff-110729384f4c9d098bd29eafab295062R94 , RequireThisCheck isn't global and should be file stateful.

Also, how are you running the check in MT mode?

**Comment by hhuijser** [comment]
@rnveach, sorry for my poor wording.
I mean that because of timing issues, you might or might not run into the NPE (for my, it would happen about 25% of the time).
I'd get a NPE [here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java#L901) if it is called right after another thread had set `current` to null [here] (https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java#L209)

I will post a stacktrace if I run into it again.

For your second question, let me explain how I am trying to use Checkstyle and you can let me know if I am trying something I shouldn't be doing, and if so, if there is another way of doing things.

I have 20,000+ files and instead of calling `checker.process(files)` on the entire set, I'd like to split up my files in smaller batches (say 1,000 files each) and run 'checker.process(batch)` on those smaller batches on multiple threads.

**Comment by hhuijser** [comment]
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.getClassFrameWhereViolationIsFound(RequireThisCheck.java:450)
	at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.getFieldWithoutThis(RequireThisCheck.java:318)
	at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.processIdent(RequireThisCheck.java:270)
	at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.visitToken(RequireThisCheck.java:231)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:425)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:581)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:365)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:205)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:82)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)

**Comment by rnveach** [comment]
if `Checker` is just the current normal Checker instead of some custom checker, like MultiThreadChecker which we are trying to introduce, then you are running MT mode in a way we don't support.

**Comment by hhuijser** [comment]
Understood.
I'll go ahead and close my tickets and pull requests.
