### ISSUE TITLE
RegexpOnFilenameCheck: NullPointerException when relative path is used to run checkstyle CLI 

### ISSUE THREAD

**Issue by kevin-wayne** [checkstyle/checkstyle#5278]
```
/var/tmp $ cat HelloWorld.java

public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}

/var/tmp $ cat config.xml

<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="RegexpOnFilename">
        <property name="fileNamePattern" value="."/>
        <property name="fileExtensions" value="java"/>
    </module>
</module>

/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.4-all.jar -c config.xml HelloWorld.java

Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing HelloWorld.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:297)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:215)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:523)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:437)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:210)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.regexp.RegexpOnFilenameCheck.getFolderPath(RegexpOnFilenameCheck.java:286)
	at com.puppycrawl.tools.checkstyle.checks.regexp.RegexpOnFilenameCheck.processFiltered(RegexpOnFilenameCheck.java:253)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:82)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:318)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:288)
	... 4 more
Checkstyle ends with 1 errors.


/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.4-all.jar -c config.xml /var/tmp/HelloWorld.java

Starting audit...
[ERROR] /var/tmp/HelloWorld.java:0: File match folder pattern '' and file pattern '.'. [RegexpOnFilename]
Audit done.
Checkstyle ends with 1 errors.
```

--------------

The CLI tool throws a NullPointerException when using RegexpOnFilename with a relative path (but works with an absolute path). Seems to be the same issue as #5127 (and perhaps the fix for #5127 already fixes this).

--------------

**Comment by rnveach** [comment]
It is a similar problem but the fix for the other issue won't fix this one as it is all related to how each Check is coded.

**Comment by romani** [comment]
fix is merged
