### ISSUE TITLE
wercker is failing with uncler message after release on non-rebased branches

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5452]
After release all PRs have to rebase to avoid problem like:
```
17 secondsNoExceptiontest - Apache Struts
Command cancelled due to error
export WERCKER_STEP_ROOT="/pipeline/script-b31bd3de-3e42-48ca-a0ac-f7980f70f445"
export WERCKER_STEP_ID="script-b31bd3de-3e42-48ca-a0ac-f7980f70f445"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="script"
export WERCKER_REPORT_NUMBERS_FILE="/report/script-b31bd3de-3e42-48ca-a0ac-f7980f70f445/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/script-b31bd3de-3e42-48ca-a0ac-f7980f70f445/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/script-b31bd3de-3e42-48ca-a0ac-f7980f70f445/artifacts"
source "/pipeline/script-b31bd3de-3e42-48ca-a0ac-f7980f70f445/run.sh" < /dev/null
Cloning into 'contribution'...
Testing Checkstyle started
Cloning git repository 'apache-struts' to repositories/apache-struts folder ...
Cloning into 'repositories/apache-struts'...
Cloning git repository 'apache-struts' - completed

apache-struts is synchronized
   [delete] Deleting directory /pipeline/source/contribution/checkstyle-tester/src/main/java
     [copy] Copying 3162 files to /pipeline/source/contribution/checkstyle-tester/src/main/java/apache-struts
Running 'mvn clean' on src/main/java ...
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sample 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sample ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.236 s
[INFO] Finished at: 2018-01-07T14:51:21+00:00
[INFO] Final Memory: 17M/966M
[INFO] ------------------------------------------------------------------------
Running Checkstyle on src/main/java ... with excludes **/apache-struts/**/resources/**/*
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sample 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-site-plugin:3.3:site (default-site) @ sample ---
[INFO] configuring report plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17
[INFO] Downloading: http://repository.apache.org/snapshots/com/puppycrawl/tools/checkstyle/8.8-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/puppycrawl/tools/checkstyle/8.8-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/puppycrawl/tools/checkstyle/8.8-SNAPSHOT/checkstyle-8.8-SNAPSHOT.pom
[INFO] Downloading: http://repository.apache.org/snapshots/com/puppycrawl/tools/checkstyle/8.8-SNAPSHOT/checkstyle-8.8-SNAPSHOT.pom
[WARNING] The POM for com.puppycrawl.tools:checkstyle:jar:8.8-SNAPSHOT is missing, no dependency information available
[INFO] Downloading: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/github/sevntu-checkstyle/sevntu-checkstyle-maven-plugin/1.26.0/sevntu-checkstyle-maven-plugin-1.26.0.pom
[INFO] Downloaded: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/github/sevntu-checkstyle/sevntu-checkstyle-maven-plugin/1.26.0/sevntu-checkstyle-maven-plugin-1.26.0.pom (4 KB at 38.4 KB/sec)
[INFO] Downloading: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/github/sevntu-checkstyle/sevntu-checks/1.26.0/sevntu-checks-1.26.0.pom
[INFO] Downloaded: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/github/sevntu-checkstyle/sevntu-checks/1.26.0/sevntu-checks-1.26.0.pom (15 KB at 179.9 KB/sec)
[INFO] Downloading: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/puppycrawl/tools/checkstyle/8.8-SNAPSHOT/checkstyle-8.8-SNAPSHOT.jar
[INFO] Downloading: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/github/sevntu-checkstyle/sevntu-checkstyle-maven-plugin/1.26.0/sevntu-checkstyle-maven-plugin-1.26.0.jar
[INFO] Downloading: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/github/sevntu-checkstyle/sevntu-checks/1.26.0/sevntu-checks-1.26.0.jar
[INFO] Downloaded: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/github/sevntu-checkstyle/sevntu-checks/1.26.0/sevntu-checks-1.26.0.jar (173 KB at 2188.0 KB/sec)
[INFO] Downloaded: http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2/com/github/sevntu-checkstyle/sevntu-checkstyle-maven-plugin/1.26.0/sevntu-checkstyle-maven-plugin-1.26.0.jar (3 KB at 23.8 KB/sec)
[INFO] Downloading: http://repository.apache.org/snapshots/com/puppycrawl/tools/checkstyle/8.8-SNAPSHOT/checkstyle-8.8-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.639 s
[INFO] Finished at: 2018-01-07T14:51:25+00:00
[INFO] Final Memory: 18M/748M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: failed to get report for org.apache.maven.plugins:maven-checkstyle-plugin: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could not be resolved: Could not find artifact com.puppycrawl.tools:checkstyle:jar:8.8-SNAPSHOT in sevntu-maven (http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: failed to get report for org.apache.maven.plugins:maven-checkstyle-plugin
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: failed to get report for org.apache.maven.plugins:maven-checkstyle-plugin
  at org.apache.maven.reporting.exec.DefaultMavenReportExecutor.buildMavenReports(DefaultMavenReportExecutor.java:159)
  at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.getReports(AbstractSiteRenderingMojo.java:235)
  at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:121)
  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
  ... 20 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could not be resolved: Could not find artifact com.puppycrawl.tools:checkstyle:jar:8.8-SNAPSHOT in sevntu-maven (http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2)
  at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:218)
  at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
  at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:400)
  at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:372)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.maven.reporting.exec.DefaultMavenPluginManagerHelper.setupPluginRealm(DefaultMavenPluginManagerHelper.java:186)
  at org.apache.maven.reporting.exec.DefaultMavenReportExecutor.buildReportPlugin(DefaultMavenReportExecutor.java:243)
  at org.apache.maven.reporting.exec.DefaultMavenReportExecutor.buildMavenReports(DefaultMavenReportExecutor.java:154)
  ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.puppycrawl.tools:checkstyle:jar:8.8-SNAPSHOT in sevntu-maven (http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2)
  at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
  at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
  at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
  at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:210)
  ... 34 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.puppycrawl.tools:checkstyle:jar:8.8-SNAPSHOT in sevntu-maven (http://sevntu-checkstyle.github.com/sevntu.checkstyle/maven2)
  at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
  at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
  at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
  at launch.executeCmd(launch.groovy:298)
  at launch.executeCmd(launch.groovy:292)
  at launch$executeCmd$8.callCurrent(Unknown Source)
  at launch.runMavenExecution(launch.groovy:219)
  at launch$_generateCheckstyleReport_closure2.doCall(launch.groovy:85)
  at launch.generateCheckstyleReport(launch.groovy:64)
  at launch$generateCheckstyleReport$1.callCurrent(Unknown Source)
  at launch.run(launch.groovy:10)
```

it is happening due to the fact that contrinution project was updated to new version of checkstyle (8.8-SNAPSHOT in this case) but cloning is still do for previous version (8.7-SNAPSHOT) as PR was created base on commit of 8.7-SNAPSHOT

To resolve this issue we should recheck in each wercker build execution that there is match
`mvn -e -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`
vs
`cd contribution/checkstyle-tester && mvn -e -q -Dexec.executable='echo' -Dexec.args='${checkstyle.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`

if any mismatch, print both values and fail a build to ask user to rebase on latest sources.

**Comment by Vladlis** [comment]
I suggest adding an option to provide checkstyle version in groovy script and set it to `cd contribution/checkstyle-tester && mvn -e -q -Dexec.executable='echo' -Dexec.args='${checkstyle.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`
this way we won't enforce users to rebase just to satisfy CI
so, jobs in Wercker would look like:
```
no-exception-struts)
  CS_POM_VERSION=$(mvn -e -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
  echo CS_version: ${CS_POM_VERSION}
  for i in 1 2 3 4 5; do git clone https://github.com/checkstyle/contribution && break || sleep 15; done
  cd contribution/checkstyle-tester
  sed -i'' 's/^guava/#guava/' projects-for-wercker.properties
  sed -i'' 's/#apache-struts/apache-struts/' projects-for-wercker.properties
  groovy ./launch.groovy --listOfProjects projects-for-wercker.properties --config checks-nonjavadoc-error.xml --csVersion ${CS_POM_VERSION}
  cd ../../
  rm -rf contribution
  ;;
```

**Comment by rnveach** [comment]
> this way we won't enforce users to rebase just to satisfy CI

IMO, we should force them. If they are using an old commit, then CI could be a false positive that it is all ok to merge. There is no way to tell if their changes once merged with the lastest master will still pass successfully. Git only tells us of close line conflicts for merging, there could still be logic conflicts once the code is merged.
Whenever there is a new release, we always tell everyone to rebase and usually won't accept it otherwise. This is just another way to ensure this.

**Comment by Vladlis** [comment]
> If they are using an old commit, then CI could be a false positive 

I don't see how merging after release is different from regular merging in this pespective.
Shouldn't we use a smarter way to avoid logical conflicts? We could create a Travis job which would check whether a PR has all the latest changes in files it is changing. This is not 100

**Comment by rnveach** [comment]
> I don't see how merging after release is different from regular merging in this pespective.

@romani Always asks everyone to rebase after a release, so controlling it by CI isn't a bad thing. It just helps make sure there won't be any issues after merge. If there is an issue, it is up to maintainers to fix it as contributors can fall off the map after a PR is done or take too long and block others.

> a PR has all the latest changes in files it is changing.

If I had my way, I would ensure CI is only run when PR is always rebased on any master commit from last 1-2 days.

**Comment by romani** [comment]
> I suggest adding an option to provide checkstyle version in groovy script and set it to

It is good idea, even we demand it in a bit different way now.

> romani always asks everyone to rebase after a release, so controlling it by CI isn't a bad thing.

yes, I did this only because it will fail in weird way and not obvious for non-maintainers.
But reason was only to escape weird failure on PRs that are based on pre-release code.
So if we define Chekcstyle version by version that is PR - we will avoid this, and that is good step forward.

>  It just helps make sure there won't be any issues after merge. If there is an issue, it is up to maintainers to fix it as contributors can fall off the map after a PR is done or take too long and block others.

that is also TRUE, and big pain and distraction and maintainers and extra rebase demands for new PRs.
This is what we also tried to archive by forcing users to rebase. Problems are sitting close to each other but they are different and in fact should be fixed separately.
Problems with merge of non-rebased branch are happening even in the middle of release (true to say more often). Unfortunately there is no hint from github that fix is base on old code base. 
We did not make it in CI as failure only because it is ok in 90% cases to make fixes on non-HEAD master code.
Looks like it is time to do smth to address issue with long non-rebased code.

Unexpected build failure happens usually because of always changing CI/validations settings.
so as some Check/rule/inspection/plugin/CI-item/internal-UT is added most PR should be rebased.

use cases:
1)
all CIs are passed, but non-merged due to some reasons.
Unfortunetely no way to detect it as github does not show stale fixes, CI status is misleading.
afte merge: build failre is potential

2)
all CIs are passed except for build Item that check issue approved state.
We do discussion in issue, eventualy approve it, no changes are required.
Maintainers relaunch only one build item and it become green.
Unfortunetely no way to detect it as github does not show stale fixes, CI status is misleading.
afte merge: build failre is potential

3)
user did PR, changed were requied.
IF we have some CI check that master:HEAD and PR code are too far (~10(any number) commits in "main" area or any commit to "config|.ci") - failre a build.
user did not do rebase - CI demand rebase.

so we can cover only "3)" - that very good also.
For 1)-2) we should send request to github.

@rnveach , @Vladlis , please share on how you agree on this .

**Comment by rnveach** [comment]
Issue not finished until circle CI is updated

**Comment by romani** [comment]
issues is resolved, all updates were done during migration to circleci2.0
