### ISSUE TITLE
StringIndexOutOfBoundsException in CommonUtils.lengthExpandedTabs

### ISSUE THREAD

**Issue by cushon** [checkstyle/checkstyle#5491]
`$ javac T.java`:

```
T.java:2: error: unclosed string literal
  @A("
     ^
```

`$ cat T.java`:

```
class T {
  @A("
  ")
    int x;
}
```

`$ cat config.xml`:

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
"-//Puppy Crawl//DTD Check Configuration 1.3//EN"
"http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name = "Checker">
  <module name="TreeWalker">
    <module name="MemberName">
      <property name="format" value="^[a-z][a-z0-9][a-zA-Z0-9]*$"/>
      <message key="name.invalidPattern"
        value="Member name ''{0}'' must match pattern ''{1}''."/>
    </module>
  </module>
</module>
```

`$ java -c config.xml T.java`:

```
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing T.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:523)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:437)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:210)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 4
	at java.lang.String.charAt(String.java:646)
	at com.puppycrawl.tools.checkstyle.utils.CommonUtils.lengthExpandedTabs(CommonUtils.java:318)
	at com.puppycrawl.tools.checkstyle.api.AbstractCheck.log(AbstractCheck.java:290)
	at com.puppycrawl.tools.checkstyle.checks.naming.AbstractNameCheck.visitToken(AbstractNameCheck.java:76)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:423)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:579)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:363)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:203)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:83)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:319)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
	... 4 more
Checkstyle ends with 1 errors.
```
## Describe what you expect in detail.

I expected checkstyle to not crash.

**Comment by romani** [comment]
> T.java:2: error: unclosed string literal

http://checkstyle.sourceforge.net/writingchecks.html#Limitations
We do not support non-compiled files.
Behavior could be weird on them, as AST could be damaged.

Why you expect no problems from Checkstyle ?

**Comment by cushon** [comment]
Rejecting invalid input is fine, but it would be nice to report the parse error instead of crashing and printing a stack trace. The current behaviour is not a good user experience: it's not clear that there's a problem with the input, and not a problem with checkstyle.

**Comment by romani** [comment]
yes, agree, but there is nuance.

We have our own java grammar, it is the most complicated part in whole project. Extending it to detect all compilation problems is huge project, I would say even undoable by our small team. But even we can it, benefit is very small(almost zero). Taking into account all issues that we have and our other plans, this issue will never be done. Probably we will change our position ones we switch to grammar/AST tree from javac (one day it will be opened to community).
