### ISSUE TITLE
unexpected 'Unclosed HTML tag found' error

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5492]
javadoc:
`/**<tr> Zero </p> nesting despite `tr` is closed </tr>*/`

cause unexpected:
`[ERROR] Test.java:18: Unclosed HTML tag found: tr [JavadocParagraph]`

identified at 
https://github.com/checkstyle/checkstyle/commit/48f6beb453666f76416a43a97511ac94e2521361#diff-410707f87051b90b5e46d27453020212R671

**Comment by romani** [comment]
@ps-sp , please explain.

**Comment by rnveach** [comment]
````
$ cat TestClass.java
/**<tr> Zero </p> nesting despitetris closed </tr>*/
public class TestClass {
    void method() {
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="JavadocParagraph">
  <property name="violateExecutionOnNonTightHtml" value="true" />
</module>
    </module>
</module>

$ java -jar checkstyle-8.7-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:1: Unclosed HTML tag found: tr [JavadocParagraph]
Audit done.
Checkstyle ends with 1 errors.
````

When printing the javadoc tree:
````
|  |  |  `--JAVADOC -> JAVADOC [1:3]
|  |  |      |--HTML_ELEMENT -> HTML_ELEMENT [1:3]
|  |  |      |  `--TR_TAG_START -> TR_TAG_START [1:3]
|  |  |      |      |--START -> < [1:3]
|  |  |      |      |--TR_HTML_TAG_NAME -> tr [1:4]
|  |  |      |      `--END -> > [1:6]
|  |  |      |--TEXT ->  Zero  [1:7]
|  |  |      |--HTML_ELEMENT -> HTML_ELEMENT [1:13]
|  |  |      |  `--P_TAG_END -> P_TAG_END [1:13]
|  |  |      |      |--START -> < [1:13]
|  |  |      |      |--SLASH -> / [1:14]
|  |  |      |      |--P_HTML_TAG_NAME -> p [1:15]
|  |  |      |      `--END -> > [1:16]
|  |  |      |--TEXT ->  nesting despitetris closed  [1:17]
|  |  |      |--HTML_ELEMENT -> HTML_ELEMENT [1:45]
|  |  |      |  `--TR_TAG_END -> TR_TAG_END [1:45]
|  |  |      |      |--START -> < [1:45]
|  |  |      |      |--SLASH -> / [1:46]
|  |  |      |      |--TR_HTML_TAG_NAME -> tr [1:47]
|  |  |      |      `--END -> > [1:49]
````

**Comment by rnveach** [comment]
@romani @ps-sp This looks like an exact duplicate of https://github.com/checkstyle/checkstyle/issues/3810 which is marked as closed.

the `</p>` tag shouldn't be breaking apart the `TR` tag like this. You can a valid tree by removing the `</p>`.
````
    |  |  |  |      |--HTML_ELEMENT -> HTML_ELEMENT [2:3]
    |  |  |  |      |  `--TR -> TR [2:3]
    |  |  |  |      |      |--TR_TAG_START -> TR_TAG_START [2:3]
    |  |  |  |      |      |  |--START -> < [2:3]
    |  |  |  |      |      |  |--TR_HTML_TAG_NAME -> tr [2:4]
    |  |  |  |      |      |  `--END -> > [2:6]
    |  |  |  |      |      |--TEXT ->  Zero nesting despitetris closed  [2:7]
    |  |  |  |      |      `--TR_TAG_END -> TR_TAG_END [2:40]
    |  |  |  |      |          |--START -> < [2:40]
    |  |  |  |      |          |--SLASH -> / [2:41]
    |  |  |  |      |          |--TR_HTML_TAG_NAME -> tr [2:42]
    |  |  |  |      |          `--END -> > [2:44]
````

**Comment by romani** [comment]
> How come this wasn't fixed in the previous issue?

In original issue `<p>` is expected, here we have `</p>`. So HTML is not valid, It is better to let user know about it.
Current behavior look like valid.

@rnveach , what behavior do you expect ? 
If such error is ok, lets close the issue.

**Comment by rnveach** [comment]
> what behavior do you expect ?

If any error, I expect error on `</p>` tag not `</tr>`.
My main issue is with the tree. We are not creating `TR_TAG_START` and `TR_TAG_END` as children of `HTML_ELEMENT`. We split it into 2 `HTML_ELEMENT`s, which is the same thing we did in the other issue for the self-closing `<br />` tag.

Here is one example where we are creating the tree as I expected and it is very similar to this issue:
````
/** <var>abc</p>def</var> */
````
````
    |  |  |  |      |--HTML_ELEMENT -> HTML_ELEMENT [2:4]
    |  |  |  |      |  `--HTML_TAG -> HTML_TAG [2:4]
    |  |  |  |      |      |--HTML_ELEMENT_START -> HTML_ELEMENT_START [2:4]
    |  |  |  |      |      |  |--START -> < [2:4]
    |  |  |  |      |      |  |--HTML_TAG_NAME -> var [2:5]
    |  |  |  |      |      |  `--END -> > [2:8]
    |  |  |  |      |      |--TEXT -> abc [2:9]
    |  |  |  |      |      |--HTML_ELEMENT -> HTML_ELEMENT [2:12]
    |  |  |  |      |      |  `--P_TAG_END -> P_TAG_END [2:12]
    |  |  |  |      |      |      |--START -> < [2:12]
    |  |  |  |      |      |      |--SLASH -> / [2:13]
    |  |  |  |      |      |      |--P_HTML_TAG_NAME -> p [2:14]
    |  |  |  |      |      |      `--END -> > [2:15]
    |  |  |  |      |      |--TEXT -> def [2:16]
    |  |  |  |      |      `--HTML_ELEMENT_END -> HTML_ELEMENT_END [2:19]
    |  |  |  |      |          |--START -> < [2:19]
    |  |  |  |      |          |--SLASH -> / [2:20]
    |  |  |  |      |          |--HTML_TAG_NAME -> var [2:21]
    |  |  |  |      |          `--END -> > [2:24]
````

See how both `HTML_ELEMENT_START` and `HTML_ELEMENT_END` are both children of `HTML_TAG`. There is no split in the tree between the 2.
If anything, we should be consistent with our behavior.

**Comment by romani** [comment]
>` If any error, I expect error on </p> tag not </tr>`

It is not that simple to make reliable data position. We follow simple rule(stack) if tag open it should be closed before any other.

> My main issue is with the tree. 

ok, I updated main description to make it a bit more visible. I agree.

**Comment by romani** [comment]
I think this will be won't fix now, as we have limitation that  javadoc tool should pass without error to let us accept defects.

@gianmarcoschifone , this is good reminder for us that we do have this limitation to be written https://checkstyle.org/writingchecks.html#Limitations let's update limitation.

**Comment by gianmarcoschifone** [comment]
@romani behavior is different now, correct as jdk javadoc tool

```
gianmarco@Mac ~/Documents/Projects/testing-checkstyle % cat Test.java
/**<tr>text1</p>text2</tr>*/
public class Test {
    void method() {
    }
}

gianmarco@Mac ~/Documents/Projects/testing-checkstyle % java -jar checkstyle-13.9.0-SNAPSHOT-all.jar -J Test.java
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:1] Javadoc comment at column 19 has parse error. Details: no viable alternative at input '</' while parsing HTML_ELEMENT
        at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseAndPrintJavadocTree(AstTreeStringPrinter.java:116)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:97)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:79)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:323)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:205)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:129)

gianmarco@Mac ~/Documents/Projects/testing-checkstyle % javadoc -d docs -private Test.java
Loading source file Test.java...
Constructing Javadoc information...
Building index for all the packages and classes...
Standard Doclet version 21.0.8+9-LTS
Building tree for all the packages and classes...
Test.java:1: error: tag not allowed here: <tr>
/**<tr>text1</p>text2</tr>*/
   ^
Test.java:1: error: text not allowed in <tr> element
/**<tr>text1</p>text2</tr>*/
       ^
Test.java:1: error: unexpected end tag: </p>
/**<tr>text1</p>text2</tr>*/
            ^
Test.java:1: error: unexpected end tag: </tr>
/**<tr>text1</p>text2</tr>*/
                     ^
Generating docs/Test.html...
Test.java:2: warning: use of default constructor, which does not provide a comment
public class Test {
       ^
Test.java:3: warning: no comment
    void method() {
         ^
Generating docs/package-summary.html...
Copying file ./doc-files/image.png to directory docs/doc-files...
Generating docs/package-tree.html...
Generating docs/overview-tree.html...
Building index for all classes...
Generating docs/allclasses-index.html...
Generating docs/allpackages-index.html...
Generating docs/index-all.html...
Generating docs/search.html...
Generating docs/index.html...
Generating docs/help-doc.html...
4 errors
2 warnings
```

**Comment by romani** [comment]
@gianmarcoschifone , please send update to Limitation of Checkstyle to explicitly mention requirements for no error from jdk javadoc tool.

**Comment by romani** [comment]
Limitation are updated
