### ISSUE TITLE
wercker build problem with hibernate-search

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5499]
https://app.wercker.com/checkstyle/checkstyle/runs/build/5a6f736a34645f00019db5e9?step=5a6f738564672700010d2f2b

```
CS_version: 8.9-SNAPSHOT
Cloning into 'hibernate-search'...
[INFO] Error stacktraces are turned on.
[ERROR] Error executing Maven.
java.io.FileNotFoundException: The specified user settings file does not exist: /pipeline/source/hibernate-search/settings-example.xml
	at org.apache.maven.cli.configuration.SettingsXmlConfigurationProcessor.process(SettingsXmlConfigurationProcessor.java:91)
	at org.apache.maven.cli.MavenCli.configure(MavenCli.java:1017)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by romani** [comment]
file was removed recently at https://github.com/hibernate/hibernate-search/commit/a503c7630d7812083e0c84043994fcd867bcfd4d

**Comment by romani** [comment]
fix is merged.
