### ISSUE TITLE
Xpath Mapper : UnsupportedOperationException when several queries are combined

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#5571]
@MEZk @rnveach 
Previous discussion [5508](https://github.com/checkstyle/checkstyle/pull/5509#issuecomment-369576950)

Here are the steps to reproduce
`/var/tmp $ cat InputTest.java`:

```
public class InputTest {
}
```

`/var/tmp $ cat checks.xml`:

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
	    <module name="OuterTypeNumber">
		<property name="max" value="0"/>
	    </module>

    	    <module name="SuppressionXpathFilter">
	    	<property name="file" value="suppressions_xpath.xml"/>
	    </module>
    </module>
</module>
```

`/var/tmp $ cat suppressions_xpath.xml`:

```
<?xml version="1.0"?>

<!DOCTYPE suppressions PUBLIC
    "-//Puppy Crawl//DTD Suppressions Xpath Experimental 1.2//EN"
    "http://checkstyle.sourceforge.net/dtds/suppressions_1_2_xpath_experimental.dtd">

<suppressions>
    <suppress-xpath checks="OuterTypeNumber"
                    query="/CLASS_DEF[@text='InputTest'] | /CLASS_DEF[@text='InputTest']/MODIFIERS | /CLASS_DEF[@text='InputTest']/MODIFIERS/LITERAL_PUBLIC"/>
</suppressions>
```

`/var/tmp $ java  -jar checkstyle-X.XX-all.jar -c checks.xml InputTest.java`:

```
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing InputTest.java
  at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:299)
  at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:217)
  at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:555)
  at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:466)
  at com.puppycrawl.tools.checkstyle.Main.main(Main.java:220)
Caused by: java.lang.UnsupportedOperationException: Operation is not supported
  at com.puppycrawl.tools.checkstyle.xpath.AbstractNode.throwUnsupportedOperationException(AbstractNode.java:384)
  at com.puppycrawl.tools.checkstyle.xpath.AbstractNode.getTreeInfo(AbstractNode.java:160)
  at net.sf.saxon.expr.sort.GlobalOrderComparer.compare(GlobalOrderComparer.java:38)
  at net.sf.saxon.expr.UnionEnumeration.next(UnionEnumeration.java:72)
  at net.sf.saxon.expr.UnionEnumeration.next(UnionEnumeration.java:20)
  at net.sf.saxon.expr.UnionEnumeration.next(UnionEnumeration.java:59)
  at net.sf.saxon.expr.UnionEnumeration.(UnionEnumeration.java:45)
  at net.sf.saxon.expr.VennExpression.iterate(VennExpression.java:668)
  at net.sf.saxon.sxpath.XPathExpression.evaluate(XPathExpression.java:190)
  at com.puppycrawl.tools.checkstyle.filters.XpathFilter.getItems(XpathFilter.java:191)
  at com.puppycrawl.tools.checkstyle.filters.XpathFilter.isXpathQueryMatching(XpathFilter.java:160)
  at com.puppycrawl.tools.checkstyle.filters.XpathFilter.accept(XpathFilter.java:123)
  at com.puppycrawl.tools.checkstyle.filters.SuppressionXpathFilter.accept(SuppressionXpathFilter.java:88)
  at com.puppycrawl.tools.checkstyle.TreeWalker.getFilteredMessages(TreeWalker.java:215)
  at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:194)
  at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:83)
  at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:320)
  at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:290)
  ... 4 more
Checkstyle ends with 1 errors.
```

After small investigation I got the following results

For the following simple XPATH queries, no exception occurred
```
/CLASS_DEF | /PACKAGE_DEF
/CLASS_DEF | /IMPORT
//CLASS_DEF | //METHOD_DEF
//CLASS_DEF | //IMPORT
/IMPORT | //METHOD_DEF
/IMPORT | /PACKAGE_DEF
//CLASS_DEF//METHOD_DEF | //METHOD_DEF
//CLASS_DEF//METHOD_DEF | /METHOD_DEF
```

These queries throw exceptions
```
/CLASS_DEF | /CLASS_DEF/OBJBLOCK
//CLASS_DEF | /CLASS_DEF/OBJBLOCK
//CLASS_DEF | //CLASS_DEF/OBJBLOCK
//CLASS_DEF | //CLASS_DEF//METHOD_DEF
/PACKAGE_DEF | /PACKAGE_DEF/ANNOTATIONS
```

**Comment by romani** [comment]
@timurt , what is root reason of problem ? What is missed ?

**Comment by timurt** [comment]
> @timurt , what is root reason of problem ? What is missed ?

Saxon has different implementations to evaluate different types of query. 
So `//CLASS_DEF | //METHOD_DEF` and `//CLASS_DEF | //CLASS_DEF//METHOD_DEF` are considered to be two different types of query and they are being evaluated differently. 
First type is the simple binary query, second one is more complex and uses `VennExpression` class.

Inside `VennExpression` implementation there is call to [GlobalOrderComparer.compare](https://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/expr/sort/GlobalOrderComparer.html#compare-net.sf.saxon.om.Item-net.sf.saxon.om.Item-) method

From documentation:

> A Comparer used for comparing nodes in document order. This comparer is used when there is no guarantee that the nodes being compared come from the same document

Here is implementation of the method
```
public int compare(Item a, /*@NotNull*/ Item b) {
        if (a == b) {
            return 0;
        }
        long d1 = ((NodeInfo) a).getTreeInfo().getDocumentNumber();
        long d2 = ((NodeInfo) b).getTreeInfo().getDocumentNumber();
        if (d1 == d2) {
            return ((NodeInfo) a).compareOrder((NodeInfo) b);
        }
        return Long.signum(d1 - d2);
    }
```
As you see Saxon assumes that it is possible nodes to be from different trees and to verify it Saxon retrieves `TreeInfo` object from nodes. Nodes from one tree should have same `TreeInfo`.
