### ISSUE TITLE
SuppressWithNearbyCommentFilter NPE

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5573]
````
$ cat TestClass.java
public class TestClass {
    void method() {
        // -@csl[FinalLocalVariable](5) my comment
        String s = "";
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="FinalLocalVariable" />

<module name="SuppressWithNearbyCommentFilter">
<property name="commentFormat" value="-@csl\[(\w{8,}((\||\(|\))\w+)*)\]\((\d+)\) .{10,}" />
<property name="checkFormat" value="$1" />
<property name="influenceFormat" value="$3" />
</module>
    </module>
</module>

$ java -jar checkstyle-8.8-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:299)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:217)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:523)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:438)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:211)
Caused by: java.lang.NullPointerException
    at java.util.regex.Matcher.appendReplacement(Matcher.java:804)
    at java.util.regex.Matcher.replaceAll(Matcher.java:955)
    at java.lang.String.replaceAll(String.java:2223)
    at com.puppycrawl.tools.checkstyle.utils.CommonUtils.fillTemplateWithStringsByRegexp(CommonUtils.java:539)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter$Tag.<init>(SuppressWithNearbyCommentFilter.java:328)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.addTag(SuppressWithNearbyCommentFilter.java:279)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagCommentLine(SuppressWithNearbyCommentFilter.java:269)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagSuppressions(SuppressWithNearbyCommentFilter.java:253)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagSuppressions(SuppressWithNearbyCommentFilter.java:235)
    at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.accept(SuppressWithNearbyCommentFilter.java:202)
    at com.puppycrawl.tools.checkstyle.TreeWalker.getFilteredMessages(TreeWalker.java:215)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:194)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:83)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:320)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:290)
    ... 4 more
Checkstyle ends with 1 errors.
````

I am expecting now exception.
I am trying to write a comment like `// -@cs[MoveVariableInside(If|Else)](6)` to be able to suppress multiple checks at a single location.
If the characters `(` or `)` can never be allowed, then we should display that as an error message instead of an NPE.

**Comment by DXTkastb** [comment]
I'm on it.

**Comment by DXTkastb** [comment]
@romani I need some help on this issue, checkstyle_checks.xml doesn't allow me to catch NPE.

**Catching exception code:**

```
catch (final NullPointerException ex){
      throw new IllegalArgumentException("Regex group is "+ex.getMessage(),ex);
}

```
**Test code the this issue:**

```
@Test
    public void organ() throws Exception {
        final DefaultConfiguration filterConfig =
                createModuleConfig(SuppressWithNearbyCommentFilter.class);
        filterConfig.addAttribute("commentFormat",
                "-@csl\\[(\\w{8,}((\\||\\(|\\))\\w+)*)\\]\\((\\d+)\\) .{10,}");
        filterConfig.addAttribute("influenceFormat", "$3");

        try {
            final String[] suppressedViolationMessages = CommonUtil.EMPTY_STRING_ARRAY;
            final String[] expectedViolationMessages = CommonUtil.EMPTY_STRING_ARRAY;
            verifySuppressed(filterConfig,
                    getPath("InputSuppressWithNearbyCommentFilterNull.java"),
                    expectedViolationMessages, suppressedViolationMessages);
            fail("Exception has occured");
        }
        catch (CheckstyleException ex) {
            final IllegalArgumentException cause = (IllegalArgumentException) ex.getCause();
            assertEquals("Regex group is null", cause.getMessage(),
                    "Invalid exception message");
        }

    }
```

The test is working fine but mvn verify clean throws checkstyle error [IllegalCatch].

**Comment by rnveach** [comment]
> checkstyle_checks.xml doesn't allow me to catch NPE.

Why do we need to catch the NPE and can't prevent it from happening in the first place?

**Comment by DXTkastb** [comment]
> Why do we need to catch the NPE and can't prevent it from happening in the first place?

Pattern: `-@csl\[(\w{8,}((\||\(|\))\w+)*)\]\((\d+)\) .{10,}`

![regex](https://user-images.githubusercontent.com/38028330/78644307-4b996c80-78d3-11ea-8639-3c1cf6e189f8.png)

With the regex expression provided group 2 and group 3 go null for String:
` -@csl[FinalLocalVariable](5) my comment`

Prevention might be possible by checking each group but eventually, the user will have to be acquainted with the error.

**Comment by rnveach** [comment]
Our utility should not throw any uncaught exceptions within our control, like NPE or out of bounds and such. To me these are seen as issues with bad code than a user configuration problem. If it is something we are stopping from happening, it should be thrown as a CheckstyleException or IllegalArgument or such.

I believe we should be checking for these `null`s and reporting back we are expecting them to be filled in. Only if we can't identify these `null`s beforehand should we consider catching them and replacing them with a different error message.

> throw new IllegalArgumentException("Regex group is "+ex.getMessage(),ex);
> final IllegalArgumentException cause = (IllegalArgumentException) ex.getCause();
assertEquals("Regex group is null", cause.getMessage(),
"Invalid exception message");

Lastly, your new throw, nor the old exception, is not telling me as the user where my issue is. This is the main thing that led me to reporting the issue instead of debugging it more myself. Exception message is too vague on where actual issue is. I have no clue where the problem is in configuration or how to fix it.

**Comment by DXTkastb** [comment]
Ok , I got your point and I will try to eradicate the null value situation. 

------------------------------------------------------------------------------------------------------------------------------------
> Lastly, your new throw, nor the old exception, is not telling me as the user where my issue is. This is the main thing that led me to reporting the issue instead of debugging it more myself. Exception message is too vague on where actual issue is. I have no clue where the problem is in configuration or how to fix it.

This was just a demo try, I will  enhance the code according to needs as far as possible.

**Comment by DXTkastb** [comment]
@rnveach The problem actually lies in CommonUtil.java :

```
 public static String fillTemplateWithStringsByRegexp(
        String template, String lineToPlaceInTemplate, Pattern regexp) {
        final Matcher matcher = regexp.matcher(lineToPlaceInTemplate);
        String result = template;
        if (matcher.find()) {
            for (int i = 0; i <= matcher.groupCount(); i++) {
                // $n expands comment match like in Pattern.subst().
                result = result.replaceAll("\\$" + i, matcher.group(i));   // PROBLEM
            }
        }
        return result;
    }
```
mather.group(i) goes null
I updated the code to :

```
public static String fillTemplateWithStringsByRegexp(
        String template, String lineToPlaceInTemplate, Pattern regexp) throws IllegalArgumentException{
        final Matcher matcher = regexp.matcher(lineToPlaceInTemplate);
        String result = template;
        if (matcher.find()) {
            for (int i = 0; i <= matcher.groupCount(); i++) {
                // $n expands comment match like in Pattern.subst().
                if (matcher.group(i) == null) {
                    i++;
                    throw new IllegalArgumentException("Regex$" + i);
                }
                else
                result = result.replaceAll("\\$" + i, matcher.group(i));
            }
        }
        return result;
    }
```

I added the respective tests required and they run fine.

But I receive this error on mvn clean verify:
The error was quite long, I have pasted the main part:

```
 [echo] Checkstyle started (checkstyle_checks.xml): 10/04/2020 04:06:44 PM
[checkstyle] Running Checkstyle  on 1140 files
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:47 min
[INFO] Finished at: 2020-04-10T16:06:50+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (ant-phase-verify) on project checkstyle: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/kaustubh/checkstyle/config/ant-phase-verify.xml:31: Unable to process files: [/home/kaustubh/checkstyle/src/it/java/com/google/checkstyle/test/base/AbstractGoogleModuleTestSupport.java, /home/kaustubh/checkstyle/src/it/java/com/google/checkstyle/test/base/AbstractIndentationTestSupport.java, /home/kaustubh/checkstyle/src/it/java/com/google/checkstyle/test/chapter2filebasic/rule21filename/OuterTypeFilenameTest.java, /home/kaustubh/checkstyle/src/it/java/com/google/checkstyle/test/chapter2filebasic/rule231filetab/FileTabCharacterTest.java, /home/kaustubh/checkstyle/src/it/java/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/IllegalTokenTextTest.java, /home/kaustubh/checkstyle/src/it/java/com/google/checkstyle/test/chapter2filebasic/rule233nonascii/AvoidEscapedUnicodeCharactersTest.java, /home/kaustubh/checkstyle/src/it/java/com/google/checkstyle/test/chapter3filestructure/rule32packagestate/LineLengthTest.java, /home/kaustubh/checkstyle/src/it/java/com/google/checkstyle/test/chapter3filestructure/rule331nowildcard/AvoidStarImportTest.java,
```
.........

```
/home/kaustubh/checkstyle/src/xdocs/releasenotes.xml, /home/kaustubh/checkstyle/src/xdocs/releasenotes_old.xml, /home/kaustubh/checkstyle/src/xdocs/report_issue.xml, /home/kaustubh/checkstyle/src/xdocs/running.xml, /home/kaustubh/checkstyle/src/xdocs/sponsoring.xml, /home/kaustubh/checkstyle/src/xdocs/style_configs.xml, /home/kaustubh/checkstyle/src/xdocs/sun_style.xml, /home/kaustubh/checkstyle/src/xdocs/writingchecks.xml, /home/kaustubh/checkstyle/src/xdocs/writingfilefilters.xml, /home/kaustubh/checkstyle/src/xdocs/writingfilters.xml, /home/kaustubh/checkstyle/src/xdocs/writingjavadocchecks.xml.vm, /home/kaustubh/checkstyle/src/xdocs/writinglisteners.xml.vm]
[ERROR] around Ant part ...<ant antfile="config/ant-phase-verify.xml"/>... @ 8:47 in /home/kaustubh/checkstyle/target/antrun/build-main.xml: Exception was thrown while processing /home/kaustubh/checkstyle/src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNPathComplexityTest.java: Regex3: Regex$3
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

I was not able to understand this error. Could you please give a try and explain to me the reason behind this?

**Comment by DXTkastb** [comment]
On the SuppressWithNearbyCommentFilter.java side, code added : 

         catch (final IllegalArgumentException ex){
             if(ex.getMessage().contains("using")) 
                 throw ex;
             else
                 throw new IllegalArgumentException("Regex"+filter.influenceFormat,ex); // catch for this issue
           }

filter.influenceFormat : is the regex group provided by user(ex; $3).

**Comment by rnveach** [comment]
The output provided from the maven command is not enough. Lines above what you pasted should be the violation being reported.

**Comment by DXTkastb** [comment]
> The output provided from the maven command is not enough. Lines above what you pasted should be the violation being reported.

I have pasted the whole error part, there are no violations regarding the checkstyle formatting.

`[ERROR] around Ant part ...<ant antfile="config/ant-phase-verify.xml"/>... @ 8:47 in /home/kaustubh/checkstyle/target/antrun/build-main.xml: Exception was thrown while processing /home/kaustubh/checkstyle/src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNPathComplexityTest.java: Regex3: Regex$3`

Please view this part of the error, it might be useful.

**Comment by rnveach** [comment]
@DXTkastb Please start a PR to help with problem to finalize code. I am just not seeing the context needed.

**Comment by romani** [comment]
![image](https://user-images.githubusercontent.com/812984/99160024-7af92e80-2697-11eb-9d00-7c0584758656.png)
![image](https://user-images.githubusercontent.com/812984/99160106-7a14cc80-2698-11eb-9ccd-7b157a75f87f.png)

attention to index of group, it should be 4.

```
/var/tmp$ cat Test.java 
public class TestClass {
    void method() {
        // -@csl[FinalLocalVariable](5) my comment
        String s = "";
    }
}

/var/tmp$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
      <module name="FinalLocalVariable" />

      <module name="SuppressWithNearbyCommentFilter">
        <property name="commentFormat" value="-@csl\[(\w{8,}((\||\(|\))\w+)*)\]\((\d+)\) .{10,}" />
        <property name="checkFormat" value="$1" />
        <property name="influenceFormat" value="$4" />
      </module>
    </module>
</module>

/var/tmp$ java -jar checkstyle-8.36.2-all.jar -c config.xml Test.java 
Starting audit...
Audit done.
```

problem is not in parentheses, problem is in reference of group that match to nothing.  

but I agree we can enhance our code to not throw exception and we should simply do not do match.

**Comment by Rahulkhinchi03** [comment]
@romani @rnveach Please close this issue if the fix is invalid as discussed here: https://github.com/checkstyle/checkstyle/issues/5573#issuecomment-727287740

**Comment by romani** [comment]
@arturict , can you help us with this issue ?
there is abandoned PR https://github.com/checkstyle/checkstyle/pull/20231 that might be useful, but might be misleading .

**Comment by arturict** [comment]
Yes, I'll take it. I'll start from current master and use #20231 only as context, especially for the full-input tests.

**Comment by romani** [comment]
@arturict , in most recent code,  error is like expected: 
```
$ java -jar checkstyle-13.9.0-SNAPSHOT-all.jar -c config.xml Test.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Test.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:313)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:227)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:429)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:347)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:205)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:129)
Caused by: java.lang.IllegalArgumentException: unable to parse influence from '-@csl[FinalLocalVariable](5) my comment' using $3
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter$Tag.parseInfluence(SuppressWithNearbyCommentFilter.java:391)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter$Tag.<init>(SuppressWithNearbyCommentFilter.java:360)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.addTag(SuppressWithNearbyCommentFilter.java:296)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagCommentLine(SuppressWithNearbyCommentFilter.java:285)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagSuppressions(SuppressWithNearbyCommentFilter.java:268)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.tagSuppressions(SuppressWithNearbyCommentFilter.java:249)
	at com.puppycrawl.tools.checkstyle.utils.WeakReferenceHolder.lazyUpdate(WeakReferenceHolder.java:69)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter.accept(SuppressWithNearbyCommentFilter.java:216)
	at com.puppycrawl.tools.checkstyle.TreeWalker.getFilteredViolations(TreeWalker.java:236)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:213)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:108)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:341)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:300)
	... 5 more
Caused by: java.lang.NumberFormatException: For input string: "$3"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:648)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWithNearbyCommentFilter$Tag.parseInfluence(SuppressWithNearbyCommentFilter.java:388)
	... 17 more
Checkstyle ends with 1 errors.

```

code that prints all in good way:
https://github.com/checkstyle/checkstyle/blob/aac71c9d1c7757df97ed492ec671d7dfafb9e22a/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java#L386-L392


I think we should simply close ticket, as it was fixed by some other update

**Comment by romani** [comment]
test extension is merged.
