### ISSUE TITLE
PMD: Cannot set non-existent property 'showClassesComplexity' on Rule CyclomaticComplexity

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5603]
I found this in build logs, should be resolved ...
```
[INFO] --- maven-pmd-plugin:3.9.0:pmd (pmd) @ checkstyle ---
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.1.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] The RuleSet rulesets/java/basic.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/braces.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/clone.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/codesize.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] Failure executing PMD: Cannot set non-existent property 'showClassesComplexity' on Rule CyclomaticComplexity
java.lang.IllegalArgumentException: Cannot set non-existent property 'showClassesComplexity' on Rule CyclomaticComplexity
	at net.sourceforge.pmd.rules.RuleFactory.setPropertyValues(RuleFactory.java:275)
	at net.sourceforge.pmd.rules.RuleFactory.decorateRule(RuleFactory.java:103)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleReferenceNode(RuleSetFactory.java:648)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:462)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:367)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:214)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:209)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetReferenceNode(RuleSetFactory.java:501)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:458)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:367)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:214)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:209)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:170)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:154)
	at net.sourceforge.pmd.RulesetsFactoryUtils.getRuleSets(RulesetsFactoryUtils.java:37)
	at net.sourceforge.pmd.processor.AbstractPMDProcessor.createRuleSets(AbstractPMDProcessor.java:71)
	at net.sourceforge.pmd.processor.AbstractPMDProcessor.processFiles(AbstractPMDProcessor.java:104)
	at net.sourceforge.pmd.PMD.processFiles(PMD.java:311)
	at org.apache.maven.plugins.pmd.PmdReport.processFilesWithPMD(PmdReport.java:503)
	at org.apache.maven.plugins.pmd.PmdReport.executePmd(PmdReport.java:432)
	at org.apache.maven.plugins.pmd.PmdReport.executePmdWithClassloader(PmdReport.java:331)
	at org.apache.maven.plugins.pmd.PmdReport.canGenerateReport(PmdReport.java:305)
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:120)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by romani** [comment]
also should be resolved:
```
$mvn pmd:pmd
...
[WARNING] Rule CyclomaticComplexity uses deprecated property 'reportLevel'. Future versions of PMD will remove support for this property. Please use 'methodReportLevel' and 'classReportLevel' instead!
```

**Comment by pbludov** [comment]
According to the docs: https://pmd.github.io/pmd-6.1.0/pmd_rules_java_design.html
the rule `CyclomaticComplexity` was moved to `design` ruleset.

**Comment by pbludov** [comment]
They changed everything: https://pmd.github.io/pmd-6.0.0/pmd_release_notes.html

There is a tool for updating the configuration in semi-automatic mode:
https://github.com/asarkar/pmd-migration-tool

**Comment by pbludov** [comment]
I must admit that PMD is completely broken.
After removing the property 'showClassesComplexity' the build fails with 892 violations.
For now, PMD noes nothing. To prove this, remove any suppression from the pmd.xml file. The build will be successful.

@romani please revert cba0f56054b402311cba2b2acb1e26e0c1506b13 asap.
Then the PMD config for version 6.x should be written from scratch.

**Comment by romani** [comment]
confirmed,
smth is wrong completely
:
```
$ git diff
diff --git a/config/pmd.xml b/config/pmd.xml
index 2e145e7..1e57866 100644
--- a/config/pmd.xml
+++ b/config/pmd.xml
@@ -17,22 +17,6 @@
     <exclude name="StdCyclomaticComplexity"/>
   </rule>
 
-  <rule ref="rulesets/java/codesize.xml/CyclomaticComplexity">
-    <properties>
-      <property name="showClassesComplexity" value="false"/>
-      <property name="reportLevel" value="11"/>
-      <!-- DeclarationOrder - 'visitToken' has just big SWITCH block which contains IF blocks.
-           If we split the block to several methods it will damage readability.
-           validateCli is not reasonable to split as encapsulation of logic will be damaged
-           getDetails - huge Switch, it has to be monolithic
-           JavadocMethodCheck, JavadocStyleCheck, JavadocUtils.getJavadocTags() - deprecated
-           FinalLocalVariableCheck.visitToken() - it is just big switch , not could be done
-           GenericWhitespaceCheck.processSingleGeneric() - it contains a lot of similar to each other and very simple condition
-           VariableDeclarationUsageDistanceCheck, CustomImportOrderCheck - it is not OK to have such a complicated logic need to be refactored.
-      -->
-      <property name="violationSuppressXPath" value="//DeclarationOrder[@Name='visitToken'] and //MethodDeclaration[@Name='validateCli' and ../../..[
-    </properties>
-  </rule>
   <rule ref="rulesets/java/codesize.xml/NPathComplexity">
     <properties>
       <!-- JavadocMethodCheck - deprecated
@@ -93,9 +77,11 @@
   <rule ref="rulesets/java/comments.xml/CommentSize">
     <properties>
       <!-- we use class comments as source for xdoc files, so content is big and that is by design -->
+      <!--
       <property name="violationSuppressXPath" value="//ClassOrInterfaceDeclaration | //PackageDeclaration | //ClassOrInterfaceDeclaration[@Image='Jav
       <property name="maxLines" value="8"/>
       <property name="maxLineLength" value="100"/>
+    -->
     </properties>
   </rule>
$ mvn pmd:pmd
[INFO] --- maven-pmd-plugin:3.9.0:pmd (default-cli) @ checkstyle ---
[WARNING] This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.1.0/pmd_userdocs_getting_started.html#incremental-analysis
[WARNING] The RuleSet rulesets/java/basic.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/braces.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/clone.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/codesize.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/comments.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/controversial.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/coupling.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/design.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/empty.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/finalizers.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/imports.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/javabeans.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/logging-jakarta-commons.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/logging-java.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/migrating.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/naming.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/optimizations.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/strings.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/typeresolution.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/unnecessary.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/unusedcode.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/basic.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/braces.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/clone.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/codesize.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/comments.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/controversial.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/coupling.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/design.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/empty.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/finalizers.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/imports.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/javabeans.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/logging-jakarta-commons.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/logging-java.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/migrating.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/naming.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/optimizations.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/strings.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/typeresolution.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/unnecessary.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/unusedcode.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/basic.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/braces.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/clone.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/codesize.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/comments.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/controversial.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/coupling.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/design.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/empty.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/finalizers.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/imports.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/javabeans.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/logging-jakarta-commons.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/logging-java.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/migrating.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/naming.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/optimizations.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/strings.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/typeresolution.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/unnecessary.xml has been deprecated and will be removed in PMD 7.0.0
[WARNING] The RuleSet rulesets/java/unusedcode.xml has been deprecated and will be removed in PMD 7.0.0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

reverted.

**Comment by pbludov** [comment]
PMD 6 has many new checks. Some of them are reasonable. The CS code should be updated to satisfy them.

**Comment by pbludov** [comment]
Part one is #5633

**Comment by romani** [comment]
initial fix is merged, but warnings are left on logs and need to be resolved.
Thanks a lot to @pbludov .

**Comment by pbludov** [comment]
PMD6 ruleset migration table
=======================

deprecated | new
------------ | -------------
android.xml | errorprone.xml
basic.xml        |   bestpractices.xml, codestyle.xml, design.xml, errorprone.xml, multithreading.xml, performance.xml
braces.xml      |    codestyle.xml
clone.xml        |   errorprone.xml
codesize.xml   |     design.xml
comments.xml  |      codestyle.xml, documentation.xml
controversial.xml |  bestpractices.xml, codestyle.xml, design.xml, errorprone.xml, multithreading.xml, performance.xml
coupling.xml    |    bestpractices.xml, design.xml
design.xml       |   bestpractices.xml, codestyle.xml, design.xml, documentation.xml, errorprone.xml, multithreading.xml, performance.xml
empty.xml        |   errorprone.xml
finalizers.xml   |   errorprone.xml
imports.xml     |    bestpractices.xml, codestyle.xml, errorprone.xml
j2ee.xml         |   codestyle.xml, errorprone.xml, multithreading.xml
javabeans.xml |      errorprone.xml
junit.xml        |   bestpractices.xml, errorprone.xml, design.xml
logging-jakarta-commons.xml | bestpractices.xml, errorprone.xml
logging-java.xml |   bestpractices.xml, errorprone.xml
metrics.xml      |   design.xml
migrating.xml    |   bestpractices.xml, errorprone.xml, performance.xml
naming.xml       |   codestyle.xml, errorprone.xml
optimizations.xml |  codestyle.xml, performance.xml
strictexception.xml | design.xml, errorprone.xml
strings.xml     |    bestpractices.xml, errorprone.xml, performance.xml
sunsecure.xml  |     bestpractices.xml
typeresolution.xml | bestpractices.xml, errorprone.xml, design.xml
unnecessary.xml   |  codestyle.xml, design.xml, errorprone.xml
unusedcode.xml    |  bestpractices.xml

**Comment by rnveach** [comment]
@pbludov How many parts are there to this issue so we know it is ready to be closed?

**Comment by romani** [comment]
issue to skip "[WARING] This analysis could be faster, please consider using Incremental Analysis ..."
is created https://issues.apache.org/jira/browse/MPMD-257

**Comment by pbludov** [comment]
> How many parts are left
`performance`,`documentation','multithreading'
Then the PMD should be upgraded to 6.2.0.

**Comment by pbludov** [comment]
All rulesets are categories now. The issue may be closed.
Note that PMD is a bit outdated. We use version 6.1.0 while 6.2.0 has been released a couple of weeks ago.
But the version 6.2.0 has some issues:
https://github.com/pmd/pmd/issues/1018
https://github.com/pmd/pmd/issues/1020
It is better to skip 6.2.0 and switch to 6.3.0 when it will be released.

**Comment by romani** [comment]
@pbludov ,
PMD 6.3.0 is released,  can we finish PMD upgrade ?

**Comment by pbludov** [comment]
> PMD 6.3.0 is released, can we finish PMD upgrade ?

All the important issues for us have been fixed in 6.3.0. I'll send a PR soon.
