### ISSUE TITLE
Jacoco: main class doesn't work after verify test with Eclipse

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5678]
Steps to repoduce:
1) clean
2) run `mvn verify test` to successful completion
3) run `com.puppycrawl.tools.checkstyle.Main` class

Results in:
````
Exception in thread "main" java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_c13123e/Offline
	at com.puppycrawl.tools.checkstyle.Main.$jacocoInit(Main.java)
	at com.puppycrawl.tools.checkstyle.Main.<clinit>(Main.java)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_c13123e.Offline
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
````

This never caused an issue before.

**Comment by romani** [comment]
> clean

?? 

> run com.puppycrawl.tools.checkstyle.Main class

from Eclipse ? what version of eclipse and jacoco ?

**Comment by rnveach** [comment]
> clean

Meant maven clean.

> from Eclipse ? what version of eclipse and jacoco ?

Jacoco is the version checkstyle uses in master.
Eclipse is Luna SR2.

**Comment by rnveach** [comment]
Linux maven does the same thing.
I can reproduce the issue with just `mvn clean test` without verify.

**Comment by pbludov** [comment]
I'm seeing the same bug in IDEA. Perhaps this is due to the update of the JaCoCo to version 0.8.1

**Comment by pbludov** [comment]
>I can reproduce the issue with just `mvn clean test`

This is by design. The goal [restore-instrumented-classes](http://www.eclemma.org/jacoco/trunk/doc/restore-instrumented-classes-mojo.html) is bound to the phase `prepare-package` which is right after the phase `test`.

**Comment by rnveach** [comment]
> which is right after the phase test.

As I stated, I can see jacoco in the class files **before** the test phase is complete. It doesn't need to wait till after.
Also `test` doesn't run jacoco's code coverage test so it shouldn't even be instrumenting in this scenario. This is probably directly related to https://github.com/checkstyle/checkstyle/issues/5640 where I wasn't running pitest but the file was still being created. An old version or something must have been putting the file in the main directory.

**Comment by rnveach** [comment]
> Perhaps this is due to the update of the JaCoCo to version 0.8.1

I rolled back to 7be8266142e1f719d82ed2b83a69f30cbed8cb33 and still see the issue.

**Comment by pbludov** [comment]
By the way, why we are using the offline instrumentation? JaCoCo docs [says](http://www.eclemma.org/jacoco/trunk/doc/instrument-mojo.html) that
> Warning: The preferred way for code coverage analysis with JaCoCo is on-the-fly instrumentation. Offline instrumentation has several drawbacks and should only be used if a specific scenario explicitly requires this mode.

We need to try the recommended way.

**Comment by rnveach** [comment]
> We need to try the recommended way.

If you know how, give it a try. I'm not seeing it yet,
Removing `default-instrument` and `default-restore-instrumented-classes` fixed the classes but jacoco didn't run during a full `verify test`.

**Comment by pbludov** [comment]
Replacing
```
          <execution>
            <id>default-instrument</id>
            <goals>
              <goal>instrument</goal>
            </goals>
            <phase>test-compile</phase>
          </execution>
          <execution>
            <id>default-restore-instrumented-classes</id>
            <goals>
              <goal>restore-instrumented-classes</goal>
            </goals>
          </execution>
```
with
```
          <execution>
            <id>default-prepare-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>default-prepare-agent-integration</id>
            <goals>
              <goal>prepare-agent-integration</goal>
            </goals>
          </execution>
```
results a failure with many violations:
```
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader: lines covered ratio is 0.85, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader: branches covered ratio is 0.68, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.FormatterType: lines covered ratio is 0.00, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.Formatter: lines covered ratio is 0.00, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.Formatter: branches covered ratio is 0.00, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask: lines covered ratio is 0.00, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask: branches covered ratio is 0.00, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.Property: lines covered ratio is 0.00, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.Listener: lines covered ratio is 0.00, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver: lines covered ratio is 0.95, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver: branches covered ratio is 0.78, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.utils.CommonUtils: lines covered ratio is 0.98, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.utils.FilterUtils: lines covered ratio is 0.87, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.PropertyCacheFile: lines covered ratio is 0.92, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.PropertyCacheFile: branches covered ratio is 0.87, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ConfigurationLoader.InternalLoader: lines covered ratio is 0.89, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ConfigurationLoader.InternalLoader: branches covered ratio is 0.91, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.PackageNamesLoader: lines covered ratio is 0.25, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.PackageNamesLoader: branches covered ratio is 0.08, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ConfigurationLoader: lines covered ratio is 0.78, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.ConfigurationLoader: branches covered ratio is 0.84, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.XmlLoader: lines covered ratio is 0.96, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.XmlLoader: branches covered ratio is 0.50, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.Main: lines covered ratio is 0.00, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.Main: branches covered ratio is 0.00, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder: lines covered ratio is 0.92, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder: branches covered ratio is 0.77, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.header.HeaderCheck: lines covered ratio is 0.60, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.header.HeaderCheck: branches covered ratio is 0.21, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck: lines covered ratio is 0.80, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck: branches covered ratio is 0.68, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.imports.ImportControlLoader: lines covered ratio is 0.91, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.imports.ImportControlLoader: branches covered ratio is 0.92, but expected minimum is 1.00
```

All of the failed test are using PowerMock. That is the answer why we are using the offline instrumentation.
From the [docs](https://github.com/powermock/powermock/wiki/Code-coverage-with-JaCoCo)
> We are going to replace Javassist with ByteBuddy (#727) and it should help to resolve this old issue. But right now there is NO WAY TO USE PowerMock with JaCoCo On-the-fly instrumentation.

**Comment by rnveach** [comment]
Since we can't disable offline mode, we should probably update contributing docs to notify them on this issue if they do full `verify`. They will need to split `verify` between jacoco and non-jacoco run and do a `clean` between the 2.

**Comment by romani** [comment]
@rnveach , a lot of time passed, is it still a problem ?

**Comment by rnveach** [comment]
@romani Yes. We are still forced to do split runs between jacoco and non-jacoco.

**Comment by romani** [comment]
one more year is passed :), powermock is limited in our code base .... 
@rnveach , is this still an issue ?

**Comment by rnveach** [comment]
Nothing has been done to mitigate it, so it is still an issue.

**Comment by pbludov** [comment]
> Nothing has been done to mitigate it, so it is still an issue.

https://github.com/powermock/powermock/issues/727 is still open. This means we still can not use on-the-fly instrumentation now.

**Comment by rnveach** [comment]
Just notifying that this is still an issue 4 years later. Powermock is still blocked.

If you run `verify` phase with Jacoco, you will have to do a clean after the run otherwise you will get this NoClassDefFoundError.

**Comment by rnveach** [comment]
Only updating title as this is a global issue.
