### ISSUE TITLE
Can't generate xpath suppression for comment

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5819]
````
$ cat TestClass.java
package mypack;

/**
 * Some javadoc
 */
public final class InputCheckstyleAntTaskError {}


$ java -jar checkstyle-8.10-all.jar -s 3:1 TestClass.java
````

AST:
````
PACKAGE_DEF -> package [1:0]
|--ANNOTATIONS -> ANNOTATIONS [1:8]
|--IDENT -> mypack [1:8]
`--SEMI -> ; [1:14]
CLASS_DEF -> CLASS_DEF [6:0]
|--MODIFIERS -> MODIFIERS [6:0]
|  |--BLOCK_COMMENT_BEGIN -> /* [3:0]
|  |  |--COMMENT_CONTENT -> *\n * Some javadoc\n  [3:2]
|  |  |  `--JAVADOC -> JAVADOC [3:3]
|  |  |      |--NEWLINE -> \n [3:3]
|  |  |      |--LEADING_ASTERISK ->  * [4:0]
|  |  |      |--TEXT ->  Some javadoc [4:2]
|  |  |      |--NEWLINE -> \n [4:15]
|  |  |      |--TEXT ->  [5:0]
|  |  |      `--EOF -> <EOF> [5:1]
|  |  `--BLOCK_COMMENT_END -> */ [5:1]
|  |--LITERAL_PUBLIC -> public [6:0]
|  `--FINAL -> final [6:7]
|--LITERAL_CLASS -> class [6:13]
|--IDENT -> InputCheckstyleAntTaskError [6:19]
`--OBJBLOCK -> OBJBLOCK [6:47]
    |--LCURLY -> { [6:47]
    `--RCURLY -> } [6:48]
````

We still need to be able to create xpaths for the start of the comment, right?
http://checkstyle.sourceforge.net/config_filters.html#SuppressionXpathFilter doesn't say anything about comments. Can't users create their own custom violation suppression comments near violation using xpath, similar to `SuppressionCommentFilter`?

**Comment by romani** [comment]
Please print AST for this file, it it better to minimize file to make AST small and easy to read.

**Comment by rnveach** [comment]
Done.

**Comment by rnveach** [comment]
This is actually a duplicate of https://github.com/checkstyle/checkstyle/issues/5821 .
````
CLASS_DEF -> CLASS_DEF [6:0]
|--MODIFIERS -> MODIFIERS [6:0]
|  |--BLOCK_COMMENT_BEGIN -> /* [3:0]
````
This shows CLASS_DEF is out of source order as line 6 is in tree before line 3.
Unlike https://github.com/checkstyle/checkstyle/issues/5821 , this issue shows the parent is further in the source then the children.

**Comment by HuGanghui** [comment]
@rnveach 

cat Test.java
```
package mypack;

/**
 * Some javadoc
 */
public final class InputCheckstyleAntTaskError {}
```
run same command:

```sh
 java $RUN_LOCALE -jar /Users/hgh/Desktop/checkstyle/target/checkstyle-8.34-SNAPSHOT-all.jar -s 3:1 Test.java

/CLASS_DEF[./IDENT[@text='InputCheckstyleAntTaskError']]/MODIFIERS/BLOCK_COMMENT_BEGIN

```

**Comment by rnveach** [comment]
Generation may have been fixed, but https://github.com/rnveach/checkstyle/tree/issue_5648 says it can't suppress what is generated.

Remove the following lines for the failure on `InputAstTreeStringPrinterFullOfSinglelineComments.java`:
https://github.com/rnveach/checkstyle/commit/5534ca8a67f57e6163c3da0ca48fe0f8381a0470#diff-e3e99432081bedc4f58e895dd739a06fR85-R87
https://github.com/rnveach/checkstyle/commit/5534ca8a67f57e6163c3da0ca48fe0f8381a0470#diff-e3e99432081bedc4f58e895dd739a06fR140-R147

Failure:
````
java.lang.AssertionError: one of the xpath suppressions must work for 'M:\checkstyleWorkspace\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\asttreestringprinter\InputAstTreeStringPrinterFullOfSinglelineComments.java' at line 1, column 0 for type SINGLE_LINE_COMMENT
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.checkNode(XpathSuppressionTest.java:184)
	at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.checkTree(XpathSuppressionTest.java:120)
````

**Comment by AkMo3** [comment]
This might be closed by #9832.

**Comment by rnveach** [comment]
Rebasing and re-running test at https://github.com/checkstyle/checkstyle/issues/5819#issuecomment-677909246 will confirm if it is fixed or not. I do not believe test is flawed, but that could also be looked into as well.

**Comment by AkMo3** [comment]
@rnveach I ran the test on https://github.com/AkMo3/checkstyle/tree/check_trailing_comment, but after running for nearly 90 min [A loot of files had been added in 3 years :) ], this test fails on file [InputLineLengthUnicodeChars.java](https://github.com/AkMo3/checkstyle/blob/check_trailing_comment/src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthUnicodeChars.java). 

<details>
<summary>
Exception Log
</summary>

```
java.nio.charset.MalformedInputException: Input length = 1
at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
at java.io.BufferedWriter.close(BufferedWriter.java:265)
at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.createSuppressionsXpathConfigFile(XpathSuppressionTest.java:214)
at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.checkNode(XpathSuppressionTest.java:177)
at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.checkTree(XpathSuppressionTest.java:120)
at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.checkFile(XpathSuppressionTest.java:113)
at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.checkDir(XpathSuppressionTest.java:71)
at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.checkDir(XpathSuppressionTest.java:74)
at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.checkDir(XpathSuppressionTest.java:74)
at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.checkDir(XpathSuppressionTest.java:74)
at com.puppycrawl.tools.checkstyle.internal.XpathSuppressionTest.testAllChecks(XpathSuppressionTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

Process finished with exit code -1
```
</details>

Test passes on file [InputAstTreeStringPrinterFullOfSinglelineComments.java](https://github.com/AkMo3/checkstyle/blob/check_trailing_comment/src/test/resources/com/puppycrawl/tools/checkstyle/asttreestringprinter/InputAstTreeStringPrinterFullOfSinglelineComments.java)

<details>
<summary>
Test log:
</summary>

```
File: H:\GitHub\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\asttreestringprinter\InputAstTreeStringPrinterAttributesAndMethodsJavadoc.java
Node: package[1x0]
Node: ANNOTATIONS[1x39]
Node: .[1x39]
Node: .[1x28]
Node: .[1x22]
Node: .[1x11]
Node: com[1x8]
Node: puppycrawl[1x12]
Node: tools[1x23]
Node: checkstyle[1x29]
Node: asttreestringprinter[1x40]
Node: ;[1x60]
Node: CLASS_DEF[6x0]
Node: MODIFIERS[6x0]
Node: class[6x0]
Node: InputAstTreeStringPrinterAttributesAndMethodsJavadoc[6x6]
Node: OBJBLOCK[6x59]
Node: {[6x59]
Node: VARIABLE_DEF[9x4]
Node: MODIFIERS[9x4]
Node: TYPE[9x4]
Node: int[9x4]
Node: attribute[9x8]
Node: ;[9x17]
Node: METHOD_DEF[14x4]
Node: MODIFIERS[14x4]
Node: public[14x4]
Node: TYPE[14x11]
Node: void[14x11]
Node: method[14x16]
Node: ([14x22]
Node: PARAMETERS[14x23]
Node: )[14x23]
Node: {[14x25]
Node: }[14x27]
Node: }[16x0]
**************
File: H:\GitHub\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\asttreestringprinter\InputAstTreeStringPrinterFullOfBlockCommentsCR.java
Node: package[1x0]
Node: ANNOTATIONS[1x43]
Node: .[1x43]
Node: .[1x32]
Node: .[1x26]
Node: .[1x15]
Node: com[1x12]
Node: puppycrawl[1x16]
Node: tools[1x27]
Node: checkstyle[1x33]
Node: asttreestringprinter[1x44]
Node: ;[1x64]
Node: CLASS_DEF[3x0]
Node: MODIFIERS[3x0]
Node: public[3x0]
Node: class[3x12]
Node: InputAstTreeStringPrinterFullOfBlockCommentsCR[3x23]
Node: OBJBLOCK[3x75]
Node: {[3x75]
Node: }[5x2]
**************
File: H:\GitHub\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\asttreestringprinter\InputAstTreeStringPrinterJavaAndJavadoc.java
Node: package[1x0]
Node: ANNOTATIONS[1x39]
Node: .[1x39]
Node: .[1x28]
Node: .[1x22]
Node: .[1x11]
Node: com[1x8]
Node: puppycrawl[1x12]
Node: tools[1x23]
Node: checkstyle[1x29]
Node: asttreestringprinter[1x40]
Node: ;[1x60]
Node: CLASS_DEF[6x0]
Node: MODIFIERS[6x0]
Node: public[6x0]
Node: class[6x7]
Node: InputAstTreeStringPrinterJavaAndJavadoc[6x13]
Node: OBJBLOCK[6x53]
Node: {[6x53]
Node: }[8x0]
**************
File: H:\GitHub\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\asttreestringprinter\InputAstTreeStringPrinterJavadoc.java
Node: package[1x0]
Node: ANNOTATIONS[1x39]
Node: .[1x39]
Node: .[1x28]
Node: .[1x22]
Node: .[1x11]
Node: com[1x8]
Node: puppycrawl[1x12]
Node: tools[1x23]
Node: checkstyle[1x29]
Node: asttreestringprinter[1x40]
Node: ;[1x60]
Node: CLASS_DEF[4x0]
Node: MODIFIERS[4x0]
Node: class[4x0]
Node: InputAstTreeStringPrinterJavadoc[4x6]
Node: OBJBLOCK[4x39]
Node: {[4x39]
Node: METHOD_DEF[6x4]
Node: MODIFIERS[6x4]
Node: TYPE[6x4]
Node: void[6x4]
Node: m[6x9]
Node: ([6x10]
Node: PARAMETERS[6x11]
Node: )[6x11]
Node: {[6x12]
Node: }[6x13]
Node: }[7x0]
**************
File: H:\GitHub\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\asttreestringprinter\InputAstTreeStringPrinterPrintBranch.java
Node: package[1x0]
Node: ANNOTATIONS[1x39]
Node: .[1x39]
Node: .[1x28]
Node: .[1x22]
Node: .[1x11]
Node: com[1x8]
Node: puppycrawl[1x12]
Node: tools[1x23]
Node: checkstyle[1x29]
Node: asttreestringprinter[1x40]
Node: ;[1x60]
Node: CLASS_DEF[3x0]
Node: MODIFIERS[3x0]
Node: public[3x0]
Node: class[3x7]
Node: InputAstTreeStringPrinterPrintBranch[3x13]
Node: OBJBLOCK[3x50]
Node: {[3x50]
Node: VARIABLE_DEF[4x4]
Node: MODIFIERS[4x4]
Node: TYPE[4x4]
Node: int[4x4]
Node: variable[4x8]
Node: =[4x17]
Node: EXPR[4x19]
Node: 10[4x19]
Node: ;[4x21]
Node: }[5x0]

Process finished with exit code 0
```
</details>

The test also passes all `trailingcomment` test files

<details>
<summary> Test log: </summary>

```
File: H:\GitHub\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\trailingcomment\InputTrailingComment.java
Node: package[1x0]
Node: ANNOTATIONS[1x46]
Node: .[1x46]
Node: .[1x39]
Node: .[1x28]
Node: .[1x22]
Node: .[1x11]
Node: com[1x8]
Node: puppycrawl[1x12]
Node: tools[1x23]
Node: checkstyle[1x29]
Node: checks[1x40]
Node: trailingcomment[1x47]
Node: ;[1x62]
Node: CLASS_DEF[3x0]
Node: MODIFIERS[3x0]
Node: public[3x0]
Node: class[3x7]
Node: InputTrailingComment[3x13]
Node: OBJBLOCK[3x34]
Node: {[3x34]
Node: VARIABLE_DEF[4x4]
Node: MODIFIERS[4x4]
Node: TYPE[4x4]
Node: int[4x4]
Node: i[4x8]
Node: ;[4x9]
Node: VARIABLE_DEF[7x4]
Node: MODIFIERS[7x4]
Node: TYPE[7x4]
Node: int[7x4]
Node: j[7x8]
Node: ;[7x9]
Node: METHOD_DEF[8x4]
Node: MODIFIERS[8x4]
Node: TYPE[8x4]
Node: void[8x4]
Node: method1[8x9]
Node: ([8x16]
Node: PARAMETERS[8x17]
Node: )[8x17]
Node: {[8x19]
Node: VARIABLE_DEF[10x8]
Node: MODIFIERS[10x8]
Node: TYPE[10x8]
Node: Runnable[10x8]
Node: r[10x17]
Node: =[10x19]
Node: EXPR[10x21]
Node: ([10x21]
Node: new[10x22]
Node: Runnable[10x26]
Node: ([10x34]
Node: ELIST[10x35]
Node: )[10x35]
Node: OBJBLOCK[10x37]
Node: {[10x37]
Node: METHOD_DEF[11x16]
Node: MODIFIERS[11x16]
Node: public[11x16]
Node: TYPE[11x23]
Node: void[11x23]
Node: run[11x28]
Node: ([11x31]
Node: PARAMETERS[11x32]
Node: )[11x32]
Node: {[11x34]
Node: }[12x16]
Node: }[13x12]
Node: )[13x13]
Node: ;[13x14]
Node: }[14x4]
Node: METHOD_DEF[21x18]
Node: MODIFIERS[21x18]
Node: TYPE[21x18]
Node: void[21x18]
Node: method2[21x23]
Node: ([21x30]
Node: PARAMETERS[21x31]
Node: PARAMETER_DEF[21x31]
Node: MODIFIERS[21x31]
Node: TYPE[21x31]
Node: long[21x31]
Node: ms[21x36]
Node: )[21x66]
Node: {[21x68]
Node: VARIABLE_DEF[22x33]
Node: MODIFIERS[22x33]
Node: TYPE[22x33]
Node: int[22x33]
Node: z[22x37]
Node: ;[22x38]
Node: VARIABLE_DEF[23x19]
Node: MODIFIERS[23x19]
Node: TYPE[23x19]
Node: int[23x19]
Node: y[23x23]
Node: ;[23x28]
Node: }[24x4]
Node: VARIABLE_DEF[29x4]
Node: MODIFIERS[29x4]
Node: final[29x4]
Node: static[29x10]
Node: public[29x17]
Node: TYPE[29x24]
Node: String[29x24]
Node: NAME[29x31]
Node: =[29x35]
Node: EXPR[29x36]
Node: "Some Name"[29x36]
Node: ;[29x47]
Node: VARIABLE_DEF[30x4]
Node: MODIFIERS[30x4]
Node: final[30x4]
Node: static[30x10]
Node: public[30x17]
Node: TYPE[30x24]
Node: String[30x24]
Node: NAME2[30x31]
Node: =[30x36]
Node: EXPR[30x37]
Node: "Some Name"[30x37]
Node: ;[30x48]
Node: VARIABLE_DEF[31x4]
Node: MODIFIERS[31x4]
Node: TYPE[31x4]
Node: String[31x4]
Node: NAME3[31x11]
Node: =[31x16]
Node: EXPR[31x17]
Node: "Some Name"[31x17]
Node: ;[31x28]
Node: METHOD_DEF[33x18]
Node: MODIFIERS[33x18]
Node: TYPE[33x18]
Node: void[33x18]
Node: method3[33x23]
Node: ([33x30]
Node: PARAMETERS[33x31]
Node: )[33x31]
Node: {[33x33]
Node: }[36x4]
Node: CLASS_DEF[38x4]
Node: MODIFIERS[38x4]
Node: private[38x4]
Node: static[38x12]
Node: class[38x19]
Node: TimerEntry[38x25]
Node: OBJBLOCK[38x36]
Node: {[38x36]
Node: VARIABLE_DEF[39x17]
Node: MODIFIERS[39x17]
Node: final[39x17]
Node: TYPE[39x23]
Node: String[39x23]
Node: operation[39x30]
Node: =[39x40]
Node: EXPR[39x42]
Node: null[39x42]
Node: ;[39x46]
Node: VARIABLE_DEF[40x17]
Node: MODIFIERS[40x17]
Node: final[40x17]
Node: TYPE[40x23]
Node: long[40x23]
Node: start[40x28]
Node: =[40x34]
Node: EXPR[40x36]
Node: 0L[40x36]
Node: ;[40x38]
Node: }[41x4]
Node: METHOD_DEF[46x18]
Node: MODIFIERS[46x18]
Node: TYPE[46x18]
Node: void[46x18]
Node: addError[46x23]
Node: ([46x31]
Node: PARAMETERS[46x32]
Node: )[46x32]
Node: {[46x34]
Node: }[47x4]
Node: }[48x0]

Process finished with exit code 0
```
</details>

So, I believe #9832 would resolve this issue

**Comment by rnveach** [comment]
@AkMo3 Yes it is a long running test and doesn't have the full list of suppressions, hence the failure. I started adding to it again in my version but it takes some time to find them all.

> est passes on file InputAstTreeStringPrinterFullOfSinglelineComments.java

https://github.com/AkMo3/checkstyle/commit/da27232396dbee786513d9d125d7f45b23169e4f#diff-f33d58f6f30f581e9d2ad517d3df2b8067424ce018093ed3de915305cf51ad7eR86
Did you remove the suppression for the file?

**Comment by AkMo3** [comment]
@rnveach Yes. I ran again now just for `asttreestringprinter` package after removing suppressions and here`s the log

<details>

<summary> Test log: </summary>

```

File: /home/akmo/GitHub/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/asttreestringprinter/InputAstTreeStringPrinterFullOfSinglelineComments.java
Node: package[2x0]
Node: ANNOTATIONS[10x0]
Node: .[10x0]
Node: .[8x0]
Node: .[6x0]
Node: .[4x0]
Node: com[3x0]
Node: puppycrawl[5x0]
Node: tools[7x0]
Node: checkstyle[9x0]
Node: asttreestringprinter[11x0]
Node: ;[14x0]
Node: CLASS_DEF[16x0]
Node: MODIFIERS[16x0]
Node: public[16x0]
Node: class[17x0]
Node: InputAstTreeStringPrinterFullOfSinglelineComments[18x0]
Node: OBJBLOCK[19x0]
Node: {[19x0]
Node: METHOD_DEF[20x0]
Node: MODIFIERS[20x0]
Node: public[20x0]
Node: static[21x0]
Node: TYPE[22x0]
Node: void[22x0]
Node: main[23x0]
Node: ([24x0]
Node: PARAMETERS[26x0]
Node: PARAMETER_DEF[26x0]
Node: MODIFIERS[26x0]
Node: TYPE[26x0]
Node: [[26x0]
Node: String[25x0]
Node: ][27x0]
Node: args[28x0]
Node: )[29x0]
Node: {[30x0]
Node: for[31x0]
Node: ([32x0]
Node: FOR_INIT[33x0]
Node: VARIABLE_DEF[33x0]
Node: MODIFIERS[33x0]
Node: TYPE[33x0]
Node: int[33x0]
Node: i[34x0]
Node: =[35x0]
Node: EXPR[36x0]
Node: 0[36x0]
Node: ;[37x0]
Node: FOR_CONDITION[39x0]
Node: EXPR[39x0]
Node: <=[39x0]
Node: i[38x0]
Node: 10[40x0]
Node: ;[41x0]
Node: FOR_ITERATOR[42x1]
Node: ELIST[42x1]
Node: EXPR[42x1]
Node: ++[42x1]
Node: i[42x0]
Node: )[43x0]
Node: {[44x0]
Node: VARIABLE_DEF[45x0]
Node: MODIFIERS[45x0]
Node: TYPE[45x0]
Node: String[45x0]
Node: line[46x0]
Node: =[47x0]
Node: EXPR[49x0]
Node: +[49x0]
Node: i[48x0]
Node: ""[50x0]
Node: ;[51x0]
Node: EXPR[57x0]
Node: ([57x0]
Node: .[55x0]
Node: .[53x0]
Node: String[52x0]
Node: CASE_INSENSITIVE_ORDER[54x0]
Node: equals[56x0]
Node: ELIST[58x0]
Node: EXPR[58x0]
Node: line[58x0]
Node: )[59x0]
Node: ;[60x0]
Node: }[61x0]
Node: }[62x0]
Node: }[63x0]
**************
File: /home/akmo/GitHub/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/asttreestringprinter/InputAstTreeStringPrinterJavaAndJavadoc.java
Node: package[1x0]
Node: ANNOTATIONS[1x39]
Node: .[1x39]
Node: .[1x28]
Node: .[1x22]
Node: .[1x11]
Node: com[1x8]
Node: puppycrawl[1x12]
Node: tools[1x23]
Node: checkstyle[1x29]
Node: asttreestringprinter[1x40]
Node: ;[1x60]
Node: CLASS_DEF[6x0]
Node: MODIFIERS[6x0]
Node: public[6x0]
Node: class[6x7]
Node: InputAstTreeStringPrinterJavaAndJavadoc[6x13]
Node: OBJBLOCK[6x53]
Node: {[6x53]
Node: }[8x0]
**************
File: /home/akmo/GitHub/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/asttreestringprinter/InputAstTreeStringPrinterFullOfBlockCommentsCR.java
Node: package[1x0]
Node: ANNOTATIONS[1x43]
Node: .[1x43]
Node: .[1x32]
Node: .[1x26]
Node: .[1x15]
Node: com[1x12]
Node: puppycrawl[1x16]
Node: tools[1x27]
Node: checkstyle[1x33]
Node: asttreestringprinter[1x44]
Node: ;[1x64]
Node: CLASS_DEF[3x0]
Node: MODIFIERS[3x0]
Node: public[3x0]
Node: class[3x12]
Node: InputAstTreeStringPrinterFullOfBlockCommentsCR[3x23]
Node: OBJBLOCK[3x75]
Node: {[3x75]
Node: }[5x2]
**************
File: /home/akmo/GitHub/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/asttreestringprinter/InputAstTreeStringPrinterAttributesAndMethodsJavadoc.java
Node: package[1x0]
Node: ANNOTATIONS[1x39]
Node: .[1x39]
Node: .[1x28]
Node: .[1x22]
Node: .[1x11]
Node: com[1x8]
Node: puppycrawl[1x12]
Node: tools[1x23]
Node: checkstyle[1x29]
Node: asttreestringprinter[1x40]
Node: ;[1x60]
Node: CLASS_DEF[6x0]
Node: MODIFIERS[6x0]
Node: class[6x0]
Node: InputAstTreeStringPrinterAttributesAndMethodsJavadoc[6x6]
Node: OBJBLOCK[6x59]
Node: {[6x59]
Node: VARIABLE_DEF[9x4]
Node: MODIFIERS[9x4]
Node: TYPE[9x4]
Node: int[9x4]
Node: attribute[9x8]
Node: ;[9x17]
Node: METHOD_DEF[14x4]
Node: MODIFIERS[14x4]
Node: public[14x4]
Node: TYPE[14x11]
Node: void[14x11]
Node: method[14x16]
Node: ([14x22]
Node: PARAMETERS[14x23]
Node: )[14x23]
Node: {[14x25]
Node: }[14x27]
Node: }[16x0]
**************
File: /home/akmo/GitHub/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/asttreestringprinter/InputAstTreeStringPrinterPrintBranch.java
Node: package[1x0]
Node: ANNOTATIONS[1x39]
Node: .[1x39]
Node: .[1x28]
Node: .[1x22]
Node: .[1x11]
Node: com[1x8]
Node: puppycrawl[1x12]
Node: tools[1x23]
Node: checkstyle[1x29]
Node: asttreestringprinter[1x40]
Node: ;[1x60]
Node: CLASS_DEF[3x0]
Node: MODIFIERS[3x0]
Node: public[3x0]
Node: class[3x7]
Node: InputAstTreeStringPrinterPrintBranch[3x13]
Node: OBJBLOCK[3x50]
Node: {[3x50]
Node: VARIABLE_DEF[4x4]
Node: MODIFIERS[4x4]
Node: TYPE[4x4]
Node: int[4x4]
Node: variable[4x8]
Node: =[4x17]
Node: EXPR[4x19]
Node: 10[4x19]
Node: ;[4x21]
Node: }[5x0]
**************
File: /home/akmo/GitHub/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/asttreestringprinter/InputAstTreeStringPrinterJavadoc.java
Node: package[1x0]
Node: ANNOTATIONS[1x39]
Node: .[1x39]
Node: .[1x28]
Node: .[1x22]
Node: .[1x11]
Node: com[1x8]
Node: puppycrawl[1x12]
Node: tools[1x23]
Node: checkstyle[1x29]
Node: asttreestringprinter[1x40]
Node: ;[1x60]
Node: CLASS_DEF[4x0]
Node: MODIFIERS[4x0]
Node: class[4x0]
Node: InputAstTreeStringPrinterJavadoc[4x6]
Node: OBJBLOCK[4x39]
Node: {[4x39]
Node: METHOD_DEF[6x4]
Node: MODIFIERS[6x4]
Node: TYPE[6x4]
Node: void[6x4]
Node: m[6x9]
Node: ([6x10]
Node: PARAMETERS[6x11]
Node: )[6x11]
Node: {[6x12]
Node: }[6x13]
Node: }[7x0]

Process finished with exit code 0
```
</details>

**Comment by romani** [comment]
Fixed at https://github.com/checkstyle/checkstyle/pull/9832
