### ISSUE TITLE
CLI XML output file: file stops dead when an execption occurs

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#5895]
Identified at https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/572 during regression on Linux OS,

````
Running PR only with PR branch 'master' and config '/var/www/html/reports/d3447adb120d811f68b4421585847fbd'
./sevntu_launch_diff.sh master -config /var/www/html/reports/d3447adb120d811f68b4421585847fbd -patchOnly
....
Running Checkstyle with config /var/www/html/reports/d3447adb120d811f68b4421585847fbd
java -Xmx3024m -jar /home/ricky/opensource/checkstyle/target/checkstyle-8.10.1-all.jar -c /var/www/html/reports/d3447adb120d811f68b4421585847fbd -f xml -o /home/ricky/regression_reports/savepull/openjdk10/results.xml /home/ricky/regression_repositories/openjdk10
/home/ricky/regression_repositories/openjdk10/test/javax/xml/bind/jxc/8073519/InputWithError.java:28:10: unexpected token: compile
/home/ricky/regression_repositories/openjdk10/test/tools/pack200/typeannos/TypeUseTarget.java:39:74: unexpected token: ...
/home/ricky/regression_repositories/openjdk10/test/tools/pack200/typeannos/TypeUseTarget.java:40:8: unexpected token: Object
/home/ricky/regression_repositories/openjdk10/test/tools/pack200/typeannos/TypeUseTarget.java:40:26: unexpected token: String
/home/ricky/regression_repositories/openjdk10/test/tools/pack200/typeannos/TypeUseTarget.java:40:36: unexpected token: [
Exception in thread "main" java.lang.Error: Error was thrown while processing /home/ricky/regression_repositories/openjdk10/src/jdk.httpserver/share/classes/sun/net/httpserver/SSLStreams.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:299)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:554)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:465)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:219)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.LinkedList.linkLast(LinkedList.java:142)
    at java.util.LinkedList.add(LinkedList.java:338)
    at com.github.sevntu.checkstyle.checks.coding.OverridableMethodInConstructorCheck.getBaseClasses(OverridableMethodInConstructorCheck.java:837)
    at com.github.sevntu.checkstyle.checks.coding.OverridableMethodInConstructorCheck.getMethodDef(OverridableMethodInConstructorCheck.java:502)
    at com.github.sevntu.checkstyle.checks.coding.OverridableMethodInConstructorCheck.getOverridables(OverridableMethodInConstructorCheck.java:353)
    at com.github.sevntu.checkstyle.checks.coding.OverridableMethodInConstructorCheck.logWarnings(OverridableMethodInConstructorCheck.java:318)
    at com.github.sevntu.checkstyle.checks.coding.OverridableMethodInConstructorCheck.visitToken(OverridableMethodInConstructorCheck.java:278)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:389)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:500)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:329)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:182)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
    ... 4 more
Running Checkstyle - finished
....
Starting all Reports
java -jar /home/ricky/opensource/contribution/patch-diff-report-tool/target/patch-diff-report-tool-0.1-SNAPSHOT-jar-with-dependencies.jar --patchReport /home/ricky/regression_reports/savepull/openjdk10/results.xml --output /home/ricky/regression_reports/diff/openjdk10 --patchConfig /var/www/html/reports/d3447adb120d811f68b4421585847fbd --refFiles /home/ricky/regression_repositories/openjdk10
patch-diff-report-tool execution started.
XML parsing is started.
Exception in thread "main" javax.xml.stream.XMLStreamException: ParseError at [row,col]:[131475,74]
Message: XML document structures must start and end within the same entity.
    at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
    at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
    at com.github.checkstyle.parser.CheckstyleReportsParser.parseXmlPortion(CheckstyleReportsParser.java:160)
    at com.github.checkstyle.parser.CheckstyleReportsParser.parse(CheckstyleReportsParser.java:133)
    at com.github.checkstyle.Main.main(Main.java:163)
patch-diff-report-tool failed on openjdk10
Regression Failed!
````

````
ricky@ubuntu17:~/opensource/regression_reports/savepull/openjdk10$ ll
total 9320
drwxr-xr-x  2 www-data www-data    4096 Jun  8 00:49 ./
drwxr-xr-x 31 www-data www-data    4096 Jun  8 06:32 ../
-rw-r--r--  1 www-data www-data 9535488 Jun  8 00:52 results.xml
````

Contents of report for `/home/ricky/regression_reports/savepull/openjdk10/results.xml` at line 131474 is:
````
<file name="/home/ricky/regression_repositories/openjdk10/src/jdk.accessibility/share/classes/com/sun/java/accessibility/util/EventQueueMonitor.java">
</file>
<file name="/home/ricky/regression_repositories/openjdk10/src/jdk.accessi
````
Last line is EOF. `<file` tag is never ended, hence why exception occurred. I was expecting the file to still be valid and print the exception inside the file to show on the reports and still examine other areas for any issues with the check.

**Comment by rnveach** [comment]
Maybe its too early and I wasn't thinking.
I think program is fully terminated when `OutOfMemoryError` occurs as we have no more memory and can't do proper shutdown?

**Comment by romani** [comment]
There is no guarantee

**Comment by rnveach** [comment]
`XMLLogger` only closes the file and the root node when [auditFinished](https://github.com/checkstyle/checkstyle/blob/6be04d9e540bb1a76419030b1b608c2960af2692/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java#L125) and [fileFinished](https://github.com/checkstyle/checkstyle/blob/6be04d9e540bb1a76419030b1b608c2960af2692/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java#L141) is called.

When `haltOnException` is turned off (by default), [we pass the exception up the chain](https://github.com/checkstyle/checkstyle/blob/6be04d9e540bb1a76419030b1b608c2960af2692/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L328) and then [give the file the exception occurred and throw it all the way out](https://github.com/checkstyle/checkstyle/blob/6be04d9e540bb1a76419030b1b608c2960af2692/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L292-L300). These 2 throws bypass the `fireFileFinished` and the `fireAuditFinished` in `Checker`.

If any exception occurs, like NPE for example, while working with XMLLogger, we are guaranteed that the file won't be a valid XML. We have 1 person requesting exceptions be in the XML file at #4377.

Since `OutOfMemoryError` is an `Error` exception, we skip the first catch and go straight to the 2nd. So it still bypasses the mentioned methods and still executes some new object instantiation, so we aren't completely out of memory if the error happens.

We should try to fail gracefully during an error and if that fails, those errors should be silenced and we fail on the original error.

**Comment by romani** [comment]
we can try to close file while exception/error is happened.
But user should not expect that file will always be correct on crash, we can try, but there is no guaranty.

we can do:
```
fireFileStarted(fileName);
try {
  final SortedSet<LocalizedMessage> fileMessages = processFile(file);
  fireErrors(fileName, fileMessages);
} finally {
  fireFileFinished(fileName);
}
```
and 
```
// Prepare to start
fireAuditStarted();
try {
....
} finally {
  fireAuditFinished();
}
```

**Comment by romani** [comment]
@rnveach , ping.

**Comment by rnveach** [comment]
Just a note, XML file is corrupted on other minor exceptions outside of memory.

This can occur during `org.antlr.v4.runtime.NoViableAltException`. So there are some valid cases where we should try to end more appropriately.

**Comment by ishu7w** [comment]
I am working on this. I will reproduce incomplete XML output after a processing failure, add regression coverage, and ensure started file/audit events are finished while preserving failure propagation.

**Comment by ishu7w** [comment]
Submitted #21520. I reproduced the issue on release 14.1.0 with a Java syntax error and XML output: the failure left a zero-byte report. With the patch, the CLI retains its failure exit code and produces valid XML. The PR adds exception/error regression coverage and includes the full-suite test and quality-check results.

**Comment by romani** [comment]
fix is merged
