### ISSUE TITLE
ClassNotFoundException: com.puppycrawl.tools.checkstyle.utils.TokenUtils

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5985]
https://travis-ci.org/checkstyle/checkstyle/jobs/398621943#L941

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (sevntu-checkstyle-check) on project checkstyle: Failed during checkstyle configuration: cannot initialize module TreeWalker - Cannot set property 'blockTypes' to 'LITERAL_IF,LITERAL_ELSE,LITERAL_WHILE,LITERAL_DO,                              LITERAL_FOR,LITERAL_SWITCH,LITERAL_TRY,LITERAL_CATCH' in module ChildBlockLength: InvocationTargetException: com/puppycrawl/tools/checkstyle/utils/TokenUtils: com.puppycrawl.tools.checkstyle.utils.TokenUtils -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (sevntu-checkstyle-check) on project checkstyle: Failed during checkstyle configuration
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed during checkstyle configuration
	at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:534)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Cannot set property 'blockTypes' to 'LITERAL_IF,LITERAL_ELSE,LITERAL_WHILE,LITERAL_DO,                              LITERAL_FOR,LITERAL_SWITCH,LITERAL_TRY,LITERAL_CATCH' in module ChildBlockLength
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:460)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:214)
	at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:529)
	... 22 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Cannot set property 'blockTypes' to 'LITERAL_IF,LITERAL_ELSE,LITERAL_WHILE,LITERAL_DO,                              LITERAL_FOR,LITERAL_SWITCH,LITERAL_TRY,LITERAL_CATCH' in module ChildBlockLength
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:238)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:191)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:155)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:455)
	... 25 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2127)
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2108)
	at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:437)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:228)
	... 29 more
Caused by: java.lang.NoClassDefFoundError: com/puppycrawl/tools/checkstyle/utils/TokenUtils
	at com.github.sevntu.checkstyle.checks.design.ChildBlockLengthCheck.setBlockTypes(ChildBlockLengthCheck.java:104)
	... 37 more
Caused by: java.lang.ClassNotFoundException: com.puppycrawl.tools.checkstyle.utils.TokenUtils
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 38 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by romani** [comment]
side effect of renaming of class - #5812

**Comment by romani** [comment]
fixed by https://github.com/checkstyle/checkstyle/commit/ec1b2e5aedb3dab9e3cfe4e203c2a8333449d65f

**Comment by romani** [comment]
sevntu extension should stay on old checkstyle 8.10.1 ([reason](https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/pom.xml#L19)), version in sevntu project can be updated only after eclipse-cs be upgraded to checktyle 8.11 at checkstyle/eclipse-cs#84

**Comment by rnveach** [comment]
> sevntu extension should stay on old checkstyle 8.10.1 (reason)

This config is wrong but can only be fixed in sevntu. There is no 8.10.1 eclipse-cs. It should be 8.10 .

**Comment by romani** [comment]
latest version on checkstyle is not compatible latest version of sevntu.
If in build config both are used, it is better to not update checksyle to 8.11 and stay on 8.10.1 till sevntu update to new version of checksyle
Example of failure:
```
 $ git diff
diff --git a/maven-project/checkstyle.xml b/maven-project/checkstyle.xml
index 27ddbb2..6529505 100644
--- a/maven-project/checkstyle.xml
+++ b/maven-project/checkstyle.xml
@@ -6,6 +6,11 @@
 
 <module name="Checker">
   <module name="TreeWalker">
-    <module name="com.github.sevntu.checkstyle.checks.coding.ReturnNullInsteadOfBooleanCheck"/>
+        <module name="ChildBlockLength">
+            <property name="blockTypes"
+                      value="LITERAL_IF,LITERAL_ELSE,LITERAL_WHILE,LITERAL_DO,
+                             LITERAL_FOR,LITERAL_SWITCH,LITERAL_TRY,LITERAL_CATCH"/>
+        </module>
+<!--    <module name="com.github.sevntu.checkstyle.checks.coding.ReturnNullInsteadOfBooleanCheck"/>-->
   </module>
 </module>

sevntu-checkstyle/checkstyle-samples/maven-project [master|✚ 1] 
$ mvn checkstyle:check
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building maven-project 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (default-cli) @ maven-project ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.080 s
[INFO] Finished at: 2018-06-30T18:06:49-07:00
[INFO] Final Memory: 13M/233M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default-cli) on project maven-project: Failed during checkstyle configuration: cannot initialize module TreeWalker - Cannot set property 'blockTypes' to 'LITERAL_IF,LITERAL_ELSE,LITERAL_WHILE,LITERAL_DO,                              LITERAL_FOR,LITERAL_SWITCH,LITERAL_TRY,LITERAL_CATCH' in module ChildBlockLength: InvocationTargetException: com/puppycrawl/tools/checkstyle/utils/TokenUtils: com.puppycrawl.tools.checkstyle.utils.TokenUtils -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
