### ISSUE TITLE
NullPointerException when using lambda expressions for member variables

### ISSUE THREAD

**Issue by smzuber** [checkstyle/checkstyle#6019]
Hi,

I have a member variable that is initialized from a lambda function. It is throwing a null pointer exception, the error goes away if I switch to anonymous class.

We use lambda functions in other places in the code but not for initializing member variables.

Below is stack trace of the exception thrown by check style.

Thanks,
Zuber

java.lang.NullPointerException at com.puppycrawl.tools.checkstyle.checks.coding.ReturnCountCheck.visitToken(ReturnCountCheck.java:111)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:401)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:479)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:334)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:188)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:73)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:263)
	at com.puppycrawl.tools.checkstyle.CheckStyleTask.realExecute(CheckStyleTask.java:318)
	at com.puppycrawl.tools.checkstyle.CheckStyleTask.execute(CheckStyleTask.java:262)

**Comment by romani** [comment]
Please report issue was it was requested in issue template, it will force you to provide all details we need

**Comment by rnveach** [comment]
> `at com.puppycrawl.tools.checkstyle.CheckStyleTask.execute(CheckStyleTask.java:262)`

@romani This is a very old version of checkstyle.
CheckStyleTask was renamed to CheckstyleAntTask in https://github.com/checkstyle/checkstyle/issues/1108 (version 6.8)
I can also confirm with the line numbers given for `ReturnCountCheck.visitToken`. The method doesn't hit lines that low until the version 6 releases.

@smzuber It is time to update your checkstyle version. We are now on 8.11 .

**Comment by smzuber** [comment]
Thanks @rnveach - the null pointer exception is resolved after upgrading to 8.0, thanks a lot.

However, I am getting instantiation errors for 2 other checks - StrictDuplicateCode and RedundantThrows.

From the Release Notes, looks like these checks were removed in 6.2 release, but wondering if there are any replacement/comparable checks for these checks

**Comment by rnveach** [comment]
There are no replacements or comparable checks.
