### ISSUE TITLE
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src\test\resources\noclasspath\A2.java

### ISSUE THREAD

**Issue by zielint0** [checkstyle/checkstyle#6065]
```
/var/tmp $ javac YOUR_FILE.java
Project builds successfully using IntelliJ IDEA/Maven.

/var/tmp $ cat config.xml
https://github.com/INRIA/spoon/blob/master/checkstyle.xml

<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN" "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="Checker">
  <module name="NewlineAtEndOfFile">
    <property name="lineSeparator" value="lf"/>
  </module>
  <!-- Trailing spaces -->
  <module name="RegexpSingleline">
    <property name="format" value="\s+$"/>
    <property name="message" value="Line has trailing spaces."/>
  </module>

  <!-- Checks for the new line format -->
  <module name="RegexpMultiline">
    <property name="format" value="\r\n"/>
    <property name="message" value="Do not use Windows line endings"/>
  </module>

  <module name="TreeWalker">
    <module name="RegexpSinglelineJava">
      <property name="format" value="^\t* "/>
      <property name="message" value="Indent must use tab characters"/>
      <property name="ignoreComments" value="true"/>
    </module>

    <!-- Checks for imports                              -->
    <!-- See http://checkstyle.sf.net/config_import.html -->
    <module name="AvoidStarImport"/>
    <module name="IllegalImport"/> <!-- defaults to sun.* packages -->
    <module name="RedundantImport"/>
    <module name="UnusedImports">
      <property name="processJavadoc" value="true"/>
    </module>

    <!-- Checks for whitespace                               -->
    <!-- See http://checkstyle.sf.net/config_whitespace.html -->
    <module name="GenericWhitespace"/>
    <module name="EmptyForIteratorPad"/>
    <module name="MethodParamPad"/>
    <module name="NoWhitespaceAfter">
      <property name="tokens" value="BNOT, DEC, DOT, INC, LNOT, UNARY_MINUS, UNARY_PLUS"/>
    </module>
    <module name="NoWhitespaceBefore"/>
    <module name="OperatorWrap"/>
    <module name="ParenPad"/>
    <module name="WhitespaceAfter"/>
    <module name="WhitespaceAround"/>

    <!-- Modifier Checks                                    -->
    <!-- See http://checkstyle.sf.net/config_modifiers.html -->
    <module name="ModifierOrder"/>
    <module name="RedundantModifier"/>

    <!-- Checks for blocks. You know, those {}'s         -->
    <!-- See http://checkstyle.sf.net/config_blocks.html -->
    <module name="LeftCurly" />
    <module name="RightCurly" />
    <module name="NeedBraces"/>

    <!-- Checks for class design                         -->
    <!-- See http://checkstyle.sf.net/config_design.html -->
    <module name="InterfaceIsType"/>
    <module name="HideUtilityClassConstructor"/>
  </module>
</module>

/var/tmp $ cat YOUR_FILE.java
spoon/test/visibility/testclasses/A2.java

package spoon.test.visibility.testclasses;

public class A2 {
	public class B {
		public static final int i = 0;
		public boolean m(Object o) {
			return i == 0;
		}
	}

	public class C<T> {
	}

	public boolean instanceOf(Object o) {
		return o instanceof A2.B;
	}

	public C<String> returnType() {
		return new C<String>();
	}

	public Foo<String>.Bar<String> returnType2(String s) {
		return null;
	}

	public void aMethod() {
		class D {
		}
		new D();
	}
}


/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java

com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src\test\resources\noclasspath\A2.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:581)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:472)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:226)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred while parsing file D:\projects\spoon\src\test\resources\noclasspath\A2.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:98)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:180)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 4 more
Caused by: D:\projects\spoon\src\test\resources\noclasspath\A2.java:19:1: expecting EOF, found '}'
        at antlr.Parser.match(Parser.java:211)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:211)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:92)
        ... 8 more
Checkstyle ends with 1 errors.
```

---------------
java -jar .\checkstyle-8.11-all.jar -c .\checkstyle.xml src

Checkstyle ended with exception.
It should provide list of violations.
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src\test\resources\noclasspath\A2.java

--------------

**Comment by rnveach** [comment]
@zielint0 Please re-verify your Java file is correct. I cannot reproduce the problem.

**Comment by zielint0** [comment]
@rnveach 
There are 2 A2.java files. The file I pasted above is correct.
The problem is with another A2.java - D:\projects\spoon\src\test\resources\noclasspath\A2.java
```
public class A2 {

	int field;

	public void b(int param) {
		IntUnaryOperator f1 = x -> x;
		IntBinaryOperator f2 = (a, b) -> a + b;
		try {
			System.out.println(f1.applyAsInt(f2.applyAsInt(field, param)));
		} catch (RuntimeException e) {
			throw e;
		}
	}

	public void c(int param) {
		c(param);
	}
}
}
```
It has an additional "}". So it does not compile. Sorry for bothering ;-)
