### ISSUE TITLE
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src\test\resources\printer-test\spoon\test\AnnotationSpecTest.java

### ISSUE THREAD

**Issue by zielint0** [checkstyle/checkstyle#6066]
```
/var/tmp $ javac YOUR_FILE.java
Project builds successfully using IntelliJ IDEA/Maven.

/var/tmp $ cat config.xml
https://github.com/INRIA/spoon/blob/master/checkstyle.xml

<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN" "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="Checker">
  <module name="NewlineAtEndOfFile">
    <property name="lineSeparator" value="lf"/>
  </module>
  <!-- Trailing spaces -->
  <module name="RegexpSingleline">
    <property name="format" value="\s+$"/>
    <property name="message" value="Line has trailing spaces."/>
  </module>

  <!-- Checks for the new line format -->
  <module name="RegexpMultiline">
    <property name="format" value="\r\n"/>
    <property name="message" value="Do not use Windows line endings"/>
  </module>

  <module name="TreeWalker">
    <module name="RegexpSinglelineJava">
      <property name="format" value="^\t* "/>
      <property name="message" value="Indent must use tab characters"/>
      <property name="ignoreComments" value="true"/>
    </module>

    <!-- Checks for imports                              -->
    <!-- See http://checkstyle.sf.net/config_import.html -->
    <module name="AvoidStarImport"/>
    <module name="IllegalImport"/> <!-- defaults to sun.* packages -->
    <module name="RedundantImport"/>
    <module name="UnusedImports">
      <property name="processJavadoc" value="true"/>
    </module>

    <!-- Checks for whitespace                               -->
    <!-- See http://checkstyle.sf.net/config_whitespace.html -->
    <module name="GenericWhitespace"/>
    <module name="EmptyForIteratorPad"/>
    <module name="MethodParamPad"/>
    <module name="NoWhitespaceAfter">
      <property name="tokens" value="BNOT, DEC, DOT, INC, LNOT, UNARY_MINUS, UNARY_PLUS"/>
    </module>
    <module name="NoWhitespaceBefore"/>
    <module name="OperatorWrap"/>
    <module name="ParenPad"/>
    <module name="WhitespaceAfter"/>
    <module name="WhitespaceAround"/>

    <!-- Modifier Checks                                    -->
    <!-- See http://checkstyle.sf.net/config_modifiers.html -->
    <module name="ModifierOrder"/>
    <module name="RedundantModifier"/>

    <!-- Checks for blocks. You know, those {}'s         -->
    <!-- See http://checkstyle.sf.net/config_blocks.html -->
    <module name="LeftCurly" />
    <module name="RightCurly" />
    <module name="NeedBraces"/>

    <!-- Checks for class design                         -->
    <!-- See http://checkstyle.sf.net/config_design.html -->
    <module name="InterfaceIsType"/>
    <module name="HideUtilityClassConstructor"/>
  </module>
</module>

/var/tmp $ cat YOUR_FILE.java

package com.squareup.javapoet;

import com.google.testing.compile.CompilationRule;
import java.lang.annotation.Annotation;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import javax.lang.model.element.TypeElement;
import org.junit.Rule;
import org.junit.Test;

import static com.google.common.truth.Truth.assertThat;

public final class AnnotationSpecTest {

  @Retention(RetentionPolicy.RUNTIME)
  public @interface AnnotationA {
  }

  @Inherited
  @Retention(RetentionPolicy.RUNTIME)
  public @interface AnnotationB {
  }

  @Retention(RetentionPolicy.RUNTIME)
  public @interface AnnotationC {
    String value();
  }

  public enum Breakfast {
    WAFFLES, PANCAKES;
    public String toString() { return name() + " with cherries!"; };
  }

  @Retention(RetentionPolicy.RUNTIME)
  public @interface HasDefaultsAnnotation {

    byte a() default 5;

    short b() default 6;

    int c() default 7;

    long d() default 8;

    float e() default 9.0f;

    double f() default 10.0;

    char[] g() default {0, 0xCAFE, 'z', '€', 'ℕ', '"', '\'', '\t', '\n'};

    boolean h() default true;

    Breakfast i() default Breakfast.WAFFLES;

    AnnotationA j() default @AnnotationA();

    String k() default "maple";

    Class<? extends Annotation> l() default AnnotationB.class;

    int[] m() default {1, 2, 3};

    Breakfast[] n() default {Breakfast.WAFFLES, Breakfast.PANCAKES};

    Breakfast o();

    int p();

    AnnotationC q() default @AnnotationC("foo");

    Class<? extends Number>[] r() default {Byte.class, Short.class, Integer.class, Long.class};

  }

  @HasDefaultsAnnotation(
      o = Breakfast.PANCAKES,
      p = 1701,
      f = 11.1,
      m = {9, 8, 1},
      l = Override.class,
      j = @AnnotationA,
      q = @AnnotationC("bar"),
      r = {Float.class, Double.class})
  public class IsAnnotated {
    // empty
  }

}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java

com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src\test\resources\printer-test\spoon\test\AnnotationSpecTest.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:581)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:472)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:226)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred while parsing file D:\projects\spoon\src\test\resources\printer-test\spoon\test\AnnotationSpecTes
.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:98)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:180)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 4 more
Caused by: line 65:43: expecting ''', found '?'
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:405)
        at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
        at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)
        at antlr.TokenBuffer.fill(TokenBuffer.java:69)
        at antlr.TokenBuffer.LA(TokenBuffer.java:80)
        at antlr.LLkParser.LA(LLkParser.java:52)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.annotationMemberArrayValueInitializer(GeneratedJavaRecognizer.java:2098)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.annotationMemberArrayInitializer(GeneratedJavaRecognizer.java:2042)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.annotationMemberValueInitializer(GeneratedJavaRecognizer.java:1893)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.annotationDefault(GeneratedJavaRecognizer.java:3122)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.annotationField(GeneratedJavaRecognizer.java:3009)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.annotationBlock(GeneratedJavaRecognizer.java:2828)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.annotationDefinition(GeneratedJavaRecognizer.java:755)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:577)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3236)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2542)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:92)
        ... 8 more
Checkstyle ends with 1 errors.

```

---------------

Checkstyle ended with exception.
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src\test\resources\printer-test\spoon\test\AnnotationSpecTest.java
It should provide list of code style violations

--------------

**Comment by rnveach** [comment]
@zielint0 Please trim your cases down to the smallest possible.

**Comment by rnveach** [comment]
> '€', 'ℕ'

We only support ASCII. See http://checkstyle.sourceforge.net/writingchecks.html#Limitations

> Java code should be written with ASCII characters only, no UTF-8 support.

**Comment by zielint0** [comment]
@rnveach 
Thank you for information. My mistake.
