### ISSUE TITLE
fails on ß

### ISSUE THREAD

**Issue by SebastianDietrich** [checkstyle/checkstyle#6080]
I get the following exception when parsing a method with a ß (german eszett) in its name:
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C:\Users\Sebastian\git\pipe.line\web-test\src\test\java\at\wrwks\transformers\cucumber\steps\BuildingSearchSteps.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:581)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:472)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:226)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred while parsing file C:\Users\Sebastian\git\pipe.line\web-test\src\test\java\at\wrwks\transformers\cucumber\steps\BuildingSearchSteps.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:98)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:181)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)

        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 4 more
Caused by: line 585:37: Unexpected character 0xbc in identifier
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:405)
        at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
        at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)
        at antlr.TokenBuffer.fill(TokenBuffer.java:69)
        at antlr.TokenBuffer.LA(TokenBuffer.java:80)
        at antlr.LLkParser.LA(LLkParser.java:52)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.modifiers(GeneratedJavaRecognizer.java:519)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3232)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2542)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.class Definition(GeneratedJavaRecognizer.java:634)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:92)
        ... 8 more
Checkstyle ends with 1 errors.

**Comment by romani** [comment]
It is good point to update  documentation, please create separate issue on this.

Uft-8 support is possible, but require update of our grammar of java, the most complicated part of checkstyle. Nobody wants to spend months on this, so it is become limitation.

**Comment by SebastianDietrich** [comment]
see #6083. Thanks for the clarification.
