### ISSUE TITLE
use openjdk10 code base in regression testing by CIs

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6162]
detected at https://github.com/checkstyle/checkstyle/pull/6140#issuecomment-431965937

file openjdk10/src/jdk.jlink/share/classes/jdk/tools/jlink/internal/plugins/SystemModulesPlugin.java

config: default checks IllegalType and UnusedImports

Exception:
```
Got an exception - java.lang.NullPointerException
#x9;at com.puppycrawl.tools.checkstyle.api.FullIdent.createFullIdentBelow(FullIdent.java:67)
#x9;at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.checkIdent(IllegalTypeCheck.java:351)
#x9;at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.checkType(IllegalTypeCheck.java:362)
#x9;at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.checkTypeArguments(IllegalTypeCheck.java:414)
#x9;at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.visitMethodCallOrRef(IllegalTypeCheck.java:296)
#x9;at com.puppycrawl.tools.checkstyle.checks.coding.IllegalTypeCheck.visitToken(IllegalTypeCheck.java:201)
#x9;at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
#x9;at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
#x9;at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:330)
#x9;at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:183)
#x9;at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
#x9;at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
#x9;at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
#x9;at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
```

**Comment by nmancus1** [comment]
@romani This appears to longer be an issue:


File is taken from https://github.com/openjdk/jdk10/blob/master/src/jdk.jlink/share/classes/jdk/tools/jlink/internal/plugins/SystemModulesPlugin.java.

```bash

➜  src cat config.xml                                                                                                    
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="IllegalType">
        </module>
        <module name="UnusedImports">
        </module>
    </module>
</module>

➜  src java -jar ~/IdeaProjects/checkstyle/target/checkstyle-8.44-SNAPSHOT-all.jar -c config.xml SystemModulesPlugin.java
Starting audit...
Audit done.

➜  src 

```
Also:

```bash
➜  src java -jar checkstyle-8.42-all.jar -c config.xml SystemModulesPlugin.java
Starting audit...
Audit done.

➜  src cat config.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="IllegalType">
        </module>
        <module name="UnusedImports">
        </module>
    </module>
</module>

➜  src 

```
I cannot reproduce this exception, it appears that this has been fixed at some point.

I think we can close this.

**Comment by romani** [comment]
thanks a lot for investigation, lets close
