### ISSUE TITLE
EmptyLineSeparator fails with ArrayIndexOutOfBoundsException if file doesn't have header

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#621]
##### Description
[EmptyLineSeparator](http://checkstyle.sourceforge.net/config_whitespace.html#EmptyLineSeparator) check with new option `allowMultipleEmptyLines` set to `false` fails with `java.lang.ArrayIndexOutOfBoundsException: -2` on input without comment in header.

##### Failing input
```java
package com.puppycrawl.tools.checkstyle.whitespace;

class A {};
```
##### Workaround
Put to every file in project some header before package declaration:
```java
//HEADER//

package com.puppycrawl.tools.checkstyle.whitespace;

class A {};
```

##### Stacktrace
```
java.lang.ArrayIndexOutOfBoundsException: -2
	at com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck.isPrePreviousLineEmpty(EmptyLineSeparatorCheck.java:274)
	at com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck.visitToken(EmptyLineSeparatorCheck.java:250)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:460)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:553)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:385)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:216)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:271)
	at com.puppycrawl.tools.checkstyle.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:119)
	at com.puppycrawl.tools.checkstyle.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:106)
	at com.puppycrawl.tools.checkstyle.BaseCheckTestSupport.verify(BaseCheckTestSupport.java:93)
	at com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheckTest.testMultipleEmptyLinesBetweenClassMembers(EmptyLineSeparatorCheckTest.java:77)
```
##### Root cause 
Problem is visible below. Array should not be accessed if `lineNo` < 3:
```java
 private boolean isPrePreviousLineEmpty(DetailAST token)
 {
    final int lineNo = token.getLineNo();
    // 3 is the number of the pre-previous line because the numbering starts from zero.
    final int number = 3;
    final String prePreviousLine = getLines()[lineNo - number];
    return prePreviousLine.trim().isEmpty();
}
```

**Comment by romani** [comment]
fixed, will be in 6.4
