### ISSUE TITLE
XmlLoader: remove incomplete namespaces support

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6262]
Identified at https://github.com/checkstyle/checkstyle/pull/6251#issuecomment-445466617 while working on line https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java#L70 ,

Removing this code results in no test failures and I don't know how to add a test to keep it. We don't use namespaces and it seems even trying to use it results in a failure anyways so we should just remove it.

```
/var/tmp$ java -jar checkstyle-8.12-all.jar -c config.xml TestClass.java 
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - Attribute "xmlns:xi" must be declared for element type "module".:6:69
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:447)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:392)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:545)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:472)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:226)
Caused by: org.xml.sax.SAXParseException; systemId: file:/var/tmp/config.xml; lineNumber: 6; columnNumber: 69; Attribute "xmlns:xi" must be declared for element type "module".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1253)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1917)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:742)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:85)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:194)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:440)
	... 4 more
Checkstyle ends with 1 errors.

/var/tmp$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name = "Checker" xmlns:xi="http://www.w3.org/2001/XInclude">
    <xi:include href="TreeWalker.xml" />
    <module name="SuppressionFilter">
      <property name="file" value="suppressions.xml"/>
      <property name="optional" value="false"/>
    </module>
</module>

```

**Comment by romani** [comment]
This was added in c94b581 .
Intention was to add xinclude feature like https://home.adelphi.edu/~pe16132/csc171/bluej/Fall2014InstallBluej/junk1/BlueJ_stuff_july2014_Mac/extensions/checkstyle-5.6/contrib/examples/XInclude/ .
Splitting config into few files can be done now with DTD Entity, example https://android.googlesource.com/platform/prebuilts/checkstyle/+/master/android-style.xml .

It is ok to restore namespace awareness functionality in future, with clear test case of usage.

**Comment by rnveach** [comment]
Fix was merged
