### ISSUE TITLE
AnnotationOnSameLineCheck: NPE

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6329]
Observed when running pitest regression. Taken from openjdk10.

````
$ cat TestClass.java
import java.io.Serializable;

public class TestClass {

    Object field = (Cloneable & Serializable) null;

}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="AnnotationOnSameLine">
  <property name="tokens" value=" CLASS_DEF, INTERFACE_DEF, ENUM_DEF, METHOD_DEF, CTOR_DEF, VARIABLE_DEF, PARAMETER_DEF, ANNOTATION_DEF, TYPECAST, LITERAL_THROWS, IMPLEMENTS_CLAUSE, TYPE_ARGUMENT, LITERAL_NEW, DOT, ANNOTATION_FIELD_DEF"/>
</module>
    </module>
</module>

$ java -jar checkstyle-8.15-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:217)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:390)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:313)
    at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:180)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
Caused by: java.lang.NullPointerException
    at com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationOnSameLineCheck.visitToken(AnnotationOnSameLineCheck.java:82)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:330)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:183)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:319)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
    ... 5 more
Checkstyle ends with 1 errors.
````

**Comment by pbludov** [comment]
Minimal code to reproduce the bug:
```
import java.io.Serializable;

public class TestClass {

    Object field = (Cloneable & Serializable) null;

}
```

Failed line is https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheck.java#L80
```
        DetailAST nodeWithAnnotations = ast;
        if (ast.getType() == TokenTypes.TYPECAST) {
            nodeWithAnnotations = ast.findFirstToken(TokenTypes.TYPE); // returns null 
        }
```

There is no `TYPE` token among `TYPECAST` children. The AST is
```
    |--VARIABLE_DEF -> VARIABLE_DEF [5:4]
    |   |--MODIFIERS -> MODIFIERS [5:4]
    |   |--TYPE -> TYPE [5:4]
    |   |   `--IDENT -> Object [5:4]
    |   |--IDENT -> field [5:11]
    |   |--ASSIGN -> = [5:17]
    |   |   `--EXPR -> EXPR [5:19]
    |   |       `--TYPECAST -> ( [5:19]
    |   |           |--BAND -> & [5:30]
    |   |           |   |--TYPE -> TYPE [5:20]
    |   |           |   |   `--IDENT -> Cloneable [5:20]
    |   |           |   `--TYPE -> TYPE [5:32]
    |   |           |       `--IDENT -> Serializable [5:32]
    |   |           |--RPAREN -> ) [5:44]
    |   |           `--LITERAL_NULL -> null [5:46]
    |   `--SEMI -> ; [5:50]
```

Note that `BAND` (binary and) shouldn't be there. It should be `TYPE_EXTENSION_AND`.

**Comment by rnveach** [comment]
Thanks, I updated the main post with the minimal code.

**Comment by rnveach** [comment]
I am closing this as NPE doesn't occur anymore in 8.17 but occurred in 8.16 .

````
$ cat TestClass.java
import java.io.Serializable;

public class TestClass {

    Object field = (Cloneable & Serializable) null;

}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="AnnotationOnSameLine">
  <property name="tokens" value=" CLASS_DEF, INTERFACE_DEF, ENUM_DEF, METHOD_DEF, CTOR_DEF, VARIABLE_DEF, PARAMETER_DEF, ANNOTATION_DEF, TYPECAST, LITERAL_THROWS, IMPLEMENTS_CLAUSE, TYPE_ARGUMENT, LITERAL_NEW, DOT, ANNOTATION_FIELD_DEF"/>
</module>
    </module>
</module>

$ java -jar checkstyle-8.17-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````
