### ISSUE TITLE
FinalLocalVariable: NPE

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6375]
````
$ cat TestClass.java
package com.puppycrawl.tools.checkstyle.checks.coding.requirethis;

public class InputRequireThisReceiver {
    public void foo4(InputRequireThisReceiver this) {}

    private class Inner {
        public Inner(InputRequireThisReceiver InputRequireThisReceiver.this) {}
    }
}


$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <property name="haltOnException" value="false"/>

    <module name="TreeWalker">

<module name="FinalLocalVariable">
  <property name="tokens" value="VARIABLE_DEF, PARAMETER_DEF"/>
</module>

    </module>
</module>

$ java -jar checkstyle-8.16-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:1: Got an exception - java.lang.NullPointerException
    at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.insertParameter(FinalLocalVariableCheck.java:465)
    at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.visitToken(FinalLocalVariableCheck.java:209)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:330)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:183)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:319)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:217)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:390)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:313)
    at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:180)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
[Checker]
Audit done.
Checkstyle ends with 1 errors.
````

**Comment by romani** [comment]
Fix is merged
