### ISSUE TITLE
please support preceding, preceding-sibling, following and following-sibling in XPath expressions

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6479]
If you use one of preceding, preceding-sibling, following and following-sibling axis in a `suppress-xpath` `query` in 8.17, you get the exception

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing .../Foo.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:217)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.processFiles(CheckstyleAntTask.java:349)
        ... 157 more
Caused by: java.lang.IllegalStateException: Cannot initialize context and evaluate query: //INSTANCE_INIT[not(preceding-sibling::LCURLY and following-sibling::RCURLY)]
        at com.puppycrawl.tools.checkstyle.filters.XpathFilter.getItems(XpathFilter.java:194)
        at com.puppycrawl.tools.checkstyle.filters.XpathFilter.isXpathQueryMatching(XpathFilter.java:160)
        at com.puppycrawl.tools.checkstyle.filters.XpathFilter.accept(XpathFilter.java:123)
        at com.puppycrawl.tools.checkstyle.filters.SuppressionXpathFilter.accept(SuppressionXpathFilter.java:87)
        at com.puppycrawl.tools.checkstyle.TreeWalker.getFilteredMessages(TreeWalker.java:213)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:192)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:319)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
        ... 159 more
Caused by: net.sf.saxon.trans.XPathException: Operation is not supported
        at net.sf.saxon.expr.Expression.dynamicError(Expression.java:1437)
        at net.sf.saxon.expr.AxisExpression.iterate(AxisExpression.java:1097)
        at net.sf.saxon.functions.Empty$1.effectiveBooleanValue(Empty.java:138)
        at net.sf.saxon.expr.OrExpression.effectiveBooleanValue(OrExpression.java:133)
        at net.sf.saxon.expr.FilterIterator$NonNumeric.matches(FilterIterator.java:184)
        at net.sf.saxon.expr.FilterIterator.getNextMatchingItem(FilterIterator.java:76)
        at net.sf.saxon.expr.FilterIterator.next(FilterIterator.java:62)
        at net.sf.saxon.om.SequenceIterator.forEachOrFail(SequenceIterator.java:127)
        at net.sf.saxon.sxpath.XPathExpression.evaluate(XPathExpression.java:189)
        at com.puppycrawl.tools.checkstyle.filters.XpathFilter.getItems(XpathFilter.java:191)
        ... 167 more
```

which is actually caused by the suppressed
```
java.lang.UnsupportedOperationException: Operation is not supported
       at com.puppycrawl.tools.checkstyle.xpath.ElementNode.throwUnsupportedOperationException(ElementNode.java:292)
       at com.puppycrawl.tools.checkstyle.xpath.ElementNode.iterateAxis(ElementNode.java:230)
       at com.puppycrawl.tools.checkstyle.xpath.AbstractNode.iterateAxis(AbstractNode.java:134)
       at net.sf.saxon.expr.AxisExpression.iterate(AxisExpression.java:1079)
       at net.sf.saxon.functions.Empty$1.effectiveBooleanValue(Empty.java:138)
       at net.sf.saxon.expr.OrExpression.effectiveBooleanValue(OrExpression.java:133)
       at net.sf.saxon.expr.FilterIterator$NonNumeric.matches(FilterIterator.java:184)
       at net.sf.saxon.expr.FilterIterator.getNextMatchingItem(FilterIterator.java:76)
       at net.sf.saxon.expr.FilterIterator.next(FilterIterator.java:62)
       at net.sf.saxon.om.SequenceIterator.forEachOrFail(SequenceIterator.java:127)
       at net.sf.saxon.sxpath.XPathExpression.evaluate(XPathExpression.java:189)
       at com.puppycrawl.tools.checkstyle.filters.XpathFilter.getItems(XpathFilter.java:191)
       at com.puppycrawl.tools.checkstyle.filters.XpathFilter.isXpathQueryMatching(XpathFilter.java:160)
       at com.puppycrawl.tools.checkstyle.filters.XpathFilter.accept(XpathFilter.java:123)
       at com.puppycrawl.tools.checkstyle.filters.SuppressionXpathFilter.accept(SuppressionXpathFilter.java:87)
       at com.puppycrawl.tools.checkstyle.TreeWalker.getFilteredMessages(TreeWalker.java:213)
       at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:192)
       at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
       at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:319)
       at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
       at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:217)
       at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.processFiles(CheckstyleAntTask.java:349)
       at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.realExecute(CheckstyleAntTask.java:316)
       at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.execute(CheckstyleAntTask.java:288)
       at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
       at groovy.util.AntBuilder.performTask(AntBuilder.java:338)
       at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:283)
       at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
       at jdk.internal.reflect.GeneratedMethodAccessor867.invoke(Unknown Source)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
       at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
       at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
       at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
       at org.gradle.api.internal.project.antbuilder.AntBuilderDelegate.nodeCompleted(AntBuilderDelegate.java:118)
       at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:154)
       at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
       at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
       at org.gradle.api.plugins.quality.internal.CheckstyleInvoker$_invoke_closure1.doCall(CheckstyleInvoker.groovy:58)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
       at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
       at groovy.lang.Closure.call(Closure.java:418)
       at groovy.lang.Closure.call(Closure.java:434)
       at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
       at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:53)
       at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:152)
       at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(DefaultIsolatedAntBuilder.java:134)
       at org.gradle.api.internal.project.antbuilder.ClassPathToClassLoaderCache.withCachedClassLoader(ClassPathToClassLoaderCache.java:134)
       at org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder.execute(DefaultIsolatedAntBuilder.java:128)
       at org.gradle.api.internal.project.IsolatedAntBuilder$execute$0.call(Unknown Source)
       at org.gradle.api.plugins.quality.internal.CheckstyleInvoker.invoke(CheckstyleInvoker.groovy:51)
       at org.gradle.api.plugins.quality.Checkstyle.run(Checkstyle.java:154)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
       at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
       at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
       at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
       at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
       at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
       at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
       at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
       at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
       at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
       at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
       at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
       at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
       at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
       at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
       at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
       at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
       at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
       at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
       at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
       at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
       at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
       at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
       at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
       at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
       at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
       at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
       at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
       at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
       at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
       at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
       at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
       at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
       at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
       at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
       at java.base/java.lang.Thread.run(Thread.java:834)
```

which occurs because those axis are not implemented in `com.puppycrawl.tools.checkstyle.xpath.ElementNode#iterateAxis`.

This makes some queries impossible or unnecessarily complex and slow.

**Comment by romani** [comment]
@Vampire , please update description to follow required template.

**Comment by romani** [comment]
@timurt , can you help us with this issue ?

**Comment by timurt** [comment]
@romani 
Ok. I am on it

**Comment by rnveach** [comment]
Fix was merged
