### ISSUE TITLE
BooleanExpressionComplexity has a NPE on catch block

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#654]
config:
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">

  <module name="NewlineAtEndOfFile">
    <property name="fileExtensions" value="java" />
  </module>

  <module name="TreeWalker">

    <module name="BooleanExpressionComplexity" />

  </module><!-- TreeWalker -->
</module><!-- Checker -->
```
input file:
```
public class A {

    static {
        try {
            System.out.println("a");
        } catch (IllegalStateException | IllegalArgumentException e) {
            throw new RuntimeException(e);
        }
    }
}
```

Output:
```
java -jar checkstyle-6.4-SNAPSHOT-all.jar -c checkstyle_NPE.xml A.java
Feb 19, 2015 8:00:14 AM com.puppycrawl.tools.checkstyle.TreeWalker processFiltered
SEVERE: Exception occurred during the analysis of file A.java .
java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.metrics.BooleanExpressionComplexityCheck.visitToken(BooleanExpressionComplexityCheck.java:126)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:458)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:551)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:383)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:216)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:271)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:128)
Starting audit...
/var/tmp/A.java:0: warning: File does not end with a newline.
/var/tmp/A.java:0: Got an exception - java.lang.NullPointerException
Audit done.
```

Expected: no NPE, and explanation why stacktrace is unattached from  audit event as it is misleading and looks like 2 exceptions and the second is swallowed exception without details.

**Comment by romani** [comment]
fixed, will be in 6.4
