### ISSUE TITLE
Error was thrown while processing java file with checkstyle 8.21

### ISSUE THREAD

**Issue by neowu** [checkstyle/checkstyle#6814]
Checkstyle 8.20 works with same java file, 
8.21 failed to process the file with following exception
looks like caused by EmptyPublicCtorInClassCheck, please help to check

Executor.java
```
public interface Executor {
    <T> Future<T> submit(String action, Callable<T> task);

    default Future<Void> submit(String action, Task task) {
        return submit(action, () -> {
            task.execute();
            return null;
        });
    }

    void submit(String action, Task task, Duration delay);
}
```

Exception thrown by checkstyle, root cause is "Found interface com.puppycrawl.tools.checkstyle.api.DetailAST, but class was expected"

```
Caused by: java.lang.Error: Error was thrown while processing /.../core-ng-project/core-ng/src/main/java/core/framework/async/Executor.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:315)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:220)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.processFiles(CheckstyleAntTask.java:349)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.realExecute(CheckstyleAntTask.java:316)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.execute(CheckstyleAntTask.java:288)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        ... 119 more
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.puppycrawl.tools.checkstyle.api.DetailAST, but class was expected
        at com.github.sevntu.checkstyle.checks.coding.EmptyPublicCtorInClassCheck.visitToken(EmptyPublicCtorInClassCheck.java:197)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:363)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:470)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:304)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:162)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:332)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
        ... 128 more
```

**Comment by neowu** [comment]
never mind, it seems to be caused by sevntu-checks, it works with both update to latest version

**Comment by rnveach** [comment]
> Found interface com.puppycrawl.tools.checkstyle.api.DetailAST, but class was expected
> com.github.sevntu.checkstyle.checks.coding.EmptyPublicCtorInClassCheck

There is nothing we can do about this error as we didn't find about it until after the release.

Sevntu has to be recompiled with the latest version of checkstyle, but it is being held back because eclipse-cs hasn't updated.

**Comment by aunkrig** [comment]
Man... is this a joke? That means one cannot write a CS contribution that works BOTH with CS <=8.20 an CS >=8.21!? Congrats... you broke the entire CS contribution system.

**Comment by romani** [comment]
@aunkrig , sorry about this, terrible problem.
Please let us know if something blocks you to upgrade to version above 8.21 ? (except for this issue)

**Comment by aunkrig** [comment]
I added a new issue #7448
