### ISSUE TITLE
Magic Number suppression does not work when space character encountered in Xpath expression

### ISSUE THREAD

**Issue by Fernal73** [checkstyle/checkstyle#6885]
```
package cstests;

public interface TestMagicNumber {

  static byte[] getAsciiRotator() {
    byte[] rotation = new byte[95 * 2];
    for (byte i = ' '; i <= '~'; i++) {
      rotation[i - ' '] = i;
      rotation[i + 95 - ' '] = i;
    }
    return rotation;
  }
}
```
Use Java 8 or above. (To compile the above code. You could move the method to another class and still have the same error.) 

Config as below:
```
  <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN" "http://www.puppycrawl                           .com/dtds/configuration_1_2.dtd">
<module name="Checker">
    <module name="TreeWalker">
          <module name="MagicNumber">
      <property name="ignoreFieldDeclaration"
                value="true" />
      <property name="ignoreAnnotation"
                value="true" />
      <property name="ignoreHashCodeMethod"
                value="true" />
    </module>
<module name="SuppressionXpathFilter">
  <property name="optional"
            value="true" />
  <property name="file"
            value="suppressions-xpath.xml" />
</module>
</module>
</module>

```
   Run checkstyle  through CLI with option -g set. 

```
java -jar checkstyle-8.20-all.jar -g -c config.xml TestMagicNumber.java
```

Use the generated suppressions in a suppressions-xpath.xml file to suppress the Checkstyle warnings. 
The file should appear as below:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suppressions PUBLIC
    "-//Checkstyle//DTD SuppressionXpathFilter Experimental Configuration 1.2//EN"
    "https://checkstyle.org/dtds/suppressions_1_2_xpath_experimental.dtd">
<suppressions>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
       query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/VARIABLE_DEF[./IDENT[@text='rotation']]/ASSIGN/EXPR/LITERAL_NEW/ARRAY_DECLARATOR/EXPR/STAR/NUM_INT[@text='95']"/>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
       query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./IDENT[@text='i']]/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text='' '']]/PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']"/>
</suppressions>
```

Run checkstyle 8.22 on the file with the suppressions-xpath.xml enabled in your config file. 

```
java -jar checkstyle-8.22-all.jar -c config.xml TestMagicNumber.java
```

Error is output as below:

```
Jul 09, 2019 8:41:51 AM com.puppycrawl.tools.checkstyle.Main runCli
FINE: Checkstyle debug logging enabled
Jul 09, 2019 8:41:51 AM com.puppycrawl.tools.checkstyle.Main runCli
FINE: Running Checkstyle with version: 8.22
Exception in thread "main" java.lang.IllegalArgumentException: Unexpected xpath query: /INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./IDENT[@text='i']]/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text='' '']]/PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']
	at com.puppycrawl.tools.checkstyle.filters.XpathFilterElement.<init>(XpathFilterElement.java:114)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.getXpathFilter(SuppressionsLoader.java:199)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.startElement(SuppressionsLoader.java:145)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:767)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1375)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2706)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:532)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:84)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.getSuppressionLoader(SuppressionsLoader.java:275)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadXpathSuppressions(SuppressionsLoader.java:260)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadXpathSuppressions(SuppressionsLoader.java:247)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionXpathFilter.finishLocalSetup(SuppressionXpathFilter.java:105)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:194)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:131)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:472)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:388)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:315)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:180)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
Caused by: net.sf.saxon.trans.XPathException: expected "]", found "<string-literal>"
	at net.sf.saxon.expr.parser.XPathParser.grumble(XPathParser.java:315)
	at net.sf.saxon.expr.parser.XPathParser.grumble(XPathParser.java:272)
	at net.sf.saxon.expr.parser.XPathParser.grumble(XPathParser.java:259)
	at net.sf.saxon.expr.parser.XPathParser.expect(XPathParser.java:245)
	at net.sf.saxon.expr.parser.XPathParser.parsePredicate(XPathParser.java:2116)
	at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:2085)
	at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:2000)
	at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1957)
	at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1971)
	at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1824)
	at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:753)
	at net.sf.saxon.expr.parser.XPathParser.parseExpression(XPathParser.java:660)
	at net.sf.saxon.expr.parser.XPathParser.parsePredicate(XPathParser.java:2159)
	at net.sf.saxon.expr.parser.XPathParser.parsePredicate(XPathParser.java:2115)
	at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:2085)
	at net.sf.saxon.expr.parser.XPathParser.parseRemainingPath(XPathParser.java:2035)
	at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1925)
	at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1971)
	at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1824)
	at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:753)
	at net.sf.saxon.expr.parser.XPathParser.parseExpression(XPathParser.java:660)
	at net.sf.saxon.expr.parser.XPathParser.parse(XPathParser.java:522)
	at net.sf.saxon.expr.parser.ExpressionTool.make(ExpressionTool.java:107)
	at net.sf.saxon.sxpath.XPathEvaluator.createExpression(XPathEvaluator.java:134)
	at com.puppycrawl.tools.checkstyle.filters.XpathFilterElement.<init>(XpathFilterElement.java:111)
	... 28 more
```

---------------

The Magic Number error should be suppressed. Checkstyle must not throw an exception. 

Addendum: The title could be changed to Checkstyle throws exception with generated suppression for Magic Number rule. Xpath has a problem with attributes containing apostrophes (single quotes). 

--------------

**Comment by romani** [comment]
@Fernal73 , please stricktly follow issue template. 
NO chunks of config is allowed.

**Comment by strkkk** [comment]
@romani I guess it is similar to #6893, single quotes were not escaped
```
CHAR_LITERAL[@text='' '']] 
```

**Comment by Fernal73** [comment]
@romani, Done.
You might wish to include a sample config or empty config file in the template provided for posting an issue. 

I'd appreciate it if you'd display the proposed solution in this thread. I wasn't able to find a resolution to this Xpath error. 

Regards, 
Linus.

**Comment by romani** [comment]
Closed as duplicate

**Comment by Fernal73** [comment]
My bug was written up earlier.
I can only assume that the other bug was written up better.

**Comment by Fernal73** [comment]
This issue can be easily fixed by escaping the single-quoted single-quotes by itself. This appears to be XPath 1.0 compliant.

as so @text=''' '''

**Comment by Fernal73** [comment]
In this case, it's the Char Literal as defined in class TokenTypes that needs to be escaped.

**Comment by Fernal73** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suppressions PUBLIC
    "-//Checkstyle//DTD SuppressionXpathFilter Experimental Configuration 1.2//EN"
    "https://checkstyle.org/dtds/suppressions_1_2_xpath_experimental.dtd">
<suppressions>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
  query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./IDENT[@text='i']]/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text='&apos;&apos;']]/PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']"/>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
  query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./IDENT[@text='i']]/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text='&quot;']]/PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']"/>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
  query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./IDENT[@text='i']]/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text='''']]/PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']"/>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
  query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./IDENT[@text='i']]/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text='&amp;']]/PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']"/>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
  query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./IDENT[@text='i']]/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text='&gt;']]/PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']"/>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
  query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./IDENT[@text='i']]/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text='&lt;']]/PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']"/>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
       query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./IDENT[@text='i']]/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text=' ']]/PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']"/>
</suppressions>
```

The above is the (test) suppressions-xpath file with sanitised entries that work with Checkstyle 8.25.

**Comment by Fernal73** [comment]
This bug also crashes Checkstyle i.e., it throws an exception with stack trace. And it doesn't write anything to the output file. This leaves the previous output, if it exists, untouched. There are at least two lines output in the text output, otherwise. Does this have to be another issue? Since you've closed this one, you could just reopen this one and fix this specific problem? It's not as though the original bug has been fixed as yet.

**Comment by romani** [comment]
please report new issue, and please provide minimized config and input file to ease investigation.

**Comment by Fernal73** [comment]
@romani The description and input files are the same as in the initial post. The only thing that needs to be updated is the release number 8.29 and the additional parameter -o cs.errors which never gets created when the exception is thrown. There really ought to be a request put in to Github to allow copying of issue to new one. This is getting ridiculous.
