### ISSUE TITLE
Checkstyle not working since yesterday's update (8.26)

### ISSUE THREAD

**Issue by tslinardo** [checkstyle/checkstyle#7258]
```
/var/tmp $ javac YOUR_FILE.java
#[[PLACE YOUR OUTPUT HERE]]

/var/tmp $ cat config.xml
#[[PLACE YOUR OUTPUT HERE]]

/var/tmp $ cat YOUR_FILE.java
#[[PLACE YOU OUTPUT HERE]]

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
#[[PLACE YOUR OUTPUT HERE]]
```

---------------
Getting this error: 

com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:472)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:255)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:127)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:140)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:307)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:173)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:147)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:467)
	... 18 more

--------------

Still not clear ???
see example - https://checkstyle.org/report_issue.html#How_to_report_a_bug

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by rnveach** [comment]
I am closing this as the template was not followed and no config/code was provided.

> CheckstyleException: TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.

This is most likely your issue. You have `TreeWalker` in the wrong location in your configuration.
`TreeWalker` should be a direct child of `Checker`.

**Comment by ikosarim** [comment]
mveach, you are wrong! This is problem not only him. Why you close this issue???

**Comment by rnveach** [comment]
@ikosarim Because nothing was provided to us and the little information that was provided I showed is just a configuration problem.

If you have a problem, please open a new issue and provide all the details we ask for in template. https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

Failure to provide the basic template will not give us enough information to help anyone or how to fix the problem. This is why it amounts to closing the issue.

**Comment by romani** [comment]
to fix such problem please read migration note at https://github.com/checkstyle/checkstyle/issues/2116
