### ISSUE TITLE
Appveyor is not failing even build is failed 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7330]
build - https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/29376511/job/c6gy7exdcedw6a87
of https://github.com/checkstyle/checkstyle/pull/7328

in logs we see that build is failed, but final status is green.
Looks like exit code is not populated to from appveyor.bat to appveyor, probably cause dby recent refactoring when appveyor.bat was created.

logs:
```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building checkstyle 8.28-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.875 s
[INFO] Finished at: 2019-12-06T23:57:35+00:00
[INFO] Final Memory: 14M/138M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "verify111". You must specify a valid lifecycle phase 
or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>
[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, 
generate-sources, process-sources, generate-resources, process-resources, 
compile, process-classes, generate-test-sources, process-test-sources,
 generate-test-resources, process-test-resources, test-compile, process-test-classes,
 test, prepare-package, package, pre-integration-test, integration-test, 
post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, 
site, post-site, site-deploy. -> [Help 1]
org.apache.maven.lifecycle.LifecyclePhaseNotFoundException: Unknown lifecycle phase
 "verify111". You must specify a valid lifecycle phase or a goal in the format 
<plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>
[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, 
generate-sources, process-sources, generate-resources, process-resources, 
compile, process-classes, generate-test-sources, process-test-sources, 
generate-test-resources, process-test-resources, test-compile, process-test-classes,
 test, prepare-package, package, pre-integration-test, integration-test, 
post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, 
site, post-site, site-deploy.
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateLifecycleMappings(DefaultLifecycleExecutionPlanCalculator.java:228)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:199)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:118)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:135)
	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:97)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:109)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException
echo "Size of caches (bytes):"
Size of caches (bytes):
Get-ChildItem -Recurse 'C:\maven\apache-maven-3.2.5' | Measure-Object -Property Length -Sum
Count    : 83
Average  : 
Sum      : 9420555
Maximum  : 
Minimum  : 
Property : Length
Get-ChildItem -Recurse 'C:\Users\appveyor\.m2' | Measure-Object -Property Length -Sum
Count    : 5087
Average  : 
Sum      : 218489990
Maximum  : 
Minimum  : 
Property : Length
Discovering tests...OK
Build success
```

**Comment by romani** [comment]
interesting approach - https://stackoverflow.com/a/8965092/1015848

**Comment by romani** [comment]
reason of why skip_commits were removed - https://github.com/checkstyle/checkstyle/pull/7328#issuecomment-562785873
it does not work for us, so it is better for CI to run always.

**Comment by pbludov** [comment]
fix is merged
