### ISSUE TITLE
Generation of xpath suppression file does not close file

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#7382]
Appveyor fails as it impossible to delete a folder with an open file on windows. 
https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/29462765/job/bclpf6jrt0yj3hgn#L3085

```
[ERROR] testGenerateXpathSuppressionOptionCustomOutput{Capturable} 
 Time elapsed: 0 s  <<< ERROR!
java.io.IOException: Failed to delete temp directory 
C:\Users\appveyor\AppData\Local\Temp\1\junit3614680234448042498. 
The following paths could not be deleted (see suppressed exceptions for details): 

Dec 11, 2019 10:10:36 AM 
org.junit.jupiter.engine.execution.JupiterEngineExecutionContext close
SEVERE: Caught exception while closing extension context: 
org.junit.jupiter.engine.descriptor.MethodExtensionContext@27ed160d
java.io.IOException: Failed to delete temp directory 
C:\Users\appveyor\AppData\Local\Temp\1\junit1317292585359068230. 
The following paths could not be deleted (see suppressed exceptions for details): 
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:211)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:168)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:61)
	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:73)
	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:222)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$9(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:83)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.ju
nit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Suppressed: java.nio.file.DirectoryNotEmptyException: 
C:\Users\appveyor\AppData\Local\Temp\1\junit1317292585359068230
at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:266)
at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
at java.nio.file.Files.delete(Files.java:1126)
at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:192)
at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:187)
at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:178)
at java.nio.file.Files.walkFileTree(Files.java:2688)
at java.nio.file.Files.walkFileTree(Files.java:2742)
at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:178)
at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:166)
... 44 more


```

After #6963, when it became possible to specify the output file for xpath suppressions, one small detail was omitted: for both output to file and output to standard output, the option was specified as `OutputStreamOptions.NONE`. As a result, the suppression file was not closed.

This was not a problem for Junit4, since `@TemporaryFolder` is a wrapper for `/tmp` directory itself, while `@TempDir ` from Junit5 creates a subdirectory and then tries to delete it ... and fails.
The`'@TempDir ` annotation from Junit5 works slightly differently than the `@TemporaryFolder` rule from Junit4. This creates a new subdirectory in the $TMP folder, and deletes it when the test completes.
This creates problems when running tests under Windows. If there are unclosed files in the temporary subdirectory, the directory cannot be deleted.

The problem only occurs in Windows. Other systems allow you to delete directories with open files.

This is not a problem to use in the CLI - the program terminates and closes all files.

**Proposal of fix:**
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L389
it should be `getOutputStreamOptions(options.outputPath)`

**Comment by pbludov** [comment]
The '@ TempDir ' annotation from Junit5 works slightly differently than the `@TemporaryFolder` rule from Junit4. This creates a new subdirectory in the $TMP folder, and deletes it when the test completes.

The '@ TempDir ' annotation from Junit5 works slightly differently than the @TemporaryFolder rule from Junit4. This creates a new subdirectory in the $TMP folder, and deletes it when the test completes.

This creates problems when running tests under Windows. If there are unclosed files in the temporary subdirectory, the directory cannot be deleted.

**Comment by romani** [comment]
@pbludov , please share link to appveyor failure and copy stracktrace in issue for future reference, build logs do not stay for long time, so some copy is always good.

**Comment by pbludov** [comment]
> @pbludov , please share link to appveyor failure and copy stracktrace in issue for future reference, build logs do not stay for long time, so some copy is always good.

https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/29462765/job/bclpf6jrt0yj3hgn#L3241

All failed tests from `CheckerTest` and `PropertyCacheFileTest` were fixed in this [PR](https://github.com/checkstyle/checkstyle/pull/7379/files#diff-621d00681a530ee55984af2131842777L280)

For `MainTest` the bug is in the `Main.java` itself.
After #6963, when it became possible to specify the output file for xpath suppressions, one small detail was omitted: for both output to file and output to standard output, the option was specified as `OutputStreamOptions.NONE`. As a result, the suppression file was not closed.

This was not a problem for Junit4, since `@TemporaryFolder` is a wrapper for `/tmp` directory itself, while '@TempDir ' from Junit5 creates a subdirectory and then tries to delete it ... and fails.

The problem only occurs in Windows. Other systems allow you to delete directories with open files.

This is not a problem to use in the CLI - the program terminates and closes all files.

**Comment by rnveach** [comment]
Fix was merged
