### ISSUE TITLE
After migration to junit5 build output become to have output

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7391]
problem can be seen at https://travis-ci.org/checkstyle/checkstyle/jobs/626861728#L1131

Example:
```
[INFO] Running com.puppycrawl.tools.checkstyle.JavadocPropertiesGeneratorTest
Missing required options [--destfile=<outputFile>, params[0]=<inputFile>]
Usage: java com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator [-hV]
       --destfile=<outputFile> <inputFile>
      <inputFile>   The input file.
      --destfile=<outputFile>
                    The output file.
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.
Missing required parameter: <inputFile>
Usage: java com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator [-hV]
       --destfile=<outputFile> <inputFile>
      <inputFile>   The input file.
      --destfile=<outputFile>
                    The output file.
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.
Usage: java com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator [-hV]
       --destfile=<outputFile> <inputFile>
      <inputFile>   The input file.
      --destfile=<outputFile>
                    The output file.
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.
Missing required option '--destfile=<outputFile>'
Usage: java com.puppycrawl.tools.checkstyle.JavadocPropertiesGenerator [-hV]
       --destfile=<outputFile> <inputFile>
      <inputFile>   The input file.
      --destfile=<outputFile>
                    The output file.
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.
```
but there are more out and even exception output.

Expected: UT should produce no output to plugin, build log should be clean from any unrelated information (as it was before)
it is not first time to come to such situation .... is there a way to fail build if some output is leaked ?

**Comment by romani** [comment]
@pbludov , please address.

**Comment by pbludov** [comment]
This is the limitation of junit5-system-extensions. I created issue https://github.com/itsallcode/junit5-system-extensions/issues/16

**Comment by romani** [comment]
Hey, junit5 creates more problems than it being benefits

**Comment by romani** [comment]
Does it make sense to revert MainTest till issue is resolved? 
I think we have no problems to mix junit5 and junit4.

**Comment by pbludov** [comment]
> Does it make sense to revert MainTest till issue is resolved?
> I think we have no problems to mix junit5 and junit4.

Let's wait for an answer from junit5-system-extensions team. If this is a difficult task, then commit https://github.com/checkstyle/checkstyle/commit/2e8dddab2c6b81d71088e1971ba805d6a6ff6eb1 for `MainTest` and `JavadocPropertiesGeneratorTest` should be reverted.

**Comment by romani** [comment]
additional problem:
when UT have bad path to config, UT method is failing with:
```

java.lang.AssertionError: Unexpected call of System.exit(-1).

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.contrib.java.lang.system.ExpectedSystemExit.handleSystemExitWithStatus(ExpectedSystemExit.java:154)
	at org.junit.contrib.java.lang.system.ExpectedSystemExit.checkSystemExit(ExpectedSystemExit.java:142)
	at org.junit.contrib.java.lang.system.ExpectedSystemExit.access$000(ExpectedSystemExit.java:88)
	at org.junit.contrib.java.lang.system.ExpectedSystemExit$1.evaluate(ExpectedSystemExit.java:133)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1$1.evaluate(LogPrintStream.java:30)
	at org.junit.contrib.java.lang.system.internal.PrintStreamHandler$3.evaluate(PrintStreamHandler.java:48)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1.evaluate(LogPrintStream.java:26)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1$1.evaluate(LogPrintStream.java:30)
	at org.junit.contrib.java.lang.system.internal.PrintStreamHandler$3.evaluate(PrintStreamHandler.java:48)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1.evaluate(LogPrintStream.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
To understand what is exactly wrong .... you have to debug, it is not good !!!

**Comment by rnveach** [comment]
> To understand what is exactly wrong .... you have to debug, it is not good !!!

This was always an issue for me even with the old junit.

**Comment by rnveach** [comment]
Fix was merged
