### ISSUE TITLE
SAXParseException with CustomImportOrder in config

### ISSUE THREAD

**Issue by pgerhard** [checkstyle/checkstyle#7410]
Check documentation: https://checkstyle.sourceforge.io/config_imports.html#CustomImportOrder

```
/var/tmp $ javac YOUR_FILE.java
**Not applicable since issue is related to config parsing**

/var/tmp $ cat config.xml
`xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <property name="severity" value="warning"/>

    <property name="fileExtensions" value="java, properties, xml"/>

    <!-- Checks for whitespace                               -->
    <!-- See http://checkstyle.sf.net/config_whitespace.html -->
    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>

    <module name="TreeWalker">
        <module name="CustomImportOrder">
            <property name="sortImportsInGroupAlphabetically" value="true"/>
            <property name="separateLineBetweenGroups" value="true"/>
            <property name="customImportOrderRules"
                      value="STATIC###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE###STANDARD_JAVA_PACKAGE"/>
        </module>
    </module>
</module>

`

/var/tmp $ cat YOUR_FILE.java
**Not applicable since issue is related to config parsing**

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
**Not applicable since config fails to parse**
```

After reading the documentation for the CustomImportOrder check I wanted to use it in my configuration. However adding the above snippet (copied from the google_check.xml) the configuration fails to parse. With the following error:

```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project oss-module-project: Failed during checkstyle execution: Failed during checkstyle configuration: unable to parse configuration stream - The value of attribute "value" associated with an element type "property" must not contain the '<' character.:21:44 -> [Help 1]
[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project oss-module-project: Failed during checkstyle execution
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[INFO]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[INFO]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[INFO]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[INFO]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[INFO]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[INFO]     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[INFO]     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[INFO]     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[INFO]     at java.lang.reflect.Method.invoke (Method.java:498)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Caused by: org.apache.maven.plugin.MojoExecutionException: Failed during checkstyle execution
[INFO]     at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute (CheckstyleViolationCheckMojo.java:546)
[INFO]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[INFO]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[INFO]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[INFO]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[INFO]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[INFO]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[INFO]     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[INFO]     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[INFO]     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[INFO]     at java.lang.reflect.Method.invoke (Method.java:498)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Caused by: org.apache.maven.plugins.checkstyle.exec.CheckstyleExecutorException: Failed during checkstyle configuration
[INFO]     at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.getConfiguration (DefaultCheckstyleExecutor.java:414)
[INFO]     at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle (DefaultCheckstyleExecutor.java:212)
[INFO]     at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute (CheckstyleViolationCheckMojo.java:537)
[INFO]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[INFO]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[INFO]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[INFO]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[INFO]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[INFO]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[INFO]     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[INFO]     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[INFO]     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[INFO]     at java.lang.reflect.Method.invoke (Method.java:498)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - The value of attribute "value" associated with an element type "property" must not contain the '<' character.:21:44
[INFO]     at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration (ConfigurationLoader.java:450)
[INFO]     at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration (ConfigurationLoader.java:395)
[INFO]     at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration (ConfigurationLoader.java:372)
[INFO]     at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.getConfiguration (DefaultCheckstyleExecutor.java:385)
[INFO]     at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle (DefaultCheckstyleExecutor.java:212)
[INFO]     at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute (CheckstyleViolationCheckMojo.java:537)
[INFO]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[INFO]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[INFO]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[INFO]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[INFO]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[INFO]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[INFO]     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[INFO]     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[INFO]     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[INFO]     at java.lang.reflect.Method.invoke (Method.java:498)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Caused by: org.xml.sax.SAXParseException: The value of attribute "value" associated with an element type "property" must not contain the '<' character.
[INFO]     at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException (Unknown Source)
[INFO]     at org.apache.xerces.util.ErrorHandlerWrapper.fatalError (Unknown Source)
[INFO]     at org.apache.xerces.impl.XMLErrorReporter.reportError (Unknown Source)
[INFO]     at org.apache.xerces.impl.XMLErrorReporter.reportError (Unknown Source)
[INFO]     at org.apache.xerces.impl.XMLErrorReporter.reportError (Unknown Source)
[INFO]     at org.apache.xerces.impl.XMLScanner.reportFatalError (Unknown Source)
[INFO]     at org.apache.xerces.impl.XMLScanner.scanAttributeValue (Unknown Source)
[INFO]     at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanAttribute (Unknown Source)
[INFO]     at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement (Unknown Source)
[INFO]     at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch (Unknown Source)
[INFO]     at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument (Unknown Source)
[INFO]     at org.apache.xerces.parsers.XML11Configuration.parse (Unknown Source)
[INFO]     at org.apache.xerces.parsers.XML11Configuration.parse (Unknown Source)
[INFO]     at org.apache.xerces.parsers.XMLParser.parse (Unknown Source)
[INFO]     at org.apache.xerces.parsers.AbstractSAXParser.parse (Unknown Source)
[INFO]     at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse (Unknown Source)
[INFO]     at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource (XmlLoader.java:84)
[INFO]     at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource (ConfigurationLoader.java:197)
[INFO]     at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration (ConfigurationLoader.java:443)
[INFO]     at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration (ConfigurationLoader.java:395)
[INFO]     at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration (ConfigurationLoader.java:372)
[INFO]     at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.getConfiguration (DefaultCheckstyleExecutor.java:385)
[INFO]     at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle (DefaultCheckstyleExecutor.java:212)
[INFO]     at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute (CheckstyleViolationCheckMojo.java:537)
[INFO]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[INFO]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[INFO]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[INFO]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[INFO]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[INFO]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[INFO]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[INFO]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[INFO]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[INFO]     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[INFO]     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[INFO]     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[INFO]     at java.lang.reflect.Method.invoke (Method.java:498)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[INFO]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

The checkstyle configuration is being used during an integration test phase of a maven archetype build. However all this does is execute a maven build in a new process with the goals "clean verify". 
The cause seems to be the triple '#' used as separators to specify the order of the import groups.

**Comment by romani** [comment]
please run CLI, we do not support maven plugin

**Comment by pgerhard** [comment]
Running the cli directly results in the same error

```zsh
/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/bin/java $RUN_LOCALE \
-jar checkstyle-8.19-all.jar \
-c build/checkstyle/checkstyle.xml \
oss-module-project/src/main/java/root/App.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - The value of attribute "value" associated with an element type "property" must not contain the '<' character.:21:44
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:450)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:395)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:357)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:315)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:180)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
Caused by: org.xml.sax.SAXParseException; systemId: file:/Users/pgerhard/DevTools/gitrepo/ossrh-multi-module-archetype/target/test-classes/projects/it-basic/project/oss-module/build/checkstyle/checkstyle.xml; lineNumber: 21; columnNumber: 44; The value of attribute "value" associated with an element type "property" must not contain the '<' character.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanAttributeValue(XMLScanner.java:944)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanAttribute(XMLDocumentFragmentScannerImpl.java:1548)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1315)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:84)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:197)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:443)
	... 5 more
Checkstyle ends with 1 errors.
```

**Comment by rnveach** [comment]
I am able to run the config with no issues, so I can't reproduce it.

````
$ cat TestClass.java
public class TestClass {
    void method() {
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <property name="severity" value="warning"/>

    <property name="fileExtensions" value="java, properties, xml"/>

    <!-- Checks for whitespace                               -->
    <!-- See http://checkstyle.sf.net/config_whitespace.html -->
    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>

    <module name="TreeWalker">
        <module name="CustomImportOrder">
            <property name="sortImportsInGroupAlphabetically" value="true"/>
            <property name="separateLineBetweenGroups" value="true"/>
            <property name="customImportOrderRules"
                      value="STATIC###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE###STANDARD_JAVA_PACKAGE"/>
        </module>
    </module>
</module>

$ java -jar checkstyle-8.27-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

**Comment by rnveach** [comment]
> `lineNumber: 21; columnNumber: 44; The value of attribute "value" associated with an element type "property" must not contain the '<' character.`

From what I can tell your config must not be parsable and that is where it is failing. I would look at the line/column it gives and look for a missing `"` or `>` or such. Also check for sanitization like `>` in a string.
https://stackoverflow.com/questions/41089496/the-value-of-attribute-value-associated-with-an-element-type-property-must-n

**Comment by pgerhard** [comment]
I feel a little like an idiot right now... I found the issue

Maven Archetypes are Velocity templates and it turns out Velocity was breaking the XML by attempting to parse the separator. It turned the configuration into 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <property name="severity" value="warning"/>

    <property name="fileExtensions" value="java, properties, xml"/>

    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>

    <module name="TreeWalker">
        <module name="CustomImportOrder">
            <property name="sortImportsInGroupAlphabetically" value="true"/>
            <property name="separateLineBetweenGroups" value="true"/>
            <property name="customImportOrderRules"
                      value="STATIC        </module>
    </module>
</module>
```

Which is obviously not valid XML. I am sorry for bothering you with this
