### ISSUE TITLE
Exception when using SuppressWarningsHolder with @SuppressWarnings as an annotation property (e.g. in Lombok)

### ISSUE THREAD

**Issue by mjustin** [checkstyle/checkstyle#7522]
Check documentation: https://checkstyle.sourceforge.io/config_annotation.html#SuppressWarningsHolder

```
$ curl -s https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.10/lombok-1.18.10.jar -O

$ javac -cp lombok-1.18.10.jar Test.java

$ cat Test.java 
import lombok.Getter;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.List;

public class Test {
    @Getter(onMethod_ = @SuppressWarnings("unchecked")) // This causes the exception
    private final List<String> problematicProperty = List.of();

    @Getter(onMethod_ = @Deprecated(forRemoval = true)) // No problems with this one
    private final List<String> workingProperty = List.of();

    @CustomAnnotation(@SuppressWarnings("unchecked")) // This also causes the exception
    private List<String> nonLombokProblematicField;

    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    public @interface CustomAnnotation {
        SuppressWarnings value();
    }
}

$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="SuppressWarningsFilter" />
    <module name="TreeWalker">
        <module name="SuppressWarningsHolder" />
    </module>
</module>

$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.29-all.jar -c config.xml Test.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Test.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:304)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:400)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:324)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
Caused by: java.lang.IllegalArgumentException: Unexpected container AST: ANNOTATION_MEMBER_VALUE_PAIR[6x12]
	at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.getAnnotationTarget(SuppressWarningsHolder.java:406)
	at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.visitToken(SuppressWarningsHolder.java:296)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:342)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:449)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:283)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:161)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
	... 5 more
Checkstyle ends with 1 errors.
```

---------------

When using Lombok's `@Getter(onMethod_ = @SuppressWarnings("unchecked"))` approach to suppress warnings on a generated getter, Checkstyle will throw an exception when `SuppressWarningsHolder` is specified in the config.  No exception is thrown if `SuppressWarningsHolder` is not configured, or for other types of annotations specified in `onMethod_`.

Note that this problem is actually more general than just a Lombok issue.  This error occurs anywhere the `@SuppressWarnings` annotation is used as the value for an annotation property.  I included an example of this in my test class.

I would expect Checkstyle to not error in this situation.  It should ignore `@SuppressWarnings` annotations that are not actually annotating program elements, but that are instead properties for other annotations.

The above example was performed against Java 11.

**Comment by romani** [comment]
method does not expect such AST: 
https://github.com/checkstyle/checkstyle/blob/baaac1625cfd2930c20855c3c7bfb9f50c9cd332/src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java#L396-L409

to expect syntax like this, very rare syntax, but as it is compilable we need to support it.

We need to update to check that it is NOT a annotation as value.
https://github.com/checkstyle/checkstyle/blob/baaac1625cfd2930c20855c3c7bfb9f50c9cd332/src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java#L293

**Comment by romani** [comment]
@AmrDeveloper, please help us resolve this issue

**Comment by AmrDeveloper** [comment]
i'm on it

**Comment by romani** [comment]
Fix is merged.
