### ISSUE TITLE
IllegalStateException: expecting RCURLY, found 'null'

### ISSUE THREAD

**Issue by petr-nehez** [checkstyle/checkstyle#7552]
Unfortunately I cannot give you full decription of the issue and data for it, it has occurred only once in IntelliJ 2019.3.2.
It could happen due to some some unexpected state of file.

Plugin version: `5.35.5`
CheckStyle version: `8.28`

This is the error from IntelliJ's EventLog:
```
The scan failed due to a parse error: IllegalStateException occurred while parsing file /home/petr/work/src/tipsport/tipsys2/commons/src/main/java/cz/tipsport/common/tools/JsonTools.java. 
Root cause: expecting RCURLY, found 'null' 
/home/petr/work/src/tipsport/tipsys2/commons/src/main/java/cz/tipsport/common/tools/JsonTools.java:119:1: expecting RCURLY, found 'null'   
at antlr.Parser.match(Parser.java:211)   
at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2564)   
at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)   
at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)   
at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)   
at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)   
at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)   
at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:159)   
at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)   
at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)   
at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)   
at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)   
at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:76)   
at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)   
at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)   
at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)   
at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)   
at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:43)   
at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$7(ScanFiles.java:197)   
at java.base/java.util.Optional.map(Optional.java:265)   
at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:197)   
at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:156)   
at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:78)   
at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:32)   
at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:274)   
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)   
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)   
at java.base/java.lang.Thread.run(Thread.java:834) 
```

**Comment by romani** [comment]
It is parse error, we need input java file `home/petr/work/src/tipsport/tipsys2/commons/src/main/java/cz/tipsport/common/tools/JsonTools.java`, version of checkstyle, ... All details that template try force you to share

**Comment by petr-nehez** [comment]
I don't have the version which has caused the error.
The current version is not causing the problem. I remember I was moving a method from one class to `JsonTools`.

**Comment by romani** [comment]
Please open issue on Idea plugin. Checkstyle validation need to be executed only on compilable java files.
It is limitation by design, plugins need to handle this.

**Comment by petr-nehez** [comment]
Sorry, I didn't realize that I should report it under plugin repo.
