### ISSUE TITLE
Update AbstractChecks to log DetailAST - IllegalCatch

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7732]
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on IllegalCatch.

**Comment by romani** [comment]
This check already reports violation on AST node:
https://github.com/checkstyle/checkstyle/blob/34615b4a3c8f8826fb6961ed9a35449e73c16a2f/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java#L187

**Comment by sulkykookie** [comment]
I'm on it.

**Comment by sulkykookie** [comment]
I need help with getting Xpath of ```java.lang.RuntimeException``` in the following code:
```
package org.checkstyle.suppressionxpathfilter.illegalcatch;

public class SuppressionXpathRegressionIllegalCatchTwo {
    public void methodOne() {
        try {
            foo();
        } catch (java.sql.SQLException e) {
        }
    }

    private void foo() throws java.sql.SQLException {
    }

    public void methodTwo() {
        try {
        } catch (java.lang.RuntimeException e) { // warn
        }
    }
}
```

The corresponding AST is:
```
PACKAGE_DEF -> package [1:0]
|--ANNOTATIONS -> ANNOTATIONS [1:45]
|--DOT -> . [1:45]
|   |--DOT -> . [1:22]
|   |   |--DOT -> . [1:11]
|   |   |   |--IDENT -> org [1:8]
|   |   |   `--IDENT -> checkstyle [1:12]
|   |   `--IDENT -> suppressionxpathfilter [1:23]
|   `--IDENT -> illegalcatch [1:46]
`--SEMI -> ; [1:58]
CLASS_DEF -> CLASS_DEF [5:0]
|--MODIFIERS -> MODIFIERS [5:0]
|   `--LITERAL_PUBLIC -> public [5:0]
|--LITERAL_CLASS -> class [5:7]
|--IDENT -> SuppressionXpathRegressionIllegalCatchTwo [5:13]
`--OBJBLOCK -> OBJBLOCK [5:55]
    |--LCURLY -> { [5:55]
    |--METHOD_DEF -> METHOD_DEF [6:4]
    |   |--MODIFIERS -> MODIFIERS [6:4]
    |   |   `--LITERAL_PUBLIC -> public [6:4]
    |   |--TYPE -> TYPE [6:11]
    |   |   `--LITERAL_VOID -> void [6:11]
    |   |--IDENT -> methodOne [6:16]
    |   |--LPAREN -> ( [6:25]
    |   |--PARAMETERS -> PARAMETERS [6:26]
    |   |--RPAREN -> ) [6:26]
    |   `--SLIST -> { [6:28]
    |       |--LITERAL_TRY -> try [7:8]
    |       |   |--SLIST -> { [7:12]
    |       |   |   |--EXPR -> EXPR [8:15]
    |       |   |   |   `--METHOD_CALL -> ( [8:15]
    |       |   |   |       |--IDENT -> foo [8:12]
    |       |   |   |       |--ELIST -> ELIST [8:16]
    |       |   |   |       `--RPAREN -> ) [8:16]
    |       |   |   |--SEMI -> ; [8:17]
    |       |   |   `--RCURLY -> } [9:8]
    |       |   `--LITERAL_CATCH -> catch [9:10]
    |       |       |--LPAREN -> ( [9:16]
    |       |       |--PARAMETER_DEF -> PARAMETER_DEF [9:25]
    |       |       |   |--MODIFIERS -> MODIFIERS [9:25]
    |       |       |   |--TYPE -> TYPE [9:25]
    |       |       |   |   `--DOT -> . [9:25]
    |       |       |   |       |--DOT -> . [9:21]
    |       |       |   |       |   |--IDENT -> java [9:17]
    |       |       |   |       |   `--IDENT -> sql [9:22]
    |       |       |   |       `--IDENT -> SQLException [9:26]
    |       |       |   `--IDENT -> e [9:39]
    |       |       |--RPAREN -> ) [9:40]
    |       |       `--SLIST -> { [9:42]
    |       |           `--RCURLY -> } [10:8]
    |       `--RCURLY -> } [11:4]
    |--METHOD_DEF -> METHOD_DEF [13:4]
    |   |--MODIFIERS -> MODIFIERS [13:4]
    |   |   `--LITERAL_PRIVATE -> private [13:4]
    |   |--TYPE -> TYPE [13:12]
    |   |   `--LITERAL_VOID -> void [13:12]
    |   |--IDENT -> foo [13:17]
    |   |--LPAREN -> ( [13:20]
    |   |--PARAMETERS -> PARAMETERS [13:21]
    |   |--RPAREN -> ) [13:21]
    |   |--LITERAL_THROWS -> throws [13:23]
    |   |   `--DOT -> . [13:38]
    |   |       |--DOT -> . [13:34]
    |   |       |   |--IDENT -> java [13:30]
    |   |       |   `--IDENT -> sql [13:35]
    |   |       `--IDENT -> SQLException [13:39]
    |   `--SLIST -> { [13:52]
    |       `--RCURLY -> } [14:4]
    |--METHOD_DEF -> METHOD_DEF [16:4]
    |   |--MODIFIERS -> MODIFIERS [16:4]
    |   |   `--LITERAL_PUBLIC -> public [16:4]
    |   |--TYPE -> TYPE [16:11]
    |   |   `--LITERAL_VOID -> void [16:11]
    |   |--IDENT -> methodTwo [16:16]
    |   |--LPAREN -> ( [16:25]
    |   |--PARAMETERS -> PARAMETERS [16:26]
    |   |--RPAREN -> ) [16:26]
    |   `--SLIST -> { [16:28]
    |       |--LITERAL_TRY -> try [17:8]
    |       |   |--SLIST -> { [17:12]
    |       |   |   `--RCURLY -> } [18:8]
    |       |   `--LITERAL_CATCH -> catch [18:10]
    |       |       |--LPAREN -> ( [18:16]
    |       |       |--PARAMETER_DEF -> PARAMETER_DEF [18:26]
    |       |       |   |--MODIFIERS -> MODIFIERS [18:26]
    |       |       |   |--TYPE -> TYPE [18:26]
    |       |       |   |   `--DOT -> . [18:26]
    |       |       |   |       |--DOT -> . [18:21]
    |       |       |   |       |   |--IDENT -> java [18:17]
    |       |       |   |       |   `--IDENT -> lang [18:22]
    |       |       |   |       `--IDENT -> RuntimeException [18:27]
    |       |       |   `--IDENT -> e [18:44]
    |       |       |--RPAREN -> ) [18:45]
    |       |       `--SLIST -> { [18:47]
    |       |           `--RCURLY -> } [19:8]
    |       `--RCURLY -> } [20:4]
    `--RCURLY -> } [21:0]
```

My guess of the correct way to get ```java.lang.RuntimeException``` would be:
```
"/CLASS_DEF[./IDENT[@text='SupressionXpathRegressionIllegalCatchOne']]/OBJBLOCK"
    + "/METHOD_DEF[./IDENT[@text='methodTwo']]/SLIST"
    + "/LITERAL_TRY/LITERAL_CATCH/PARAMETER_DEF"
    + "/TYPE[@text='java.lang.RuntimeException']"
```

Am I correct?

**Comment by sulkykookie** [comment]
Can I get help with this? I'm getting this while doing ```mvn clean verify```
```
[ERROR] Failures:
[ERROR]   XpathRegressionIllegalCatchTest.testOne:59->AbstractXpathTestSupport.runVerifications:209->AbstractXpathTestSupport.verifyXpathQueries:125 Generated queries do not match expected ones ==>
expected: <[/CLASS_DEF[./IDENT[@text='SupressionXpathRegressionIllegalCatchOne']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='foo']]/SLIST/LITERAL_TRY/LITERAL_CATCH]> 
but was: <[]>
```
The code is:
```
package org.checkstyle.suppressionxpathfilter.illegalcatch;

public class SuppressionXpathRegressionIllegalCatchOne {
	public void foo() {
		try {
		} catch (Exception e) { // warn
		}
	}
}
```

The AST is:
```
PACKAGE_DEF -> package [1:0]
|--ANNOTATIONS -> ANNOTATIONS [1:45]
|--DOT -> . [1:45]
|   |--DOT -> . [1:22]
|   |   |--DOT -> . [1:11]
|   |   |   |--IDENT -> org [1:8]
|   |   |   `--IDENT -> checkstyle [1:12]
|   |   `--IDENT -> suppressionxpathfilter [1:23]
|   `--IDENT -> illegalcatch [1:46]
`--SEMI -> ; [1:58]
CLASS_DEF -> CLASS_DEF [3:0]
|--MODIFIERS -> MODIFIERS [3:0]
|   `--LITERAL_PUBLIC -> public [3:0]
|--LITERAL_CLASS -> class [3:7]
|--IDENT -> SuppressionXpathRegressionIllegalCatchOne [3:13]
`--OBJBLOCK -> OBJBLOCK [3:55]
    |--LCURLY -> { [3:55]
    |--METHOD_DEF -> METHOD_DEF [4:1]
    |   |--MODIFIERS -> MODIFIERS [4:1]
    |   |   `--LITERAL_PUBLIC -> public [4:1]
    |   |--TYPE -> TYPE [4:8]
    |   |   `--LITERAL_VOID -> void [4:8]
    |   |--IDENT -> foo [4:13]
    |   |--LPAREN -> ( [4:16]
    |   |--PARAMETERS -> PARAMETERS [4:17]
    |   |--RPAREN -> ) [4:17]
    |   `--SLIST -> { [4:19]
    |       |--LITERAL_TRY -> try [5:2]
    |       |   |--SLIST -> { [5:6]
    |       |   |   `--RCURLY -> } [6:2]
    |       |   `--LITERAL_CATCH -> catch [6:4]
    |       |       |--LPAREN -> ( [6:10]
    |       |       |--PARAMETER_DEF -> PARAMETER_DEF [6:11]
    |       |       |   |--MODIFIERS -> MODIFIERS [6:11]
    |       |       |   |--TYPE -> TYPE [6:11]
    |       |       |   |   `--IDENT -> Exception [6:11]
    |       |       |   `--IDENT -> e [6:21]
    |       |       |--RPAREN -> ) [6:22]
    |       |       `--SLIST -> { [6:24]
    |       |           `--RCURLY -> } [7:2]
    |       `--RCURLY -> } [8:1]
    `--RCURLY -> } [9:0]


```

**Comment by sulkykookie** [comment]
Can I get help with the diff file? I'm getting this:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  55.658 s
[INFO] Finished at: 2020-03-18T14:38:40+05:30
[INFO] ------------------------------------------------------------------------
Starting diff report generation ...
Error: Unable to access jarfile C:\Users\Shrey\Desktop\Checkstyle
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at diff.executeCmd(diff.groovy:353)
        at diff.executeCmd(diff.groovy:347)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at diff$_generateDiffReport_closure3.doCall(diff.groovy:235)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at diff.generateDiffReport(diff.groovy:218)
        at diff$generateDiffReport$14.callCurrent(Unknown Source)
        at diff.run(diff.groovy:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by strkkk** [comment]
@sulkykookie try to switch your repo to master branch first

**Comment by sulkykookie** [comment]
> @sulkykookie try to switch your repo to master branch first

**Doesn't work.**
Also I'm getting this error while diff.groovy fetches checkstyle/springframework repo:
```
error: unable to create file spring-test/src/test/java/org/springframework/test/context/configuration/ContextConfigurationWithPropertiesExtendingPropertiesAndInheritedLoaderTests-context.properties: Filename too long
```
for a few files and it results in:
```
fatal: Could not reset index file to revision 'v4.1.6.RELEASE'.
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at launch.executeCmd(launch.groovy:322)
        at launch$executeCmd$11.callCurrent(Unknown Source)
        at launch.cloneRepository(launch.groovy:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at launch$_generateCheckstyleReport_closure2.doCall(launch.groovy:92)
        at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at launch.generateCheckstyleReport(launch.groovy:70)
        at launch$generateCheckstyleReport$1.callCurrent(Unknown Source)
        at launch.run(launch.groovy:10)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at diff.executeCmd(diff.groovy:353)
        at diff.executeCmd(diff.groovy:347)
        at diff$executeCmd$10.callCurrent(Unknown Source)
        at diff.generateCheckstyleReport(diff.groovy:187)
        at diff$generateCheckstyleReport$6.callCurrent(Unknown Source)
        at diff.run(diff.groovy:26)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by rnveach** [comment]
> error: unable to create file spring-test/src/test/java/org/springframework/test/context/configuration/ContextConfigurationWithPropertiesExtendingPropertiesAndInheritedLoaderTests-context.properties: Filename too long

If you are on Windows or another OS that can't have deeply nested files, you must use the `shortFilePaths` argument. Please see documentation.

**Comment by sulkykookie** [comment]
> > error: unable to create file spring-test/src/test/java/org/springframework/test/context/configuration/ContextConfigurationWithPropertiesExtendingPropertiesAndInheritedLoaderTests-context.properties: Filename too long
> 
> If you are on Windows or another OS that can't have deeply nested folders, you must use the `shortFilePaths` argument. Please see documentation.

Okay.
Also what about the ```Error: Unable to access jarfile C:\Users\Shrey\Desktop\Checkstyle``` error?

**Comment by rnveach** [comment]
> what about the Error: Unable to access jarfile C:\Users\Shrey\Desktop\Checkstyle error?

This one I am unsure about. Did the previous maven command finish and build the jar? Can you locate jar in where it seems to be looking? You have read access to the jar?

> Starting diff report generation ...

https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L217
After this is a command execution for the JAR and it is executed inside `executeCmd`.
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L347
I would change this to print out the command it is executing to help us debug further.

**Comment by sulkykookie** [comment]
> > what about the Error: Unable to access jarfile C:\Users\Shrey\Desktop\Checkstyle error?
> 
> This one I am unsure about. Did the previous maven command finish and build the jar? Can you locate jar in where it seems to be looking? You have read access to the jar?
> 
> > Starting diff report generation ...
> 
> https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L217
> After this is a command execution for the JAR and it is executed inside `executeCmd`.
> https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L347
> I would change this to print out the command it is executing to help us debug further.

I installed linux, and it worked perfectly there.

**Comment by rnveach** [comment]
Fix was merged
