### ISSUE TITLE
NoWhitespaceAfter: Allow for use of DO_WHILE, LITERAL_CATCH, LITERAL_FOR, LITERAL_IF, and LITERAL_WHILE 

### ISSUE THREAD

**Issue by 4tuw2tuv0** [checkstyle/checkstyle#8312]
https://checkstyle.org/checks/whitespace/nowhitespaceafter.html#NoWhitespaceAfter

```
/tmp/checkstyle
❯ javac MyClass.java

/tmp/checkstyle
❯ cat checkstyle.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
  "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="NoWhitespaceAfter">
      <property name="allowLineBreaks" value="false"/>
      <property name="tokens" value="DO_WILE,LITERAL_WHILE,LITERAL_IF,LITERAL_FOR,LITERAL_SWITCH,
                                                  LITERAL_SYNCHRONIZED,LITERAL_TRY"/>
    </module>
  </module>
</module>

/tmp/checkstyle
❯ cat MyClass.java
package com.acme;

import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.temporal.ChronoUnit;

public class MyClass {

  public static void main( String ... args ) {

    // Common:

    // DO_WILE
    do {
      System.out.println( "Hello!" );
    } while( false );

    // LITERAL_WHILE
    while( args.length < -1 ) {
      System.out.println( "Hello!" );
    }

    // LITERAL_IF
    if( args.length == 0 )
      System.out.println( "No args." );

    // LITERAL_FOR
    for( String arg : args )
      System.out.println( "Arg: " + arg );

    // LITERAL_SWITCH
    switch( ChronoUnit.FOREVER ) {
      default:
        break;
    }

    // LITERAL_SYNCHRONIZED
    synchronized( new Object() ) {
      // nothing
    }

    // LITERAL_TRY / LITERAL_CATCH
    try( Reader reader = Files.newBufferedReader( Paths.get( "here.txt" ) ) ) {
      throw new Exception( "Something's fishy." );
    } catch( Exception ex ) {
      System.out.println( ex );
    } finally {
      System.out.println( "Juste one more thing!" );
    }
    try {
      throw new Exception( "Something's fishy again." );
    } catch( Exception ex ) {
      System.out.println( ex );
    } finally {
      System.out.println( "That's all folks!" );
    }

  }

}

/tmp/checkstyle
❯ RUN_LOCALE="-Duser.language=en -Duser.country=US"

/tmp/checkstyle
❯ java $RUN_LOCALE -jar checkstyle-8.41-all.jar -c checkstyle.xml MyClass.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - 
     Token "LITERAL_SWITCH" was not found in Acceptable tokens list in check
com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:482)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:405)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:332)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "LITERAL_SWITCH" 
   was not found in Acceptable tokens list in check
com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck
	at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:221)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:131)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:477)
	... 5 more
Checkstyle ends with 1 errors.
```
---
**The expectation is that no errors are reported**
We would like to add more tokens to check in NoWhitespaceAfter:
 * at the very least, DO_WHILE, LITERAL_CATCH, LITERAL_FOR, LITERAL_IF, and LITERAL_WHILE,
 * maybe align available tokens for NoWhitespaceAfter, NoWhitespaceBefore and WhitespaceAround,
 * maybe don't restrict at all the available token for these checkers.

The purpose of the feature is to check there is **no** space after these tokens, so to answer @romani, WhitespaceAround is not adapted.

The case of LITTERAL_TRY can be tricky. Is there a way to constrain the format of the two displayed try / catch, one with resources and the second without?

------

I routinely want to disallow the use of space between the listed tokens and their following open parenthesis but, currently, there's no means to do so.

#2803/#3649 added this ability for LITERAL_SYNCHRONIZED and the addition for these tokens would be more or less the same change.

**Comment by romani** [comment]
please follow https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

imagine it is just bug and please report issue as described at https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by romani** [comment]
in checkstyle we use another Check for this - https://checkstyle.org/config_whitespace.html#WhitespaceAround .

```
$ git diff
diff --git a/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java b/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
index c95cdd2..df29984 100644
--- a/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
+++ b/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
@@ -175,7 +175,7 @@ public class Checker extends AutomaticBean implements MessageDispatcher, RootMod
         fileSetChecks.clear();
         beforeExecutionFileFilters.clear();
         filters.clear();
-        if (cacheFile != null) {
+        if(cacheFile != null) {
             try {
                 cacheFile.persist();
             }
$mvn compile antrun:run@ant-phase-verify
...
[INFO] --- maven-antrun-plugin:3.0.0:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks
[INFO]      [echo] Checkstyle started (checkstyle_checks.xml): 07/02/2021 02:49:28 PM
[INFO] [checkstyle] Running Checkstyle  on 1402 files
[ERROR] [checkstyle] [ERROR] src/main/java/com/puppycrawl/tools/checkstyle/Checker.java:
   178:9: 'if' is not followed by whitespace. [WhitespaceAround]
[INFO]      [echo] Checkstyle finish
```

**Comment by b-charles** [comment]
Hello,

Following the bug report template:
```
/tmp/checkstyle
❯ javac MyClass.java

/tmp/checkstyle
❯ cat checkstyle.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
  "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">

  <module name="TreeWalker">

    <module name="NoWhitespaceAfter">
      <property name="allowLineBreaks" value="false"/>
      <property name="tokens" value="DO_WILE,LITERAL_WHILE,LITERAL_IF,LITERAL_FOR,LITERAL_SWITCH,LITERAL_SYNCHRONIZED,LITERAL_TRY"/>
    </module>

  </module>

</module>

/tmp/checkstyle
❯ cat MyClass.java
package com.acme;

import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.temporal.ChronoUnit;

public class MyClass {

  public static void main( String ... args ) {

    // Common:

    // DO_WILE
    do {
      System.out.println( "Hello!" );
    } while( false );

    // LITERAL_WHILE
    while( args.length < -1 ) {
      System.out.println( "Hello!" );
    }

    // LITERAL_IF
    if( args.length == 0 )
      System.out.println( "No args." );

    // LITERAL_FOR
    for( String arg : args )
      System.out.println( "Arg: " + arg );

    // LITERAL_SWITCH
    switch( ChronoUnit.FOREVER ) {
      default:
        break;
    }

    // LITERAL_SYNCHRONIZED
    synchronized( new Object() ) {
      // nothing
    }

    // LITERAL_TRY / LITERAL_CATCH
    try( Reader reader = Files.newBufferedReader( Paths.get( "here.txt" ) ) ) {
      throw new Exception( "Something's fishy." );
    } catch( Exception ex ) {
      System.out.println( ex );
    } finally {
      System.out.println( "Juste one more thing!" );
    }
    try {
      throw new Exception( "Something's fishy again." );
    } catch( Exception ex ) {
      System.out.println( ex );
    } finally {
      System.out.println( "That's all folks!" );
    }

  }

}

/tmp/checkstyle
❯ RUN_LOCALE="-Duser.language=en -Duser.country=US"

/tmp/checkstyle
❯ java $RUN_LOCALE -jar checkstyle-8.41-all.jar -c checkstyle.xml MyClass.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "LITERAL_SWITCH" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:482)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:405)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:332)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "LITERAL_SWITCH" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck
	at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:221)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:131)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:477)
	... 5 more
Checkstyle ends with 1 errors.
```
---
**The expectation is that no errors are reported**
We would like to add more tokens to check in NoWhitespaceAfter:
 * at the very least, DO_WHILE, LITERAL_CATCH, LITERAL_FOR, LITERAL_IF, and LITERAL_WHILE,
 * maybe align available tokens for NoWhitespaceAfter, NoWhitespaceBefore and WhitespaceAround,
 * maybe don't restrict at all the available token for these checkers.

The purpose of the feature is to check there is **no** space after these tokens, so to answer @romani, WhitespaceAround is not adapted.

The case of LITTERAL_TRY can be tricky. Is there a way to constrain the format of the two displayed try / catch, one with resources and the second without?

**Comment by romani** [comment]
@nrmancuso , I am ok to aprove this issue.

**Comment by nrmancuso** [comment]
This issue is too broad and ambiguous, we should utilize the new sub-issue feature to create an issue for each token, with expected good code/ code that should ave violations.

**Comment by romani** [comment]
just extension of token and no changes to defaults it is ok.
So users can do whatever they want if there is such need.

**Comment by ZaheerAhmadDev** [comment]
I am on it.

**Comment by romani** [comment]
Fix is merged
