### ISSUE TITLE
Indentation check throws NPE when used on Java14 enhanced instanceof syntax

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8351]
Child of #8391 
Check documentation: https://checkstyle.org/config_misc.html#Indentation
Identified at #8294 

```
➜  initial-pattern-def-grammar /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 TestClass.java
Note: TestClass.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
➜  initial-pattern-def-grammar cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">

  <module name="JavadocPackage"/>
  <module name="TreeWalker">
	<module name="Indentation"></module>
  </module>
</module>
➜  initial-pattern-def-grammar cat TestClass.java 
public class TestClass {
    {
        Object obj = "string";
        if (obj instanceof String str) { }
    }
}
➜  initial-pattern-def-grammar java $RUN_LOCALE -jar ~/IdeaProjects/checkstyle/target/checkstyle-8.35-SNAPSHOT-all.jar -c config.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.indentation.MemberDefHandler.checkIndentation(MemberDefHandler.java:47)
	at com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck.visitToken(IndentationCheck.java:505)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
	... 5 more
Checkstyle ends with 1 errors.
```
---------------
I expect this code to be successfully parsed by checkstyle. The issue is that since the `VARIABLE_DEF` child of the `PATTERN_DEF` AST has no modifiers AST (unlike a typical variable definition), when `checkIndentation()` tries to reference the modifiers AST, it is null.

**Comment by nmancus1** [comment]
Since we have changed the implementation of #8294, closed that PR, and this check no longer causes null pointer exception with the new PR #8401, I am closing this issue.

**Comment by romani** [comment]
please confirm that Check works without false positives on wrapped pattern.

**Comment by nmancus1** [comment]
@romani I closed this because there was no NPE with the new PR #8401, and therefore no issue.  I have opened the simple "vaildation" issue at #8403.  We can close this one.

**Comment by romani** [comment]
Ok to close as it duplicates 8403
