### ISSUE TITLE
Checkstyle reports NPE when parsing nested switch

### ISSUE THREAD

**Issue by damianszczepanik** [checkstyle/checkstyle#837]
With [this PR](https://github.com/sevntu-checkstyle/sevntu.checkstyle/commit/3f13341b98e1b36d9cb65111dbb1bd7bbb2206c7) I introduced new [input file](https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputNestedSwitchCheck.java) that causes `NullPointerException` in Checkstyle when executing`launch.sh` in [checkstyle tester](https://github.com/damianszczepanik/contribution/commit/6dbea700b44e986683869c891814758061207ddb).

```
[INFO] Generating "Checkstyle" report    --- maven-checkstyle-plugin:2.14
[ERROR] Exception occurred during the analysis of file checkstyle-tester\src\main\java\sevntu-checkstyle\sevntu-checks\src\test\resources\com\github\sevntu\checkstyle\checks\design\InputNestedSwitchCheck.java .
java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.coding.FallThroughCheck.isTerminated(FallThroughCheck.java:178)
        at com.puppycrawl.tools.checkstyle.checks.coding.FallThroughCheck.checkSwitch(FallThroughCheck.java:318)
        at com.puppycrawl.tools.checkstyle.checks.coding.FallThroughCheck.isTerminated(FallThroughCheck.java:197)
        at com.puppycrawl.tools.checkstyle.checks.coding.FallThroughCheck.checkSlist(FallThroughCheck.java:225)
        at com.puppycrawl.tools.checkstyle.checks.coding.FallThroughCheck.isTerminated(FallThroughCheck.java:187)
        at com.puppycrawl.tools.checkstyle.checks.coding.FallThroughCheck.visitToken(FallThroughCheck.java:155)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:458)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:551)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:383)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:216)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:271)
        at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:253)
```

and the snipped code that causes this problem is:

```java
package com.github.sevntu.checkstyle.checks.design;

public class InputNestedSwitchCheck {

    private int type;

    public void simple() {
        switch (hashCode()) {
        case 1:
            switch (hashCode()) { // error
            case 1:
            }
        case 2:
            switch (type) { // error
            }
        }
    }
}
```

**Comment by romani** [comment]
merged
