### ISSUE TITLE
super::clone breaks SuperCloneCheck

### ISSUE THREAD

**Issue by nik9000** [checkstyle/checkstyle#8399]
https://checkstyle.org/config_coding.html#SuperClone
https://checkstyle.org/config_coding.html#SuperFinalize

```
/var/tmp $ javac --release 11 A.java
# This only works in Java 11+

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="charset" value="UTF-8" />

  <module name="TreeWalker">
    <module name="SuperCloneCheck" />
  </module>
</module>


/var/tmp $ cat A.java
class A {
  @FunctionalInterface
  public interface CheckedSupplier<R, E extends Exception> {
    R get() throws E;
  }

  public Object clone() {
    CheckedSupplier<Object, CloneNotSupportedException> r = super::clone; // NPE consuming this
    try {
      return r.get();
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
  }
}
 
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-8.34-all.jar -c config.xml YOUR_FILE.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing A.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.coding.AbstractSuperCheck.hasArguments(AbstractSuperCheck.java:142)
	at com.puppycrawl.tools.checkstyle.checks.coding.AbstractSuperCheck.isSuperCall(AbstractSuperCheck.java:106)
	at com.puppycrawl.tools.checkstyle.checks.coding.AbstractSuperCheck.visitToken(AbstractSuperCheck.java:85)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
	... 5 more
Checkstyle ends with 1 errors.

```

---------------

**Describe what you expect in detail.**
I'm unsure if the built in check should pass when you make a reference to the superclass implementation. I was looking at extending `AbstractSuperCheck` to force calling `super.close()` in implementations of `close`. In my case it is normal and common to do stuff like `IOUtils.close(super::close, other, stuff, here);`. So, at least for me, it'd be best if `AbstractSuperCheck` considered a reference to the superclass implementation to pass. Or if it could be configured to do so.

--------------

**Comment by nik9000** [comment]
> I'm unsure if the built in check should pass when you make a reference to the superclass implementation. I was looking at extending `AbstractSuperCheck` to force calling `super.close()` in implementations of `close`. In my case it is normal and common to do stuff like `IOUtils.close(super::close, other, stuff, here);`. So, at least for me, it'd be best if `AbstractSuperCheck` considered a reference to the superclass implementation to pass. Or if it could be configured to do so.

It looks like I was a bit confused. You can't actually call `super.close` when there isn't a concrete superclass implementation. And checkstyle can't really check for that because it doesn't have type information. So I can't get what I was looking for anyway. But the NPE still stands, I guess.

**Comment by pbludov** [comment]
> But the NPE still stands, I guess.

If this is valid Java code successfully compiled by javac, then Checkstyle should be able to process it.

**Comment by pbludov** [comment]
This bug also affects `SuperFinalizeCheck`

**Comment by romani** [comment]
fix is merged
