### ISSUE TITLE
Specify suppressions through CLI option while executing check

### ISSUE THREAD

**Issue by Fernal73** [checkstyle/checkstyle#8418]
Referenced from: 
https://github.com/checkstyle/checkstyle/issues/8340#issuecomment-654912227

**Is your feature request related to a problem? Please describe.**
The CLI does not have options to specify usage of suppressions file while running the check. This is currently configured in the config file but not exposed to be altered through the command line. The Maven plugin allows this file value to be overridden. 

**Describe the solution you'd like**
The CLI must provide an option to specify suppressions file as a set that can include both Xpath suppressions and regex ones. More than one suppression file can be specified; only one of each type. (This is to match the current configuration in the rules file. Will it be possible to allow more than one  of each type?)

The CLI must be smart enough to recognise the type of suppression file provided.

**Comment by pbludov** [comment]
@Fernal73 Please explain why you are using the CLI interface. I've always thought of the CLI as a hacking tool. For the CI a special tool must be used.

**Comment by Fernal73** [comment]
Why do I use the CLI interface, @pbludov ? Because it's there, because it is quicker than any tool including Ant and because I don't see it as a hacking tool. I'd imagine calling your API directly might be considered that. 

I don't see any other way of generating Xpath suppressions besides the CLI. And I find those very useful. 

Finally , I think CI is overkill for my small, learning project(s) .

**Comment by Fernal73** [comment]
The more pertinent question is why should this option to specify suppressions be added. Should it be added? Or should it remain buried in the config file? What's the motivation for exposing it in the maven plugin goal? Wouldn't the motivation be the same through any other interface? Should multiple suppression files of each type be permitted? Should the config file be updated to allow multiple suppression files of each type be permitted?

**Comment by rnveach** [comment]
> What's the motivation for exposing it in the maven plugin goal? 

We don't control the maven plugin, so we don't know their motivation or thoughts.

>  Should multiple suppression files of each type be permitted? Should the config file allow multiple suppression files of each type?

Users can configure the suppressions however they want. They can do it based on file type or combine everything into 1. They can use as many suppression files as they want to define in the config. We don't limit them in the configuration.

======

Users can specify their suppression file through the config via properties.

See Property expansion.
https://checkstyle.org/config.html#Properties
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L37

You can use this to do what you want. If you need something more, then you need to explain all what you are trying to do at a high level to prevent you from having to keep open issue after issue.

**Comment by Fernal73** [comment]
@rnveach @pbludov @romani 
There appears to be some misunderstanding.
I understood that @romani needed a new issue for the CLI to use Xpath suppressions generated as output.

https://github.com/checkstyle/checkstyle/issues/8340#issuecomment-654899051

Is that no longer the case?

**Comment by Fernal73** [comment]
> 
> Users can configure the suppressions however they want. They can do it based on file type or combine everything into 1. 

I meant regex suppressions versus Xpath suppressions---as types.

**Comment by Fernal73** [comment]
They can use as many suppression files as they want to define in the config. We don't limit them in the configuration.
> 
> ======
> 
> Users can specify their suppression file through the CLI to the config via expansion properties.
> https://checkstyle.org/config.html#Properties
> https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L37
> 

https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.html

https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.html

These allow only one file each. So to configure more, they need to add more instances using the id property to differentiate?

**Comment by rnveach** [comment]
> I understood that @romani needed a new issue for the CLI to use Xpath suppressions generated as output.

Your issue does not mention xpath very much, even in title. I am sure he was saying you could have the CLI generated xpath suppressions saved to a suppression file. Your issue is asking to load a suppression file through CLI.

> So to configure more, they need to add more instances using the id property to differentiate?

You need to declare the module multiple times but with different files. `id` property is really only for modules that create violations. Not ones that suppress violations.

**Comment by Fernal73** [comment]
> > I understood that @romani needed a new issue for the CLI to use Xpath suppressions generated as output.
> 
> Your issue does not mention xpath very much, even in title. I am sure he was saying you could have the CLI generated xpath suppressions saved to a suppression file.
> 
>

Isn't that already available by overloading the -o option in conjunction with the -g switch.

**Comment by Fernal73** [comment]
> > So to configure more, they need to add more instances using the id property to differentiate?
> 
> You need to declare the module multiple times but with different files. `id` property is really only for modules that create violations. Not ones that suppress violations.

I haven't tried this. Haven't felt the need to. I'd assumed it'd be the same as for rules with different configurations.

**Comment by Fernal73** [comment]
>>>>Your issue is asking to load a suppression file through CLI.

As far as I can see, a command line option is an exposing of an internal configuration to the user. 
The Maven plugin exposes suppression files through one of its parameters. Whether you control development of the plugin or not is immaterial. Once users are accustomed to having that option exercised, they will not wish for a reduced version in any other mode of executing Checkstyle. Of course, you can always argue that it can be done through the config file.
That's splitting hairs, IMHO.
If on the other hand, you're arguing that there's not been any demand for this feature from the user community , it's acceptable.
Wrt to Xpath suppressions specifically its generation and use, would you consider that it has been adequately promoted? Given the sparseness of user questions about it on StackOverflow or other developer forums, I don't think so.

**Comment by Fernal73** [comment]
```
FINE: Running Checkstyle with version: 8.34
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - cannot initialize module SuppressionXpathFilter - Unable to parse suppressions-xpath.xml - Premature end of file.
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:482)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:404)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module SuppressionXpathFilter - Unable to parse suppressions-xpath.xml - Premature end of file.
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:125)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:477)
        ... 5 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to parse suppressions-xpath.xml - Premature end of file.
        at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.getSuppressionLoader(SuppressionsLoader.java:292)
        at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadXpathSuppressions(SuppressionsLoader.java:267)
        at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadXpathSuppressions(SuppressionsLoader.java:253)
        at com.puppycrawl.tools.checkstyle.filters.SuppressionXpathFilter.finishLocalSetup(SuppressionXpathFilter.java:576)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:197)
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:120)
        ... 7 more
Caused by: org.xml.sax.SAXParseException; systemId: file:/data/data/com.termux/files/home/LearnJava/Concurrency/suppressions-xpath.xml; lineNumber: 1; columnNumber: 1; Premature end of file.
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1013)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:86)
        at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.getSuppressionLoader(SuppressionsLoader.java:283)
        ... 12 more
Checkstyle ends with 1 errors.

```

If I execute CLI with switch -o and -g with output file the same as the one specified in the SuppressionXPathFilter , the above exception is thrown since the output file overwrites the existing suppression file.
