### ISSUE TITLE
Java 14 Text Blocks Support Check validation: IllegalTokenText

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8576]
Child of #8601
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#IllegalTokenText

From check documentation:
_Checks specified tokens text for matching an illegal pattern. By default no tokens are specified._

```
➜  text-blocks-grammar /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 TestClass.java
Note: TestClass.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
➜  text-blocks-grammar cat config.xml     
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
	<module name="IllegalTokenText">
	  <property name="tokens" value="TEXT_BLOCK_CONTENT"/>
	  <property name="format" value="a href"/>
	</module>
  </module>
</module>
➜  text-blocks-grammar cat TestClass.java 
public class TestClass {
    String hello = """
                Hello, world!
                """;

}
➜  text-blocks-grammar java $RUN_LOCALE -jar ~/IdeaProjects/checkstyle/target/checkstyle-8.36-SNAPSHOT-all.jar -c config.xml TestClass.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "TEXT_BLOCK_CONTENT" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenTextCheck
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:482)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:404)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Token "TEXT_BLOCK_CONTENT" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenTextCheck
	at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:220)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:130)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:477)
	... 5 more
Checkstyle ends with 1 errors.
```

I expect this check to check the content of a text block and report illegal patterns.  We need to add support for `TEXT_BLOCK_CONTENT` to IllegalTokenTextCheck

**Comment by pbludov** [comment]
Fix is merged
