### ISSUE TITLE
Checkstyle fails to parse unusual parameter names

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8650]
Identified at https://github.com/checkstyle/checkstyle/pull/8634#discussion_r468594904
Check documentation: https://checkstyle.sourceforge.io/config_naming.html#ClassTypeParameterName

```
➜  IdeaProjects /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 jdk14/test/langtools/tools/javac/MethodParameters/UncommonParamNames.java
➜  IdeaProjects cat single-module-config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <!-- Here we use simple module to prove that we can parse files -->
    <module name="ClassTypeParameterName"/>
  </module>
</module>
➜  IdeaProjects cat jdk14/test/langtools/tools/javac/MethodParameters/UncommonParamNames.java
/*
 * Copyright (c) 2013, 2016, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * @test
 * @bug 8006582
 * @summary javac should generate method parameters correctly.
 * @modules jdk.jdeps/com.sun.tools.classfile
 * @build MethodParametersTester ClassFileVisitor ReflectionVisitor
 * @compile -parameters UncommonParamNames.java
 * @run main MethodParametersTester UncommonParamNames UncommonParamNames.out
 */

/** Test uncommon parameter names */
class UncommonParamNames {
    public UncommonParamNames(int _x) { }
    public UncommonParamNames(short $1) { }
    public UncommonParamNames(long \u0061) { }
    public UncommonParamNames(char zero\u0000zero\u0000) { }
    public UncommonParamNames(String zero\u0000zero\u0000seven\u0007) { }
    public UncommonParamNames(Object zero\u0000zero\u0000eight\u0008) { }
    public UncommonParamNames(Object aLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongName,
                              Object baLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongName,
                              Object cbaLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongName) { }
    public UncommonParamNames(int a, int ba, int cba, int dcba, int edcba, int fedcba, int gfedcba,
                              int hgfedcba, int ihgfedcba, int jihgfedcba, int kjihgfedcba, int lkjihgfedcba,
                              int mlkjihgfedcba, int nmlkjihgfedcba, int onmlkjihgfedcba, int ponmlkjihgfedcba,
                              int qponmlkjihgfedcba, int rqponmlkjihgfedcba, int srqponmlkjihgfedcba,
                              int tsrqponmlkjihgfedcba, int utsrqponmlkjihgfedcba, int vutsrqponmlkjihgfedcba,
                              int wvutsrqponmlkjihgfedcba, int xwvutsrqponmlkjihgfedcba,
                              int yxwvutsrqponmlkjihgfedcba, int zyxwvutsrqponmlkjihgfedcba) { }

    public void foo(int _x) { }
    public void foo(short $1) { }
    public void foo(long \u0061) { }
    public void foo(char zero\u0000zero\u0000) { }
    public void foo(String zero\u0000zero\u0000seven\u0007) { }
    public void foo(Object zero\u0000zero\u0000eight\u0008) { }
    public void foo(Object aLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongName,
                    Object baLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongName,
                    Object cbaLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongName) { }
    public void foo(int a, int ba, int cba, int dcba, int edcba, int fedcba, int gfedcba,
                    int hgfedcba, int ihgfedcba, int jihgfedcba, int kjihgfedcba, int lkjihgfedcba,
                    int mlkjihgfedcba, int nmlkjihgfedcba, int onmlkjihgfedcba, int ponmlkjihgfedcba,
                    int qponmlkjihgfedcba, int rqponmlkjihgfedcba, int srqponmlkjihgfedcba,
                    int tsrqponmlkjihgfedcba, int utsrqponmlkjihgfedcba, int vutsrqponmlkjihgfedcba,
                    int wvutsrqponmlkjihgfedcba, int xwvutsrqponmlkjihgfedcba,
                    int yxwvutsrqponmlkjihgfedcba, int zyxwvutsrqponmlkjihgfedcba) { }
}
➜  IdeaProjects java -jar /home/nick/IdeaProjects/checkstyle/target/checkstyle-8.36-SNAPSHOT-all.jar -c single-module-config.xml jdk14/test/langtools/tools/javac/MethodParameters/UncommonParamNames.java

Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing jdk14/test/langtools/tools/javac/MethodParameters/UncommonParamNames.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred while parsing file /home/nick/IdeaProjects/jdk14/test/langtools/tools/javac/MethodParameters/UncommonParamNames.java.
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:120)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:149)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
	... 5 more
Caused by: line 38:36: unexpected char: '\'
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:412)
	at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
	at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)
	at antlr.TokenStreamSelector.nextToken(TokenStreamSelector.java:65)
	at antlr.TokenBuffer.fill(TokenBuffer.java:69)
	at antlr.TokenBuffer.LA(TokenBuffer.java:80)
	at antlr.LLkParser.LA(LLkParser.java:52)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.parameterDeclarationList(GeneratedJavaRecognizer.java:4370)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.ctorHead(GeneratedJavaRecognizer.java:4573)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3106)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:3416)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:646)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:561)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:402)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:212)
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:114)
	... 9 more
Checkstyle ends with 1 errors.


```

Checkstyle should be able to parse this file, since it is compilable.

**Comment by nmancus1** [comment]
Once this issue is fixed, we can remove the "UncommonParamNames.java" `BeforeExecutionExclusionFileFilter` from `openjdk14-excluded.files`.

**Comment by nmancus1** [comment]
From https://github.com/checkstyle/checkstyle/issues/8656#issuecomment-898542081:

This issue could be solved by using a technique similar to that of Java itself: 

> A compiler for the Java programming language ("Java compiler") first recognizes Unicode escapes in its input, translating the ASCII characters \u followed by four hexadecimal digits to the UTF-16 code unit (§3.1) for the indicated hexadecimal value, and passing all other characters unchanged. Representing supplementary characters requires two consecutive Unicode escapes. This translation step results in a sequence of Unicode input characters.

_From https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-JavaLetterOrDigit_

We would translate unicode escapes first before further processing. In `JavaParser.java`, we could have an intermediate step before creating the `CharStream` where we handle this translation; or perhaps it would be better to take care of such a translation in `FileText#getText` so that the translation is handled for all of Checkstyle.

**Comment by gianmarcoschifone** [comment]
I'm on it

**Comment by gianmarcoschifone** [comment]
Hi @nrmancuso @romani,
this fix conflicts with AvoidEscapedUnicodeCharactersCheck.
Since Unicode escapes (\uXXXX) are decoded before parsing, the check can no longer see the original escaped sequences and may miss violations.
This creates a mismatch between the parsed (decoded) input and checks that rely on raw source text.
We may need to preserve access to the original input or avoid decoding at this stage.

> From [#8656 (comment)](https://github.com/checkstyle/checkstyle/issues/8656#issuecomment-898542081):
> 
> This issue could be solved by using a technique similar to that of Java itself:
> 
> > A compiler for the Java programming language ("Java compiler") first recognizes Unicode escapes in its input, translating the ASCII characters \u followed by four hexadecimal digits to the UTF-16 code unit (§3.1) for the indicated hexadecimal value, and passing all other characters unchanged. Representing supplementary characters requires two consecutive Unicode escapes. This translation step results in a sequence of Unicode input characters.
> 
> _From https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-JavaLetterOrDigit_
> 
> We would translate unicode escapes first before further processing. In `JavaParser.java`, we could have an intermediate step before creating the `CharStream` where we handle this translation; or perhaps it would be better to take care of such a translation in `FileText#getText` so that the translation is handled for all of Checkstyle.
