### ISSUE TITLE
HiddenFieldCheck throws a NPE on switch expression syntax

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8659]
Child of #8658 
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#HiddenField

_Checks that a local variable or a parameter does not shadow a field that is defined in the same class._

```
➜  src /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 TestClass.java
➜  src cat config.xml                                                                    
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="HiddenField"/>
    </module>
</module>
➜  src cat TestClass.java                                                                
public class TestClass {
    private int x;
    private int y;
    private int z;
    private int a;
    private int b;


    int howMany1(int k) {
        int x = 2; // violation
        switch (k) {
            case 1:
                int y = x + 1; // violation
                x = y;
                break;
            case 2:
                int z = x + 2; // violation
                x = z;
                break;
            case 3:
                int a = x + 3; // violation
                x = a;
                break;
            default:
                int b = x + 4; // violation
                x = b;
        }
        return x;
    }

    int howMany2(int k) {
        int x = 2; // should be violation
        return switch (k) {
            case 1 -> {
                int y = x + 1; // should be violation
                yield y;
            }
            case 2 -> {
                int z = x + 2; // should be violation
                yield z;
            }
            case 3 -> {
                int a = x + 3; // should be violation
                yield a;
            }
            default -> {
                int b = x + 4; // should be violation
                yield b;
            }
        };
    }

}
➜  src java -jar /home/nick/IdeaProjects/checkstyle/target/checkstyle-8.36-SNAPSHOT-all.jar -c config.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.coding.HiddenFieldCheck.processLambda(HiddenFieldCheck.java:295)
        at com.puppycrawl.tools.checkstyle.checks.coding.HiddenFieldCheck.visitToken(HiddenFieldCheck.java:278)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
        ... 5 more
Checkstyle ends with 1 errors.

```
I expect this check to work with switch expressions and not throw a NPE, so we need to update it.

**Comment by esilkensen** [comment]
Fix is merged
