### ISSUE TITLE
UnnecessaryParenthesesCheck throws a NPE on switch expression syntax

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8660]
Child of #8658
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#UnnecessaryParentheses

_Checks if unnecessary parentheses are used in a statement or expression._ 

```
➜  src /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 TestClass.java                               
➜  src cat config.xml                                                                                                   
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="UnnecessaryParentheses"/>
    </module>
</module>
➜  src cat TestClass.java                                                                                               
public class TestClass {

    MathOperation2 tooManyParens(int k) {
        return switch (k) {
            case 1 -> {
                MathOperation2 case5 = (a, b) -> (a + b); // should be violation
                yield case5;
            }
            case (2) -> { // should be violation
                MathOperation2 case6 = (int a, int b) -> (a + b); // should be violation
                yield case6;
            }
            case 3 -> {
                MathOperation2 case7 = (int a, int b) -> {
                    return (a + b); // should be violation
                };
                yield (case7); // should be violation
            }
            default -> {
                MathOperation2 case8 = (int x, int y) -> {
                    return (x + y); // should be violation
                };
                yield case8;
            }
        };
    }

    interface MathOperation2 {
        int operation(int a, int b);
    }

}
➜  src java -jar /home/nick/IdeaProjects/checkstyle/target/checkstyle-8.36-SNAPSHOT-all.jar -c config.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.coding.UnnecessaryParenthesesCheck.isLambdaSingleParameterSurrounded(UnnecessaryParenthesesCheck.java:426)
        at com.puppycrawl.tools.checkstyle.checks.coding.UnnecessaryParenthesesCheck.visitToken(UnnecessaryParenthesesCheck.java:317)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
        ... 5 more
Checkstyle ends with 1 errors.

```
I expect Checkstyle to parse this code and not throw a NPE.

**Comment by esilkensen** [comment]
Fix is merged
