### ISSUE TITLE
VariableDeclarationUsageDistanceCheck throws a NPE on switch expression syntax

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8676]
Child of #8658 
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#VariableDeclarationUsageDistance

_Checks the distance between declaration of variable and its first usage._

```
➜  src /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 TestClass.java                               
➜  src cat config.xml                                                                                                   
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="VariableDeclarationUsageDistance">
            <property name="allowedDistance" value="2"/>
            <property name="validateBetweenScopes" value="true"/>
            <property name="ignoreFinal" value="false"/>
        </module>
    </module>
</module>
➜  src cat TestClass.java                                                                                               
public class TestClass {
    private int a;
    private int b;

    public boolean equals1(Object obj) {
        int i = 1;
        switch (i) {
            case 1:
                int count;
                a = a + b;
                b = a + a;
                count = b;
                break;
            case 2:
            case 3:
            case 4:
            case 5:
            case 6:
        }
        return false;
    }

    public boolean equals2(Object obj) {
        int i = 1;
        switch (i) {
            case 1 -> {
                int count;
                a = a + b;
                b = a + a;
                count = b;
            }
        }
        return false;
    }
}

➜  src java -jar /home/nick/IdeaProjects/checkstyle/target/checkstyle-8.36-SNAPSHOT-all.jar -c config.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck.getFirstNodeInsideSwitchBlock(VariableDeclarationUsageDistanceCheck.java:749)
        at com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck.calculateDistanceBetweenScopes(VariableDeclarationUsageDistanceCheck.java:559)
        at com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck.visitToken(VariableDeclarationUsageDistanceCheck.java:318)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
        ... 5 more
Checkstyle ends with 1 errors.

```
This check throws a NPE, so we need to update it.

**Comment by esilkensen** [comment]
Fix is merged
