### ISSUE TITLE
Sonar violation: Disable access to external entities in XML parsing.

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8768]
Leak of violations from https://github.com/checkstyle/checkstyle/pull/8762 in master
https://sonarcloud.io/organizations/checkstyle/rules?open=java%3AS2755&rule_key=java%3AS2755

from PR where CI is passed:
https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle&pullRequest=8762 - gate is passed, but there were violations.

![image](https://user-images.githubusercontent.com/812984/91511406-6f664a80-e894-11ea-8591-4949835bd145.png)

**Comment by romani** [comment]
unfortunately application of suggected fix for TransformerFactory did not work, there is exception:
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/rivanov/java/github/romani/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java

  at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
  at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
  at com.puppycrawl.tools.checkstyle.meta.MetadataGenerator.dumpMetadata(MetadataGenerator.java:98)
  at com.puppycrawl.tools.checkstyle.meta.MetadataGenerator.generate(MetadataGenerator.java:64)
  at com.puppycrawl.tools.checkstyle.meta.MetadataGeneratorTest.testBasic(MetadataGeneratorTest.java:47)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:567)
  at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
  at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
  at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
  at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
  at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
  at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
  at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
  at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
  at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
  at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
  at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
  at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
  at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
  at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
  at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
  at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
  at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
  at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
  at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
  at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
  at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
  at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
  at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
  at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
  at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
  at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
  at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
  at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
  at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
  at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
  at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.IllegalArgumentException: Unrecognized configuration feature: http://javax.xml.XMLConstants/property/accessExternalDTD
  at net.sf.saxon.Configuration.setConfigurationProperty(Configuration.java:4412)
  at net.sf.saxon.jaxp.SaxonTransformerFactory.setAttribute(SaxonTransformerFactory.java:311)
  at com.puppycrawl.tools.checkstyle.meta.XmlMetaWriter.writeToFile(XmlMetaWriter.java:182)
  at com.puppycrawl.tools.checkstyle.meta.XmlMetaWriter.write(XmlMetaWriter.java:108)
  at com.puppycrawl.tools.checkstyle.meta.JavadocMetadataScraper.finishJavadocTree(JavadocMetadataScraper.java:194)
  at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck.processTree(AbstractJavadocCheck.java:353)
  at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck.visitToken(AbstractJavadocCheck.java:317)
  at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
  at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
  at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
  at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:155)
  at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
  at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
  at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
  ... 67 more
```

so I tried https://stackoverflow.com/questions/27128578/set-feature-accessexternaldtd-in-transformerfactory

**Comment by romani** [comment]
I added new block
`Conditions on New Code. Conditions on New Code apply to all branches and to Pull Requests.`
![image](https://user-images.githubusercontent.com/812984/91512612-3da2b300-e897-11ea-8ade-d88685178bdb.png)

**Comment by romani** [comment]
fix is merged

**Comment by romani** [comment]
fix was reverted due to failure at https://github.com/checkstyle/sonar-checkstyle/pull/318#issuecomment-682614907 .
I will suppress temporarily Sonar violations, but this needs to be after release.

**Comment by romani** [comment]
I did temporal marking them as WONFIX, to resolve in next release

**Comment by agigleux** [comment]
Did you try to use:

```
transformerFactory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, ""); // Compliant
transformerFactory.setAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET, "");
```

to fix the issue on `final TransformerFactory transformerFactory = TransformerFactory.newInstance();`?

I don't see any commit like this whereas this is the recommended way to fix XXE vulnerabilities for TransformerFactory object.

**Comment by romani** [comment]
@agigleux , we moved this code to another project
https://github.com/checkstyle/checkstyle/blob/58bae0f3defcf7ba4a9fa69bed97aadcb35eb2ae/src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaWriter.java#L72-L74

and I do not see any violation on it at https://sonarcloud.io/project/issues?fileUuids=org.checkstyle%3Acheckstyle%3Asrc%2Fmain%2Fjava%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fmeta%2FXmlMetaWriter.java&id=org.checkstyle%3Acheckstyle

but code is the same without disablement of such EXTERNALs, is it false-negaive ?

**Comment by agigleux** [comment]
The expected issues are indeed not reported on your scan but what is surprising is that when I manual scan the CheckStyle code locally with SonarQube 8.5 or on SonarCloud, I can see the 3 XXE issues:

![image](https://user-images.githubusercontent.com/1057037/96739803-7c00ae00-13c0-11eb-97e2-7e4b48370495.png)

How do you trigger the code scan that is uploaded on SonarCloud? Which command is executed?

**Comment by romani** [comment]
@agigleux , thansk a lot for help.

https://github.com/checkstyle/checkstyle/blob/master/.ci/wercker.sh#L27

you can execute it from your local by 
https://github.com/checkstyle/checkstyle/blob/58bae0f3defcf7ba4a9fa69bed97aadcb35eb2ae/wercker.yml#L343

**Comment by nrmancuso** [comment]
@romani added another violation to main description

**Comment by aditimahabole** [comment]
Is there any solution to this ? or we just mark this as false positive.
Please guide me I am also having the same issue
I have used below lines:
 ```
tFactory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, ""); 
tFactory.setAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET, "");
```

still sonarqube issue is comming , I have put this in try catch block because somehow tFactory.setAttribute gives exception so , altough catch is empty and after that I have writtent code 

`
 private static String getStringFromXMLDocument(Document doc, boolean removeHeaderTag) throws TransformerException {
        TransformerFactory tFactory = TransformerFactory.newInstance("assume there is a class here like [com.dev.something]",null);
        try {
	        tFactory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, ""); 
	        tFactory.setAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET, "");
        }catch(Exception e) {
        }
        Transformer transformer = tFactory.newTransformer();
        DOMSource source = new DOMSource(doc);
        StringWriter sw = new StringWriter();
        StreamResult result = new StreamResult(sw);
        if (removeHeaderTag) {
            transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "yes");
        }
        transformer.transform(source, result);
        String xmlString = sw.toString();
        return xmlString;
    }
`
Please guide me.
