### ISSUE TITLE
SuppressWithPlainTextCommentFilter is slow on files with multiple errors

### ISSUE THREAD

**Issue by basinilya** [checkstyle/checkstyle#8807]
Check documentation: https://checkstyle.org/config_filters.html#SuppressWithPlainTextCommentFilter

```
> javac BigJava.java
>

> type ..\checkstyle\checkstyle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">
<!--
    This configuration file was written by the eclipse-cs plugin configuration editor
-->
<!--
    Checkstyle-Configuration: project-local
    Description: none
-->
<module name="Checker">
  <property name="severity" value="warning"/>
  <module name="TreeWalker">
  </module>
  <module name="LineLength">
    <property name="severity" value="warning"/>
    <property name="max" value="120"/>
    <property name="fileExtensions" value="java" />
  </module>
  <module name="SuppressWithPlainTextCommentFilter">
    <property name="offCommentFormat" value="CHECKSTYLE\.OFF\: ([\w\|]+)"/>
    <property name="onCommentFormat" value="CHECKSTYLE\.ON\: ([\w\|]+)"/>
    <property name="checkFormat" value="$1"/>
  </module>
</module>


> type BigJava.java
public interface BigJava {
    int XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0 = 0;
... full file attached
    int XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX2999 = 0;
}


> set "RUN_LOCALE=-Duser.language=en -Duser.country=US"
> java %RUN_LOCALE% -jar checkstyle-8.36-all.jar -c config.xml BigJava.java
Starting audit...
[WARN] C:\11\eclipse-cs-254-bad\src\BigJava.java:3: Line is longer than 120 characters (found 134). [LineLength]
...
[WARN] C:\11\eclipse-cs-254-bad\src\BigJava.java:3002: Line is longer than 120 characters (found 137). [LineLength]
Audit done.
```

---------------

I expect the command above to run in roughly 2 seconds on a mobile 2GHz i7. However, it takes not less than 16 seconds. It becomes a pain when my IDE waits for the checkstyle plugin during the full build.

The filter SuppressWithPlainTextCommentFilter re-reads the file from disk on each error instead of reading it just one time.

I'm willing to create a pull request that will add caching to the filter.

--------------
[BigJava.java.txt](https://github.com/checkstyle/checkstyle/files/5184721/BigJava.java.txt)

**Comment by romani** [comment]
@basinilya, please send a fix

**Comment by basinilya** [comment]
Actually, I'm unable to make all code quality happy. On one hand, I have to call AuditListener.addException from a test case for full coverage and to do that I had to make my AuditListener implementation public. On the other hand, `config/checkstyle_checks.xml` requires a javadoc for the inner class, but then pmd report fails with: 

```
java.lang.Error: Error was thrown while processing src\main\java\com\puppycrawl\tools\checkstyle\filters\SuppressWithPlainTextCommentFilter.
java
        at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:209)
        at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:182)
Caused by: org.opentest4j.AssertionFailedError:
SuppressWithPlainTextCommentFilter's class-level JavaDoc ==> expected: < <javadoc-of-SuppressWithPlainTextCommentFilter> > but was: < <javadoc-of-SuppressWithPlainTextCommentFilter.SuppressionsCache> >
        at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:209)
        at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:182)
```

**Comment by romani** [comment]
Please send PR and we will think what to do.

**Comment by basinilya** [comment]
https://github.com/checkstyle/checkstyle/pull/8820

**Comment by pbludov** [comment]
@basinilya your code is too hackish. This can be done in the same way as [SuppressionCommentFilter](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java#L483) does.

**Comment by basinilya** [comment]
@pbludov Do you mean that the map is not needed and it's sufficient to compare with the file name for the previous accept() call?

**Comment by pbludov** [comment]
> @pbludov Do you mean that the map is not needed and it's sufficient to compare with the file name for the previous accept() call?

Yes, this works for SuppressionCommentFilter.

**Comment by basinilya** [comment]
> Yes, this works for SuppressionCommentFilter.
Okay. But we still need to invalidate the cache entry on fileStarted() because when there's only one checked file in the project it must ber re-read.

**Comment by basinilya** [comment]
Please tell me how to suppress Idea inspections. When I try the `// noinspection` comment, the suppression itself is marked as error by Teamcity https://teamcity.jetbrains.com/viewLog.html?buildId=3116783&buildTypeId=Checkstyle_IdeaInspectionsPullRequest&tab=Inspection

I need Optional.get() to throw NoSuchElementException. I don't want to use orElse.

Also I don't understand why `Checker`  is a forbidden import inside my filter class. I had to use the fully qualified class name, but it's also treated as an error by Idea.

**Comment by strkkk** [comment]
`I need Optional.get() to throw NoSuchElementException. I don't want to use orElse.`
@basinilya you can use `orElseThrow(exceptionSupplier)` instead and pass there exception you want

**Comment by basinilya** [comment]
I don't have access to https://app.wercker.com/checkstyle/checkstyle/runs/build/5f690ff67e996800080f4394 . Why did it fail?

**Comment by strkkk** [comment]
@basinilya it failed sonar quality gate. Reason https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&open=AXSyh1lffqMQB_2Dz1If&pullRequest=8820&resolved=false&severities=MAJOR&sinceLeakPeriod=true

**Comment by basinilya** [comment]
Can I run Sonar locally?

**Comment by romani** [comment]
> Can I run Sonar locally?

not possible for now, we keep profile with all rules in Sonar service.

**Comment by pbludov** [comment]
@basinilya have you tried to replace `SuppressWithPlainTextCommentFilter` with [SuppressWarningsFilter](https://checkstyle.org/config_filters.html#SuppressWarningsFilter) or [SuppressionXpathSingleFilter](https://checkstyle.org/config_filters.html#SuppressionXpathSingleFilter)?

it makes sense to use [SuppressWithPlainTextCommentFilter](https://checkstyle.org/config_filters.html#SuppressWithPlainTextCommentFilter) only for non-java files, as there is no other option.

**Comment by pbludov** [comment]
@romani @strkkk  @rnveach The problem with this issue is that the `Filter` interface has only one method: `accept(AuditEvent event)`. There is no way to perform any initialization or cleanup in the filter.

To solve this problem, @basinilya used an ugly [hack](https://github.com/checkstyle/checkstyle/pull/8820/files#diff-c66b169e2477f5776072a4ac21715b4d1fc2ede559f17668817f1f79eb09efe4R425) that I don't like.

What can be improved here:
* extend the [Filter](https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/api/Filter.html) interface with `fileStarted`/`fileFinished` methods
* add a new `interface FilterWithSomeLifecycle extends Filter` with such methods
* allow a class to implement both `Filter` and `AuditListener`
* add a new interface with `fileStarted`/`fileFinished` methods on top of `AuditListener`

**Comment by basinilya** [comment]
> it makes sense to use [SuppressWithPlainTextCommentFilter](https://checkstyle.org/config_filters.html#SuppressWithPlainTextCommentFilter) only for non-java files, as there is no other option.

This filter won't allow me to control line length warnings.

**Comment by basinilya** [comment]
> What can be improved here
Or you could add getFileContents() to AuditEvent just like in TreeWalkerAuditEvent

**Comment by pbludov** [comment]
> Or you could add getFileContents() to AuditEvent just like in TreeWalkerAuditEvent

This makes sense. Currently, `FileContents` is created in each `AbstractFileSetCheck` descendant. This is redundant, since the file should not change and the result is always the same. This should be done once in the `Checker.processFiles` method.

**Comment by romani** [comment]
I shared thoughts on how to make it without API changes at https://github.com/checkstyle/checkstyle/pull/8820#issuecomment-1870600093

Referenced PR is abandoned, so anybody from web is welcome to fix this issue.

**Comment by Harsh-Agrawal96** [comment]
I see this issue requires to solve the issue [#12242](https://github.com/checkstyle/checkstyle/issues/12242), now I will continue with `#12242 issue.

**Comment by nrmancuso** [comment]
Closed via #16476
