### ISSUE TITLE
NoWhitespaceBeforeCheck: String index out of range (with Java 15 Text Block) when tabs are used

### ISSUE THREAD

**Issue by dodgex** [checkstyle/checkstyle#8849]
https://checkstyle.org/config_whitespace.html#NoWhitespaceBefore

$ javac Main.java
(no output)

$ cat config.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
 "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="severity" value="warning"/>
    <module name="TreeWalker">
        <module name="NoWhitespaceBefore"/>
    </module>
</module>
```

ATTENTION: File contains tabs, 
please use Edit mode of issue to copy content, or download attached file
$ cat [Main.java](https://github.com/checkstyle/checkstyle/files/5268800/Main.java.txt)
```
package checkstyle.bug;

public class Main {

    private void brokenCheck_space_before_tabs() {
        String x = """
            Some Text
 		""";
    }

    private void brokenCheck_space_after_tabs() {
        String x = """
            Some Text
		 """;
    }

    private void brokenCheck_just_tabs() {
        String x = """
            Some Text
		""";
    }
}
```

$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java $RUN_LOCALE -jar checkstyle-8.36.1-all.jar -c checkstyle.xml Main.java
```
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Main.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 18
        at java.lang.String.charAt(Unknown Source)
        at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceBeforeCheck.visitToken(NoWhitespaceBeforeCheck.java:215)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
        ... 5 more
Checkstyle ends with 1 errors.
```

**Comment by strkkk** [comment]
@dodgex Please follow the issue template, this will help to solve your issue

**Comment by dodgex** [comment]
$ javac Main.java
(no output)

/var/tmp $ cat config.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="severity" value="warning"/>
    <module name="TreeWalker">
        <module name="ConstantName"/>
        <module name="LocalVariableName"/>
        <module name="MemberName"/>
        <module name="MethodName"/>
        <module name="PackageName"/>
        <module name="ParameterName"/>
        <module name="StaticVariableName"/>
        <module name="TypeName"/>
        <module name="AvoidStarImport">
            <property name="allowStaticMemberImports" value="true"/>
        </module>
        <module name="IllegalImport"/>
        <module name="RedundantImport"/>
        <module name="UnusedImports">
            <property name="processJavadoc" value="true"/>
        </module>
        <module name="MethodLength"/>
        <module name="ParameterNumber">
            <property name="max" value="8"/>
        </module>
        <module name="EmptyForIteratorPad"/>
        <module name="MethodParamPad"/>
        <module name="NoWhitespaceAfter"/>
        <module name="NoWhitespaceBefore"/>
        <module name="OperatorWrap"/>
        <module name="ParenPad"/>
        <module name="TypecastParenPad"/>
        <module name="WhitespaceAfter"/>
        <module name="WhitespaceAround">
            <property name="tokens" value="ASSIGN,BAND,BAND_ASSIGN,BOR,BOR_ASSIGN,BSR,BSR_ASSIGN,BXOR,BXOR_ASSIGN,COLON,DIV,DIV_ASSIGN,EQUAL,GE,GT,LAND,LCURLY,LE,LITERAL_ASSERT,LITERAL_CATCH,LITERAL_DO,LITERAL_ELSE,LITERAL_FINALLY,LITERAL_FOR,LITERAL_IF,LITERAL_RETURN,LITERAL_SYNCHRONIZED,LITERAL_TRY,LITERAL_WHILE,LOR,LT,MINUS,MINUS_ASSIGN,MOD,MOD_ASSIGN,NOT_EQUAL,PLUS,PLUS_ASSIGN,QUESTION,SL,SLIST,SL_ASSIGN,SR,SR_ASSIGN,STAR,STAR_ASSIGN,LITERAL_ASSERT,TYPE_EXTENSION_AND"/>
        </module>
        <module name="ModifierOrder"/>
        <module name="RedundantModifier"/>
        <module name="AvoidNestedBlocks"/>
        <module name="EmptyBlock"/>
        <module name="LeftCurly"/>
        <module name="NeedBraces"/>
        <module name="RightCurly"/>
        <module name="EmptyStatement"/>
        <module name="EqualsHashCode"/>
        <module name="IllegalInstantiation"/>
        <module name="InnerAssignment"/>
        <module name="MissingSwitchDefault"/>
        <module name="SimplifyBooleanExpression"/>
        <module name="SimplifyBooleanReturn"/>
        <module name="FinalClass"/>
        <module name="HideUtilityClassConstructor"/>
        <module name="InterfaceIsType"/>
        <module name="VisibilityModifier">
            <property name="packageAllowed" value="true"/>
            <property name="protectedAllowed" value="true"/>
        </module>
        <module name="ArrayTypeStyle"/>
        <module name="TodoComment"/>
        <module name="UpperEll"/>
        <module name="GenericWhitespace"/>
        <module name="MissingOverride"/>
        <module name="MissingDeprecated"/>
        <module name="SuppressionCommentFilter" />
    </module>
    <module name="NewlineAtEndOfFile">
        <property name="fileExtensions" value="java,xml,css,less,properties"/>
    </module>
    <module name="Translation"/>
    <module name="FileLength"/>
    <module name="RegexpSingleline">
        <property name="id" value="trailingSpacesCheck"/>
        <property name="format" value="(?&lt;!\*)\s+$|\*\s\s+$"/>
        <property name="message" value="Line has trailing spaces."/>
    </module>
    <module name="RegexpSingleline">
        <property name="format" value="System\.(out)|(err)\.print(ln)?\("/>
        <property name="message" value="Use a proper Logger."/>
    </module>
    <module name="RegexpSingleline">
        <property name="format" value="Logger (logger)|(LOGGER)"/>
        <property name="message" value="Always use private static final Logger LOG."/>
    </module>
    <module name="LineLength">
        <property name="max" value="150"/>
    </module>
</module>
```

$ cat Main.java (please use the file provided in the ZIP as github replaces tabs with spaces)
```
package checkstyle.bug;

import java.text.SimpleDateFormat;
import java.util.Optional;

public class Main {

    public static void main(String[] args) {
    }

    private void workingCheck() {
        String x = """
                 Some Text
                """;
    }

    private void workingCheck_spaces() {
        String x = """
                    Some Text
                """;
    }

    private void workingCheck_no_spaces() {
        String x = """
                            Some Text
                """;
    }

    private void brokenCheck_space_before_tabs() {
        String x = """
                         Some Text
                """;
    }

    private void brokenCheck_space_after_tabs() {
        String x = """
                         Some Text
                """;
    }

    private void brokenCheck_just_tabs() {
        String x = """
                          Some Text
                """;
    }
}
```

$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java $RUN_LOCALE -jar checkstyle-8.36.1-all.jar -c checkstyle.xml Main.java
```
Starting audit...
[WARN] C:\Daten\intellij-projects\checkstyle_bug\Main.java:3:8: Unused import - java.text.SimpleDateFormat. [UnusedImports]
[WARN] C:\Daten\intellij-projects\checkstyle_bug\Main.java:4:8: Unused import - java.util.Optional. [UnusedImports]
[WARN] C:\Daten\intellij-projects\checkstyle_bug\Main.java:17:18: Name 'workingCheck_spaces' must match pattern '^[a-z][a-zA-Z0-9]*$'. [MethodName]
[WARN] C:\Daten\intellij-projects\checkstyle_bug\Main.java:23:18: Name 'workingCheck_no_spaces' must match pattern '^[a-z][a-zA-Z0-9]*$'. [MethodName]
[WARN] C:\Daten\intellij-projects\checkstyle_bug\Main.java:29:18: Name 'brokenCheck_space_before_tabs' must match pattern '^[a-z][a-zA-Z0-9]*$'. [MethodName]
[WARN] C:\Daten\intellij-projects\checkstyle_bug\Main.java:35:18: Name 'brokenCheck_space_after_tabs' must match pattern '^[a-z][a-zA-Z0-9]*$'. [MethodName]
[WARN] C:\Daten\intellij-projects\checkstyle_bug\Main.java:41:18: Name 'brokenCheck_just_tabs' must match pattern '^[a-z][a-zA-Z0-9]*$'. [MethodName]
Audit done.
```

**Comment by dodgex** [comment]
Updated version of the run as the Main.java in previous run got all tabs replaced...

$ java $RUN_LOCALE -jar checkstyle-8.36.1-all.jar -c checkstyle.xml Main.java
```
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Main.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 18
        at java.lang.String.charAt(Unknown Source)
        at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceBeforeCheck.visitToken(NoWhitespaceBeforeCheck.java:215)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
        ... 5 more
Checkstyle ends with 1 errors.

```

**Comment by strkkk** [comment]
@dodgex Please add all this items in first post and cut config and code to minimal that is necessary to reproduce the issue

**Comment by dodgex** [comment]
@strkkk I updated the first post.

**Comment by romani** [comment]
@dodgex, please remove from issue description all reference to maven

**Comment by romani** [comment]
@nmancus1 , please help us to fix issue

**Comment by nmancus1** [comment]
It will be a little while until I can get to this, I have a lot going on right now.  In the meantime, we can discuss what's going on here, and how to best proceed:

Here is the file that was included in the original issue report, modified to be a checkstyle test case, with line numbers added to aid in discussion:

```
➜  nowhitespacebefore git:(issue-8849-nowhitespacebefore) ✗ cat -n InputNoWhitespaceBeforeTextBlocksTabIndent.java 
     1  //non-compiled with javac: Compilable with Java14
     2  package com.puppycrawl.tools.checkstyle.checks.whitespace.nowhitespacebefore;
     3  
     4  /* Config:
     5   * default
     6   */
     7  public class InputNoWhitespaceBeforeTextBlocksTabIndent {
     8  
     9      public static void main(String[] args) {}
    10  
    11      private void workingCheck() {
    12          String x = """
    13                  Some Text
    14                 """;
    15      }
    16  
    17      private void workingCheck_spaces() {
    18          String x = """
    19              Some Text
    20          """;
    21      }
    22  
    23      private void workingCheck_no_spaces() {
    24          String x = """
    25              Some Text
    26  """;
    27      }
    28                  ;
    29  
    30      private void brokenCheck_space_before_tabs() {
    31          String x = """
    32              Some Text
    33                  """;
    34      }
    35  
    36      private void brokenCheck_space_after_tabs() {
    37          String x = """
    38              Some Text
    39                   """;
    40      }
    41  
    42      private void brokenCheck_just_tabs() {
    43          String x = """
    44              Some Text

```
On line 28, I've added two tabs, then a semi. When NoWhitespaceBefore checks this line, this is the case:
![image](https://user-images.githubusercontent.com/31252532/94169964-736a9580-fe5d-11ea-8d96-aeb28a7d6b76.png)

Ok, so Checkstyle counts each tab as one char, and the "before" index is exactly what it should be.

On line 33, we have this:
![image](https://user-images.githubusercontent.com/31252532/94170040-8bdab000-fe5d-11ea-813d-f1021fa7fdd8.png)

This is what is causing the out of bounds issue.

I think we have three choices:

1. Make changes to  `.getColumnNo()` such that it returns what the user sees as the column number; i.e. the semi on line 28 is in column 10.
2. Make changes to the text block implementation, so that it will count each control char as one, and report that the `TEXT_BLOCK_LITERAL_END` token ends in column 5 on line 33.
3. Some hack in this check to work around this issue completely; perhaps check if the previous sibling's last child is a `TEXT_BLOCK_LITERAL_END`; then adjust the index of the character before.

For context:

Intellij reports that the semi on line 28 is in column 10.
![image](https://user-images.githubusercontent.com/31252532/94169827-47e7ab00-fe5d-11ea-877a-e3a16b14fae5.png)

Intellij reports that the semi on line 33 is in column 13.
![image](https://user-images.githubusercontent.com/31252532/94169881-58982100-fe5d-11ea-9d01-bbe463e8e7b1.png)

 Let's discuss.

**Comment by pbludov** [comment]
Just a note: the Java compiler treats tabs as spaces:
```java
public class TestClass {

    final static String TEXT_BLOCK = """
    four spaces
          ten spaces
		two tabs"""; // <- two tabs in this line

    public static void main(String... args) {
        System.out.println(TEXT_BLOCK);
    }

}
```
output:
```bash
$ /usr/lib/jvm/java-14-openjdk-amd64/bin/java --enable-preview --source=14 TestClass.java
Note: TestClass.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
  four spaces
        ten spaces
two tabs
```

Our parser should work in the same way:
```java
public class Main {

    private void brokenCheck_space_after_tabs() {
	String x = """ // <-tab on this line
            Some Text
		"""; // <-two tabs on this line
    }
}
```
```bash
$ java -jar checkstyle-8.36.2-all.jar  -J TestClass.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> Main [1:13]
`--OBJBLOCK -> OBJBLOCK [1:18]
    |--LCURLY -> { [1:18]
    |--METHOD_DEF -> METHOD_DEF [3:4]
    |   |--MODIFIERS -> MODIFIERS [3:4]
    |   |   `--LITERAL_PRIVATE -> private [3:4]
    |   |--TYPE -> TYPE [3:12]
    |   |   `--LITERAL_VOID -> void [3:12]
    |   |--IDENT -> brokenCheck_space_after_tabs [3:17]
    |   |--LPAREN -> ( [3:45]
    |   |--PARAMETERS -> PARAMETERS [3:46]
    |   |--RPAREN -> ) [3:46]
    |   `--SLIST -> { [3:48]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [4:1]  // <- Note column 1 here
    |       |   |--MODIFIERS -> MODIFIERS [4:1]
    |       |   |--TYPE -> TYPE [4:1]
    |       |   |   `--IDENT -> String [4:1]                          // <- Note column 1 here
    |       |   |--IDENT -> x [4:8]
    |       |   `--ASSIGN -> = [4:10]
    |       |       `--EXPR -> EXPR [4:12]
    |       |           `--TEXT_BLOCK_LITERAL_BEGIN -> """ [4:12]
    |       |               |--TEXT_BLOCK_CONTENT -> \n            Some Text\n\t\t  [4:15]
    |       |               `--TEXT_BLOCK_LITERAL_END -> """ [6:16] // <- IMO there should be column 2
    |       |--SEMI -> ; [6:20]
    |       `--RCURLY -> } [7:4]
    `--RCURLY -> } [8:0]
```
I think that the most consistent way is 2 (changes to the text block implementation).

**Comment by romani** [comment]
> Make changes to the text block implementation, so that it will count each control char as one, and report that the TEXT_BLOCK_LITERAL_END token ends in column 5 on line 33.

please use single char for tabs. Tabs are always render differently in applications (as 2 spaces, as 4 spaces or .... ). That is why it is trend to NOT use tabs at all to let code looks same in any IDE and even in browser.

if update for grammar is not simple, it would be awesome to make some hack in Check to avoid exception (I am on to ease pitest/coverage for this case).

during testing we can convert all spaces to tabs in Inputs for text block and run Check on them.

**Comment by pbludov** [comment]
Fix is merged.
