### ISSUE TITLE
Run regression testing in CI over openjdk14 or newer codebase

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#8901]
from https://github.com/checkstyle/checkstyle/issues/8895#issuecomment-707688814

we need to run openjdk14 (latest is ok too) with all Checks enabled (chekcstyle config) but with extra filter for parse errors
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/my_check.xml#L45

it will not find parse errors but it will find exceptions in Checks on weird/test code.

**Comment by rnveach** [comment]
Beware of https://github.com/checkstyle/contribution/issues/483 as this file will have to be continued to be ignored to avoid freezing up.

**Comment by nmancus1** [comment]
The files that I had to exclude to run AST regression on openjdk14 were:
[NestedLambdaGenerics.java](https://github.com/openjdk/jdk14/tree/master/test/langtools/tools/javac/lambda/speculative/NestedLambdaGenerics.java)
[NestedLambdaNoGenerics.java](https://github.com/openjdk/jdk14/tree/master/test/langtools/tools/javac/lambda/speculative/NestedLambdaNoGenerics.java)
[DeepStringConcat.java](https://github.com/openjdk/jdk14/tree/master/test/langtools/tools/javac/DeepStringConcat.java)
[InferStrict.java](https://github.com/openjdk/jdk14/tree/master/test/langtools/tools/javac/lambda/speculative/InferStrict.java)

I wonder, could we just add:
```
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="NestedLambdaGenerics\.java$"/>
</module>
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="NestedLambdaNoGenerics\.java$"/>
</module>
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="DeepStringConcat.java\.java$"/>
</module>
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="InferStrict.java\.java$"/>
</module>
```
to our config for this purpose?

**Comment by romani** [comment]
>could we just add

Good idea, as regression diff report ignore ignore list in property file

**Comment by romani** [comment]
@rnveach , please put approved label if you agree.

**Comment by rnveach** [comment]
I approved.

We have full regression config at https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/checks-nonjavadoc-error.xml and https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/checks-only-javadoc-error.xml which is forced to maintain all our checks. I would check if there is some way to reuse it between its current use and for this new JDK14 specific without having to maintain new, different files for just JDK14.

Maybe add an optional suppression file that will be only be used for JDK14?

**Comment by nmancus1** [comment]
I'm on this.

**Comment by romani** [comment]
Please do not place it in Travis, we have new CI for extra load

**Comment by nmancus1** [comment]
>Please do not place it in Travis, we have new CI for extra load

I am using Semaphore, is that OK?

**Comment by nmancus1** [comment]
Update:  I have written the new, no-exception test for Semaphore using the `openjdk14`  project in https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties . I have created a script:

```
#!/bin/bash
OUTPUT="test"
while  [ -n "$OUTPUT" ]
do
    OUTPUT=$(.ci/no-exception-test.sh openjdk14-checkstyle-checks-no-exception | grep "Caused by: " | grep -oh '/.*.java' | sed 's|.*/||' | cut -f 1 -d '.' | uniq)
    echo "$OUTPUT"
    echo -e "<module name=\"BeforeExecutionExclusionFileFilter\">\n  <property name=\"fileNamePattern\" value=\"/$OUTPUT\.java\$\"/>\n</module>" >> config/openjdk14-excluded.files
    rm -rf .ci-temp/contribution
done
```

This script is creating a file of `BeforeExecutionExclusionFileFilter` modules, one for each file that causes exception.  The semiphore job that I created `sed -i `'s this file into  https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/checks-nonjavadoc-error.xml.

Once we can run regression testing to completion, i.e. all files that cause exception have been included in the file of  `BeforeExecutionExclusionFileFilter` modules, I will create commented sections within the file; one for non-compilables, one for reported Checkstyle issues, and one for issues that still need to be created.

Luckily, as I noted in https://github.com/checkstyle/checkstyle/issues/8631#issue-675622362 there are some patterns within the non-compilable files such that they can be grepped out and compared to the BeforeExecutionExclusionFileFilter` modules file.

For the rest files causing exception, I am writing  a script to verify that they can be compiled, so that I can manually sort through them (hopefully).

**Comment by nmancus1** [comment]
Ok, so I think that I have compiled the entire list of files in openjdk14 that cause exception, and can generate the checstyle report.  Then, report generation fails with:

```
[INFO] Generating "Source Xref" report    --- maven-jxr-plugin:2.5
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:11 min
[INFO] Finished at: 2020-10-20T12:43:33-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.NullPointerException
    at org.apache.maven.jxr.pacman.JavaFileImpl.parse (JavaFileImpl.java:108)
    at org.apache.maven.jxr.pacman.JavaFileImpl.<init> (JavaFileImpl.java:64)
    at org.apache.maven.jxr.pacman.FileManager.getFile (FileManager.java:68)
    at org.apache.maven.jxr.pacman.PackageManager.parse (PackageManager.java:123)
    at org.apache.maven.jxr.pacman.PackageManager.process (PackageManager.java:161)
    at org.apache.maven.jxr.JXR.xref (JXR.java:262)
    at org.apache.maven.plugin.jxr.AbstractJxrReport.createXref (AbstractJxrReport.java:279)
    at org.apache.maven.plugin.jxr.AbstractJxrReport.executeReport (AbstractJxrReport.java:473)
    at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:255)
    at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument (ReportDocumentRenderer.java:219)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule (DefaultSiteRenderer.java:319)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (DefaultSiteRenderer.java:135)
    at org.apache.maven.plugins.site.SiteMojo.renderLocale (SiteMojo.java:175)
    at org.apache.maven.plugins.site.SiteMojo.execute (SiteMojo.java:138)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
        at launch.executeCmd(launch.groovy:322)
        at launch.executeCmd(launch.groovy:315)
        at launch$executeCmd$8.callCurrent(Unknown Source)
        at launch.runMavenExecution(launch.groovy:239)
        at launch$_generateCheckstyleReport_closure2.doCall(launch.groovy:95)
        at launch.generateCheckstyleReport(launch.groovy:70)
        at launch$generateCheckstyleReport$1.callCurrent(Unknown Source)
        at launch.run(launch.groovy:10)

```
@rnveach this is very similar to the https://github.com/checkstyle/contribution/pull/85.  How did you overcome this?

**Comment by rnveach** [comment]
@nmancus1 Sadly I use a completely separate maintained regression scripts than the groovy files. It doesn't use JXR so I don't run into this problem. I am the only one that can regression on sevntu (https://github.com/checkstyle/contribution/issues/340). My changes are located in https://github.com/rnveach/contribution/blob/rvmaster/checkstyle-tester/ with the main script being `launch_diff.sh` .

The issue with JXR could be resolved with https://github.com/checkstyle/contribution/issues/273 as we don't need this entire phase. It generates HTML files that we don't use, wasting disk access.

Until it is reworked, the following lines are the only way to ignore files from being processed by JXR but they would have to be maintained for each repo.
https://github.com/checkstyle/contribution/pull/85/files#diff-87c07fc673fa6e48e28785588ce45ed3dfbf04dacdc6435b58a96752d8fa3b65R84
https://github.com/checkstyle/contribution/pull/85/files#diff-991751f5f256d8b411789bbed38b50d5a9dbe1feebb8fd8c479fcfc01665d781R69

The PR you mentioned, apache apex, still doesn't have in the project in the file to regress on, so there is no current workaround for the groovy scripts without modifications.

**Comment by rnveach** [comment]
> only way to ignore files from being processed by JXR

Maybe as an intermediate step, JXR could be changed to ignore all files. This would also help show and prove it isn't needed for regression.
I don't remember what other changes I had to make to my scripts when removing JXR.

**Comment by nmancus1** [comment]
@rnveach Thanks a lot for your idea.  I got this working by doing this:
https://github.com/nmancus1/contribution/commit/94b8492c611132b6252f8cfc93f9c54b47187c57

```
...
[INFO] Generating "Checkstyle" report    --- maven-checkstyle-plugin:3.1.1
[INFO] Generating "Source Xref" report    --- maven-jxr-plugin:2.5
[INFO] Skipping JXR.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14:50 min
[INFO] Finished at: 2020-10-21T13:05:21-04:00
[INFO] ------------------------------------------------------------------------
Running Checkstyle on src/main/java - finished
linking report to index.html
Removing non referenced xref files in report ...
   [delete] Deleting directory /home/nick/IdeaProjects/checkstyle/.ci-temp/contribution/checkstyle-tester/src/main/java/openjdk14
     [move] Moving 39 files to /home/nick/IdeaProjects/checkstyle/.ci-temp/contribution/checkstyle-tester/reports/openjdk14

```

The openjdk-14 run now completes successfully. However, is this change to `launch.groovy` acceptable for other our other usages of this script? If nothing else, I could just `sed` that line for this run and add `-Dmaven.jxr.skip=true` to the command line args for maven.

**Comment by rnveach** [comment]
@romani would have to confirm of the uses with `launch.groovy` and the impact to not having it do JXR. If there is an issue, `diff.groovy` should send `launch`  a parameter for disabling/enabling it.

I know we used `launch.groovy` outside regression for standalone runs in CI, but I am now seeing `diff.groovy` being the official way to do runs, even if only on 1 project and even for just 1 branch. I see no problems as I have been trying to progress us to not rely on JXR and maven-checkstyle for our needs.

**Comment by nmancus1** [comment]
@rnveach thanks for the feedback.  I will see what @romani thinks, then open up a PR in contribution to resolve this issue; after that is merged, I will submit the PR for this issue.

**Comment by romani** [comment]
we use JXR for generation of html pages from source files that are easy to reference by line numbers as http link with anchor to exact number.
If any of you know tool that can do simply this, we do not JXR and can use such tool.

JXR do more that we need, and has parser for fancy code highlighting in web and .... . We do not need all that.
https://maven.apache.org/jxr/maven-jxr-plugin/jxr-mojo.html
https://maven.apache.org/jxr/maven-jxr-plugin/jxr-mojo.html#excludes
We can try to provide system variable to exclude some files :).

if we do not want to generate HTML pages of sources, and looking simply for exceptions in our html page (links will dead, but it is fine we see report of exception on file), we can skip JXR by suggested system property, I am fine with extra CLI option for groovy scripts, may be good name is `-Dextra.mvn.options="-Dmaven.jxr.skip=true -Dmaven.some.other=true"`

**Comment by rnveach** [comment]
> we use JXR for generation of html pages from source files that are easy to reference by line numbers as http link with anchor to exact number.

`patch-diff-report-tool` is what creates our final HTML files which is outside `checkstyle-tester`'s POM. 

To be clear, we are talking about removing JXR from `checkstyle-tester`'s POM, NOT `patch-diff-report-tool`'s POM.
See https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/pom.xml#L39-L43

@nmancus1 How does `patch-diff-report-tool` complete on the files that fail in `checkstyle-tester` at https://github.com/checkstyle/checkstyle/issues/8901#issuecomment-713017725

JXR is not needed in `checkstyle-tester`. As shown by @nmancus1 it just causes more issues and has been brought up before. I have already removed this part of JXR from my own regression scripts without problem. It is also removes `maven-checkstyle-plugin` which is another problem area. My issue in contribution covers removing them.

**Comment by romani** [comment]
If can live without jxr, let's remove it.
We already migrated to diff.groovy completely, so let's remove it.

**Comment by rnveach** [comment]
@romani We are not completely migrated to `diff.groovy`. See https://github.com/checkstyle/checkstyle/search?q=%22launch.groovy%22
Hence why I am not sure how much launch needs JXR if it is relying on JXR to create the reports that diff naturally creates through our util.

**Comment by romani** [comment]
all this cases can be redone to use diff.groovy, 
or we can copy code with extraMvOptions to launch.groovy.

**Comment by nmancus1** [comment]
What is left to be done here? Should we open a issue for complete diff.groovy migration and close this one?

**Comment by romani** [comment]
I am closing this issue, let create new issue in refactoring of launch.groovy and diff.groovy .
