### ISSUE TITLE
FinalLocalVariable throws a NPE on Switch expression in assignment

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8934]
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#FinalLocalVariable

Discovered at https://github.com/checkstyle/checkstyle/pull/8920#pullrequestreview-518815743

FinalLocalVariable is throwing a NPE when a switch expression is used on the RHS of an assignment expression:

```
➜  src /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 ExpressionSwitchBugs.java
➜  src cat config.xml                                                                               
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="FinalLocalVariable"/>
    </module>
</module>
➜  src cat ExpressionSwitchBugs.java 
public class ExpressionSwitchBugs {
    private static final int staticValue = 2;
    private static final int staticField = switch(staticValue) {
        case 0 -> -1;
        case 2 -> 2;
        default -> 3;
    };
}
➜  src java -jar /home/nick/IdeaProjects/checkstyle/target/checkstyle-8.37-SNAPSHOT-all.jar -c config.xml ExpressionSwitchBugs.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing ExpressionSwitchBugs.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.updateUninitializedVariables(FinalLocalVariableCheck.java:482)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.updateAllUninitializedVariables(FinalLocalVariableCheck.java:471)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.leaveToken(FinalLocalVariableCheck.java:345)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyLeave(TreeWalker.java:357)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:454)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
        ... 5 more
Checkstyle ends with 1 errors.

```
I would expect FinalLocalVariable to be able to successfully check this file.

**Comment by nmancus1** [comment]
Once this fix is merged, we can remove `ExpressionSwitchBugs.java` from the excluded files in `openjdk14-excluded.files`.

**Comment by anhminhtran235** [comment]
I am on it

**Comment by pbludov** [comment]
Fix is merged
