### ISSUE TITLE
Checkstyle fails on nested type parameters

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#8945]
Discovered at #8920 :

```
➜  src /usr/lib/jvm/java-14-openjdk/bin/javac --enable-preview --source 14 NestedTypes.java                                   
➜  src cat NestedTypes.java 
import java.lang.annotation.*;

class Outer {
    class Inner {
        class Inner2 {
        }
    }

    class GInner<X> {
        class GInner2<Y, Z> {}
    }

    static class Static {}
    static class GStatic<X, Y> {
        static class GStatic2<Z> {}
    }
}

class Test1 {
    @A Outer . @B GInner<@C MyList<@D Object @E[] @F[]>>.@G GInner2<@H Integer, @I Object> @J[] @K[] f4arrtop;
}


class MyList<K> { }


@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface A { }
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface B { }
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface C { }
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface D { }
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface E { }
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface F { }
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface G { }
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface H { }
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface I { }
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface J { }
@Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
@interface K { }
➜  src java -jar /home/nick/IdeaProjects/checkstyle/target/checkstyle-8.37-SNAPSHOT-all.jar -t NestedTypes.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/nick/Desktop/enhanced-switch/src/NestedTypes.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:120)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFileText(JavaParser.java:137)
        at com.puppycrawl.tools.checkstyle.JavaParser.parseFile(JavaParser.java:157)
        at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:65)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:284)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.IllegalStateException:  areLtsAndGtsBalanced(currentLtLevel)
        at com.puppycrawl.tools.checkstyle.JavaParser$1.reportError(JavaParser.java:108)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:424)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:212)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:114)
        ... 6 more
Caused by:  areLtsAndGtsBalanced(currentLtLevel)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeArguments(GeneratedJavaRecognizer.java:1374)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classOrInterfaceType(GeneratedJavaRecognizer.java:1148)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classTypeSpec(GeneratedJavaRecognizer.java:887)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeArgument(GeneratedJavaRecognizer.java:1415)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeArguments(GeneratedJavaRecognizer.java:1326)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classOrInterfaceType(GeneratedJavaRecognizer.java:1148)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classTypeSpec(GeneratedJavaRecognizer.java:887)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeSpec(GeneratedJavaRecognizer.java:849)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3119)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:3415)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:646)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:561)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:402)
        ... 8 more
Checkstyle ends with 1 errors.

```
I would expect Checkstyle to be able to parse this code.

**Comment by nmancus1** [comment]
Once this is fixed, we can remove the "NestedTypes.java" `BeforeExecutionExclusionFileFilter` from openjdk14-excluded.files.

**Comment by pbludov** [comment]
Fix is merged.
