### ISSUE TITLE
Checkstyle 8.37 parser crashes processing sealed classes or interfaces

### ISSUE THREAD

**Issue by 100yo** [checkstyle/checkstyle#8989]
C:\checkstyle-8.37>type checkstyle.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name = "Checker">
  <module name="TreeWalker">
    <module name="OuterTypeFilename"/>
    <module name="IllegalTokenText">
      <property name="tokens" value="STRING_LITERAL, CHAR_LITERAL"/>
      <property name="format"
               value="\\u00(09|0(a|A)|0(c|C)|0(d|D)|22|27|5(C|c))|\\(0(10|11|12|14|15|42|47)|134)"/>
      <property name="message"
               value="Consider using special escape sequence instead of octal value or Unicode escaped value."/>
    </module>
  </module>
</module>

C:\checkstyle-8.37>type DeliveryService.java
public sealed interface DeliveryService permits MJTExpressWarehouse {

}

C:\checkstyle-8.37>java -jar checkstyle-8.37-all.jar -c checkstyle.xml DeliveryService.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing DeliveryService.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file C:\checkstyle-8.37\DeliveryService.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:120)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:149)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
        ... 5 more
Caused by: java.lang.IllegalStateException: C:\checkstyle-8.37\DeliveryService.java:1:8: unexpected token: sealed
        at com.puppycrawl.tools.checkstyle.JavaParser$1.reportError(JavaParser.java:108)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:424)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:212)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:114)
        ... 9 more
Caused by: C:\checkstyle-8.37\DeliveryService.java:1:8: unexpected token: sealed
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:596)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:402)
        ... 11 more
Checkstyle ends with 1 errors.

**Comment by romani** [comment]
It is jdk15 feature https://openjdk.java.net/jeps/360
We support only jdk14 for now, but yes, we need to support it.

**Comment by nmancus1** [comment]
Related grammar: https://docs.oracle.com/en/java/javase/15/docs/specs/sealed-classes-jls.html#jls-8.1.7

Brief article about sealed classes/ interfaces: https://medium.com/better-programming/java-15-features-sealed-and-hidden-classes-pattern-matching-and-text-blocks-38f4efdc8adc

It is interesting to note that while `non-sealed` *is* a keyword, `sealed` and `permits` are restricted identifiers, similar to `var` and `yield`.

**Comment by izrobin** [comment]
Hi! Now that JDK16 is out, and sealed classes is in its second preview, what's the status on this one?

**Comment by strkkk** [comment]
> what's the status on this one?

status is: PRs to fix this issue are welcome

**Comment by nmancus1** [comment]
I'm on this.

**Comment by strkkk** [comment]
fix is merged
