### ISSUE TITLE
Unexpected Token:Interface

### ISSUE THREAD

**Issue by ek08** [checkstyle/checkstyle#8991]
The doc says(https://checkstyle.org/config_design.html#FinalClass_Description)
Doesn't check for classes nested in interfaces.

$ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="severity" value="error"/>
    <module name="TreeWalker">
		<module name="FinalClass"/>
    </module>
</module>

$ cat CheckInterface.java
Interface CheckInterface
{
class MyClass
{
void m1(){
System.out.println("inside m1");
}
void m2(){
System.out.println("inside m2");
}
}
}

$ java -jar "-Duser.language=en -Duser.country=US" checkstyle-8.37-all.jar -c config.xml CheckInterface.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing CheckInterface.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred while parsing file /home/ehtesham/CheckInterface.java.
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:120)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:149)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
	... 5 more
Caused by: /home/ehtesham/CheckInterface.java:1:1: unexpected token: Interface
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:191)
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:114)
	... 9 more
Checkstyle ends with 1 errors.

**The output is same when I run**
$ java -jar "-Duser.language=en -Duser.country=US" checkstyle-8.37-all.jar -c config.xml CheckInterface$MyClass.java

**Checkstyle ended with error. It should provide  code style is OK or it should skip it as it doesn't check for classes nested in interfaces.**

**Comment by ek08** [comment]
Here is the config.xml file

&lt ?xml version="1.0"?&gt
&lt !DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd"&gt

&lt module name="Checker"&gt
    &ltproperty name="severity" value="error"/&gt
    &lt module name="TreeWalker"&gt
		&ltmodule name="FinalClass"/&gt
    &lt/module&gt
&lt/module&gt
`

**Comment by strkkk** [comment]
you have Interface (uppercase I) instead of interface (lowercase i) in your code. Checkstyle expects compilable java code.

FYI please try to do `javac your_file.java` before to make sure it compiles (no output in console)

**Comment by ek08** [comment]
I am so sorry.I did a blunder.
