### ISSUE TITLE
IndentationCheck throws NPE on switch expresion with `->` on new line

### ISSUE THREAD

**Issue by champo** [checkstyle/checkstyle#9037]
https://checkstyle.org/config_misc.html#Indentation

```
$ javac CheckstyleCrasher.java
$ cat -p CheckstyleCrasher.java
package test;

class CheckstyleCrasher {

    enum A {
        one
    }

    enum B {
        one
    }

    private B map(A a) {

        return switch (a) {
            case one
                    -> B.one;
        };
    }

}
$ cat -p config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name = "Checker">
    <module name="TreeWalker">
        <module name="Indentation" />
    </module>
</module>
$ java -jar checkstyle-8.37-all.jar -c config.xml CheckstyleCrasher.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing CheckstyleCrasher.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.getLineStart(AbstractExpressionHandler.java:210)
	at com.puppycrawl.tools.checkstyle.checks.indentation.LambdaHandler.getIndentImpl(LambdaHandler.java:84)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.getIndent(AbstractExpressionHandler.java:84)
	at com.puppycrawl.tools.checkstyle.checks.indentation.LambdaHandler.checkIndentation(LambdaHandler.java:112)
	at com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck.visitToken(IndentationCheck.java:534)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
	... 5 more
Checkstyle ends with 1 errors.
```

I've also tested with non-default settings. Moving the `->` to the previous line avoid the NPE.

**Comment by Abhishek-kumar09** [comment]
<details><summary>$ cat test.java</summary>
<p>

```java
class CheckstyleCrasher {

    enum A {
        one
    }

    enum B {
        one
    }

    private B map(A a) {
        return switch (a) {
            case one 
            -> B.one;
        };
    }

}
```
</p>
</details>

$ javac test.java 

```
test.java:12: error: illegal start of expression
        return switch (a) {
               ^
test.java:14: error: : expected
            -> B.one;
                    ^
2 errors
```

I am using java amazon-coretto 11.
It is not compiling, should I have to update the jdk to compile it.

**Comment by champo** [comment]
Hi! I'm using OpenJDK 14

**Comment by Abhishek-kumar09** [comment]
Oh yes, I guess I have to update to OpenJDK 14 for this. Though amazon-coretto 11 had its own advantages :)

**Comment by champo** [comment]
I guess that the same issue should be present with coretto 15 too!

**Comment by pbludov** [comment]
The crash site is [here](https://github.com/checkstyle/checkstyle/blob/9797eadadccf376533480901cc1ad3d4915340b6/src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java#L83)
```java
final DetailAST firstChild = getMainAst().getFirstChild();
```
The main AST is `->[17x20]`, it has no children:
```
SWITCH_RULE -> SWITCH_RULE [16:12]
 |--LITERAL_CASE -> case [16:12]
 |   `--EXPR -> EXPR [16:17]
 |       `--IDENT -> one [16:17]
 |--LAMBDA -> -> [17:20]                    // <- Here is the lambda
 |--EXPR -> EXPR [17:24]
 |   `--DOT -> . [17:24]
 |       |--IDENT -> B [17:23]
 |       `--IDENT -> one [17:25]
 `--SEMI -> ; [17:28]
```
the code is valid for javac version 14 and later

**Comment by nmancus1** [comment]
I'm on this.

**Comment by romani** [comment]
fix is merged.

**Comment by romani** [comment]
@champo, let us know you use checkstyle in some open source project that use new jdk features.
we can use this project for regression testing on each commit to make sure we do not regressions in future.

**Comment by champo** [comment]
@nmancus1 thanks for the quick fix!
@romani I don't 🙁 We're usually up to date with checkstyle releases so if anything pops up I'll let you know asap
