### ISSUE TITLE
NoSuchMethodError: CheckUtil.getAccessModifierFromModifiersToken(tools/checkstyle/checks/naming/AccessModifierOption)

### ISSUE THREAD

**Issue by samvaity** [checkstyle/checkstyle#9094]
https://github.com/Azure/azure-sdk-for-java/blob/master/eng/code-quality-reports/src/main/java/com/azure/tools/checkstyle/checks/BlacklistedWordsCheck.java#L85

>Caused by: java.lang.NoSuchMethodError: com.puppycrawl.tools.checkstyle.utils.CheckUtil.getAccessModifierFromModifiersToken(Lcom/puppycrawl/tools/checkstyle/api/DetailAST;)Lcom/puppycrawl/tools/checkstyle/checks/naming/AccessModifierOption;
        at com.azure.tools.checkstyle.checks.BlacklistedWordsCheck.isPublicApi(BlacklistedWordsCheck.java:85)
        at com.azure.tools.checkstyle.checks.BlacklistedWordsCheck.visitToken(BlacklistedWordsCheck.java:63)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:342)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:449)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:283)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:161)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
        ... 25 more

Using version 8.38

**Comment by rnveach** [comment]
> com.azure

This seems similar to https://github.com/checkstyle/checkstyle/issues/9098 . We are not maintainers checkstyle-idea plugin.

We can only help with bugs in our own utility. See https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F .

**Comment by rnveach** [comment]
I am closing until it can be shown issue is in our repo.
