### ISSUE TITLE
Generated suppressions.xml is ignored

### ISSUE THREAD

**Issue by alanbuttars** [checkstyle/checkstyle#9245]
This bug appears in version 8.40

Step 1: Set up Java file.
```
[buttarsa@ch12ldvdi302 buttarsa]$ cat Test.java 
class Test {
    public void onAction(String transactionId) {
            System.out.println("123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 " +
                            "123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 ");
    }
}

[buttarsa@ch12ldvdi302 buttarsa]$ javac Test.java
```

Step 2: Create checkstyle.xml
```
[buttarsa@ch12ldvdi302 buttarsa]$ cat checkstyle.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
    "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="Indentation">
      <property name="basicOffset" value="4"/>
      <property name="braceAdjustment" value="4"/>
      <property name="caseIndent" value="4"/>
      <property name="throwsIndent" value="4"/>
      <property name="lineWrappingIndentation" value="4"/>
      <property name="arrayInitIndent" value="4"/>
    </module>
    <module name="OperatorWrapCheck">
      <property name="option" value="NL" />
      <property name="tokens" value="BAND, BOR, BSR, BXOR, DIV, EQUAL, GE, GT, LAND, LE, LITERAL_INSTANCEOF, LOR,
                    LT, MINUS, MOD, NOT_EQUAL, PLUS, QUESTION, SL, SR, STAR, METHOD_REF "/>
    </module>
  </module>
</module>
```

Step 3: Generate suppressions.xml
```
[buttarsa@ch12ldvdi302 buttarsa]$ java -jar ~/Downloads/checkstyle-8.40-all.jar com.puppycrawl.tools.checkstyle.Main -c checkstyle.xml -g -o suppressions.xml Test.java 
Checkstyle ends with 2 errors.

[buttarsa@ch12ldvdi302 buttarsa]$ cat suppressions.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suppressions PUBLIC
    "-//Checkstyle//DTD SuppressionXpathFilter Experimental Configuration 1.2//EN"
    "https://checkstyle.org/dtds/suppressions_1_2_xpath_experimental.dtd">
<suppressions>
<suppress-xpath
       files="Test.java"
       checks="IndentationCheck"
       query="/CLASS_DEF[./IDENT[@text='Test']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='onAction']]/SLIST/EXPR/METHOD_CALL/DOT[./IDENT[@text='println']]/DOT/IDENT[@text='System']"/>
<suppress-xpath
       files="Test.java"
       checks="OperatorWrapCheck"
       query="/CLASS_DEF[./IDENT[@text='Test']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='onAction']]/SLIST/EXPR/METHOD_CALL/ELIST/EXPR/PLUS[./STRING_LITERAL[@text='123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 ']]"/>
</suppressions>
```

Step 4: Update checkstyle.xml so it references suppressions.xml
```
[buttarsa@ch12ldvdi302 buttarsa]$ cat checkstyle.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
    "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="SuppressionFilter">
    <property name="file" value="suppressions.xml"/>
  </module>

  <module name="TreeWalker">
    <module name="Indentation">
      <property name="basicOffset" value="4"/>
      <property name="braceAdjustment" value="4"/>
      <property name="caseIndent" value="4"/>
      <property name="throwsIndent" value="4"/>
      <property name="lineWrappingIndentation" value="4"/>
      <property name="arrayInitIndent" value="4"/>
    </module>
    <module name="OperatorWrapCheck">
      <property name="option" value="NL" />
      <property name="tokens" value="BAND, BOR, BSR, BXOR, DIV, EQUAL, GE, GT, LAND, LE, LITERAL_INSTANCEOF, LOR,
                    LT, MINUS, MOD, NOT_EQUAL, PLUS, QUESTION, SL, SR, STAR, METHOD_REF "/>
    </module>
  </module>
</module>
```

Step 5: Run check again. The suppressions.xml is ignored.
```
[buttarsa@ch12ldvdi302 buttarsa]$ java -jar ~/Downloads/checkstyle-8.40-all.jar com.puppycrawl.tools.checkstyle.Main -c checkstyle.xml  Test.java 
Starting audit...
[ERROR] /ctc/buttarsa/Test.java:3:13: 'method def' child has incorrect indentation level 12, expected level should be 8. [Indentation]
[ERROR] /ctc/buttarsa/Test.java:3:155: '+' should be on a new line. [OperatorWrap]
Audit done.
Checkstyle ends with 2 errors.
```

**Comment by rnveach** [comment]
> `<module name="SuppressionFilter">`

It looks like the wrong filter was used. Xpath suppressions has to use it's own specific filter. See https://checkstyle.org/config_filters.html#SuppressionXpathFilter .

@romani It is weird that the normal suppression filter did not produce an error since the wrong config was supplied.

**Comment by alanbuttars** [comment]
If I change the module name to `SuppressionXpathFilter`, I see this:

```
[buttarsa@ch12ldvdi302 buttarsa]$ java -jar ~/Downloads/checkstyle-8.40-all.jar com.puppycrawl.tools.checkstyle.Main -c checkstyle.xml  Test.java 
com.puppycrawl.tools.checkstyle.api.CheckstyleException: SuppressionXpathFilter is not allowed as a child in Checker
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:502)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:404)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Checkstyle ends with 1 errors.
```

**Comment by rnveach** [comment]
it must be placed inside `TreeWalker` as the documentation suggests.
https://checkstyle.org/config_filters.html#SuppressionXpathFilter_Parent_Module

**Comment by alanbuttars** [comment]
Moving the `SuppressionXpathFilter` module inside `TreeWalker` works for my above code sample. Thank you!
