### ISSUE TITLE
SuppressWarningsHolder fails on @SuppressWarnings in annotation array initialization

### ISSUE THREAD

**Issue by nmancus1** [checkstyle/checkstyle#9260]
Check documentation: https://checkstyle.sourceforge.io/config_annotation.html#SuppressWarningsHolder

Identified at https://github.com/checkstyle/checkstyle/pull/9229#issuecomment-775176345:

```bash
➜  checkstyle git:(issue-9229) ✗ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="SuppressWarningsHolder"/>
    </module>
</module>

➜  checkstyle git:(issue-9229) ✗ cat TrailingComma.java 
import java.lang.annotation.*;

@interface TestAnnotation {
    SuppressWarnings[] value() default {@SuppressWarnings({"",})};
}

public class TrailingComma {
}

➜  checkstyle git:(issue-9229) ✗ javac TrailingComma.java

➜  checkstyle git:(issue-9229) ✗ java -jar target/checkstyle-8.41-SNAPSHOT-all.jar -c config.xml TrailingComma.java 
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TrailingComma.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
        at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.IllegalArgumentException: Unexpected container AST: {[4x39]
        at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.getAnnotationTarget(SuppressWarningsHolder.java:422)
        at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.visitToken(SuppressWarningsHolder.java:312)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:340)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:451)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:278)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:151)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:337)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:298)
        ... 5 more
Checkstyle ends with 1 errors.


```

Filter in `openjdk14-excluded.files` for `TrailingComma.java` should be removed while fixing this issue:

```xml
<!-- until https://github.com/checkstyle/checkstyle/issues/9260 -->
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="annotations[\\/]pos[\\/]TrailingComma.java$"/>
</module>

```

**Comment by nmancus1** [comment]
I can take care of this once it is approved.

**Comment by strkkk** [comment]
Issue is valid. Also cases like
```
@interface TestAnnotation {
    SuppressWarnings value() default @SuppressWarnings({"",});
}
```
cause failure

**Comment by pbludov** [comment]
Fix is merged.
