### ISSUE TITLE
Throw StackOverflowError when config.xml include RegexpSinglelineJava

### ISSUE THREAD

**Issue by gksxodnd007** [checkstyle/checkstyle#9330]
Test.java
```java
/**
 * @author gksxodnd007
 * @since 2021.02.25
 */
class Test {
    String name;

    String getName() {
        return this.name;
    }
}
```

config.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
...
<module name="RegexpSinglelineJava">
    <property name="id" value="indentation_tab"/>
    <property name="severity" value="warning"/>
    <property name="ignoreComments" value="true"/>
    <!-- this value is problem. if default value is used to format property, checkstyle execute success  -->
    <property name="format" value="^\t*"/> 
    <property name="message" value="[indentation-tab] Indent must use tab characters"/>
</module>
...
```
```bash
java -jar ./checkstyle-8.40-all.jar -c ./config.xml ./Test.java

#[[PLACE YOUR OUTPUT HERE]]
Starting audit...
Exception in thread "main" java.lang.Error: Error was thrown while processing ./Test.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:319)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:408)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:331)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: java.lang.StackOverflowError
	at java.base/java.util.Collection.stream(Collection.java:711)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1693)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.puppycrawl.tools.checkstyle.api.FileContents.hasIntersectionWithBlockComment(FileContents.java:287)
	at com.puppycrawl.tools.checkstyle.api.FileContents.hasIntersectionWithComment(FileContents.java:267)
	at com.puppycrawl.tools.checkstyle.checks.regexp.CommentSuppressor.shouldSuppress(CommentSuppressor.java:47)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:113)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
	at com.puppycrawl.tools.checkstyle.checks.regexp.SinglelineDetector.checkLine(SinglelineDetector.java:114)
        ...
```

**Comment by strkkk** [comment]
I do not think it is related to checkstyle, it looks like a problem with regex itself

**Comment by rnveach** [comment]
@gksxodnd007 
The issue is the `*`. Since it means 0 or more, it is infinitely matching all empty selections (no characters). You should be using `+` if I understand what you are looking for.

````
$ cat TestClass.java
/**
 * @author gksxodnd007
 * @since 2021.02.25
 */
class Test {
String name;

String getName() {
return this.name;
}
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="RegexpSinglelineJava">
    <property name="id" value="indentation_tab"/>
    <property name="severity" value="warning"/>
    <property name="ignoreComments" value="true"/>
    <!-- this value is problem. if default value is used to format property, checkstyle execute success  -->
    <property name="format" value="^\t+"/> 
    <property name="message" value="[indentation-tab] Indent must use tab characters"/>
</module>
    </module>
</module>

$ java -jar checkstyle-8.40-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[WARN] TestClass.java:6: [indentation-tab] Indent must use tab characters [indentation_tab]
[WARN] TestClass.java:8: [indentation-tab] Indent must use tab characters [indentation_tab]
[WARN] TestClass.java:9: [indentation-tab] Indent must use tab characters [indentation_tab]
[WARN] TestClass.java:10: [indentation-tab] Indent must use tab characters [indentation_tab]
Audit done.
````
