### ISSUE TITLE
Failure to generate Javadoc tree structure when inline tag inside html list item

### ISSUE THREAD

**Issue by AkMo3** [checkstyle/checkstyle#9690]
I have read check documentation: https://checkstyle.org/writingjavadocchecks.html
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
$ javac Test1.java
<-- NO OUTPUT SUCCESSFUL COMPILATION -->

$ cat Test1.java
 public class Test1{
 
   /**
     * {@summary first sentence is normally the summary.
     * Use of html tags:
     * <ul>
     * <li>{@throws error}</li>
     * <li>Item two.</li>
     * </ul>}
     */
    private void validInlineJavadoc() // violation
    {
    }
 }

$ javadoc Test1.java
Loading source file Test1.java...
Constructing Javadoc information...
Standard Doclet version 14.0.2
Building tree for all the packages and classes...
Generating ./Test1.html...
Generating ./package-summary.html...
Generating ./package-tree.html...
Generating ./constant-values.html...
Building index for all the packages and classes...
Generating ./overview-tree.html...
Generating ./deprecated-list.html...
Generating ./index-all.html...
Building index for all classes...
Generating ./allclasses-index.html...
Generating ./allpackages-index.html...
Generating ./system-properties.html...
Generating ./index.html...
Generating ./help-doc.html...

$ java -jar checkstyle-8.42-SNAPSHOT-all.jar -J Test1.java
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:9] Javadoc comment at column 9 has parse error. Details: no viable alternative at input '</ul' while parsing HTML_ELEMENT
	at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseAndPrintJavadocTree(AstTreeStringPrinter.java:116)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:97)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:101)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:79)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:306)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
```

---
#### Expected: 
Successful parsing of file and printing of Javadoc Tree structure

---

Found at [#7202 Comment](https://github.com/checkstyle/checkstyle/pull/9174#issuecomment-803623910)

**Comment by gianmarcoschifone** [comment]
@romani I rechecked this on current upstream master.

The reported parser failure no longer reproduces. I think this issue can be closed as fixed.

```text
$ cat Test.java
public class Test {

   /**
     * {@summary first sentence is normally the summary.
     * Use of html tags:
     * <ul>
     * <li>{@throws error}</li>
     * <li>Item two.</li>
     * </ul>}
     */
    private void validInlineJavadoc()
    {
    }
}

$ java -jar target/checkstyle-13.8.0-SNAPSHOT-all.jar -J Test.java
COMPILATION_UNIT -> COMPILATION_UNIT [1:1]
`--CLASS_DEF -> CLASS_DEF [1:1]
    |--MODIFIERS -> MODIFIERS [1:1]
    |   `--LITERAL_PUBLIC -> public [1:1]
    |--LITERAL_CLASS -> class [1:8]
    |--IDENT -> Test [1:14]
    `--OBJBLOCK -> OBJBLOCK [1:19]
        |--LCURLY -> { [1:19]
        |--METHOD_DEF -> METHOD_DEF [11:5]
        |   |--MODIFIERS -> MODIFIERS [11:5]
        |   |   |--BLOCK_COMMENT_BEGIN -> /* [3:4]
        |   |   |   |--COMMENT_CONTENT -> *\n     * {@summary first sentence is normally the summary.\n     * Use of html tags:\n     * <ul>\n     * <li>{@throws error}</li>\n     * <li>Item two.</li>\n     * </ul>}\n      [3:6]
        |   |   |   |   `--JAVADOC_CONTENT -> JAVADOC_CONTENT [3:7]
        |   |   |   |       |--NEWLINE -> \n [3:7]
        |   |   |   |       |--LEADING_ASTERISK ->      * [4:1]
        |   |   |   |       |--TEXT ->   [4:7]
        |   |   |   |       |--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG [4:8]
        |   |   |   |       |   `--SUMMARY_INLINE_TAG -> SUMMARY_INLINE_TAG [4:8]
        |   |   |   |       |       |--JAVADOC_INLINE_TAG_START -> {@ [4:8]
        |   |   |   |       |       |--TAG_NAME -> summary [4:10]
        |   |   |   |       |       |--DESCRIPTION -> DESCRIPTION [4:17]
        |   |   |   |       |       |   |--TEXT ->  first sentence is normally the summary. [4:17]
        |   |   |   |       |       |   |--NEWLINE -> \n [4:57]
        |   |   |   |       |       |   |--LEADING_ASTERISK ->      * [5:1]
        |   |   |   |       |       |   |--TEXT ->  Use of html tags: [5:7]
        |   |   |   |       |       |   |--NEWLINE -> \n [5:25]
        |   |   |   |       |       |   |--LEADING_ASTERISK ->      * [6:1]
        |   |   |   |       |       |   |--TEXT ->   [6:7]
        |   |   |   |       |       |   `--HTML_ELEMENT -> HTML_ELEMENT [6:8]
        |   |   |   |       |       |       |--HTML_TAG_START -> HTML_TAG_START [6:8]
        |   |   |   |       |       |       |   |--TAG_OPEN -> < [6:8]
        |   |   |   |       |       |       |   |--TAG_NAME -> ul [6:9]
        |   |   |   |       |       |       |   `--TAG_CLOSE -> > [6:11]
        |   |   |   |       |       |       |--NEWLINE -> \n [6:12]
        |   |   |   |       |       |       |--LEADING_ASTERISK ->      * [7:1]
        |   |   |   |       |       |       |--HTML_CONTENT -> HTML_CONTENT [7:7]
        |   |   |   |       |       |       |   |--TEXT ->   [7:7]
        |   |   |   |       |       |       |   |--HTML_ELEMENT -> HTML_ELEMENT [7:8]
        |   |   |   |       |       |       |   |   |--HTML_TAG_START -> HTML_TAG_START [7:8]
        |   |   |   |       |       |       |   |   |   |--TAG_OPEN -> < [7:8]
        |   |   |   |       |       |       |   |   |   |--TAG_NAME -> li [7:9]
        |   |   |   |       |       |       |   |   |   `--TAG_CLOSE -> > [7:11]
        |   |   |   |       |       |       |   |   |--HTML_CONTENT -> HTML_CONTENT [7:12]
        |   |   |   |       |       |       |   |   |   `--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG [7:12]
        |   |   |   |       |       |       |   |   |       `--CUSTOM_INLINE_TAG -> CUSTOM_INLINE_TAG [7:12]
        |   |   |   |       |       |       |   |   |           |--JAVADOC_INLINE_TAG_START -> {@ [7:12]
        |   |   |   |       |       |       |   |   |           |--TAG_NAME -> throws [7:14]
        |   |   |   |       |       |       |   |   |           |--DESCRIPTION -> DESCRIPTION [7:20]
        |   |   |   |       |       |       |   |   |           |   `--TEXT ->  error [7:20]
        |   |   |   |       |       |       |   |   |           `--JAVADOC_INLINE_TAG_END -> } [7:26]
        |   |   |   |       |       |       |   |   `--HTML_TAG_END -> HTML_TAG_END [7:27]
        |   |   |   |       |       |       |   |       |--TAG_OPEN -> < [7:27]
        |   |   |   |       |       |       |   |       |--TAG_SLASH -> / [7:28]
        |   |   |   |       |       |       |   |       |--TAG_NAME -> li [7:29]
        |   |   |   |       |       |       |   |       `--TAG_CLOSE -> > [7:31]
        |   |   |   |       |       |       |   |--NEWLINE -> \n [7:32]
        |   |   |   |       |       |       |   |--LEADING_ASTERISK ->      * [8:1]
        |   |   |   |       |       |       |   |--TEXT ->   [8:7]
        |   |   |   |       |       |       |   |--HTML_ELEMENT -> HTML_ELEMENT [8:8]
        |   |   |   |       |       |       |   |   |--HTML_TAG_START -> HTML_TAG_START [8:8]
        |   |   |   |       |       |       |   |   |   |--TAG_OPEN -> < [8:8]
        |   |   |   |       |       |       |   |   |   |--TAG_NAME -> li [8:9]
        |   |   |   |       |       |       |   |   |   `--TAG_CLOSE -> > [8:11]
        |   |   |   |       |       |       |   |   |--HTML_CONTENT -> HTML_CONTENT [8:12]
        |   |   |   |       |       |       |   |   |   `--TEXT -> Item two. [8:12]
        |   |   |   |       |       |       |   |   `--HTML_TAG_END -> HTML_TAG_END [8:21]
        |   |   |   |       |       |       |   |       |--TAG_OPEN -> < [8:21]
        |   |   |   |       |       |       |   |       |--TAG_SLASH -> / [8:22]
        |   |   |   |       |       |       |   |       |--TAG_NAME -> li [8:23]
        |   |   |   |       |       |       |   |       `--TAG_CLOSE -> > [8:25]
        |   |   |   |       |       |       |   |--NEWLINE -> \n [8:26]
        |   |   |   |       |       |       |   |--LEADING_ASTERISK ->      * [9:1]
        |   |   |   |       |       |       |   `--TEXT ->   [9:7]
        |   |   |   |       |       |       `--HTML_TAG_END -> HTML_TAG_END [9:8]
        |   |   |   |       |       |           |--TAG_OPEN -> < [9:8]
        |   |   |   |       |       |           |--TAG_SLASH -> / [9:9]
        |   |   |   |       |       |           |--TAG_NAME -> ul [9:10]
        |   |   |   |       |       |           `--TAG_CLOSE -> > [9:12]
        |   |   |   |       |       `--JAVADOC_INLINE_TAG_END -> } [9:13]
        |   |   |   |       |--NEWLINE -> \n [9:14]
        |   |   |   |       `--TEXT ->       [10:1]
        |   |   |   `--BLOCK_COMMENT_END -> */ [10:6]
        |   |   `--LITERAL_PRIVATE -> private [11:5]
        |   |--TYPE -> TYPE [11:13]
        |   |   `--LITERAL_VOID -> void [11:13]
        |   |--IDENT -> validInlineJavadoc [11:18]
        |   |--LPAREN -> ( [11:36]
        |   |--PARAMETERS -> PARAMETERS [11:37]
        |   |--RPAREN -> ) [11:37]
        |   `--SLIST -> { [12:5]
        |       `--RCURLY -> } [13:5]
        `--RCURLY -> } [14:1]
```

**Comment by romani** [comment]
We did big update for Javadoc parser at summer of 2025
https://checkstyle.org/releasenotes.html#Release_12.0.0 so now it works well.
